### ISSUE TITLE
Risk Actualisation not working after update to 1.3.0(37)

### ISSUE THREAD

**Issue by pmiru-hub** [corona-warn-app/cwa-app-android#1149] opened 2020-09-14 07:30 UTC
After updating cwa via google playstore on 06 september, there has been no further risk actualisation. 
If I try to trigger risk actualisation manually, which I do every two or three days, I always get error code 39508.
Phone: Acer T04 on Android 6.0
Version as indicated in settings->google->covid-19-benachrichtigungen: 17203704003

**Comment by abro1i** [comment] 2020-09-14 09:59
Hi @pmiru-hub ,

thank you very much for your feedback. 

Can you confirm that your problem is identical to this issue here: #1119? 

Best regards,
ABB

Corona-Warn-App Open Source Team

**Comment by pmiru-hub** [comment] 2020-09-14 10:13
It seems indeed to be the identical behaviout

abb <notifications@github.com> schrieb am Mo., 14. Sep. 2020, 12:00:

**Comment by abro1i** [comment] 2020-09-14 10:18
Hey @pmiru-hub,

thanks for the quick reply.

Good news, this issue is fixed with Version 1.3.1 👍 

Best regards,
ABB

Corona-Warn-App Open Source Team

**Comment by pmiru-hub** [comment] 2020-09-14 10:33
Sounds good. Can you tell me, when 1.3.1 ist going to be released?

**Comment by abro1i** [comment] 2020-09-14 11:50
Sadly i cant give you the exact date but i can tell you that it will be released "soon" :wink:

Best regards,
ABB

Corona-Warn-App Open Source Team

**Comment by daimpi** [comment] 2020-09-14 13:18
@pmiru-hub 
The tracking issue for this Error (39508) is this one: https://github.com/corona-warn-app/cwa-app-android/issues/1021

This is a rate-limiting error, i.e. your app was trying to access a certain API functionality too frequently today. Normally what helps in such circumstances: stop the app -> wait for 24h -> open the app again.
The reason is that the limits are reset once a day, after which everything should work fine again :)

(Strictly speaking you don't even have to wait 24h, just waiting till 02:00 CEST (00:00 UTC) should suffice, as limits are reset at 00:00 UTC every day).

What I find curious, is that the error doesn't disappear for you even after some days…

Maybe you could try what I suggested above: stop the App, wait until tomorrow (after 2 am) and see whether the error still appears. If it does: you could share your ENF log (either here or over at #1021) , then we could try get a better feeling for how exactly your app fails.

Btw: do you have "Prioritized Background Activity" enabled in your app?

**Comment by heinezen** [comment] 2020-09-17 16:21
Hey everyone,

Since this seems to be a duplicate it's recommended to continue the discussion in #1021 . @pmiru-hub Did you try the workaround that @daimpi suggested? The information might help us to figure out the cause of the issue.

Regards,
CH

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-09-17 16:21
Duplicate of #1021

**Closed by heinezen** 2020-09-17 16:21 UTC
Labels: bug, duplicate
