### ISSUE TITLE
[UI] Elements missing from images based on theme

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#265] opened 2020-06-07 21:56 UTC
## Describe the bug
The images on the screen where a user can choose how to enter the TAN (QR-Code, manually, request the TAN) are missing some details based on the theme color, see pictures below.

The back-arrow is also not visible on the black theme, but this might be a seperate issue...

There might be other views with similar error, but i noticed it on this screen.

## Expected behaviour
The pictures should show identical content, regardless of the theme.

## Steps to reproduce the issue
If your phone has the option to change the system color from light to dark, do it. Open the app in both themes and see the different behaviour.

![dark (2)_LI](https://user-images.githubusercontent.com/6652142/83980903-90fd0900-a919-11ea-973d-e9a584af5709.jpg)
![light (2)_LI](https://user-images.githubusercontent.com/6652142/83980905-92c6cc80-a919-11ea-902a-424b7010c643.jpg)

## Technical details

- Smartphone with Android 10
- Build from dev-branch https://github.com/corona-warn-app/cwa-app-android/commit/8dd22995d2d609c9e1ec96e356c3faf551c6c3b1

## Additional context

---
Internal Tracking ID: EXPOSUREAPP-1968

**Comment by marcmuschko** [comment] 2020-06-09 08:22
Closing this issue as it was resolved in PR #288 
Please reopen if it still seems to be malfunctioning! 
Thanks and best,
Marc

**Comment by IndianaDschones** [comment] 2020-06-09 22:25
Hi @marcmuschko 

i have a device running Android 6 (Marshmallow) and there are the fingers from the hand holding the smartphone on the qr-code and the "still no tan" card rectangular, see screenshot.

On my Android 10 (Q) device this bug isn´t present.

However on both devices the header (Selection) including the back-arrow is scrolling up. The header is sticky on all other screens. Is this intended?

![selection-header](https://user-images.githubusercontent.com/6652142/84206724-0f8baf00-aab0-11ea-9fe2-5aa0b870d0a1.png)

Unfortunately i don´t have a option to reopen this issue.

**Comment by Fabian-K** [comment] 2020-06-11 15:07
Hi @IndianaDschones,

I can´t reproduce the "still no tan" issue on Android 6. Do you still face the issue on your device using the current dev branch?

Thanks, Fabian

**Comment by IndianaDschones** [comment] 2020-06-11 21:14
The fingers are still missing from the first and third card. If you cannot reproduce it on a device running Marshmallow, maybe it is something device specific?
I´ve got a Motorola Moto G (2nd Generation)

**Comment by LukaHarambasic** [comment] 2020-06-22 08:57
I also can't reproduce it. @IndianaDschones could you test it with the latest version from the Play Store (currently 1.0.4)?

Cheers,
Luka

**Comment by IndianaDschones** [comment] 2020-06-22 20:49
@LukaHarambasic @Fabian-K 

Still happening. But i did some research. This ain´t an Android version issue but rather a `dpi` issue. The Moto G (2nd Gen.) has a `xhdpi` resolution. Taking a look in the generated drawables at `res/drawable-xhdpi-v4` i found the exact same image, with a rectangle instad of fingers:
![ic_submission_illustration_qr_code_card](https://user-images.githubusercontent.com/6652142/85325974-c5052c00-b4cc-11ea-9d3a-496f4fd041a1.png)

`ic_submission_illustration_qr_code_card.png`

This applies to other resource folders as well

- `res\drawable-ldpi-v4`
- `res\drawable-hdpi-v4`
- `res\drawable-xxxhdpi-v4`
- `res\drawable-xxhdpi-v4`
- `res\drawable-xhdpi-v4`
- `res\drawable-mdpi-v4`

**Comment by MikeMcC399** [comment] 2021-01-10 09:21
@IndianaDschones 
This issue has been sleeping for quite a while and based on your findings I dug into this.

Apparently Android Studio doesn't treat the vector asset https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/drawable/ic_submission_illustration_qr_code_card.xml well. 

The bad rendering with the block instead of fingers can be seen on the Android Studio emulator
4.65 720p (Galaxy Nexus) 720x1280 xhdpi API 23 (Android 6.0). CWA does not run properly on Android emulators before API 30 due to lack of Bluetooth, also there are no Google Play services on this emulator, but after ignoring errors due to this, tapping on NEXT STEPS brings up the "Test with QR Code". The fingers are replaced with a block.

In the Project view of Android Studio showing the generated pngs graphic files
cwa-app-android\Corona-Warn-App\build\generated\res\pngs\deviceForTesters\debug\drawable-xhdpi there are two other files suffering from the finger problem:
- ic_illustrations_qr_code_scan_info.png
- ic_information_illustration_technical.png

On the same emulator the bad rendering can also be seen via
Three dot overflow menu > App Information > Legal Notices

I marked the issue, related to the original issue, in the screen shot below with the red rectangle:

![image](https://user-images.githubusercontent.com/66998419/104118996-035d1e00-532d-11eb-909a-eb3f69ca15e5.png)

I'm using the current master branch of the repo.

**Comment by dsarkar** [comment] 2021-01-12 09:46
@IndianaDschones , @MikeMcC399 

Thanks! Info is forwarded into the ticket now.

**Comment by MikeMcC399** [comment] 2021-04-16 14:53
PR #2800 is now merged into the [release/2.1.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.1.x) branch.

**Comment by MikeMcC399** [comment] 2021-04-16 15:27
@dsarkar 
Would you like to mark this issue as fixed in 2.1?

## Steps to verify

On the  Android Studio emulator
4.65 720p (Galaxy Nexus) 720x1280 xhdpi API 23 (Android 6.0) I did the following tests:

1. On Start screen, tap three-dot icon > App Information > Legal Notices
2. Check that graphic shows fingers
3. On Start screen, tap "NEXT STEPS"
4. Check that graphic next to "Test with QR Code" has fingers

**Comment by dsarkar** [comment] 2021-04-17 17:10
@MikeMcC399 Thanks for the hint!

**Comment by dsarkar** [comment] 2021-05-04 10:21
@IndianaDschones This has been fixed with version 2.1.  Thanks for contributing. We suggest closing this issue now. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-05-04 10:33
@dsarkar / @IndianaDschones 

I checked using the final release 2.1.2 using the repo steps from https://github.com/corona-warn-app/cwa-app-android/issues/265#issuecomment-821255737 and everything looks fine. Fingers are shown.

**Comment by vaubaehn** [comment] 2021-05-04 14:45
@dsarkar @IndianaDschones 
I also have fingers now where previously had been unattractive cubes.
Thank you!

**Closed** 2021-05-09 15:29 UTC
Labels: Fix 2.1, UX, bug, community, mirrored-to-jira, ready-to-close

**Comment by dsarkar** [comment] 2021-05-10 10:11
@vaubaehn @MikeMcC399 Thanks for the feed back! ;-)
