### ISSUE TITLE
Error when communicating with Google API(10)

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-app-android#763] opened 2020-06-26 14:28 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

This error occurred after reinstalling / cleaning app data couple of times. It seems that user may exceed Google's API limit of 20 calls by repeatedly reinstalling the app or cleaning app data. Right now it requires couple of repetitions, but with 14 Diagnosis Keys in internal storage it would require only 1 action of reinstalling / cleaning data to trigger this error.

![error10_1](https://user-images.githubusercontent.com/28542783/85867342-93e96c00-b7ea-11ea-9445-1f1da4c31d01.png)

![error10_2](https://user-images.githubusercontent.com/28542783/85867361-977cf300-b7ea-11ea-92ad-80c03b9dbf78.png)

## Expected behaviour

Error handled gracefully, and providing Diagnosis Keys to the framework from most recent to the oldest (as the most recent file contains most Diagnosis Keys which are still relevant).

## Steps to reproduce the issue

Reinstall / clean data and open the app every time until the error appears.

## Technical details

- Mobile device: Motorola G2
- Android version: 6

**Comment by jakobmoellersap** [comment] 2020-06-26 14:30
Duplicate of #737

**Closed by jakobmoellersap** 2020-06-26 14:30 UTC
Labels: bug
