### ISSUE TITLE
Ursache3 es ist etwas schiefgelaufen 

### ISSUE THREAD

**Issue by DK1979** [corona-warn-app/cwa-app-android#1147] opened 2020-09-12 15:50 UTC
Hallo zusammen,
Die Corona App aktualisiert nicht mehr. Seit dem 10.9., auch nicht wenn man die App öffnet.
App Version 1.3.0 kein Update verfügbar 
Android 10, Samsung Galaxy A40
Neustart Smartphone erfolglos, Hintergrund Aktualisierungen aktiv, kein Sparmodus.
Gruß Daniela. 
![Screenshot_20200912-173937_Corona-Warn](https://user-images.githubusercontent.com/71185209/92999319-4397c580-f520-11ea-93af-79c7493440fa.jpg)
![Screenshot_20200912-174948_Corona-Warn](https://user-images.githubusercontent.com/71185209/92999340-61fdc100-f520-11ea-800c-d423b81335fd.jpg)

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Mobile device:
- Android version:

**Comment by heinezen** [comment] 2020-09-12 16:43
Hey @DK1979 ,

Thanks for your submission. Your bug was already reported in #1021 . The issue is currently being addressed by the development team. More information about that can be found here: https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-683748329

Regards,
CH

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-09-12 16:43
Duplicate of #1021 .

**Closed** 2020-09-12 16:44 UTC
Labels: bug, duplicate
