### ISSUE TITLE
Use android:inputType=textVisiblePassword for tan input edittext

### ISSUE THREAD

**Issue by dadosch** [corona-warn-app/cwa-app-android#43] opened 2020-05-31 10:22 UTC
## Feature description
Currently,  `android:inputType=text` is used for the tan input edittext. This has the consequence that the user's soft keyboard shows suggestions and may save the TAN to a dictionary.

With `android:inputType=textVisiblePassword`, no suggestions are shown and the keyboard shouldn't save it in its dictionary.

## Problem and motivation
The autocompletion of the softkeyboard may alter the TAN the user has typed in.

## Is this something you're interested in working on

No

**Comment by ironjan** [comment] 2020-05-31 10:34
I'll pick that up

**Comment by jakobmoellersap** [comment] 2020-05-31 10:37
Just a suggestion, we should wait for verification on issues before doing PR's. Otherwise it could happen that your PR will not get into the codebase and you will have lost effort.

I am not saying your PR here is invalid or will not get confirmed.

**Comment by ironjan** [comment] 2020-05-31 11:09
@jakobmoellersap thanks for the input. The change was trivial enough (1 line) to risk that ;)

**Comment by kolyaopahle** [comment] 2020-06-01 08:45
This looks like a sensible change to me, text suggestions should indeed not happen during tan entry we should accept this as a contribution.

**Comment by kolyaopahle** [comment] 2020-06-05 12:52
fixed in #46

**Closed by kolyaopahle** 2020-06-05 12:52 UTC
Labels: in progress
