### ISSUE TITLE
Exposure notification system logs before the 14-days window

### ISSUE THREAD

**Issue by vaggelisdouros** [corona-warn-app/cwa-app-android#1535] opened 2020-11-05 01:19 UTC
Hello,

I just checked the logs of my exposure notification system and there are still records for the days of 20 October and 21 October. 

My understanding is that when I check the corona warn app on 5th of November at 1 am, it should cover the period from 22nd of October until 4th of November. Prior data are outdated and should not be checked (actually, they should be deleted automatically). Shouldn't it be the case? Am i missing something? 

![Screenshot_20201105-021345](https://user-images.githubusercontent.com/73972744/98185358-c4fe4980-1f0c-11eb-88ef-a1dfd6007e8f.png)

I use the app version 1.5.1 on a samsung galaxy A5 that runs android 7.0.

**Comment by MikeMcC399** [comment] 2020-11-05 06:53
Hi @vaggelisdouros 

I reported a similar problem (see https://github.com/corona-warn-app/cwa-app-android/issues/1020 "Recorded number of exposure checks too high after 14 days").

What version of the Exposure Notifications System (ENS) is installed on your Samsung Galaxy A5? You can find this by going back from the screen shot you posted and then scrolling to the bottom of the screen.  You should see something like "Version 17203915000". Full instructions are in the [FAQ - [Google/Android]: Which version of the COVID-19 Exposure Notification System is currently installed?](https://www.coronawarn.app/en/faq/#ENF_version).

It does seem like the Google ENS is holding on to the exposure checks longer than they say they do; something like 16 days instead of 14 days. I have not seen any explanation for this so far, however it doesn't seem to cause any particular problem, apart from showing an inconsistency between the message to the user and the action of the system.

**Comment by dsarkar** [comment] 2020-11-05 11:10
Dear @vaggelisdouros,

Thanks for your post.  As mentioned by @MikeMcC399 this is a very similar problem already reported.

I will close this issue as a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1020. Please continue any further discussion there and provide any additional information also there. 

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-05 11:10
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1020

**Closed by dsarkar** 2020-11-05 11:10 UTC
Labels: duplicate, question
