### ISSUE TITLE
Mock Test

### ISSUE THREAD

**Issue by Gagandeep1408** [corona-warn-app/cwa-app-android#1693] opened 2020-11-23 11:50 UTC
How i can test exposure notifications?
I've downloaded  code but not able to enable notification

**Comment by MikeMcC399** [comment] 2020-11-23 19:40
@Gagandeep1408 

> How i can test exposure notifications?
> I've downloaded code but not able to enable notification

I responded to your question in https://github.com/google/exposure-notifications-android/issues/59 without realizing that you had asked the question here as well.

You can't test the code from the German Corona-Warn-App unless you are a member of the team which belongs to the German public health authority Robert Koch Institut and its sub-contractors SAP and T-Systems.

There is a technical discussion in ["Is it really possible to test the apps? How to become whitelisted?"](https://github.com/corona-warn-app/cwa-documentation/issues/214) where I made some recent comments in https://github.com/corona-warn-app/cwa-documentation/issues/214#issuecomment-731573968 about the errors you get when you try to test.

**Comment by dsarkar** [comment] 2020-11-24 09:53
Dear @Gagandeep1408,

Did @MikeMcC399 satisfactorily answer your question? If so, I suggest you close this issue. The question about CWA beta testing has been raised with the development team and will be discussed and answered here https://github.com/corona-warn-app/cwa-documentation/issues/214 and here https://github.com/corona-warn-app/cwa-wishlist/issues/153.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Gagandeep1408** [comment] 2020-11-24 09:58
sure

**Comment by dsarkar** [comment] 2020-11-24 10:23
Dear @Gagandeep1408,

Thanks again for contributing here. I will close this issue, and please follow our other open issues on this topic.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-11-24 10:23 UTC
Labels: further input needed, question

**Comment by dsarkar** [comment] 2020-11-26 13:29
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/214
