### ISSUE TITLE
App takes long to launch

### ISSUE THREAD

**Issue by ucmichan** [corona-warn-app/cwa-app-android#1222] opened 2020-08-30 14:06 UTC
It takes ca 10 seconds to launch the app and to show the risk status. This happens since the last update of the app.

Device:
Galaxy A6 (a6lte)
Android 10

---
Internal Tracking ID: EXPOSUREAPP-2837

**Comment by GPclips** [comment] 2020-09-24 07:16
Hello @ucmichan ,

does this issue still occur? 
@abro1i do we have any update on this?

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by phpman89** [comment] 2020-10-26 08:05
I have the same problem with version 1.5 on my Mi 9 with MIUI 12 / Android 10

**Comment by daimpi** [comment] 2020-10-26 15:02
@phpman89 thanks for sharing your screen recording. Does this issue appear every time you try to open CWA or was this a one off?

**Comment by phpman89** [comment] 2020-10-26 19:25
Unfortunately the issue appear every time I open the CWA.

**Comment by daimpi** [comment] 2020-10-26 19:40
@phpman89 thanks the devs probably have to take a look at that 🙂. 

(cc @GPclips @abro1i)

**Comment by ralfgehrer** [comment] 2020-12-14 11:21
This was very likely fixed with https://github.com/corona-warn-app/cwa-app-android/pull/1857 by @d4rken 

The update check during app launch could happen on the main thread, blocking the UI.
Further changes to app config behavior should also have a positive effect on this.

Hence, we would consider this as being addressed and closed, @JoachimFritsch .

**Comment by dsarkar** [comment] 2020-12-22 07:15
Hi @ucmichan, this issue should be fixed now. We would appreciate your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-02-09 14:57
Since there is no more feedback on this, I assume the issue is fixed. We are therefore closing this issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-02-09 14:57 UTC
Labels: Fix 1.8, Solved, bug, mirrored-to-jira
