### ISSUE TITLE
Scan errors for non-CWA QR codes pop up on frontend

### ISSUE THREAD

**Issue by koehntopp** [corona-warn-app/cwa-app-android#2909] opened 2021-04-22 12:04 UTC
From

https://twitter.com/sand2drn/status/1385197350025564163

![Bildschirmfoto 2021-04-22 um 14 04 01](https://user-images.githubusercontent.com/7113567/115711289-a1707380-a373-11eb-99a8-ce7ea551476d.png)

Exception handling should be improved, meaningful error message shown.

---
https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.4
Internal Tracking ID: [EXPOSUREAPP-6658](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6658)

**Comment by MikeMcC399** [comment] 2021-04-22 12:19
If a user inadvertently tries to scan in a QR code from a PCR test instead of from a check in, then the same error occurs.

## Steps to reproduce

1. Tap Check In
2. Tap "SCAN QR CODE" and then point to QR code from bottom half of example form [10C form](https://www.kbv.de/media/sp/Ansichtsexemplar_Muster10C.pdf)

![image](https://user-images.githubusercontent.com/66998419/115712920-ad5d3500-a375-11eb-9f2d-78432c2727f3.png)

## Expected result

In this special case, a dedicated error message should point users to the correct way of scanning in an PCR test QR code.

For other QR codes, which are not in the format for checking in, then a user-friendly error message should be output.

**Comment by koehntopp** [comment] 2021-04-22 12:21
![Bildschirmfoto 2021-04-22 um 14 21 34](https://user-images.githubusercontent.com/7113567/115713258-16dd4380-a376-11eb-8e75-df06f186a6ef.png)

**Comment by sand2dorn** [comment] 2021-04-22 12:24
Oh, you're fast… 😺

**Comment by dsarkar** [comment] 2021-04-22 12:27
@koehntopp @MikeMcC399 Thank you very much for the reports. Internal Tracking ID: [EXPOSUREAPP-6658](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6658)


---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-04-22 15:09
@dsarkar 
What do you think about the suggestion from @Ein-Tim ?

> I suggest that you open a new wishlist item regarding [#2909 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/2909#issuecomment-824789923).

Is wrongly scanning a PCR Test QR code using the Check-in QR code scanner already covered by Internal Tracking ID: [EXPOSUREAPP-6658](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6658) or does it need a separate wishlist item?

**Comment by MikeMcC399** [comment] 2021-04-22 15:26
@Ein-Tim 

What happens on iOS if you try to scan in the sample PCR test QC code using check-in?

![image](https://user-images.githubusercontent.com/66998419/115712920-ad5d3500-a375-11eb-9f2d-78432c2727f3.png)

Do you get a user-friendly error message?

**Comment by Ein-Tim** [comment] 2021-04-22 17:12
@MikeMcC399 

iOS shows this message, which i quite good I think: 

<img src="https://user-images.githubusercontent.com/67682506/115756609-88c98300-a39e-11eb-8c92-9229f76a579f.png" width="300">

**Comment by dsarkar** [comment] 2021-04-22 17:44
@MikeMcC399 @Ein-Tim 

> Is wrongly scanning a PCR Test QR code using the Check-in QR code scanner already covered by Internal Tracking ID: EXPOSUREAPP-6658 or does it need a separate wishlist item?

That would be a new wishlist item.

The alignment of iOS and Android error messages is dealt with in this ticket.

**Comment by dsarkar** [comment] 2021-04-23 10:29
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2919

**Comment by MikeMcC399** [comment] 2021-04-23 11:03
@dsarkar 

In https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.4-RC0 which includes PR "Human friendly QR Dialog Message 9002 (EXPOSUREAPP-6658)" https://github.com/corona-warn-app/cwa-app-android/pull/2919

the issue is fixed in the code, however the message is not translated yet. If the locale is set to English (United Kingdom) then the UI is shown in German. The default strings file includes only German, and the specific English strings file is missing the entries.

I assume this is known, however I just wanted to mention it.

https://github.com/corona-warn-app/cwa-app-android/blob/59015a7a14efbcb203254d2698ec9cfbc3dc0ef1/Corona-Warn-App/src/main/res/values/strings.xml#L2004-L2011

**Comment by dsarkar** [comment] 2021-04-23 14:26
@MikeMcC399 Many thanks. Forwarded into internal ticket.

**Comment by MikeMcC399** [comment] 2021-04-23 15:07
The missing English language strings have been delivered and incorporated into https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.4-RC1.

Scanning the PCR test example QR code, with the device locale set to English (United Kingdom), results in a human-readable error message in English.

It looks like the fix is now good to go!

**Comment by dsarkar** [comment] 2021-04-24 11:50
FYI https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.4

**Comment by MikeMcC399** [comment] 2021-04-24 12:15
@dsarkar 

Google Play Store has already delivered the bug-fix release [v2.0.4](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.4) to me and I was able to verify that the fix correctly displays a user-friendly error message when scanning the PCR test QR code.

From my point of view this issue can be closed. Perhaps @koehntopp can confirm when he is able to update and check?

**Comment by dsarkar** [comment] 2021-04-24 12:26
@MikeMcC399 Thanks for confirming the fix.

**Comment by heinezen** [comment] 2021-04-26 13:27
Dear community,

This issue has been fixed in CWA 2.0.4. We will close this issue now.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-04-26 13:27 UTC
Labels: Fix 2.0.4, bug, mirrored-to-jira
