### ISSUE TITLE
'System-UI was stopped' if Bluetooth or GPS is turned off on specific Sony Devices

### ISSUE THREAD

**Issue by Bumblebee38** [corona-warn-app/cwa-app-android#597] opened 2020-06-17 13:11 UTC
## Describe the bug

If I turned on the "Risiko-Ermittlung", which works pretty fine, and turn Bluetooth off after that my device says 'System-UI was stopped' (originally "System-UI wurde angehalten"). After closing this message, everything except my wallpaper disappears. After a few seconds instead of my current wallpaper, a black screen is showing. How do I know that this is a black screen showing instead of my phone getting locked? I have a display overlay active which is visible at the whole time unless I lock my phone. Then again after a few seconds my current wallpaper is showing again. This procedure repeats all the time which ends in a loop of these actions which I can only escape if I restart my phone which I can still do with holding the power button and than selecting 'Restart' (originally "Neu starten"). After a restart, the whole loop just begins after a few minutes. I cannot do anything else like using the notification bar or getting feedback if I touch anywhere on my screen. 
The weird thing is that seeing my wallpaper like that only happens if I restart my phone and then want to immediately use the pre-installed launcher of my phone which I does not use anymore so this is even more confusing. 

## Expected behaviour

By turning off Bluetooth it should just remind me in my notification bar that I turned off Bluetooth which is needed so that the app is working properly. 

## Steps to reproduce the issue

1. Turn "Risiko-Ermittlung" on
2. Turn off Bluetooth

## Technical details

- Sony Xperia Z2
- Android 6.0.1

If any logs are needed, please let me know which logs you need and what I should do or connect to to create such logs. 

## Possible Fix

Since I do not know why it is behaving like that I am not able to suggest a fix. 

## Additional context

I already updated the Google Play Services as my device told me to do so.

---
EXPOSUREAPP-1855

**Comment by Bumblebee38** [comment] 2020-06-17 20:57
After I turned off "Risiko-Ermittlung" for testing, I turned Bluetooth off again and now the System-UI did not crash / was not stopped. 

Maybe if "Risiko-Ermittlung" is turned on but Bluetooth is not turned on, I think that something does not work properly as the Corona-Warn-App requires Bluetooth to be turned on. And I think that if something (Bluetooth) is missing that the app needs to work, the system results in a crash like stopping System-UI for some reason, right?

**Comment by realansgar** [comment] 2020-06-18 14:03
I've had the same issue with a Sony Xperia E5. I'm guessing that is has to do with the Google ENS API. When you turn off Bluetooth or Location, the API issues a notification telling you to turn it back on. Maybe the Sony specific UI doesn't play well with this notification for some reason. But I could be totally wrong here.

**Comment by BUBUsnet** [comment] 2020-06-18 15:59
Same behavior on Xperia Z3 Compact with Android 6.0.1.

**Comment by buergerapp** [comment] 2020-06-19 09:32
I just got an Error 4000 while tryinig to reproduce this.
On my Huawei Mate 10 pro i only disabled Bluetooth and then an error popup was shown "4000". I clicked on details an a list of calls appears. Unfortunally i could not screenshot them to post here.

**Comment by JonasKemmer** [comment] 2020-06-19 10:27
> Same behavior on Xperia Z3 Compact with Android 6.0.1.

Can confirm. Same here.

**Comment by jakobmoellersap** [comment] 2020-06-26 09:47
@buergerapp please take a look at #712

**Comment by jakobmoellersap** [comment] 2020-06-26 09:49
Just a quick update: We will try to identify the issue in detail. We are seeing multiple issues on Sony devices related to this crash and think this is a device bug. We will update here once we have more information. The issue does not appear on specific model numbers. Also we do not see this specific issue outside of Sony Xperia devices.

Current known affected Devices:
- Xperia Z2
- Xperia Z3 (D6603 but not D5803)
- Xperia Z3 Compact

**Comment by tkowark** [comment] 2020-06-26 19:22
Please add the  "Sony Xperia E5 (F3311) to the list (reported via email)

**Comment by Radon8472** [comment] 2020-08-20 21:33
I have similar behavoir on

Xperia XZ1 (G8341)
Android 9

And I even have this problems when I dont have installed the warn app.
It seems to be a problem with the google services.

In the comments for the Corona App I found a statement from "Robert Koch Institut"

> Dieser Fehler wird mit dem Update der Google Play Dienste behoben, welches gerade bei allen Android-Geräten ausgerollt wird (ENF 1.5)

But for me the problems still exist, even after updating the google services

**Comment by GisoSchroederSAP** [comment] 2020-09-25 17:13
Alcatel Handy 5026D seems to have the same issue, but stopping only after 14 days of working:

> Ich besitze ein Alcatel Handy 5026D, knapp 2 Jahre alt.
> Die Corona App habe ich am zweiten Tag der Ausgabe erstmals geladen.
> 
> Danach habe ich sie im Juli erneut geladen, mit der "verbesserten Version".
> Seither habe ich aber immer noch das Problem, dass die App 15 Tage nach dem Laden nicht mehr einzuschalten ist, sondern
> beim Antippen die Mitteilung erscheint "Die App wurde angehalten", mit der Möglichkeit, dass ich "App erneut öffnen" oder "feedback geben" anklicken kann. "Feedback" geht offenbar an google, eine Nachricht, wie dort damit verfahren wird, erhalte ich nicht. Bei "App erneut öffnen" beginnt der beschriebene Zyklus erneut von vorne "Die App witd weiterhin > angehalten...usw.".
> Ich habe nun im August und September die App jeweils einmal erneut aus dem App Store geladen, mit der Folge, dass zunächst nur "unbekanntes Risiko" angezeigt wurde (die tägliche Aktualisierung erfolgte tgl. um 02:31). Nach einigen Tagen dann "geringes Risiko" und nach 15 Tagen "Corona Warn wurde angehalten" .

**Comment by IsabellLD** [comment] 2020-10-21 08:16
Please add Sony Xperia XZ2 Compact Android 10

**Comment by Ste678** [comment] 2020-12-28 11:36
> > Same behavior on Xperia Z3 Compact with Android 6.0.1.
> Can confirm. Same here.
Same with my mobile.

> Just a quick update: We will try to identify the issue in detail. We are seeing multiple issues on Sony devices related to this crash and think this is a device bug. We will update here once we have more information. The issue does not appear on specific model numbers. Also we do not see this specific issue outside of Sony Xperia devices.
> 
> Current known affected Devices:
>     * Xperia Z2
>     * Xperia Z3 (D6603 but not D5803)
>     * Xperia Z3 Compact
>     * Xperia E5 (F3311)

In case the information would be beneficial: Due to GPS problems (gps.conf - some settings seems to be faulty) I rooted the phone* and only after that, the "System UI..." message with installed CWA appears.

*After extensive research - I am a normal mobile user/newbie, not a programmer.

Is there something I can contribute or test to help to solve the issue?

**Comment by dsarkar** [comment] 2020-12-30 21:59
@Ste678, thanks for reporting. We will update the ticket for the developers with your information. 

  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment] 2022-06-13 14:01
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Unfortunately, no additional information was added to this Jira ticket.

**Closed by svengabr** 2022-06-13 14:01 UTC
Labels: bug, mirrored-to-jira, community, UX
