### ISSUE TITLE
"Risiko-Ermittlung nicht möglich"

### ISSUE THREAD

**Issue by zigel** [corona-warn-app/cwa-app-android#638] opened 2020-06-18 11:42 UTC
Ich habe CWA am 15.06. installiert.
Heute ist 18.06. 
Ich bekomme die Meldung 
"Risiko-Ermittlung nicht möglich. Ihre Risiko-Ermittlung konnte seit mehr als 24 Stunden nicht aktualisiert werden. Letzte Risiko-Ermittlung: Niedriges Risiko. Aktualisiert 16. Juni, 09:14." Mit dem Button "Risiko-Ermittlung Einschalten". 

Handy-Modell Huawei Mate 20 Pro.

**Comment by mueslo** [comment] 2020-06-18 11:43
likely duplicate of #637

**Comment by marcmuschko** [comment] 2020-06-18 12:29
Hi @zigel,

thank you very much for reporting this! We are currently investigating this issue and will come back to you as soon as possible. If you can provide us with additional details, it might help a lot to identify the root cause for this behavior:
Did you change your phone date & time setting recently, disable background activity for the Corona-Warn-App or change the battery optimization settings for the Corona-Warn-App?

As #637 is very much the same, I will update #637 and close this issue soon to avoid duplicates.

Thank you very much and best,
Marc

**Comment by zigel** [comment] 2020-06-18 13:12
Hi @marcmuschko,

- i haven't changed date&time settings
- i changed optimzation policy for this app: marked it as "locked" or "safe from optimization", like described here: https://www.reddit.com/r/Huawei/comments/ccdtu4/what_does_this_lock_icon_mean/ 

and officially here: 
https://consumer.huawei.com/en/support/content/en-us00746352/.

**Closed** 2020-06-18 16:59 UTC
Labels: bug, in progress

**Comment by Kimtinki** [comment] 2020-06-21 11:41
Same Problem with Samsung Galaxy A3 (2017). "Risiko-Ermittlung nicht möglich", letzte Risiko-Ermittlung am 18. Juni, 17:49.
