### ISSUE TITLE
Download with long time

### ISSUE THREAD

**Issue by Drachenbauer** [corona-warn-app/cwa-app-android#2092] opened 2021-01-13 14:50 UTC
The green field shows, that files are being downloaded.
Since this morning.
Can something need a whoole day to Download?

I also see no download progress icon in the top bar of the phone.

**Comment by Ein-Tim** [comment] 2021-01-13 15:15
Duplicate of #2081

**Comment by dsarkar** [comment] 2021-01-13 16:15
@Drachenbauer Thanks for reporting. Monitor this issue https://github.com/corona-warn-app/cwa-app-android/issues/2081, please. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-01-13 18:05
Duplicate of #2081

**Closed by heinezen** 2021-01-13 18:05 UTC
Labels: duplicate
