### ISSUE TITLE
Negative value of the counter for how long the app has been active

### ISSUE THREAD

**Issue by 1ukast** [corona-warn-app/cwa-app-android#828] opened 2020-07-06 12:37 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug
The green risk indicator box in the app reads "-5 von 14 Tagen aktiv" (-5 of 14 days active).

## Expected behaviour
The number of days that the app has been active cannot be below zero.

## Steps to reproduce the issue

1. I have downloaded the app at the release date.
2. I have switched off "Risiko-Ermittlung" as well as bluetooth and GPS on that same day.
3. I reactivated all of the above on 5th of July, 2020.
4. When opening the app, the negative counter occurs (Even after restarting the app or disabling and enabling "Risiko-Ermittlung" again). 

## Technical details

- Mobile device: Samsung SM-J530F
- Android version: 9
- App Version 1.0.4

## Additional context

- I have never changed any date or time settings on my phone during the last months.  

---
Internal Tracking ID: EXPOSUREAPP-1844

**Comment by 1ukast** [comment] 2020-07-06 13:03
[Update:] 

When checking existing issues, i was searching for other entries that mentioned negative numbers.
Now I just found this entry in the FAQ: https://www.coronawarn.app/en/faq/#days_active_Android

If someone can confirm that this is the same problem, the issue can be closed i guess.

**Comment by schindlboeckLi** [comment] 2020-07-06 13:55
Yes your are right

**Comment by jkrwdf** [comment] 2020-07-06 14:01
The issue #796 linked in the FAQ deals with a rounding effect which causes the days counter to increase unexpectedly slow. 

According to my understanding of the algorithm, I think this rounding effect cannot cause the number to become negative, so I recommend not to close this issue yet and give the maintainers a chance to assess it.

**Comment by tkowark** [comment] 2020-07-06 15:10
Thanks for reporting the issue. The value turning negative really seems to be a different bug than just a rounding error and should not really happen. The team will have a look.

**Comment by AlexanderAlferov** [comment] 2020-07-06 16:08
@1ukast thank you for your input!

I tried to reproduce this issue, but could not see negative value.

Please, kindly share some more details:
1) Did you switch off "Risiko-Ermittlung", bluetooth and GPS after on-boarding process? Or before application main screen was shown?
3) Did you kill the application after first start? Or may be you just have used "Close all apps" button.
2) Did you turn on all the above before application start on 5th of July?

Thank you!

Best regards,
Alex

**Comment by 1ukast** [comment] 2020-07-06 20:23
Unfortunately, I do not remember every detail.
But yes, I think I started the app at least once when bluetooth and GPS was disabled. 
I often close all apps with the "Alle schließen" button. But I have **not** killed the application with the "Stopp erzwingen" button in the system settings or something similar.

If i remember correctly, I was not connected to any network when I opened the app yesterday (July 5th) after this long period without using the app. Since the application was complaining about a missing network connection, I was enabling mobile data then. 

Is there any way that I can help you by reading out some data from my application? 
Should I try if the bug persists after a reboot of the system or do I risk loosing information that could be relevant to identify/fix the bug?

Best regards.

**Comment by pwoessner** [comment] 2020-07-07 07:23
Hi @1ukast 
A reboot of you phone will not cause a loss of data in the app, so you can try that one. The only thing that you only should do as a last solution is reinstalling the app, since this will delete the tracing data if that is the only tracing app installed on your device (e.g. if you have installed SwissCovid or Immuni).

Have you manually changed the device date & time at some point in time?

Thanks,
Philipp

**Comment by 1ukast** [comment] 2020-07-08 18:02
Hi,

my current number of days is still -5 of 14.
I rebooted the device today and it didn't change anything. 

As written above, I have not changed any date&time settings before the error occured.
However, just now I was trying to play with setting different dates to see the result:

Setting it to days in the past:
- any day from June 29th until today: Counter remains at -5
- Setting it to June 28th: Counter is at -6 
- Setting it to June 27th: Counter is at -7 
- Setting it to June 26th: Counter is at -8
- ...
- Setting it to June 20th: Counter is at -14
- ...
- Setting it to June 17th: Counter is at -17
- Setting it to June 16th: Counter shows -18 for a few milliseconds after opening the app, then the box turns grey and reads "Unbekanntes Risiko - Da Sie die Risiko-Ermittlung noch nicht lange genug aktiviert haben, konnten ....."

Until this point, the numbers above were reproducable when changing the date back and forth. Then I tried days in the future:
- Setting it to July 13th: Counter remains at -5
- Setting it to July 30th: Counter hits 14/14

From now on, I can't get any negative numbers anymore by changing the date.

**Comment by mDeisen** [comment] 2020-08-13 20:29
Hi,

I encountered the same problem when switching to and back from the SwissCovid app.

Currently the counter shows -35 out of the last 14 days. 
This roughly fits with decrementing one for every day that the app was inactive (due to usage of the SwissCovid app).
Before the switch, the app was active for longer than 14 days and the counter was behaving normally. 
Updating the app, restarting or switching back and forth between SwissCovid and Corona Warn does not change anything about the counter (It might increment by 1/day again if i switch back to Corona Warn).

Currently I expect it to keep decrementing with every day I keep using the SwissCovid app -> I will give an update on this.

Mobile device: Samsung SM-G986B/DS
Android version: 10
App Version 1.2.1

Best Regards,
Mattis
![Corona-Warn](https://user-images.githubusercontent.com/55016563/90183746-5057bb00-ddb4-11ea-9ad1-29cd69c4075f.jpg)

**Comment by darkdragon-001** [comment] 2020-08-14 08:24
Same problem here. My usage so far:
- Install the app and run it for 4 days for testing.
  -> correct count increasing daily
- Turn it off and turn Austrian app on
  -> correct count stays constant
- After about 10 days, turn Austrian app off and CWA on
  -> wrong count does not increase
- Turn CWA off after two days
  -> wrong count is at `-1` 10 days later

**Comment by pwoessner** [comment] 2020-08-14 09:03
Hi all, 
thanks for your details and your updates. With your input we managed to identified the issue and will fix it in an upcoming version. 

Technical background: We are storing the time intervals (point in time when you deactivated it _from_ and point in time when you activated it _to_) of the time when tracing is deactivated to calculate the tracing time. More details about the calculation can be found here: https://github.com/corona-warn-app/cwa-app-android/issues/796#issuecomment-652381709
We only delete an interval when the point in time of **to** is no longer in the past 14 days. This leads to an issue with periods where the app is deactivated for a long amount of time and the **from** timestamp is no longer in the last 14 days but the **to** timestamp is still in that last 14 days time period. In that case we take the complete duration of the deactivated time instead of the corrected duration (**from** should be max the point in time --> today - 14 days). 

This leads to the issue that when tracing is deactivated for example for 20 days, we calculate the active tracing times like this: 14 possible days - 20 days inactive days = - 6.

**Closed** 2020-08-18 06:56 UTC
Labels: UX, bug, community, in review, mirrored-to-jira
