### ISSUE TITLE
Exposure logging stopped and cannot be restarted

### ISSUE THREAD

**Issue by abulgher** [corona-warn-app/cwa-app-android#3602] opened 2021-07-01 19:49 UTC
Huawei p20 lite
Ane-lx1
Android 9

CWA version 2.4.2

From time to time when accessing the app a message saying that the exposure logging is stopped. If I click on the button "activate exposure logging", it brings me to the exposure logging activation page, i can activate the logging but as soon as I come back to the main page the logging is automatically stopped. 

Closing the app doesn't fix the issue nor cycling the airplane mode.

Restarting the phone restore the logging, but after some hours the problem comes up again.

**Comment by MikeMcC399** [comment] 2021-07-01 19:57
@abulgher 
Your problem sounds like the one discussed in https://github.com/corona-warn-app/cwa-app-android/issues/3093. Perhaps you could check this out and compare?

**Comment by abulgher** [comment] 2021-07-01 20:10
Exactly identical. You can merge the two issues or delete this one. Sorry
for double posting.

Cheers

Il gio 1 lug 2021, 21:57 Mike McCready ***@***.***> ha
scritto:

**Comment by heinezen** [comment] 2021-07-04 11:04
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/3093

**Closed by heinezen** 2021-07-04 11:04 UTC
