### ISSUE TITLE
Cannot manually select the app language

### ISSUE THREAD

**Issue by gitterman** [corona-warn-app/cwa-app-android#2905] opened 2021-04-22 05:59 UTC
## Current Implementation
The app derives the language from the android operating system language and there is no setting for the user to change this.
It is a bad programming style to set defaults without allowing the user to adapt them.
My phone is a business phone and has an English operating system for compatibility with business apps which are only available in English.
Nonetheless, I want apps which are specific to Germany in German of course.

## Suggested Enhancement
Add a setting which allows the user to change the app language to any of the supported languages.

## Expected Benefits
Better user experience and compatibility with other users. If I present my app to only German speakers they cannot properly understand what the apps shows.

**Comment by MikeMcC399** [comment] 2021-04-22 07:12
@gitterman 

There is already an old generic wishlist item corresponding to this suggestion https://github.com/corona-warn-app/cwa-wishlist/issues/22.

Starting in Android 7 you can have multiple locales selected and apps will pick in priority order. (See https://developer.android.com/guide/topics/resources/multilingual-support.) So if you generally prefer working in German, and have some apps which only have an English UI you could set the language list to be:

1. Deutsch (Deutschland)
2. English (United Kingdom) or English (United States).

CWA would pick Deutsch. Your business apps would go down the list until they reached English and use this language.

That might solve your issue if you have the appropriate environment.

**Comment by heinezen** [comment] 2021-04-22 11:00
Hello @gitterman ,

@MikeMcC399 is correct here that a similar wishlist entry already exists. Please upvote or comment there so we can track how popular the request is overall. You can also try the workaround @MikeMcC399 suggested.

I will close your issue as a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/22

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-04-22 11:00
Duplicate of corona-warn-app/cwa-wishlist#22

**Closed by heinezen** 2021-04-22 11:00 UTC
Labels: enhancement
