### ISSUE TITLE
Landkreis and Bundesland does not fit together

### ISSUE THREAD

**Issue by Aschroet** [corona-warn-app/cwa-app-android#4346] opened 2021-11-08 14:28 UTC
When do "Lokale 7-Tage-Inzidenz hinzufügen" -> Thüringen -> Ilm-Kreis, the app shows the "Hospitalisierungen in Baden-Würtemberg" which is wrong because Ilm-Kreis is located in Thuringia (and not Baden-Wurtemberg).

![Screenshot_20211108-112207_Corona-Warn](https://user-images.githubusercontent.com/19612739/140757387-0d9c6f09-7688-4ebc-a1d5-b80bfd6843e8.jpg)

Please fix!

**Comment by marcauberer** [comment] 2021-11-08 14:29
Duplicate of #4327

**Comment by MikeMcC399** [comment] 2021-11-12 09:18
@dsarkar 
Since this is a duplicate it could be closed in favour of the other issue (of #4327).

(@Aschroet - you could also close your issue.)

**Comment by dsarkar** [comment] 2021-11-12 15:08
@Aschroet we close this issue in favour of #4327. Thanks for reporting. Will be fixed soon.

**Comment by MikeMcC399** [comment] 2021-11-15 13:19
@Aschroet 
Would you like to check with the version 2.13.3 which is now in the Google Play Store?

**Comment by Aschroet** [comment] 2021-11-23 15:01
@MikeMcC399 works now.

![Screenshot_20211123-155653_Corona-Warn](https://user-images.githubusercontent.com/19612739/143048678-3d971cee-33a4-4247-a334-6e889190f219.jpg)

**Closed** 2021-11-23 15:06 UTC
Labels: bug, duplicate, ready-to-close, Fix 2.13.3

**Comment by dsarkar** [comment] 2021-11-24 11:08
Hi @Aschroet, thanks for your feedback.

---
Corona-Warn-App Open Source Team
