### ISSUE TITLE
Can't use this application with new Huawei P40

### ISSUE THREAD

**Issue by Bdschi** [corona-warn-app/cwa-app-android#2117] opened 2021-01-15 16:49 UTC
I am still not able to use this application with my new Huawei P40. It's not yet available in the Huawei app store and it doesn't work when downloaded otherwise. This despite the fact that this was promised as early as July 2020.

**Comment by MikeMcC399** [comment] 2021-01-15 17:01
@Bdschi 

Notably there is a statement from Google on https://support.google.com/android/thread/29434011?hl=en 
"Answering your questions on Huawei devices and Google services."

There is also a related (closed) discussion on https://github.com/corona-warn-app/cwa-app-android/issues/490.

**Comment by codejus** [comment] 2021-01-15 18:11
@Bdschi You can try if the fork [CCTG](https://codeberg.org/corona-contact-tracing-germany/cwa-android) of the CWA is working on your P40, as it uses the bundled microG implementation of the Google/Apple ENF. I'm assuming that it schould run, but will need some tweaking with the energy saving measures of Huawei probably.

As @MikeMcC399 provided links state it will be not available officialy for devices without Google PlayService.

**Comment by Bdschi** [comment] 2021-01-16 07:38
The above fork works fine for me. Thank you @codejus.

**Comment by heinezen** [comment] 2021-01-17 13:38
Hey @Bdschi ,

For the discussion about microG and availability via F-Droid please watch https://github.com/corona-warn-app/cwa-app-android/issues/75 and https://github.com/corona-warn-app/cwa-app-android/issues/1483 respectively. Chances are that a solution to these issues will also resolve your issue. Until then, using the CCTG fork seems like the best options for you.

Compatability on Huawei phones also has a wishlist entry https://github.com/corona-warn-app/cwa-wishlist/issues/106 . Even though it is an older issue, we are still trying to find a solution. I'll close your issue in favor of https://github.com/corona-warn-app/cwa-wishlist/issues/106

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-01-17 13:38
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/106

**Closed by heinezen** 2021-01-17 13:38 UTC
Labels: enhancement
