### ISSUE TITLE
Adding a Schnelltest a second time hides the test certificate

### ISSUE THREAD

**Issue by GitRon** [corona-warn-app/cwa-app-android#5141] opened 2022-04-29 19:39 UTC
## Avoid duplicates
* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) -> as far as I can tell, I don't have an iOS device
* [ x] Bug is not already reported in another issue (used the search...)

## Technical details

- Device name: Samsung Galaxy S8
- Android version: 9
- App version: Latest

## Describe the bug

When scanning the Schnelltest QR a second time, there is a warning about this test already being in the system (even if it's in the trash or deleted). This is fine (though somehow not the best UX), when you click on overwriting the old test, it shows up in the main dashboard screen but the certificate under tab "certificates" is gone. Usually, there would be a second button next to your vaccination certificate.

## Steps to reproduce the issue

Scan schnelltest QR
Go to certificates and validate that you can view the Schnelltest certificate
Put Schnelltest in Trash (not sure if this is required)
Scan schnelltest QR again
Tell the app to overwrite the old one
Schnelltest shows up in main screen but not the certificate

## Expected behaviour

Well, the certificate is the reason why I scan it in the first place, right? So I expect it to show up.

## Possible Fix

-

## Additional context
Thx!

---
Internal Tracking ID: [EXPOSUREAPP-12981](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12981)

**Comment by larswmh** [comment] 2022-05-02 05:35
Thanks for your report @GitRon. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12981](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12981)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2022-05-02 09:45
@GitRon Thanks again for reporting: Could you please confirm, that following your steps leads to the following:
- in the certificate tab, the 2 tabs for the vaccination and test certificates disappear, and QR code of the vaccination certificate is shown?
- When you tap on the QR code and scroll down you see the list of certificates belonging to the same person. Has the test certificate also disappeared there?

Thanks for your feedback.

**Comment by GitRon** [comment] 2022-05-03 06:05
@dsarkar 

1. The vaccination certificate stays, only the tiny button where you can switch between the vaccination and the rapid test is gone and therefore I cannot select the QR of the rapid test.

2. Yes

**Comment by dsarkar** [comment] 2022-05-03 08:50
@GitRon ok, thanks for your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2022-05-03 09:56
Hi @GitRon We could not reproduce this issue on a Huawei P10 Lite, Android 7 device with CWA 2.21. We tested your steps in two versions:
- moving the RAT into the bin
- without moving the RAT into the bin.

In any case, the vaccination certificate and test certificate tabs are present all the time and do not disappear. 

Might it be that you accidentally deleted your test certificate?

Best wishes, DS

**Comment by GitRon** [comment] 2022-05-03 11:34
Even if I did and I scan the code again, I see no reason why I get the info, that the certificate will be created/restored but nothing happens on the certificate-side BUT I see it in the main screen, right?

**Comment by dsarkar** [comment] 2022-05-03 12:08
@GitRon 
- If you delete your rapid test (RAT) (but not the certificate (DCC)) you get this sequence of screens, if you scan the RAT QR code againand the RAT is recovered from the bin: 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/1409741/166449164-3c0caef6-64bb-478c-9050-fb4b7166e92c.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/1409741/166449261-91b95116-7240-420c-b35b-bbcd88b06bd4.png">
We don't observe any changes in the vaccination DCC tab and RAT DCC tab.

- if you scan your RAT again (not having to deleted it), you get this sequence of screens:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/1409741/166449615-3243186b-7945-4993-abb3-e578dac492c0.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1409741/166449653-e93f002e-bb25-4838-8c0f-c369ce5f7140.png">
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1409741/166449692-10bbbd52-4104-4fdf-a338-1a49fc0fb32c.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/1409741/166449718-64079d37-d950-430c-b12c-5d1d8d7d78cc.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1409741/166449743-95490e87-3a89-4c2c-991e-050b2f11e18d.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/1409741/166449820-624e46f2-ec99-4c91-a4de-12efb5e7a0f7.png">
Also here, we don't observe any changes in the vaccination DCC tab and RAT DCC tab.

Altogether, the RAT DCC is during whole process accessible from the tab.

**Comment by dsarkar** [comment] 2022-05-04 15:20
@GitRon Suggestion: Next time you register a RAT, try to reproduce this issue. In order not to loose your test certificate, export it as PDF file and print it before you move the RAT to the bin, so that you can scan it again, should it disappear as you described in this issue. Ideally, before you start reproducing this issue, start error logging, and also record the screen if possible. Many thanks, Best wishes, DS

See also:

- Print DCC
EN https://www.coronawarn.app/en/faq/results/#eu_dcc_export
DE https://www.coronawarn.app/de/faq/results/#eu_dcc_export
- Error logging
EN https://www.coronawarn.app/en/faq/results/#error_log
DE https://www.coronawarn.app/de/faq/results/#error_log

---
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment] 2022-06-09 06:16
Closing as suggested in https://github.com/corona-warn-app/cwa-app-android/issues/5141#issuecomment-1117384935

**Closed by larswmh** 2022-06-09 06:16 UTC
Labels: bug, mirrored-to-jira
