### ISSUE TITLE
App closing immediately on start

### ISSUE THREAD

**Issue by FriederikeHanssen** [corona-warn-app/cwa-app-android#1053] opened 2020-08-21 11:26 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

Since a couple of days the app closes immediately after opening it. 
## Expected behaviour

App opening.
## Steps to reproduce the issue

 Open the app.

## Technical details

- Mobile device: Huawei P8 Lite
- Android version: 6.0

## Additional context

 Until now, it has worked as expected. 
Restarted the phone multiple times and checked that the App is part of the protected background apps.
App version: 1.2.1

---
Internal Tracking ID: EXPOSUREAPP-2249, EXPOSUREAPP-1851

**Comment by vaubaehn** [comment] 2020-08-31 12:58
Hi @FriederikeHanssen , could you provide how things were going for you in the last 10 days? Did any crash on app start ocuur again? (Other issues like API 39508 or no automatic background update don't count here in this context ;) )
Thanks in advance for your feedback!

**Comment by FriederikeHanssen** [comment] 2020-08-31 13:03
Hi @vaubaehn ! Everything works fine and as expected now 🎉 . No crashes, no API errors either 😄

**Comment by vaubaehn** [comment] 2020-09-01 14:30
> 
> 
> Hi @vaubaehn ! Everything works fine and as expected now tada . No crashes, no API errors either smile

Hi @FriederikeHanssen , that's great! Thanks for your feedback! Please report back here, if any problem occurs again.
Last question for now:
How are your system settings, that allow CWA to run quite smoothly... as far as I read from you, you set up CWA as protected background app (system setting). Did you additionally activate "Prioritized Background Activity" from inside CWA's settings? Did you set up anything else or could you give other users with similar problems some recommendations?

Thank you very much for your support!

**Comment by FriederikeHanssen** [comment] 2020-09-07 08:33
Hi @vaubaehn!

EMUI version number: 4.0.3

Yes, when installing the app, 

1. I added it to the protected apps:
    Einstellungen > Einstellungen > Akkumanager > Geschützte Apps

2. Priorisierte Hintergrundaktivität is turned off. I actually was not aware of this feature until now.

3. Other than that, I just followed your suggestions:
    Turned off: Einstellungen > Einstellungen > Apps mit Nutzungsdatenzugriff > Huawei Mobile Services

4. And then deleting the cache & storage did solve it. However, this seems to have caused a deletion of contacts. This step should not be necessary when newly installing the app though.

**Comment by vaubaehn** [comment] 2020-09-07 11:23
Hi @FriederikeHanssen ,

thanks a lot for your well structured feedback! Personally, I find your information very useful. :+1: 

@svengabr : do you think, the stakeholders might consider it to be useful to extend the FAQ, especially for HUAWEI devices according to information/device setup presented here (points 1 to 3 provided in the afore comment by @FriederikeHanssen ) for increased stability? I would volunteer to create a PR for the FAQ (like I did before here -> https://github.com/corona-warn-app/cwa-website/pull/308) , if it is welcomed. Details could be discussed in Slack before creating PR.

@FriederikeHanssen 
Just some additional points:
As far as I currently know, there may be different root causes, which in the end of a chain may result in this app crash.
Trying to set up the device, that CWA and its background tasks/transactions are not killed by any OS specific behaviour (battery optimisation, app usage analysis (HMS), ...), can at least mitigate the likelihood of an app crash.
In this context you might want to consider to turn on "Priorisierte Hintergrundaktivität" additionally, but I can't tell, if it has a positive additional effect to decrease the probability of future crashes.
Anyway, as far as I can interpret some of the code changes, it looks like CWA will be more robust in general in future versions.
As for your point 4:

> And then deleting the cache & storage did solve it. However, this seems to have caused a deletion of contacts. This step should not be necessary when newly installing the app though.

It's not quite clear yet, whether the collected contacts (RPIs of exposures) have actually been deleted, or 'only' the history of the past checks. Unfortunately, this subject has been stale for more than two weeks now, after @thomasaugsten suggested to clarify with Google. **Maybe @svengabr can push that subject to the developers again, because if deleting CWA data proves to reliable bring back CWA to work, without deleting collected RPIs/own TEKs, then this method should be immediately made public to support a big crowd of users who frequently run into the problem of app crashes!**

Thanks again!

**Comment by FriederikeHanssen** [comment] 2020-09-07 11:28
I have turned the "Priorisierte Hintergrundaktivität" now. Will report back, if it crashes or leads to unexpected behaviour. But even without it, it has been running stable for now.

**Comment by svengabr** [comment] 2020-09-07 13:34
@vaubaehn regarding your pull request you can go ahead. @mtb77 will have a look at it afterward.

Regarding the second issue, I will bring that up to the development team to answer your question.

Thank you!

**Comment by vaubaehn** [comment] 2020-09-07 17:07
> 
> 
> @vaubaehn regarding your pull request you can go ahead. @mtb77 will have a look at it afterward.
> 
> Regarding the second issue, I will bring that up to the development team to answer your question.
> 
> Thank you!

Hi @svengabr and @mtb77 ,

Regarding the first issue (PR), thanks a lot for your consideration. I'll try to finish it within the next days. If you don't hear anything from me until Thurdsday night, feel free to ping me.

Regarding the second issue (deletion of CWA data), there was a reply by @thomasaugsten ( https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-688267231 ) , as soon as after my comment. Let's track that issue over there :) 

Thanks again!

**Comment by vaubaehn** [comment] 2020-09-10 18:45
### Erste Hilfe: „App schließt sich sofort nach dem Öffnen“

Die nachfolgenden Informationen wurden dank der Unterstützung vieler Nutzerinnen und Nutzer, sowie Entwickler aus verschiedenen Beiträgen im GitHub-Issue #642 zusammengestellt (z. B. https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-674783001 , https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-674797144 ,  https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-678687066 , https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-678692188 ). Allerdings kann ich keine Gewährleistung für Vollständigkeit und Richtigkeit geben. Anwendung auf eigene Gefahr.

Wenn die Corona-Warn-App durch einen Fehler im Betriebssystem oder durch aggressive Energiesparmaßnahmen des Telefons unerwartet beendet wird, kann es vorkommen, dass bei einem erneuten Start die Corona-Warn-App nicht mehr auf ihre verschlüsselten Datenbanken zugreifen kann. In diesem Fall schließt sie sich sofort wieder. Die Corona-Warn-App kann wieder zum Laufen gebracht werden, indem die Daten und der Cache der App über die Android-Einstellungen gelöscht werden.

### Achtung: Wenn Sie die Daten der Corona-Warn-App löschen, gehen folgende Daten/Einstellungen verloren:
-	Falls Sie zuvor über einen QR-Code einen COVID-19-Test in der App registriert hatten, kann dieser nicht mehr über die App abgerufen und auch nicht mehr erfolgreich neu registriert werden. Falls Ihr Testergebnis positiv sein sollte, werden Sie aller Voraussicht nach telefonisch oder per Post benachrichtigt.
-	Einmal am Tag übergibt die Corona-Warn-App die geteilten Codes von positiv getesteten Nutzerinnen und Nutzern an die Google-Schnittstelle, um mögliche Risiko-Begegnungen in den letzten 14 Tagen zu ermitteln. Dieser Vorgang (aber nicht die Ergebnisse selbst) wird in ein Protokoll eingetragen, dass Sie auf Ihrem Telefon über Einstellungen > Google > COVID-19-Benachrichtigungen > Überprüfungen auf mögliche Begegnungen einsehen können. Dieses Protokoll wird beim Löschen der Daten der Corona-Warn-App ebenfalls gelöscht. Nach den aktuell vorliegenden Informationen https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-688267231 bleiben aber die auf ihrem Telefon gespeicherten Codes von Begegnungen mit anderen Nutzerinnen und Nutzern erhalten, so dass beim nächsten Start der App Ihr Risiko für die letzten 14 Tage erneut ermittelt werden kann.
-	Die Anzahl der Tage, wie lange die Risiko-Ermittlung auf Ihrem Telefon aktiviert war, wird ebenfalls gelöscht. Mit einem kleinen Trick kann dieser Zeitraum aber wiederhergestellt werden (siehe unten).

### Zum Löschen der Daten der Corona-Warn-App gehen Sie wie folgt vor:
(die angegebenen Pfade zum Erreichen der jeweiligen Einstellungen können je nach Telefon und Android-Version leicht abweichen):
1.	Navigieren Sie auf Ihrem Telefon zu Einstellungen > Apps > Corona-Warn-App.
2.	Klicken Sie auf „Stoppen erzwingen“.
3.	Wählen Sie „Speicher“, und löschen Sie danach Cache und Daten, indem Sie auf die jeweiligen Buttons klicken.
4.	Um sicherzustellen, dass die Corona-Warn-App beim nächsten Start für die Risiko-Ermittlung die gesamten letzten 14 Tage berücksichtigt, können Sie zunächst das System-Datum Ihres Telefons zurückstellen https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-684953232 . Damit alle Codes für die Risiko-Ermittlung vom Server heruntergeladen werden, reicht es, wenn Sie das Datum auf den gestrigen Tag einstellen https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-688466416 . Wenn Sie auch möchten, dass die Corona-Warn-App anzeigt, dass Ihre Risiko-Ermittlung in den letzten 14 Tagen dauerhaft aktiv war, können Sie das System-Datum auch 14 Tage zurückstellen https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-685037382 . Um das System-Datum zurückzustellen, navigieren Sie auf Ihrem Telefon zu Einstellungen > Datum und Uhrzeit. Um das Datum einzustellen, müssen Sie ggf. Zeit automatisch ermitteln deaktivieren.
5.	Öffnen Sie nun die Corona-Warn-App. Ihnen wird erneut die Einführung gezeigt (das Onboarding). Führen Sie das Onboarding bis zum Ende durch. Wenn Ihnen der Hauptbildschirm angezeigt wird, warten Sie, bis Ihnen irgendein Risiko-Status angezeigt wird, und schließen Sie die App wieder.
6.	Stellen Sie nun das System-Datum wieder auf den aktuellen Tag ein (Android-Einstellungen > Datum und Uhrzeit). Aktivieren Sie ggf. wieder die automatische Zeitermittlung.
7.	Öffnen Sie nun die Corona-Warn-App erneut. Ihnen sollte nun Ihr richtiger Risiko-Status („niedriges Risiko“ oder „erhöhtes Risiko“) angezeigt werden.

### Achtung:
Um die Zuverlässigkeit der Hintergrundaktualisierung zu optimieren, und unerwarteten Abstürzen der Corona-Warn-App beim Öffnen vorzubeugen, befolgen Sie bitte diese Anleitung in den FAQ -> [hier ](https://www.coronawarn.app/de/faq/#no_risk_update).
Falls Sie ein Huawei oder Honor Smartphone besitzen, sollten Sie zusätzliche diese Punkte beachten -> hier LINK.
Falls Sie ein Smartphone eines anderen Herstellers besitzen, können Sie hier überprüfen, ob Sie noch zusätzliche Einstellungen zur Verbesserung der Zuverlässigkeit vornehmen können: https://dontkillmyapp.com/ (englisch) oder https://slack.com/intl/de-de/help/articles/360001562747-Bekannte-Probleme-mit-Android%E2%80%91Benachrichtigungen

**Comment by vaubaehn** [comment] 2020-09-10 18:46
Zusätzliche Einstellungen für ältere Huawei- oder Honor-Smartphones
Es ist bekannt, dass Huawei-Geräte ein besonders aggressives Verhalten zur Optimierung der Akkulaufzeit zeigen. So werden Hintergrundprozesse der Corona-Warn-App sehr schnell beendet, wenn die App nicht anhand besonderer Einstellungen von der Akku-Optimierung ausgenommen wird. Das ‚Killen‘ dieser Hintergrundprozesse kann dazu führen, dass die Corona-Warn-App entweder die Hintergrundaktualisierung zur Risiko-Ermittlung nicht durchführt, oder im schlimmsten Fall die Datenbanken der App beschädigt werden könnten. Es wird daher empfohlen, die ‚Priorisierte Hintergrundaktivität‘ zu aktivieren, wie in der FAQ angegeben https://www.coronawarn.app/de/faq/#no_risk_update  .
Für ältere Geräte mit EMUI 4 (z. B. Huawei P8 lite) sollte neben dieser allgemeinen Empfehlung noch eine zusätzliche Einstellung vorgenommen werden: Stellen Sie die Corona-Warn-App wie folgt als ‚Geschützte App‘ ein:
-	Navigieren Sie auf Ihrem Telefon zu Einstellungen > Erweiterte Einstellungen > Akkumanager > Geschützte Apps
-	Stellen Sie dort den Schalter für die Corona-Warn-App auf „an“.
Um die Stabilität der Corona-Warn-App zu erhöhen, ist noch eine weitere Einstellung möglich – das Entziehen der Erlaubnis auf den Zugriff der Nutzungsdaten für die Huawei Mobile Services. Ob es tatsächlich etwas bringt, oder eher nicht, ist Gegenstand der Diskussion und noch nicht abschließend geklärt (https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-678413047 https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-678542265  https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-678743289 ). Aber einen Versuch ist es vielleicht wert:
-	Navigieren Sie auf Ihrem Telefon zu Einstellungen > Erweiterte Einstellungen > Apps mit Nutzungsdatenzugriff > Huawei Mobile Services
-	Stellen Sie den Schalter auf „aus“.
-	Starten Sie das Telefon neu.
Um die Stabilität weiter zu verbessern, sollten Sie überprüfen, ob noch mindestens 2GB freier Speicher für den internen Speicher zu Verfügung stehen. Ist nämlich der Speicher zu voll (weniger als 1 GB freier Speicher), wird das Telefon immer langsamer, wodurch timeout-Probleme auftreten können. Sie erhalten dann z. B. Meldungen wie „App xyz reagiert nicht mehr“. Geben Sie in diesem Fall Speicher frei, z. B.:
-	löschen Sie besonders lange Videos, z. B. in Whatsapp
-	löschen Sie den Cache (nicht die Daten) Ihrer Apps
-	löschen Sie Apps, die Sie nicht mehr benötigen

Für neuere Huawei / Honor Smartphones liegt möglicherweise ein Firmware-Update vor, dass die Corona-Warn-App auf eine Huawei-interne White-List setzt, und vom besonders aggressiven Energiesparen ausschließt. Überprüfen Sie hier, ob Sie vielleicht ein Firmware-Update erhalten können. Link: https://www.huaweiblog.de/news/huawei-geraete-bekommen-877kb-grosses-systemparameter-update/ 
Ansonsten können Sie prüfen, ob Sie für Ihr Telefon noch weitere Einstellungen vornehmen können, z. B. hier https://dontkillmyapp.com/huawei (englisch), oder hier https://www.huaweiblog.de/news/benachrichtigungen-push-problem-loesung-anleitung/ .

**Comment by vaubaehn** [comment] 2020-09-10 18:46
placeholder

**Comment by vaubaehn** [comment] 2020-09-10 18:46
placeholder

**Comment by vaubaehn** [comment] 2020-09-10 19:03
@mtb77 @svengabr @thomasaugsten 
If you find time, you'd like to check if above instructions are appropriate.

@mtb77 : Tomorrow I will send you a draft for changes to the FAQ. If they are in line with your needs, I will create a PR respectively. FAQ changes will be short and link to above comments.
Enjoy your night!

**Comment by svengabr** [comment] 2020-09-11 08:50
Thank you very much for the effort @vaubaehn! Your texts are looking very good to me.

I would like to discuss this as a topic in our daily meeting today so maybe a developer can have a look at it before publishing it to the FAQ website.

I will keep you updated.

**Comment by vaubaehn** [comment] 2020-09-11 10:42
Hi @svengabr , thanks for your feedback. I also think, it's a good idea when dev department has a look on it.

I guess the GitHub rights management allows you to edit my comments at any time - **so, please feel free to adjust anything according to your needs!**

**Comment by vaubaehn** [comment] 2020-09-11 17:30
@mtb77 (and @svengabr ) : You've Got Mail

;)

**Comment by GPclips** [comment] 2020-09-29 12:08
This issue has been marked as obsolete and will be closed now.

**Comment by GPclips** [comment] 2020-09-29 15:24
Hello community,

this issue has been closed by mistake.
I will reopen it.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by FriederikeHanssen** [comment] 2020-10-04 18:43
Hi!

Same thing happened again. Deleting cache&storage fixed it, but once again it looks like the IDs have been deleted.

Cheers,

**Comment by sandoxy** [comment] 2020-10-17 08:02
My CWA P8 lite started to crash at startup, after I used it for more the 14 days. Now I did the following steps:

1. I turned of the access for huawei to user data
2. I turned of battery optimization fo CWA
3. I turned on preor. background activity in CWA
4. I forced CWA to stop
5. I deleted cache and data of CWA
6. I changed system date to 03.10.
7. I started CWA again and followed thr instructions
8. I closed CWA
9. I chanched system date back to today

CWA says: no risc status known, because CWA did not run 14 days

Google-Covid shows 14 checkups from today. The other checkups, wich where there before I deleted the CWA-data, are gone. And the checkup from today does not contain any keys - key-amount=0.

What did I do wrong?

**Comment by svengabr** [comment] 2020-10-20 08:06
Could you please update to the latest version 1.5 and test if the update did fix the error?

**Comment by sandoxy** [comment] 2020-10-20 08:28
> Could you please update to the latest version 1.5 and test if the update did fix the error?

The app seemed to work after the reset of cache and data, before the update. But the contacts for the last 14 days are still lost (V1.5).

**Comment by FriederikeHanssen** [comment] 2020-10-20 08:38
Updated it just now. now it hangs in the start screen (Logo on background) for about 10 seconds and then dies. Up until now it at least opened and I could navigate to the main window.

**Comment by sandoxy** [comment] 2020-10-20 10:26
> My CWA P8 lite started to crash at startup, after I used it for more the 14 days. Now I did the following steps:
> 
>     1. I turned of the access for huawei to user data
> 
>     2. I turned of battery optimization fo CWA
> 
>     3. I turned on preor. background activity in CWA
> 
>     4. I forced CWA to stop
> 
>     5. I deleted cache and data of CWA
> 
>     6. I changed system date to 03.10.
> 
>     7. I started CWA again and followed the instructions
> 
>     8. I closed CWA
> 
>     9. I chanched system date back to today
> 
> 
> CWA says: no risc status known, because CWA did not run 14 days
> 
> Google-Covid shows 14 checkups from today. The other checkups, wich where there before I deleted the CWA-data, are gone. And the checkup from today does not contain any keys - key-amount=0.
> 
> What did I do wrong?

After update to 1.5. I did all the steps above againg and again all contacts are lost.

**Comment by daimpi** [comment] 2020-10-20 10:55
@sandoxy @FriederikeHanssen 

Your keys are not lost as long as you just deleted the CWA data and didn't un-/reinstall the app. They are still safely stored inside the Google Exposure Notification Framework (ENF). 

That "days active" is zero again is just a display problem, but function wise nothing is lost. If you care about getting the full "14 days active" display immediately again just follow @vaubaehn's instructions [here](https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690615473). 

Some background: Afaiu the update to 1.5 should have caught errors such as yours, but [there was a bug](https://github.com/corona-warn-app/cwa-app-android/pull/1433) in the implementation (see also @vaubaehn's explanation [here](https://github.com/corona-warn-app/cwa-app-android/issues/1121#issuecomment-712758505)) which is why the error was not caught and you were not properly informed by the app.

**Comment by vaubaehn** [comment] 2020-10-20 11:01
Hi @sandoxy ,

I'm a common user like you, but familiar with that issue, I will try to support you a little.

> CWA says: no risc status known, because CWA did not run 14 days
> 
> Google-Covid shows 14 checkups from today. The other checkups, wich where there before I deleted the CWA-data, are gone. And the checkup from today does not contain any keys - key-amount=0.
> 
> What did I do wrong?

I'm not sure what went wrong here for you in particular - all steps you told us seem to be right, and for other users this procedure was succeeding.

... in the moment I'm writing here, above @daimpi already answered (and again: ... one thought :laughing: )

> > Could you please update to the latest version 1.5 and test if the update did fix the error?
> 
> The app seemed to work after the reset of cache and data, before the update. But the contacts for the last 14 days are still lost (V1.5).

like @daimpi wrote already, contacts should not be lost, only the entries in the log are gone.

> After update to 1.5. I did all the steps above againg and again all contacts are lost.

like @daimpi wrote, contacts are retained, but due to a problem in a bug fix, CWA's data could not be reset automatically during the upgrade to 1.5.

**Comment by vaubaehn** [comment] 2020-10-20 11:11
Hi @FriederikeHanssen ,
happy to find you here again (thanks for reporting!), but I'm sad about the circumstances :cry: .
I'm trying to gather some information, to understand the underyling root cause better and to support developers in that way.

> 
> Updated it just now. now it hangs in the start screen (Logo on background) for about 10 seconds and then dies. Up until now it at least opened and I could navigate to the main window.
> 
> Update: I deleted storage & cache and it works again for now. But any previous contacts are gone. Will update you in the next days whether it is now running or failing again

Did I understand you right:
- On October 4, CWA crashed again for you, and you cleared storage and cache.
- Since then, the app was working fine again, just until you updated to CWA 1.5.0.
- After the update, opening the app first time in version 1.5.0, CWA's boot logo hangs for around 10 seconds, then app crashes.
- Opening CWA again after results again in a crash.
- You then cleared CWA's storage again, and now it works.

Did I understand everything correct? Having your feedback would be very helpful indeed.

And as @daimpi already wrote, only the history of checks should be cleared, but not the collected contacts. We had a verification for that in a different issue yesterday, that a risk encounter was showing up again after solely deleting storage, following the procedure above in this thread.

Thank you!

**Comment by sandoxy** [comment] 2020-10-20 13:02
> @sandoxy @FriederikeHanssen
> 
> Your keys are not lost as long as you just deleted the CWA data and didn't un-/reinstall the app. They are still safely stored inside the Google Exposure Notification Framework (ENF).

When I go to Settings-> Google->Covid-19.
I see just two checkups, 08.10.(into that date I changed the settings while I resetted cache and data) and today.

CWA shows, that it runs for 12 days. 

I did not reinstall tve app.

**Comment by daimpi** [comment] 2020-10-20 13:14
@sandoxy could you provide us your device name, Android version and ENF version (ENF version can be found [here](https://www.coronawarn.app/de/faq/#ENF_version)).

**Comment by sandoxy** [comment] 2020-10-20 13:20
> @sandoxy could you provide us your device name, Android version and ENF version (ENF version can be found [here](https://www.coronawarn.app/en/faq/#ENF_version)).

Of cource:
Huawei P8 lite
Emui 4.0.3
Android 6.0
Version 17203704005

**Comment by FriederikeHanssen** [comment] 2020-10-20 20:43
@vaubaehn ,

let's hope this helps fixing it then 😃 .

 - On Oct 4th app crashed -> I followed the above steps
 - Worked fine for a while, but eventually crashed again (can't tell you precisely when)
 - Repeated the above steps, just in case. Eventually, this also didn't help anymore. 
 - Actually installed the Swiss covid app, it was written in some issue that this would preserve the contacts. Re-installed CWA, set it up as above, crashed as well
 - At some point then reported here again and was advised to update to 1.5.0, which I did. Then it got stuck in the start screen, clearing cache&storage ones again helped

Let me know, if you need more info.

@daimpi Great to hear the contacts are not lost 👍 . I assumed they would be, because when I navigate to Google > Covid Benachrichtigungen it only shows a few (10ish or fewer) and only from the date of when I reseted storage &cache.

**Comment by vaubaehn** [comment] 2020-10-21 01:58
Hi @FriederikeHanssen , thanks again for your support!

Please excuse my following pedantic questions... As we have 50 Shades of Crashes with CWA, I just want to be double sure, we're having only one source of crash here.

> * On Oct 4th app crashed -> I followed the above steps
> * Worked fine for a while, but eventually crashed again (can't tell you precisely when)
> * Repeated the above steps, just in case. Eventually, this also didn't help anymore.

Were all of these crashes of the same type? I'm asking, because you wrote in the third step, that clearing cache and data didn't help anymore, what would point to a different root cause.
Did you see something like "9002: timed out while waiting for 60000 ms"? Or "cause 3: API(10).. no public key found"? Or have all crashes been like your first reported one: app immediately closing on start, without any error message?

> * Actually installed the Swiss covid app, it was written in some issue that this would preserve the contacts. Re-installed CWA, set it up as above, crashed as well

Same here: app closing or some different error message?

> * At some point then reported here again and was advised to update to 1.5.0, which I did. Then it got stuck in the start screen, clearing cache&storage ones again helped

That last one actually looks like the "old" app closes immediatly on start.

Thanks again...

**Comment by svengabr** [comment] 2020-10-22 09:02
Hey everyone,

according to our developer's meeting, the issue is most likely related to https://github.com/corona-warn-app/cwa-app-android/issues/642 which should have been initially resolved for 1.5. Unfortunately, a small code fragment needed to be added which will be part in an upcoming hotfix release 1.5.1.

The related pull request is https://github.com/corona-warn-app/cwa-app-android/pull/1433

In the mean time you could try the workaround of @vaubaehn 

Thank you very much for your understanding!

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Neuwessi11** [comment] 2020-10-22 22:38
Hi svengabr,

gibt es denn schon eine Vorstellung von dem ungefähren Termin, an dem das Hotfix kommt?

**Comment by Neuwessi11** [comment] 2020-10-30 10:37
Hi at all,
my sister told me, that nothing has changed.
Even after updating to 1.5.1 white screen with CWA-symbol, no chance of pressing any button, followed by a shutdown of the app.
I maybe should mention that she did not try the workaround, because she hoped for the 1.5.1. But this unfortunatly did not work in her case.

Still Huawei P8 Lite
Android 6.0

**Comment by MikeMcC399** [comment] 2020-10-30 11:03
@Neuwessi11 

If your sister's app is still crashing then the options are:

1. Workaround by deleting the app data, which means that the history of exposure checks is lost. We are told though that the actual keys are kept, even though you can't see them. (See https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-688267231).
2. Wait for version 1.6 which is expected to fix the issue in https://github.com/corona-warn-app/cwa-app-android/issues/642 which is another one of the hot topics.

I have no information about when 1.6 will be released, but I would expect it will be soon.

**Comment by Neuwessi11** [comment] 2020-10-31 20:21
Thanks again!

My sister now tried the workaraound incl. changing of time settings, and today is already the 2. day CWA working!

So thanks to all who answer and answered here!

But one point of criticism is still left: I am a complete unsuspecting layman in app-building, but it is more than hard for me to understand why a workaround is necessary for not too less people just to make CWA working. Especially when this bug is known for months. Why has it during months not been possible to fix this bug? It is the Telekom and SAP writing the app, and as far as I know these are two very big players (recieving some money for that) and not only my cousin or brother-in-law scribbling around in their leisure time.
Please do not misunderstand me: I don't want at all to revile all the people who write here in their leisure time to help those unsuspecting people like me, and I have the utmost respect to all these people, especially regarding that the workaround came from them and neither from Telekom nor SAP.
Have a nice weekend!

**Comment by heinezen** [comment] 2020-12-26 09:53
This was addressed in CWA 1.5 and 1.6. The issue should be fixed now. Please comment here if it is still re-occuring for you.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2020-12-26 09:53 UTC
Labels: bug, mirrored-to-jira
