### ISSUE TITLE
Wrong share-link

### ISSUE THREAD

**Issue by NickWue** [corona-warn-app/cwa-app-android#485] opened 2020-06-16 06:30 UTC
The share link (english and german) is https://www.corona-warn-app.de/ which is not available. Correct link (I assume) should be https://www.coronawarn.app/de/. I am on Android, Huawei Mate 20.

**Comment by tomjschwanke** [comment] 2020-06-16 06:32
Duplicate of #480

**Comment by w-flo** [comment] 2020-06-16 06:32
The share link works for me, but seems to be slow right now. Probably due to high load.

**Comment by SebastianWolf-SAP** [comment] 2020-06-16 06:48
Closing as discussed in #480 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-16 06:48 UTC
Labels: bug
