### ISSUE TITLE
Valid certificate results in VC_HC_CBOR_DECODING_FAILED

### ISSUE THREAD

**Issue by ltekieli** [corona-warn-app/cwa-app-android#3417] opened 2021-06-10 19:42 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung J5 2017, Samsung M31
- Android version: 9, 10
- App version: 2.3.2

## Describe the bug

I have a EU Digital COVID certificate issued in Poland. The certificate, according to the Android App is not valid and results in an error code: VC_HC_CBOR_DECODING_FAILED

The same certificate can be successfully imported in the iOS version of the application.

I tried two different certificates, on different Android phones and the result is the same.

## Steps to reproduce the issue

1. Scan the certificate

## Expected behaviour

Certificate is correctly imported, same as on the iOS version of the app.

---
- Internal Tracking ID: [EXPOSUREAPP-7776](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7776) 
VC_HC_CBOR_DECODING_FAILED
- Internal Tracking ID: [EXPOSUREAPP-7829](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7829) 
CovPassCheck does not accept Polish/Bulgarian DCC shown on CWA

**Comment by vaubaehn** [comment] 2021-06-10 19:49
Can someone try if this is reproducable with QR codes found here:
https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/PL

**Comment by vaubaehn** [comment] 2021-06-10 19:54
@ltekieli Could you try if you are able to import your certificate into the CovPass app:
https://play.google.com/store/apps/details?id=de.rki.covpass.app

This might help to see if the problem is Android related or CWA specific.

**Comment by ltekieli** [comment] 2021-06-10 19:59
> Can someone try if this is reproducable with QR codes found here:
> https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/PL

I tried those QR codes and I can import all of them, even nr. 9 which is labelled as incorrect.

> @ltekieli Could you try if you are able to import your certificate into the CovPass app:
> https://play.google.com/store/apps/details?id=de.rki.covpass.app
> 
> This might help to see if the problem is Android related or CWA specific.

I also cannot import it here. Error:
```
Es ist ein unerwarteter Fehler aufgetreten
```

**Comment by thomasaugsten** [comment] 2021-06-10 20:01
@ltekieli  The reference certificates from poland are working fine. Can you please provide me a photo of the certificate via email
thomas.augsten@sap.com

**Comment by vaubaehn** [comment] 2021-06-10 20:10
at first glance sounds like the certificate was issued with a flaw, that iOS cbor lib can recover, but Android cbor lib can't...

Would be great if you could keep us updated on your findings, @thomasaugsten . Thank you

**Comment by vaubaehn** [comment] 2021-06-10 20:17
@ltekieli Would you like to try another experiment? After you imported your certificate into CWA iOS, are you able to import the in-app QR code from iOS to CWA Android?
There is a good chance that this works, as the health certificate might be encoded correctly again by CWA iOS after decoding the flawed original.

**Comment by ltekieli** [comment] 2021-06-10 20:28
> @ltekieli Would you like to try another experiment? After you imported your certificate into CWA iOS, are you able to import the in-app QR code from iOS to CWA Android?
> There is a good chance that this works, as the health certificate might be encoded correctly again by CWA iOS after decoding the flawed original.
> Edit: in case this does not work, I'd suspect treating of (some few) special characters in cbor is different between iOS and Android

I tried it, and it does not work, error code is exactly the same.

**Comment by vaubaehn** [comment] 2021-06-10 20:29
@ltekieli Thank you, I guess that narrows the source of error.
This could be a bigger problem, maybe not only affecting CWA but also other apps/other countries

**Comment by stgeo** [comment] 2021-06-10 21:04
I also have this problem with a Bulgarian vaccination certificate. I get the same error message and the following detailed trace:
`de.rki.coronawarnapp.vaccination.core.certificate.InvalidHealthCertificateException: CBOR decoding failed.
de.rki.coronawarnapp.vaccination.core.certificate.InvalidHealthCertificateException: CBOR decoding failed. at de.rki.coronawarnapp.vaccination.core.qrcode.VaccinationQRCodeExtractor.extract(VaccinationQRCodeExtractor.kt:51) at de.rki.coronawarnapp.vaccination.core.qrcode.VaccinationQRCodeExtractor.extract(VaccinationQRCodeExtractor.kt:1) at de.rki.coronawarnapp.vaccination.core.qrcode.VaccinationQRCodeValidator.validate(VaccinationQRCodeValidator.kt:5) at de.rki.coronawarnapp.vaccination.ui.scan.VaccinationQrCodeScanViewModel$onScanResult$1.invokeSuspend(VaccinationQrCodeScanViewModel.kt:12) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:12)`

Out of the 4 QR codes at https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/BG the app only accepts the 3rd one labeled "Vaccinated DGC - schema errors fixed", all others report the same error.

I do not have an iOS device to test that app. If one the devs wants to take a look, I can send you my QR code.

**Comment by vaubaehn** [comment] 2021-06-10 21:07
@thomasaugsten 
Do you know if CovPass App and CWA Android use the same code base (i.e., CovPass "forked" from CWA)?

**Comment by thomasaugsten** [comment] 2021-06-10 21:09
Bulgaria app will be fixed tomorrow 
CovPass and CWA not sharing a code base

**Comment by vaubaehn** [comment] 2021-06-10 21:11
@stgeo Do you have any "special character" in your name or address or another field, like @ltekieli has in its name: Ł in Łukasz ?

**Comment by vaubaehn** [comment] 2021-06-10 21:21
@stgeo 
> Out of the 4 QR codes at https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/BG the app only accepts the 3rd one labeled "Vaccinated DGC - schema errors fixed", all others report the same error.

As the first two have schema errors, an error while decoding can be expected. The 3rd one is corrected, and the 4th one is a recovery certificate, that is not yet accepted by CWA afaik.

Did you try only with these 4 or did your intial error come up with a valid certificate issued to you?

**Comment by stgeo** [comment] 2021-06-10 21:30
@vaubaehn 
> Do you have any "special character" in your name or another field, like @ltekieli has in its name: Ł in Łukasz ?

No special characters in my latinized name or address - all ASCII - but the originals are in Cyrillic, I don't actually know what's encoded in the QR code. There is actually no address printed on the certificate and all names are in both Curillic and Latin.

> Did you try only with these 4 or did your intial error come up with a valid certificate issued to you?

The initial error was with my personal certificate.

**Comment by thomasaugsten** [comment] 2021-06-11 10:24
A fix for Bulgaria and Poland will be delivered tomorrow with Android v2.3.4

**Comment by vaubaehn** [comment] 2021-06-11 13:45
Hi @thomasaugsten , I understood the underlying problem of this issue as follows:
There is no bug in the platform specific implementation, but some issuing authorities want to stay a little bit, er, flexible on how to use some data fields. This would require all scanning and validating apps to be as lenient/relaxed to the data as the issuing authorities make use of it.
By chance, CWA iOS was already relaxed enough to decode CBOR without crashing. But neither CWA Android nor CovPass App were similarly lenient.

Is my interpretation correct?

If my interpretation is correct, are you in contact with CovPass to forward these findings?
And what will be future consequences? Will all issuing instances (European-wide) with their own interpretation of data field contents/formats needed to be notified to correct their use? Or will all app developers (European-wide) need to adapt for any anticipated possible divergence of expected data formats?
If not, many travellers may experience bad surprises, when they travel only with their digital certificate, that was successfully scanned by their relaxed wallet app, but cannot validated by a verifier app that uses the consented constraints for data fields...

**Comment by thomasaugsten** [comment] 2021-06-11 13:49
I can confirm all points.
There is a schema definition and some country add the time to date and now the schema definition needs to relax the checking on this
This is reported back to the EU and they will inform all apps and adjust the schema definition.

**Comment by vaubaehn** [comment] 2021-06-11 13:49
@thomasaugsten Thank you! Let's hope the best then.

**Comment by stgeo** [comment] 2021-06-11 14:23
Thanks for the fast response! I'll try with v2.3.4 when it rolls out on Google Play and I'll check back in with the results.

**Comment by thomasaugsten** [comment] 2021-06-12 19:49
@stgeo  @ltekieli  The v 2.3.4 is available for download please retest the version with your QR-Codes

**Comment by ltekieli** [comment] 2021-06-12 19:55
> @stgeo @ltekieli The v 2.3.4 is available for download please retest the version with your QR-Codes

Works fine for me, thanks!

**Comment by vaubaehn** [comment] 2021-06-12 20:24
@ltekieli 
Could you please try with [CovPassCheck App](https://play.google.com/store/apps/details?id=de.rki.covpass.checkapp) if your QR presented with CWA is accepted? You will need a second phone to achieve this...

**Comment by ltekieli** [comment] 2021-06-13 07:35
> @ltekieli
> Could you please try with [CovPassCheck App](https://play.google.com/store/apps/details?id=de.rki.covpass.checkapp) if your QR presented with CWA is accepted? You will need a second phone to achieve this...

CovPassCheck fails to validate the CWA generated QR code, with message "Prüfung nicht erfolgreich".

I installed CovPassCheck both on Android and iOS, it fails the same way.

**Comment by stgeo** [comment] 2021-06-13 11:33
> @stgeo @ltekieli The v 2.3.4 is available for download please retest the version with your QR-Codes

Also works for me, thanks! I actually think it was already fine on Friday after update to 2.3.3.

> Could you please try with [CovPassCheck App](https://play.google.com/store/apps/details?id=de.rki.covpass.checkapp) if your QR presented with CWA is accepted? You will need a second phone to achieve this...

Version 0.160.3 of CovPassCheck also failed for my certificate with "Es ist ein unerwarteter Fehler aufgetreten."

**Comment by vaubaehn** [comment] 2021-06-13 12:55
@ltekieli and @stgeo Thank you so much for your support!

@chiljamgossow and @d4rken 
How are the scanned DCC data persisted inside CWA for generating a QR code at a later time for presentation to a verifier app?
**Exactly** bit by bit like they have been scanned? Then this would mean, that the generated QR code has a valid PKI signature, but the CovPassCheck (and possibly all other verifier apps) refuse the wrong field format introduced by the issuing authority.
Or is the scanned data sanitized (i.e., the superflous timestamp is eliminated) and persisted? That would break the PKI signature upon presentation, and lead to refusal in all verifier apps, now and in future.

Pinging @mlenkeit here, also pointing to https://github.com/corona-warn-app/cwa-app-android/pull/3403#discussion_r649057138 :
It looks like the whole approach how to handle correctly signed DCCs with issues in their JSON fields need to be re-evaluated.

In discussions with @thomasaugsten I understood, that ehn will adapt schemas that also will retain backwards compability. But for now I don't see any hint that they will be able to incoorporate all potential issues.
Maybe it would be good to mirror back the problems and your findings back to the EU taskforce in charge asap, and to find a solution that can also account for the already faulty issued DCCs in a coordinated approach.
Thomas mentioned the "business rule runner", but after having a look into the related schema repos, I have my doubts that a rule runner can solve all these problems.

**Comment by vaubaehn** [comment] 2021-06-13 20:18
After looking into https://github.com/eu-digital-green-certificates/dgc-testdata/issues/298 and to other issues reported in that repo, I'm wondering if it is useful at all for the time being to have ANY wallet app and verifier app live and in production.
It becomes obvious, that many issues already exist, and by adjusting schemas and their validation rules new issues may be introduced.
As far as I understand the whole current approach, it will work only reliably for users/travellers from that only moment on, when
a) wallet apps nearly accept anything for importing, storing and later presentation of DCCs/QR codes, and
b) verifier apps everywhere work without any issue, meaning they are working that flexible that they can update their validation rules at any time.

For now, for me it looks like we're still far away from that point.

If wallet apps like CovPass but also CWA are already offering their service, we'll probably see much more often problems like reported in this issue.

This may result in
a) users, who are irritated why their DCCs are not imported to CWA (any other wallet app) or not being successfully approved by any/some verifier apps, and
b) likely much headache on our developers side, to continuously catch up with necessary adjustments caused by implementation problems all over the EU.

The only useful application of DCCs with wallet apps and verifiers, I can only see at the national level for this point in time, as single code adjustments to the apps (if necessary at all) can be controlled by far more easy. (To achieve this, CWA could refuse any non-DE DCC, until the EU DCC system works reliably).

If we leave the situation like it is for now, then at least CWA should present a warning to the user, that it cannot be guaranteed that the imported DCC is valid/approved at all points of verification.

I'd be happy to hear/read your thoughts - maybe I'm wrong or perceiving the problem bigger than it actually is?

**Comment by dsarkar** [comment] 2021-06-14 06:09
Good morning @ltekieli @stgeo @vaubaehn, Thanks for reports and latest discussion. Internally tracked:
Internal Tracking ID: [EXPOSUREAPP-7829](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7829) 
CovPassCheck does not accept Polish/Bulgarian DCC shown on CWA

**Comment by vaubaehn** [comment] 2021-06-14 12:13
Follow-up: I also placed some of the above questions here: https://github.com/eu-digital-green-certificates/dgc-testdata/issues/298#issuecomment-860619264

**Comment by d4rken** [comment] 2021-06-14 18:02
> How are the scanned DCC data persisted inside CWA for generating a QR code at a later time for presentation to a verifier app?
Exactly bit by bit like they have been scanned?

We store the original QR code and decode on-the-fly when necessary.

See (for 2.4.x):
https://github.com/corona-warn-app/cwa-app-android/blob/e1d100bf8959cdb4bbc7ee29cb86c593a8cdee52/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/VaccinationQRCodeExtractor.kt#L29-L42
https://github.com/corona-warn-app/cwa-app-android/blob/e1d100bf8959cdb4bbc7ee29cb86c593a8cdee52/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/qrcode/DccQrCode.kt#L7-L16
https://github.com/corona-warn-app/cwa-app-android/blob/e1d100bf8959cdb4bbc7ee29cb86c593a8cdee52/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt#L20-L23

**Comment by vaubaehn** [comment] 2021-06-14 20:57
@d4rken 
> We store the original QR code and decode on-the-fly when necessary.

Great, and thanks for the pointer into the code.

So biggest headache/challlenge for CWA then seems to be how to incorporate all other known and still unknown deviations from the schema (currently 1.3) to allow for a basic but relaxed validation for accepting and decoding DCC.

And let's see how the verifier apps will do.

**Comment by heinezen** [comment] 2021-06-20 14:31
@ltekieli 

We have fixed this bug in CWA hotfix release 2.3.4. Please retest with the current app version.

----
Corona-Warn-App Open Source Team

**Comment by ltekieli** [comment] 2021-06-21 09:23
> @ltekieli
> 
> We have fixed this bug in CWA hotfix release 2.3.4. Please retest with the current app version.
> 
> Corona-Warn-App Open Source Team

Yes, we already checked and the 2.3.4 works fine.

FYI, the Polish wallet app https://play.google.com/store/apps/details?id=pl.nask.mobywatel&hl=pl&gl=US is now supporting the certificates. What I noticed is that my certificates were regenerated and now have a different identification number. This certificate is now correctly scanned by the CovPassCheck application.

**Comment by vaubaehn** [comment] 2021-06-21 10:20
@ltekieli 
> What I noticed is that my certificates were regenerated and now have a different identification number.

Do I understand correctly:
* you imported the troubled Polish certificate to the Polish wallet app
* At some point in time, your DCC was regenerated with correct field formats and pushed into your wallet app actively by the related health authority?

@heinezen 
For a short sum-up: Not only the Polish DCC (@ltekieli ) was affected from not being imported into CWA due to wrong usage of allowed field formats by the issuing institutions, but also the Bulgarian DCC (@stgeo ). There is a certain likelihood that more issues may pop up with other DCCs in the future, too.
CWA devs could handle that gracefully by adapting JSON field parsing and validating.
But then there was the problem, that verifier apps (here: CovPassCheck-App) had the same problem in not being able to correctly parse the DCC, and in result not accepting them. That part of the problem is also tracked in this issue, and here: https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7829

So the still open problem in this issue is, how CWA should handle similar DCC flaws in the future. If CWA devs adapt quickly to accept DCCs with flaws, it could be, that users may import generally valid DCCs into CWA, but later be rejected at border control, because their verifier apps have not been updated that fast.
The minimalst solution could be, to provide a warning to the user inside CWA, that there is no guarantee that the DCC will be accepted at border control.
The best solution would be, that all wallet apps and verifier apps could rely on a centrally maintained and updated config that can be used for a more dynamic and flexible field parsing, and that would need to be implemented into CWA as well (note: this is not the business rule runner that has a different aim. I'm not sure if maybe CertLogic introduced by @dslmeinte could solve the problem?).

As long it's unclear which way CWA should go and we'll receive feedback here, I'd suggest to leave this Issue open.

**Comment by ltekieli** [comment] 2021-06-21 10:32
> Do I understand correctly:
> 
>     * you imported the troubled Polish certificate to the Polish wallet app
> 
>     * At some point in time, your DCC was regenerated with correct field formats and pushed into your wallet app actively by the related health authority?
> 
No, the polish wallet received the certificate synchronization just today. It does the import automatically from the polish health portal. So I imported the certificate and noticed it has a different ID. I also download the PDF directly from the health portal and it now contains a new ID as well.
So the DCC was regenerated at some point.

**Comment by vaubaehn** [comment] 2021-06-21 10:54
@ltekieli 
Thanks for your explanation. Sounds like a great approach how it was designed in Poland. Maybe one day we get Germany digitized as well...

**Comment by heinezen** [comment] 2021-06-22 11:20
>But then there was the problem, that verifier apps (here: CovPassCheck-App) had the same problem in not being able to correctly parse the DCC, and in result not accepting them. That part of the problem is also tracked in this issue, and here: https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7829

That was a different issue than the one in CWA, in the CovPassCheck app (which got fixed).

> The best solution would be, that all wallet apps and verifier apps could rely on a centrally maintained and updated config that can be used for a more dynamic and flexible field parsing, and that would need to be implemented into CWA as well (note: this is not the business rule runner that has a different aim. I'm not sure if maybe CertLogic introduced by @dslmeinte could solve the problem?).

As far as I know that already exists (or is planned). You can request the individual schemas the countries use through the DCC API. Using the correct schema is mostly the responsibility of the verifier app.

----
Anyway, I suggest opening a new discussion/question issue for schema validation in cwa-documentation if that needs more input for discussion because it is out of scope for this specific Android issue. The bug is fixed and all related tickets have been completed already. 

I'll close here and we can either mirror the relevant comments or link them in the new issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-06-22 11:20 UTC
Labels: Fix 2.3.4, bug, mirrored-to-jira
