### ISSUE TITLE
Not downloadable in neighboring countries (here CZ)

### ISSUE THREAD

**Issue by WastlDe** [corona-warn-app/cwa-app-android#500] opened 2020-06-16 08:19 UTC
We have thousands of daily cross-border commuters (e.g. from .CZ) - The app is not downloadable if the CZ play-store is active (I assume it also applies for other countries like PL). For foreigners living(!) in germany it makes sense to change the app store locale but for commuters and day/short time tourists this is not an acceptable solution. please allow it globally. 
Attached pic I got from a person who lives in CZ but works in DE - It says: The application is not availiable in your country.
![FB_IMG_1592295494304](https://user-images.githubusercontent.com/44362954/84749805-c1e4da00-afba-11ea-98f0-70434faf9c98.jpg)

**Comment by tomjschwanke** [comment] 2020-06-16 08:21
Duplicate of #478

**Comment by SebastianWolf-SAP** [comment] 2020-06-16 10:43
Closing as duplicate, see #478 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-16 10:43 UTC
Labels: bug, duplicate
