### ISSUE TITLE
(at least) low risk exposure count clears the next day in v1.5

### ISSUE THREAD

**Issue by Optiligence** [corona-warn-app/cwa-app-android#1497] opened 2020-10-29 04:09 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

3 times since the update my low risk exposure count immediately dropped the following day

Before the update to v1.5 i had 2 low risk encounters. 
After i got the update on the 22nd i had 1 low risk encounter. 
From the 23rd to the 27th 0. 
On the 28th 1 new and today again 0. 

It’s hard for me to believe that they drop immediately the next day several times like this. (and i have no way to verify)

## Steps to reproduce the issue

get 1 low risk exposure
wait 1 day
observe 0

## Technical details

- Mobile device: v1.5.1
- Android version: 9

## Additional context

[all-exposure-checks.json (6).txt](https://github.com/corona-warn-app/cwa-app-android/files/5456079/all-exposure-checks.json.6.txt)

**Comment by quickcoffee** [comment] 2020-10-30 08:43
experienced the same behavior today.
Yesterday the counter increased to 1 (was 0 before) and today back to 0.

**Comment by 0bitas** [comment] 2020-10-30 12:07
I have experienced a similar behavior.
In the json file, it looks like all old hash keys are deleted after one day. 

**Technical Details** 
Andorid version 8
Warn app version 1.5.1

[all-exposure-checks.json.txt](https://github.com/corona-warn-app/cwa-app-android/files/5464979/all-exposure-checks.json.txt)

**Comment by thomasaugsten** [comment] 2020-10-30 20:43
This behavior is normal because the keys are deleted after 14 days. In your case you saw 13 days ago a person which has submitted his keys yesterday. This is the reason why you get today a low risk and today the low risk was gone because it was deleted after 14 days from your phone

**Comment by Optiligence** [comment] 2020-10-30 20:57
as i said, this happened basically 3 times since the update and there was no behavior that would showcase it functioning correctly…

**Comment by Optiligence** [comment] 2020-10-31 00:56
a new curious development: 

i started using RaMBLE to register BLE signals manually
and [corona-warn-companion-android](https://github.com/mh-/corona-warn-companion-android) now shows a match for the evening of the 28th (cwa was matching in morning)

cwa does not show any matches although it refreshed just now

my phone is not rooted, so unfortunately i cannot say for certain that cwa was picking up that signal as well, but it’s certainly another indicator in the wrong direction

**Comment by thomasaugsten** [comment] 2020-10-31 11:34
The RPIs are collected by the ENF of Google. The ENF decides which RPIs are stored. The ENF has also a lower scan rate than RaMBLE. The CWA is displaying only the values of the ENF when you root your device I'm very confident the RPI you collected via RaMBLE is not stored int the ENF database.

**Comment by Optiligence** [comment] 2020-11-03 11:26
today again: low risk exposure that appeared yesterday is already gone

**Comment by heinezen** [comment] 2021-01-12 12:06
This was addressed in a blogpost: https://www.coronawarn.app/en/faq/#encounter_deletion . As @thomasaugsten pointed out in https://github.com/corona-warn-app/cwa-app-android/issues/1497#issuecomment-719788304 , this behaviour is normal and very likely not a bug.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-01-12 12:06 UTC
Labels: bug
