### ISSUE TITLE
Fehlercode #39508

### ISSUE THREAD

**Issue by JohnGrgn** [corona-warn-app/cwa-app-android#1568] opened 2020-11-10 17:56 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Mobile device:
- Android version:

**Comment by MikeMcC399** [comment] 2020-11-10 18:11
Hello @JohnGrgn 

The error code 39508 you mentioned in the title is being handled in the issue https://github.com/corona-warn-app/cwa-app-android/issues/1459.

If you are using the current version of the app, which is 1.5.1, you might like to try the steps in https://github.com/corona-warn-app/cwa-app-android/issues/1459#issuecomment-724099296 which were successful for another user.

It would be useful to hear from you which mobile device you are using and what version of Android operating system is running on your device. You can add this information to the issue https://github.com/corona-warn-app/cwa-app-android/issues/1459.

**Comment by dsarkar** [comment] 2020-11-11 09:35
Dear @JohnGrgn,

Thank you very much for reporting this issue. As mentioned by @MikeMcC399 it is a duplicate of
https://github.com/corona-warn-app/cwa-app-android/issues/1459. Please, post your issue there, so we can collect all the information on this specific topic in only place. Also, please add the information requested by @MikeMcC399. I will have to close this issue as a duplicate. Thank you again.


Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-11 09:35
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1459

**Closed by dsarkar** 2020-11-11 09:35 UTC
Labels: bug, duplicate

**Comment by otacke** [comment] 2020-11-13 00:44
I am getting this error on 1.6.0.
