### ISSUE TITLE
com.google.android.gms.common.api.ApiException on Android 6.0

### ISSUE THREAD

**Issue by not-a-user** [corona-warn-app/cwa-app-android#773] opened 2020-06-27 14:34 UTC
Consistently showing up every time the app is brought up:

![Screenshot_2020-06-27_141604](https://user-images.githubusercontent.com/1785927/85924586-9522a380-b893-11ea-837c-078f23a3f7b2.jpg)
![Screenshot_2020-06-27_141611](https://user-images.githubusercontent.com/1785927/85924589-994ec100-b893-11ea-8a36-557887a990c7.jpg)
![Screenshot_2020-06-27_162448](https://user-images.githubusercontent.com/1785927/85924593-9eac0b80-b893-11ea-9a43-b072beb1a660.jpg)

**Comment by jakobmoellersap** [comment] 2020-06-27 14:59
Duplicate of #737

**Closed by jakobmoellersap** 2020-06-27 14:59 UTC
