### ISSUE TITLE
Make "prioritized background" more present

### ISSUE THREAD

**Issue by error401de** [corona-warn-app/cwa-app-android#926] opened 2020-07-25 11:28 UTC
## Current Implementation
Important setting is hidden in the settings menu, I only heard of this in the news.
It's good that this issue has been addressed. But as long as this is not well-known, it's not resolved.

## Suggested Enhancement
There should be a visible hint on the start page, maybe even a one-time-notification.

## Expected Benefits
Avoid situations that many users will not get notified

**Comment by daimpi** [comment] 2020-07-25 14:40
Duplicate of #925

**Closed** 2020-07-25 15:00 UTC
Labels: enhancement
