### ISSUE TITLE
2147483647 Tage seit der letzten Begegnung

### ISSUE THREAD

**Issue by carstenkowalzczek** [corona-warn-app/cwa-app-android#1786] opened 2020-12-02 08:02 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Describe the bug

I had a high risk contact on November 17th.  This mornig the app status was still red and showed
'15 Tage seit der letzten Risiko Begegnung'. After updating the risk status it shows 
'2147483647 Tage seit der letzten Begegnung'

## Steps to reproduce the issue

I did just open the app.
![Screenshot_20201202-072034_Corona-Warn](https://user-images.githubusercontent.com/56067428/100845104-0129b900-347d-11eb-9a8a-6febe6a5a055.jpg)

## Technical details

- Mobile device: Galaxy S10
- Android version: 10
- Corona Warn App Version 1.7.1

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-4255](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4255)

**Comment by ndegendogo** [comment] 2020-12-09 06:48
@dsarkar @svengabr seems your robot didn't pick up this one?

**Comment by vaubaehn** [comment] 2020-12-09 11:11
2147483647 decimal is 32 bit binary 01111111 11111111 11111111 11111111. So probably a calculation was performed on a wrong persisted value.

Please forgive me in advance for kidding, I just can't resist:
Or did you indeed have an encounter 2147483647 days ago? I mean, that's around 6 million years ago, I would also have problems to remember who I met that day.

**Comment by ndegendogo** [comment] 2020-12-09 12:30
> probably a calculation was performed on a wrong persisted value.

@vaubaehn or a wrong datatype is also a good candidate for this kind of bug

**Comment by vaubaehn** [comment] 2020-12-09 13:21
@ndegendogo : or both: wrong data type with a negative number (looks like this to me).
Maybe something similar like #1029 / #1082 which was related to tracing days?

**Comment by ndegendogo** [comment] 2020-12-09 19:42
@vaubaehn 🤪🤪🤪

**Comment by Ein-Tim** [comment] 2020-12-09 20:36
I came here because @ndegendogo linked to this Issue (normally I don't take the 🚆 to the Android Repo) but reading through this I have just one small question 

@carstenkowalzczek:
Is the App still showing this number?

**Comment by dsarkar** [comment] 2020-12-10 10:39
Dear @carstenkowalzczek, @ndegendogo, @Ein-Tim, @vaubaehn,

Thank you for your contributions and analysis. We have created a ticket for the bug in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4255](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4255)

**Comment by dsarkar** [comment] 2020-12-10 20:37
Issue of to googles ENF, mitigated with ENF 2.0, CWA 1.8

**Comment by ndegendogo** [comment] 2020-12-10 22:49
@dsarkar very nice idea to indicate the planning for the fix in the headline. 🎉🎉

**Comment by MKTH2020** [comment] 2020-12-20 09:47
My App shows the same issue on Android 9.

**Comment by dsarkar** [comment] 2020-12-20 09:56
@MKTH2020, thanks for the feedback. Please, let us know

- CWA version 1.9.1?
- Device model/name
- Android 9
- More details: The day before, what did it show, the next day, and the day after. 
- Screenshots if possible would be nice

Many thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MKTH2020** [comment] 2020-12-20 10:09
Cwa 1.7.1
Sony Xperia
The Day before: High risk with correct Date and correct Test result
This morning: Bug showed 
When I opened again a minute ago to look up the version number, it was already gone. App shows green again now.

**Comment by MKTH2020** [comment] 2020-12-20 10:09
![_20201220_103235](https://user-images.githubusercontent.com/76389331/102710628-e1372980-42b3-11eb-8589-f55a3f296ef7.JPG)

**Comment by MKTH2020** [comment] 2020-12-20 10:11
![Uploading _20201220_111106.JPG…]()

**Comment by dsarkar** [comment] 2020-12-20 10:27
@MKTH2020, thanks.
CWA 1.9.1 was released a few days ago. This issue should have been fixed in 1.9.1. Please update and we would appreciate your feedback if this issue was resolved for you and others. Thanks, DS

---
Corona-Warn-App Open Source Team

**Comment by MKTH2020** [comment] 2020-12-20 11:34
Thanks. After the update, App shows Red again without showing a number of encounters.
![_20201220_120533](https://user-images.githubusercontent.com/76389331/102712213-a3d89900-42bf-11eb-8f58-f9ea17ef600f.JPG)

**Comment by ndegendogo** [comment] 2020-12-20 14:38
@MKTH2020 yes, cwa 1.9 is using the new improved risk calculation formula based on ENS v1.5 (Google) / ENF v2 (Apple).
This improved formula yields not number of encounters, but number of days with risky exposition (in your case: 1 day).

**Comment by heinezen** [comment] 2020-12-20 16:23
Hey @carstenkowalzczek ,

We are getting positive feedback from users that the issue is fixed in CWA version 1.9 which just got released, so we will therefore close this issue. Please update to 1.9 if you haven't already. If the error stilloccurs, make a comment here and we will reopen the issue.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2020-12-20 16:23 UTC
Labels: Fix 1.8, Solved, bug, mirrored-to-jira
