### ISSUE TITLE
Cause: 3 Something went wrong. error when communicating with Google API (39508)

### ISSUE THREAD

**Issue by ejgeo** [corona-warn-app/cwa-app-android#824] opened 2020-07-06 07:14 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Mobile device:
- Android version:

**Comment by tkowark** [comment] 2020-07-06 07:19
Duplicate of #774 or #822

**Closed by tkowark** 2020-07-06 07:19 UTC
Labels: bug
