### ISSUE TITLE
imported vaccination cert not signature verified

### ISSUE THREAD

**Issue by msmeissn** [corona-warn-app/cwa-app-android#3505] opened 2021-06-19 15:21 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S9
- Android version: 10
- App version: 2.3.4

## Describe the bug

Vaccination certificates can be imported without signature checking.

See https://github.com/stealth/greenday  security researcher report.

## Steps to reproduce the issue

Go to https://github.com/stealth/greenday scroll down to the QR code, scan the QR code with CWA Android. 
It Should not import it (CovPass rejects it).

[direct QR code link](https://raw.githubusercontent.com/stealth/greenday/master/rambo.jpg)

## Expected behaviour

QR code should be rejected

## Possible Fix

Apparently add signature verification.

## Additional context

Found by Sebastian Krahmer of c-skills.

**Comment by thomasaugsten** [comment] 2021-06-19 15:38
Duplicate corona-warn-app/cwa-documentation/#634

**Comment by vaubaehn** [comment] 2021-06-19 20:04
@heinezen @dsarkar 
> Duplicate [corona-warn-app/cwa-documentation#634](https://github.com/corona-warn-app/cwa-documentation/issues/634)

Should we leave this open here anyways, to hopefully avoid more duplicates in the Android repo?

**Comment by heinezen** [comment] 2021-06-20 10:49
@vaubaehn 

I'd rather not because then people will start discussing the problem in several issues and it's going to be hard to rrack the discussion. We'll swallow the additional effort to redirect users to the correct issue.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-20 10:53
Hey @msmeissn 

Tanks for reporting. However, the issue is already being discussed in https://github.com/corona-warn-app/cwa-documentation/issues/634. We encourage you to read the existing discussion and participate there if you have further questions. In your particular case, https://github.com/corona-warn-app/cwa-documentation/issues/634#issuecomment-858662924 is the moost relavant comment:

> This behavior is intended.
> 
> A signature check is not adding security to the "gate keeper" case.
> Distracted "gate keeper" can be fooled with screenshots or self compiled apps with deactivated signature check.
> A scan with a valid verifier app is mandatory otherwise the concept is not working.
> 
> To prevent unintended scan of example qr codes is not an important requirement.
> 
> The EU doesn't require a signature check in wallet apps to reduce the complexity and prevent possible compatible issue with very old devices and OS versions.

I'll close your issue as a duplicate.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-20 10:53
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/634

**Closed by heinezen** 2021-06-20 10:53 UTC
Labels: bug, duplicate

**Comment by vaubaehn** [comment] 2021-06-20 12:37
@heinezen 
> We'll swallow the additional effort to redirect users to the correct issue.

Although I didn't have strong feelings either to leave it open, I thought it could be more easy to leave it open to let the users redirect themselves to the issue in the docu repo. But true, even the link is provided to the other issue, users may still comment here.

But a suggestion in case something similar pops up in Android or iOS again: it could be marked as duplicate, link to docu repo provided, and then lock the issue against further commenting maybe? I know it's lockable for overheating discussions, don't know if other reasons for locking can be chosen?
Anyway, have a nice Sunday. I hope you can enjoy from a cool place. Here heat and air humidity makes it a bit uncomfortable... Greetings!

**Comment by heinezen** [comment] 2021-06-20 15:47
> But a suggestion in case something similar pops up in Android or iOS again: it could be marked as duplicate, link to docu repo provided, and then lock the issue against further commenting maybe? I know it's lockable for overheating discussions, don't know if other reasons for locking can be chosen?

I'm not a fan of locking issues because it can come across as shutting off a discussion which is not what we want. Also, we are sometimes wrong about issues being duplicates and in a locked thread no oe will be able to tell us. I also might make searching for the "correct" issue less intuitive because users would stumble upon open issues where they can't comment. Some users would not follow the links and not participate in the discussion at all.

Writing an answer that redirects to the duplicated issue also doesn't take much time. IMO, the personal answers work much better because I can include relevant infos like in https://github.com/corona-warn-app/cwa-app-android/issues/3505#issuecomment-864535234. After all managing users so they end up at the correct pace is what the community team is for.

> Anyway, have a nice Sunday. I hope you can enjoy from a cool place. Here heat and air humidity makes it a bit uncomfortable... 

Thank you! (at least there were no heated discussions in the repos today 😉 )

----
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment] 2021-06-21 17:13
@heinezen 
Your points are all good and convincing! Nothing more to say.
Happy it all cooled down a bit (at least the weather) - hope you had a good start into the week! CU
