### ISSUE TITLE
Android 6.0.1 Smartphone System-UI service dies on deactivating GPS Tracking 

### ISSUE THREAD

**Issue by Demactus** [corona-warn-app/cwa-app-android#691] opened 2020-06-20 19:22 UTC
## Describe the bug

In the case that you deactivate GPS on a Sony Xperia Z3 with Android 6.0.1 there is short system message on screen saying System-UI has stopped and you can acknowledge the messag.
After this the screen turns black and only a manual reset is possible

## Expected behaviour
Normally the app should work even without GPS activated on the device

## Steps to reproduce the issue

1. Install the app on the mentioned device ( can't say if it is a general Android 6.0.1 problem)
2. Deactivate the GPS of the device through the menu
3. Wait a bit and you should get the message 
### Optional:
4. When you restart and don't reactivate GPS --> same behavior as in 3.

## Technical details

- Mobile device: Sony Xperia Z3 (D6603)
- Android version: 6.0.1
- Build-Number: 23.5.A.1.291

## Possible Fix
Don't deactivate GPS on the device

**Comment by realansgar** [comment] 2020-06-21 07:55
Sort of duplicate of #597. The limited reports suggest this is a Sony UI specific issue.

**Comment by treysis** [comment] 2020-06-21 11:10
GPS or Location Access? Location Access needs always to be turned on in system settings.

**Comment by Demactus** [comment] 2020-06-21 16:39
It's mentioned as "Location" in the system settings but represents the location tracking of the device such as GPS, WLANs, mobile networks and sensors.

**Comment by Demactus** [comment] 2020-06-21 16:41
I looked into Issue #597 and would deduce that it seems like the same problem but in his case he is just mentioning Bluetooth. From that I would deduce that if either one of them (Location or Bluetooth) is turned off the problem occurs

**Comment by amatenki** [comment] 2020-06-23 21:36
I have a Z3 with the same specifications but a different model. Mine is D5803. CWA is 1.0.4.
Cannot reproduce the bug on this device. Deactivating "Location" has CWA inform me that "Benachrichtigungen zu möglicher Begegnung [...] nicht möglich", please activate Location (Standortermittlung). Nothing crashes.
Hope this helps.

**Comment by jakobmoellersap** [comment] 2020-06-26 09:45
Duplicate of #597 with the addition that both settings cause the crash. We deduce this is the same root cause.

**Closed by jakobmoellersap** 2020-06-26 09:45 UTC
Labels: bug
