### ISSUE TITLE
Prevent notifications asking the user to enable GPS when it's not necessary

### ISSUE THREAD

**Issue by prototyperspective** [corona-warn-app/cwa-app-android#5157] opened 2022-05-06 20:49 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

There already is https://github.com/corona-warn-app/cwa-wishlist/issues/35 but it Android-specific and _not_ solved. It is mentioned but not addressed, duplicate or solved.

## Technical details

- Device name:
- Android version: 11
- App version: 2.21.1

## Describe the bug

The app shows the notification via _Google Play Services_ multiple times every day:
>Fehler beim Überprüfen der Kontakte
>Aktiviere die Standortermittlung für dein Gerät, um weiterhin mögliche Begegnungen mit Personen zu erfassen, die positiv auf COVID-19 getestet wurden

I thought it didn't need GPS and that the notification could be ignored, then I looked it up and all issues and info I found about it said that GPS _is_ needed because of some issue in Android, and then I came across https://www.coronawarn.app/en/faq/results/#android_location which says:
> If you are using Android 11 and the Corona-Warn-App version 1.5 or above, you don't have to allow location access in order to use the Corona-Warn-App.
so it's not needed after all if you have a new phone. This is very confusing.

Could you please:
* Make Google or Android developers fix the bugs that require GPS to be enabled on phones running Android >11 (that's a separate issue: #5158)
* Prevent these notifications from appearing on phones where they aren't required (this unsolved issue)

There are many reasons for why you may not want to have your GPS turned on all the time. Not just the battery drain. For example, the Corona Warn App itself can be the most privacy-friendly app...but if it requires GPS to be switched on, all other apps that run in the background (or alongside) that have permissions to use GPS can then make use of it (a clear privacy concern). 

I'd like to keep my GPS turned off and not get annoyed by these notifications showing multiple times each day which, in addition, confuse users about whether or not the app works.

## Steps to reproduce the issue

1. Run the latest version of the CWA on Android
2. Turn on Bluetooth (with GPS remaining off)
3. See this notification (re)appear all the time

## Expected behaviour

If GPS is needed for the app to work this notification should be shown to the user. If it is not needed it shouldn't be shown.

GPS should never be needed but that is a separate issue.

## Possible Fix

It may or may not be necessary to put pressure on Google or to implement code changes in other Android code or to at least create an issue in another repository (please link it here).

**Comment by Ein-Tim** [comment] 2022-05-06 21:42
Suggestion to add the https://github.com/corona-warn-app/cwa-app-android/labels/google label to this issue.

**Comment by MikeMcC399** [comment] 2022-05-07 07:49
@prototyperspective 

Could you say which version of Android you are using? (Also it would be useful to know which device.)

Depending on the Android version and the device, the GPS setting is not necessarily the same as the Location setting. For instance I have a Samsung device running Android 8 and if I choose the option Standort EIN, I can choose the Suchmethode Energie sparen, which only uses WLAN and mobile networks. GPS is switched off. This is enough to allow Risiko-Ermittlung aktiv.

**Comment by prototyperspective** [comment] 2022-05-07 08:25
Android 11, still waiting for the Librem5 phone (which isn't Android or iOS).

Interesting but this isn't a solution (or a good workaround) as most people running Android < 11 don't have this option or if they have aren't aware of it.

**Comment by MikeMcC399** [comment] 2022-05-07 09:06
@prototyperspective 

> Android 11, still waiting for the Librem5 phone (which isn't Android or iOS).

If I understood you correctly, you are using an Android 11 device and you get the notification:

![image](https://user-images.githubusercontent.com/66998419/167247017-b957a676-cf19-456d-8b0e-78506405e21c.png)

If you have a standard Android 11 device with standard Google Play services installed, I would not expect to see this notification displayed. Do you have any other Exposure Notification apps installed, like CCTG, apart from the Corona-Warn-App?

The Google Play services app has a separate notification category "Exposure Notifications" which you could disable if you do not wish to receive these notifications.

You did not say which device you are currently using. CWA supports devices as described in https://www.coronawarn.app/en/faq/results/#minimum_requirements. If you are planning to move to a phone which is neither Android nor iOS, this will not be on the list of supported environments.

**Comment by prototyperspective** [comment] 2022-05-07 09:44
> If I understood you correctly, you are using an Android 11 device and you get the notification:

Exactly, thanks for adding a screenshot.
(Note that in my notification (dark mode) it also says "Google Play Services".)

> If you have a standard Android 11 device with standard Google Play services installed, I would not expect to see this notification displayed.

It's standard Android 11, with standard Google Play services and I didn't modify it in any strange/comprehensive way like trying to run microG on it. Why is it displayed then and what should be displayed instead? From other issues and reports, it seems like getting these annoying notifications is normal.

> Do you have any other Exposure Notification apps installed, like CCTG, apart from the Corona-Warn-App?

No, and never had or tried. I would very much support CWA moving to CCTG and don't know why it hasn't been done so far btw and will research why at a later point.

> The Google Play services app has a separate notification category "Exposure Notifications" which you could disable if you do not wish to receive these notifications.

Most people aren't aware of this, it's a workaround not a solution and as I'm one of the very <1% percentage of users that looks into details of the app that include code issues here, I've learned about this workaround (most haven't). However, I also read that this would impact core functionality of the app, like showing warning notifications so it's not a viable workaround even if nearly everybody knew about this / there was a big button in the app or the notification to disable the notifications this way.

> You did not say which device you are currently using. CWA supports devices as described in https://www.coronawarn.app/en/faq/results/#minimum_requirements.

It's a standard device that many are using. It's supported.

> If you are planning to move to a phone which is neither Android nor iOS, this will not be on the list of supported environments.

Yes, Librem5 support is a separate issue. Maybe CCTG could be useful for this and if there is no dedicated app, Android apps can run on it with Anbox (but it may not work this way nevertheless). This is a separate issue and probably currently not high-priority.

**Comment by MikeMcC399** [comment] 2022-05-07 11:49
@prototyperspective

> Exactly, thanks for adding a screenshot.
(Note that in my notification (dark mode) it also says "Google Play Services".)

My screenshot is from an Android 8 system which doesn't show the text "Google Play Services" in the notification. Perhaps you could paste a screenshot from your notification for completeness.

>  I also read that this would impact core functionality of the app, like not showing warning notifications 

The notifications from the Google Play services app are separate from the notifications from the Corona-Warn app. Google Play services has many notification categories. Disabling "Exposure Notifications" in Google Play services still allows other Google Play services notification. On Android 11, CWA shows the categories (General and Check-ins). So if you disable the Location warning you should still get notification from CWA for any of its status changes, like for risk changes or booster notifications for instance.

Thank you for confirming that you are running standard Android 11 with standard Google Play services. I can't reproduce your issue on a Samsung device running Android 11. If I disable Location, then I get no notification and CWA continues with active exposure logging.

On your device, if you set Location to Off (Standort ein) in the Android settings, does the display in CWA continue to show Exposure Logging Active (Risiko-Ermittlung aktiv) or does it change to Location services deactivated (Standortdienste deaktiviert)?

What is the ENF Version shown in CWA App Information (accessible through the three-dot menu)? It should be something like 18221514000.

**Comment by MikeMcC399** [comment] 2022-05-07 15:58
@prototyperspective 

You did not state your device name / vendor and there is a possibility that it may not be fully supported.

Please check if your device is Play Protect certified.

"To check if your device is certified, open the Google Play Store app on your Android phone, tap “Menu” and look for “Settings.” You will see if your device is certified under “Play Protect certification."

**Comment by prototyperspective** [comment] 2022-05-08 16:01
>Google Play services has many notification categories. Disabling "Exposure Notifications" in Google Play services still allows other Google Play services notification.

* Under Notifications there is no entry for Google Play Services.
* Under Notifications->CWA one can only toggle COVID-19 notifications (and toggle popups, configure vibrations, show on lockscreen).
* Under Manage apps->Google Play Services one can only toggle COVID-19 notifications (and toggle popups, configure vibrations, show on lockscreen).
* Under Manage apps->CWA one can only toggle Show notifications. (There is one item under Notification categories which is General)

> Thank you for confirming that you are running standard Android 11 with standard Google Play services. I can't reproduce your issue on a Samsung device running Android 11

Maybe it needs permissions to access location? I have that disabled.

> On your device, if you set Location to Off (Standort Aus) in the Android settings, does the display in CWA continue to show Exposure Logging Active (Risiko-Ermittlung aktiv) or does it change to Location services deactivated (Standortdienste deaktiviert)?

I could test this later but in the app it says "Standortdienste deaktiviert" with GPS/Location off.

>What is the ENF Version shown in CWA App Information

18221514000

>You did not state your device name / vendor and there is a possibility that it may not be fully supported.

I think it's one of the most used Android 11 phones so I'm sure it's supported.

>You will see if your device is certified under “Play Protect certification."

Device is certified.

**Comment by MikeMcC399** [comment] 2022-05-08 16:39
@prototyperspective 

>>On your device, if you set Location to Off (Standort Aus) in the Android settings, does the display in CWA continue to show Exposure Logging Active (Risiko-Ermittlung aktiv) or does it change to Location services deactivated (Standortdienste deaktiviert)?
>
> I could test this later but in the app it says "Standortdienste deaktiviert" with GPS/Location off.

Thanks for the feedback. It seems that you have an Android 11 phone which requires "Standortdienste" activated in order to use Exposure Logging. This is what the COVID-19 Notification said, however this conflicted with other information you read, which said that this was not necessary on Android 11 phones (for example https://www.coronawarn.app/en/faq/results/#android_location and https://support.google.com/android/answer/9930236?hl=en). So it looks like you assumed that the notification was being sent incorrectly. 

In fact there are some known exceptions to the rule that Android 11 doesn't need Location enabled. @dsarkar wrote in https://github.com/corona-warn-app/cwa-app-android/issues/2506#issuecomment-789725466 "As far as I understand there are even some OEM Android 11 devices that require location services to be enabled, apparently Oneplus Devices with Android 11." I also found some other reports about this issue on Android 11 devices, which did not say which device models were involved, nor did they give a solution - so they are not much help.

If you activate CWA Error Reporting on your device (see https://www.coronawarn.app/en/faq/results/#error_log) and examine the log, you may find a line
`V/DefaultScanningSupport$isLocationLessScanningSupported: isLocationLessScanningSupported FLOW emission: false`
from the [API call to ENS](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods) `deviceSupportsLocationlessScanning()`.

`false` means that the device needs Location enabled, `true` means it is not needed. I expect your device returns `false`.

Unfortunately there is nothing that the CWA app can do to change this. It is under the control of Android and Google Play services.

Your device vendor may be able to assist you. Perhaps your device vendor also has a community forum where you could ask?

**Comment by prototyperspective** [comment] 2022-05-08 16:46
>however this conflicted with other information you read, which said that this was not necessary on Android 11 phones

Confusing.

>examine the log, you may find a line

I'd need to know where I can find this log file.

**Comment by MikeMcC399** [comment] 2022-05-08 17:01
@prototyperspective 

> I'd need to know where I can find this log file.

If you have your phone set to German, then you tap on "Teilen und fortsetzen" to get access to the log file. There are some details in the blog https://www.coronawarn.app/en/blog/2021-05-12-corona-warn-app-version-2-2/ linked to the FAQ articles. On the website you can switch between EN (English) / DE (German) texts using the selection at the top.

Here is a current German screenshot from 2.22.1:

![image](https://user-images.githubusercontent.com/66998419/167306877-46b4af11-9eed-4d77-b524-6ec652d0bbe7.png)

**Comment by MikeMcC399** [comment] 2022-09-08 08:52
@prototyperspective 

Do you need any additional assistance on this topic? If not, then I suggest to close the issue.

As I mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/5157#issuecomment-1120449898 the issue you describe is device-specific and it's quite unlikely that the Corona-Warn-App has any influence on the behaviour.

**Comment by mtwalli** [comment] 2022-09-09 10:59
@prototyperspective  we have no influence on when and how Google play services send notifications

**Closed by mtwalli** 2022-09-09 10:59 UTC
Labels: bug, google
