### ISSUE TITLE
App size too big, minimization required

### ISSUE THREAD

**Issue by Phoenix616** [corona-warn-app/cwa-app-android#527] opened 2020-06-16 10:34 UTC
## Current Implementation
App download on the playstore is ~15MB (38 after install)

## Suggested Enhancement
Minimize the app, remove unnecessary large libraries with minimal (native) implementations. Under one megabyte should be easily possible and the goal!

## Expected Benefits
An app that just needs to generate, exchange and check random IDs should not need to be that big and will stop a lot of people from installing the app as space constraint is a common occurrence on Android, especially budget phones with small internal space so please find a way to minimize the size. 

**Edited to match enhancement template, did not show up on mobile github client used my apologies**

**Comment by tobidwest** [comment] 2020-06-16 10:36
Does it use the Android App Bundle?

**Comment by tomjschwanke** [comment] 2020-06-16 10:42
see #482

**Comment by corneliusroemer** [comment] 2020-06-16 10:51
Thanks for mentioning budget phones. You're right 38 MB is large for what little the app does. Size should be optimised in future releases.

Similar issue #482 got tagged "wontfix" unjustifiedly. SAP should stop closing important issues that should be fixed in the near term with future releases.

**Comment by ironjan** [comment] 2020-06-16 17:43
@tkowark Could you also take a look at the more extensive #482? This issue is a duplicate of #482 which was marked as wontfix  despite listing potential steps to improve the app size.

**Comment by tkowark** [comment] 2020-06-17 09:18
Thanks for the pointer @ironjan . We're looking into both issues. But please note that main priorities right now are bug fixes and implementing planned features for the next releases. If we can reduce size along that path, we'll, of course, do that, but it is currently not a top priority.

**Comment by ironjan** [comment] 2020-06-17 10:33
@tkowark I fail to understand how your comment connects to my comment. According to the state of #482 (closed, wontfix), SAP/Telekom are not looking into the problem. According to this one #527 (duplicate, less detailed, open, enhancement), SAP/Telekom are looking into the problem. Your comment does not address the duplication nor the more detailed nature of #482.

So my question to you is: should all comments and steps that describe how the big app size can be solved copied from #482 into #527? No to mention the fact that there was no comment about the intentional closure of #482 in neither issue.

**Comment by tkowark** [comment] 2020-06-17 11:57
Sorry for the confusion @ironjan . I'll clarify with the team and get back to you about how we'll proceed with the two issues and the respective comments.

**Comment by tkowark** [comment] 2020-06-17 17:02
Ok, we clarified that issue with the team. Following proposal:

* we'll reopen #482 as it provides more details on *how* size could be reduced
* This issue will be closed accordingly to only have one central discussion point

But again, while the team will of course have possible improvements in size in mind, it is not a main priority. We appreciate any suggestions for that endeavour as comments in #482 !

Sorry for the confusion and best regards,
TK
Corona-Warn-App Open Source Team

**Closed by tkowark** 2020-06-17 17:02 UTC
Labels: enhancement, in progress

**Comment by corneliusroemer** [comment] 2020-06-17 17:28
Thanks @tkowark for a thoroughly explained response. This is the interaction style that would be great moving forward.
