### ISSUE TITLE
What if user deletes the report accidently, are the results can be recovered, as QR code for the next it will be invalid

### ISSUE THREAD

**Issue by rebelgiri** [corona-warn-app/cwa-app-android#1001] opened 2020-08-11 20:10 UTC
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

**Comment by daimpi** [comment] 2020-08-11 20:13
Duplicate of #960 

Unfortunately you'll have to wait until they contact you via Phone/mail:
> Hi unfortunately this is not possible. We have to ensure only one phone can scan the qr code and submit his diagnoses keys. We are not allowed to save an ID of the phone this is the reason why the qr code is only valid for one scan.
> Please wait for the normal way (a letter via post mail or Gesundheitsamt calls you) of the test lab to get your result.

**Closed** 2020-08-11 20:15 UTC
Labels: question
