### ISSUE TITLE
Ursache 3: Etwas ist schief gelaufen (Fehler bei Kommunikation mit Google API (10))

### ISSUE THREAD

**Issue by sqrt-1764** [corona-warn-app/cwa-app-android#833] opened 2020-07-07 09:24 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue
(At least not with the exact error code of 10)

## Describe the bug
After successfully installing the app I was able to sync with the servers for some time. Since 28.6.20 I get the error mentioned above. The details are in the following screenshot:

Because of locking the screenshot feature (totally unecessary in this context!) I had to use my smartphone for the screenshot:
![IMG_20200707_110611-1](https://user-images.githubusercontent.com/16422347/86758143-ef65f600-c043-11ea-8449-cda2bf574cf8.jpg)

## Technical details
- Mobile device:
Asus Nexus 7 (2013)

- Android version:
6.0.1

**Comment by tkowark** [comment] 2020-07-07 09:32
Duplicate of #737

**Closed by tkowark** 2020-07-07 09:32 UTC
Labels: bug
