### ISSUE TITLE
Risk state is not updated.

### ISSUE THREAD

**Issue by DannySchumann** [corona-warn-app/cwa-app-android#621] opened 2020-06-18 06:39 UTC
## Describe the bug

The app is running since 16th of June (more than two days now). It shows "2 von 14 Tagen aktiv" and "Aktualisiert: Vorgestern 12:07". The app was never deactivated.

## Expected behaviour

It should never show "Aktualisiert: Vorgestern" because the app is supposed to update the state every day.

## Technical details

I run it on a Honor 10 Smartphone.
AppVersion 1.0.2.

**Comment by Fabus1184** [comment] 2020-06-18 06:48
Do you have restricted app background tasks in your system settings ?

**Comment by DannySchumann** [comment] 2020-06-18 06:56
> Do you have restricted app background tasks in your system settings ?

I don't think so. The app settings in the OS is configured to "Hintergrundaktivität nicht eingeschränkt".

**Comment by bersbersbers** [comment] 2020-06-18 07:05
I can confirm this report: running since 2 days, did a couple of tests in-between (disabled bluetooth, disabled the exposure API, all just for a few seconds), but had the app running constantly. I definitely opened it yesterday, too. Still, says "Updated: 2 days ago, 9:25 am".

**Comment by CBRWLF98** [comment] 2020-06-18 07:19
I am having the same issue. "Updated: 2 days ago, 9:33am".
I am using the Huawei P10 lite and my background settings are also untouched.

**Comment by gizmo21** [comment] 2020-06-18 08:03
Same issue on Huawei P10 Shows vorgestern instead of gestern.
Just installed App so far, did no optimization.

Now, today changed Menü "App Start" on CWA App to "Manual" and put all switches ON.
So far no imediate change.

Huawei app restriction experts needed.

**Comment by CBRWLF98** [comment] 2020-06-18 08:29
Update: My Risk state just updated, now it says: today, 10:27 and it also says 2 days active.
I have opened the app several times yesterday but nothing happened.
So in conclusion my status has not been updated for 2 days and 1 hour

**Comment by bauerj** [comment] 2020-06-18 09:24
Same here (Huawei P20 Pro). Is it possible to manually trigger an update?

**Comment by AlexanderAlferov** [comment] 2020-06-18 10:32
Thank you so much for your issue report!
Unfortunately, there are some known issues with background tasks on some firmware.

While we are investigating this issue, you could turn on manual mode:
Settings -> Apps -> Corona Warn App -> Battery -> turn off Allow background activity
After this, please, kindly open the application and check if Update (Aktualisieren) button is available.

Thank you.
Best regards,
Alex

**Comment by datenstau** [comment] 2020-06-18 10:49
Same issue on P-Smart 2019.

**Comment by juefried** [comment] 2020-06-18 11:06
Same issue here: Xiaomi Mi 9T Pro. Also, following the instructions above (with small differences in the path to the settings) did not bring up the „Aktualisieren“-button.

**Comment by fjalowski** [comment] 2020-06-18 11:12
Same problems with Huawei Mate 10 Pro. I tried playing around with the energy saving/battery settings for the app, but so far I couldn't see a change in behavior. Still stuck on last update being two days ago.

**Comment by gizmo21** [comment] 2020-06-18 11:20
My settings (see above)  and app update to 1.0.2 triggered the inapp download. But not immediately, took a while. 

Also tried what Alexander suggested which (as I understand it) could be used as manual trigger, but even with force closing app and disabling background data, the mentioned button does not appear. Perhaps cause I now already updated today.

**Comment by DannySchumann** [comment] 2020-06-18 11:26
# Status update
My app now shows "Risiko-Ermittlung nicht möglich. Ihre Risiko-Ermittlung konnte seit mehr als 24 Stunden nicht aktualisiert werden" and a Button "RISIKO-ERMITTLUNG EINSCHALTEN" appears, but the "RISIKO-ERMITTLUNG" is still active. It shows "RISIKO-ERMITTLUNG AKTIV" in the status bar.

**Comment by fjalowski** [comment] 2020-06-18 11:30
Can confirm that, as gizmo21 said, turning app start from automatic to manual in the power saving/battery settings and setting the other three power options to on led to a successful update after a while.

**Comment by AlexanderAlferov** [comment] 2020-06-18 11:37
@juefried, this is something new.
Could you, please, provide the full path to that setting on your device?
Thank you!

Best regards,
Alex

**Comment by juefried** [comment] 2020-06-18 11:49
> @juefried, this is something new.
> Could you, please, provide the full path to that setting on your device?

Einstellungen > Apps > Apps Verwalten > Corona-Warn 

There I disabled Autostart, in addition I set Energiesparmodus to "Hintergrundaktivitäten beschränken", then "Beenden erwingen", then restart of the App.

What I also find strange is, that for the CWA no data-transfer has been recorded today.
![CWA 20200618](https://user-images.githubusercontent.com/32573236/85016680-812bc300-b16a-11ea-8459-9f0259d62f8e.jpg)

**Comment by juefried** [comment] 2020-06-18 11:54
While making the screenshot, the CWA suddenly updated the data :-o

**Comment by DannySchumann** [comment] 2020-06-18 13:03
My app updated its state now (after two days). Its the same like described by CBRWLF98.

**Comment by corneliusroemer** [comment] 2020-06-18 19:17
This possibly belongs to the class of "problems related to failure to download keys in set window, e.g. due to no internet"
https://github.com/corona-warn-app/cwa-app-android/issues/621 https://github.com/corona-warn-app/cwa-app-android/issues/632

**Comment by bersbersbers** [comment] 2020-06-19 06:40
After updating to 1.0.2 and plugging in my phone last night (don't do that daily), risk was updated yesterday, 11:46 PM. I did not tinker with background/battery settings (yet).

**Comment by gizmo21** [comment] 2020-06-19 19:23
> Same issue on Huawei P10 Shows vorgestern instead of gestern.
> Just installed App so far, did no optimization.
> 
> Now, today changed Menü "App Start" on CWA App to "Manual" and put all switches ON.
> So far no imediate change.
> 
> Huawei app restriction experts needed.



> My settings (see above) and app update to 1.0.2 triggered the inapp download. But not immediately, took a while.
> 
> Also tried what Alexander suggested which (as I understand it) could be used as manual trigger, but even with force closing app and disabling background data, the mentioned button does not appear. Perhaps cause I now already updated today.

Just as info from another day later: Huawai P10 updated exactly 24h later automatically as my other devices should with my settings above:
App-Start to manual and all three switches to ON

For me it seems to to fixed that way.

**Comment by Pozzdamm** [comment] 2020-06-20 05:57
... Ich habe dasselbe Problem, Gerät Redmi 8A.

**Comment by birgit-xy** [comment] 2020-06-20 08:02
Uh, yesterday I posted below #637 - this is obviously wrong. The problem is #621 for Xiaomi Redmi Note 8 T - Android 9 . App installed 16th of June - no update till now, no Akku used

**Comment by ikarisan** [comment] 2020-06-20 08:48
Same here with my Huawei P20pro CLT-L29 (Android 10). Last time I got an updated status was the morning of June 18.

**Comment by skick3** [comment] 2020-06-20 12:11
Das klingt nach einem Xiaomi und Stromsparmodus-Problem. Die Lösung:
> Hier müsst Ihr den Punkt "Autostart" beziehungsweise "App-Start" suchen. Bei Huawei-Smartphones findet sich dieser je nach OS-Version entweder direkt im "Apps"-Menü oder bei den Stromspar-/Akku-Optionen. Bei Xiaomi-Telefonen liegt der Punkt im Unterverzeichnis "Rechte" unter "Apps" verborgen.

That sounds like a Xiaomi and power saving problem. The solution:
> Here you have to search for "auto-start" or "app-start" On Huawei smartphones, depending on the OS version, you can find it either directly in the "Apps" menu or in the power save/battery options. On Xiaomi phones, the item is hidden in the "Apps" subdirectory in the "Rights" folder.

Quelle/Source: https://www.androidpit.de/corona-warn-app-probleme-loesungen-fehler-bugs

**Comment by birgit-xy** [comment] 2020-06-20 15:32
Heute wurde aktualisiert. Gestern die App de- und wieder installiert. Autostart aus. Keine Energiebeschränkung. Bluetooth und GPS sowieso. Eine Berechtigung (Nachrichten). Endlich!!! Dafür habe ich jetzt 4 Tage herumgehampelt. Xiaomi Redmi Note 8 T. Wollen hoffen, dass es so bleibt.

**Comment by mbw83** [comment] 2020-06-20 17:47
> Das klingt nach einem Xiaomi und Stromsparmodus-Problem. Die Lösung:
> 
> > Hier müsst Ihr den Punkt "Autostart" beziehungsweise "App-Start" suchen. Bei Huawei-Smartphones findet sich dieser je nach OS-Version entweder direkt im "Apps"-Menü oder bei den Stromspar-/Akku-Optionen. Bei Xiaomi-Telefonen liegt der Punkt im Unterverzeichnis "Rechte" unter "Apps" verborgen.
> 
> That sounds like a Xiaomi and power saving problem. The solution:
> 
> > Here you have to search for "auto-start" or "app-start" On Huawei smartphones, depending on the OS version, you can find it either directly in the "Apps" menu or in the power save/battery options. On Xiaomi phones, the item is hidden in the "Apps" subdirectory in the "Rights" folder.
> 
> Quelle/Source: https://www.androidpit.de/corona-warn-app-probleme-loesungen-fehler-bugs

Sorry, but I think this is wrong. As also can be seen in #637 (which I think is related), this doesn't help in all cases. In Addition, as far as I understand, the big advantage of using the API of Google/Apple is, that the App doesn't have to run respectively be active the whole Day. It simply has to download the IDs of infected people from a Server every 24 hours. And it doesn't matter if this is done every 24 hours or more or less frequent. 
Even of the App is doing more than this, than it should be possible to do this without These settings. At least all my messaging, email and other Apps which have to on run respectively sync 24/7 are working without these wird settings.

The IT "expert" of bayerischer Rundfunk said on tuesday, that the CWA is for sure not a "Banana Software". I'm not quite sure about this....

**Comment by tkowark** [comment] 2020-06-21 12:12
In the meantime, the team identified a workaround that solved the problem at least for some users: https://www.coronawarn.app/de/faq/#no_risk_update. Would be great if you can let us know whether it worked for you as well.

Of course, the team is nevertheless still working on a proper solution for the issue.

**Comment by mbw83** [comment] 2020-06-21 15:35
> In the meantime, the team identified a workaround that solved the problem at least for some users: https://www.coronawarn.app/de/faq/#no_risk_update. Would be great if you can let us know whether it worked for you as well.
> 
> Of course, the team is nevertheless still working on a proper solution for the issue.

I still can not see the point, why setting this (weird) options should help solving the problem. As pointed out by @mh- in [this thread](https://github.com/corona-warn-app/cwa-documentation/issues/236#issuecomment-646238207) of the [cwa-documentation#236](https://github.com/corona-warn-app/cwa-documentation/issues/236) three attemps within 1 minute are done to get the data from the server. If this fails (this can also be because the internet is not available), the next attempt will be done 24 hours later. 
And as I also said before, my messaging (Signal, Telegram, WhatsApp, ...) and eMail (K-9 Mail, GMail, ...) apps are also able to retrieve the data on my phone without adjusting any energy options.

I do not want to offend anybody, I'm just trying to understand why this should help.

**Comment by mh-** [comment] 2020-06-21 15:53
@mbw83 I'm waiting for the commit mentioned [here](https://github.com/corona-warn-app/cwa-documentation/issues/236#issuecomment-646639138) to be published.

**Comment by mbw83** [comment] 2020-06-21 16:23
> @mbw83 I'm waiting for the commit mentioned [here](https://github.com/corona-warn-app/cwa-documentation/issues/236#issuecomment-646639138) to be published.

Yes, I also saw that, but this still doesn't have to do anything with energy saving options. The current state is just a Bug and has nothing to do with vendors not fully compliing with the Android specification. This can be an additional reason of course, but not the main one.

**Comment by mbw83** [comment] 2020-06-21 19:03
> @mbw83 I'm waiting for the commit mentioned [here](https://github.com/corona-warn-app/cwa-documentation/issues/236#issuecomment-646639138) to be published.

Seems that it got published now. Google play just updated my CWA and the risk state got updated when starting the App (or maybe automatically just seconds before).

**Comment by tkowark** [comment] 2020-06-23 15:10
@DannySchumann does the risk state update now work for you, too, with the latest app version?

**Comment by DannySchumann** [comment] 2020-06-23 19:56
Yes it is working now. I had only a single missing day.

**Comment by jakobmoellersap** [comment] 2020-06-25 08:19
Since the issue seems to be resolved for all parties. Please feel free to open up a follow-up issue if you still encounter similar errors. Thanks everyone!

**Closed by jakobmoellersap** 2020-06-25 08:19 UTC
Labels: bug, in progress

**Comment by bersbersbers** [comment] 2020-06-25 11:26
I hate to ask this, but is it ensured that the risk state updates without changing battery settings and without opening the app? I assume that most of the people here checked the risk state updates (probably) after changing battery settings and (surely) by opening the app. I myself have not yet changed battery settings yet, and it seems the risk state is (only) updated upon starting the app.

So what happens with people who install the app in a rush, but don't change battery settings and then never open the app again? They will probably not have their risk state updated, nor be aware of this. Previously, I had problems with missed notifications with the Signal messaging app for weeks (on a Huawei P30) until I changed battery settings - this would be dramatic for CWA.

**Comment by ikarisan** [comment] 2020-06-25 14:35
> I had problems with missed notifications with the Signal messaging app for weeks (on a Huawei P30) until I changed battery settings - this would be dramatic for CWA.

On Android this may be prevented by showing a static/fixed notification and/or by displaying an icon in the notification bar. As far as I know this is the way the "Mi Band Notify" app handles this.

**Comment by jakobmoellersap** [comment] 2020-06-26 07:33
@bersbersbers There are battery optimisation implications with some manufacturers (Honor being one of them) that we are currently tackling and trying to resolve by specifically designing a solution that asks for ignoring these restrictions to allow optimal operation for these cases. One of the ideas is to introduce a dedicated permission resolution like the immuni app, however there are certain UX implications and this is also resulting in less trust for people who would not even need that permission check. 

I would thus ask for your patience until we came to a final conclusion on how to finally resolve that topic. In the meantime, by going into the app now and then or disabling battery optimisations should help for almost all devices that have this problem. It is unfortunate that we then have to include a workaround only applicable for certain devices and manufacturers but this is the general disadvantage of the Android ecosystem and we will try to get around this problem as good and as soon as we can responsibly. We are aware of the implications this might have, but have to think of the (now) big user base we are targeting and can and will not take this decision lightly.

@ikarisan The "static/fixed" notification is a so called foreground service that handles completely different to our current background job solution, but is also being investigated as one of the possible resolutions.

**Comment by mhellmeier** [comment] 2020-07-23 22:00
We just talked and discussed about exactly this problem in #522 on the release day. I also tried to make a proposal without any response. Sad story that the mentioned issue has been largely ignored and this bug could have been fixed much sooner and now makes such big waves. :disappointed:
