### ISSUE TITLE
wrong date calculation for vaccination certificate and status

### ISSUE THREAD

**Issue by Geimpfter** [corona-warn-app/cwa-app-android#3448] opened 2021-06-15 09:39 UTC
My last vaccination was on 2021-06-01 and I inserted my certificate yesterday (2021-06-14).
Since today midnight (2021-06-15) the "cwa-app-android" app shows "Impfschutz" which let me think, I have an active vaccination status right now and can enjoy my privileges.

An other app from german health administration with name "CovPass" shows the same certificate with message "Vollständiger Impfschutz ab 16.06.2021." so this is not today but tomorrow! There is also an other official app "Covpass Check" that is supposed to be used by security personal shows on my certificate "Impfstatus nicht gültig. Das geprüfte Zertifikat weist keine vollständige Impfung nach."

Same issue is have on iphone version, too.

Please check date calculation!

**Comment by DerVogel2020** [comment] 2021-06-15 09:56
Duplicate: https://github.com/corona-warn-app/cwa-documentation/issues/638

**Comment by heinezen** [comment] 2021-06-15 10:36
Hey @Geimpfter ,

As pointed out by @DerVogel2020 , we will use https://github.com/corona-warn-app/cwa-documentation/issues/638 for discussion of this specific problem. Therefore, I will close your issue here. Nice username btw.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-15 10:37
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/638

**Closed by heinezen** 2021-06-15 10:37 UTC
Labels: bug

**Comment by dsarkar** [comment] 2021-06-16 09:33
---
Internal Tracking ID: [EXPOSUREAPP-7831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7831) iOS
Internal Tracking ID: [EXPOSUREAPP-7865](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7865) Android
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-06-16 10:43
FYI PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/2950

**Comment by dsarkar** [comment] 2021-06-16 11:35
FYI PR Android https://github.com/corona-warn-app/cwa-app-android/pull/3467
