### ISSUE TITLE
Bluetooth status reported incorrectly after long idle time (deep sleep/ doze)

### ISSUE THREAD

**Issue by lpfann** [corona-warn-app/cwa-app-android#626] opened 2020-06-18 08:40 UTC
## Describe the bug

After the last two nights, where I did not use my phone and had it sitting on a table, the bluetooth status in the CWA is incorrectly reported as deactivated.
Bluetooth still works for others devices (smartwatch), so the hardware definetly is active after using the phone again in the morning.
After toggling the bluetooth switch twice (from on to off and off to on)  the CWA correctly reports bluetooth as working again.

I suspect some kind of deep sleep mechanism in Android which activates when no movement of the phone is detected.
My phone is using Android 9 and I think such a feature was introduced in Android 7 or 8.

## Expected behaviour

The bluetooth status should be correctly recognized even after the phones deep sleep.

## Steps to reproduce the issue

1. Activate App and Exposure notification.
2. Keep Bluetooth activated.
3. CWA Status is working.
3. Let phone sit on table for a few hours without charger (but enough for it to not poweroff).
4. Check CWA status which is complaining about disabled Bluetooth (even though Bluetooth is still on).

## Technical details

- Device: OnePlus 3T, Android 9

## Possible Fix

- Possibly the [doze mechanism](https://developer.android.com/training/monitoring-device-state/doze-standby) in Android?

---
Internal Tracking ID: EXPOSUREAPP-1941

**Comment by SnejPro** [comment] 2020-06-18 09:49
Same Problem on two OnePlus 6 with Android 10/Oxygen 10.3.4.

Maybe a problem with the Oxygen battery optimation. I have disabled it for CWA and will report the result tomorrow.

**Comment by corneliusroemer** [comment] 2020-06-18 19:37
Possibly duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/496

**Comment by SnejPro** [comment] 2020-06-20 10:01
Since i deactivated battery optimization, i haven't seen this error message anymore.

**Comment by lpfann** [comment] 2020-06-21 11:13
> Since i deactivated battery optimization, i haven't seen this error message anymore. 
> 
> ![Screenshot_20200620-115636](https://user-images.githubusercontent.com/11321022/85199183-db08c600-b2ed-11ea-8ff6-588962a760db.jpg)
> 

I made the same expirience.

So I would propose to add an info screen in the app for people to deactivate battery saving.

Or talk with manufactures to add exceptions to their battery saver if that is possible ( for old phones).

**Comment by m-brandl** [comment] 2020-06-24 10:22
I can confirm the same issue on a OnePlus 7T with recently updated OS (Oxygen OS 10.0.11.HD65BA). Deactivating power optimization seemed to fix the issue, at least it seemed fixed this morning.

**Comment by holstuwe** [comment] 2020-07-02 07:12
Copy that for OnePlus 7T Pro with Oygen10.0.9.HD01BA.  Trying deactivation of power optimization.

**Comment by heinezen** [comment] 2020-11-22 17:33
Solved in CWA version 1.5, so I'm closing this. Please report back if the issue still persists.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2020-11-22 17:33 UTC
Labels: UX, bug, documentation, mirrored-to-jira
