### ISSUE TITLE
No warning in CWA ( 1.11.0) Android even after close contact to risky person for days

### ISSUE THREAD

**Issue by doc-cwa** [corona-warn-app/cwa-app-android#2282] opened 2021-02-03 17:11 UTC
A member of our family has been tested positive and has registered this immediately on CWA same day. An appropriate warning is shown in the CWA on my mobile ( Huawei P30)  but not on the mobile ( Samsung-Android)  of my wife even after 2- succesfull updates on 2 aubsequent days. 
The information  **Ich habe eine Risiko-Begegnung, mir wird aber nach wie vor ein niedriges Risiko angezeigt** doesn't explain this behaviour ( or at least I couldn't understand )
Does the application check, if required version of Android ( interface) have been installed on respective mobile ? 

 

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:        Samsung 
- Android version:
- App version:

**Comment by MikeMcC399** [comment] 2021-02-03 17:59
Hello @doc-cwa 

There is an FAQ article https://www.coronawarn.app/en/faq/#dissimilar_indication_of_risk_status (or https://www.coronawarn.app/de/faq/#dissimilar_indication_of_risk_status) which tries to explain about this, but it is quite general.

Was exposure logging in the Corona-Warn-App activated on the phone of your wife and your family member **before** the family member reported their infection through the app? The app only alerts for past contacts and not for current ones. 

> Does the application check, if required version of Android ( interface) have been installed on respective mobile ?

Could you explain what you mean about this question? The app sends out Bluetooth signals which are picked up by any other device with the app installed. There is an explanation on https://www.coronawarn.app/en/ of how the app works (or https://www.coronawarn.app/de/ in German). If it is not clear then ask again.

**Comment by doc-cwa** [comment] 2021-02-03 19:04
Hi Mike,

 

thanks a lot for the fast response . 

If have put my feedback under your questions. If I understood the logic of CWA right you may close the issue

 

thanks again and take care

 

 

 

Von: Mike McCready <notifications@github.com> 
Gesendet: Mittwoch, 3. Februar 2021 19:00
An: corona-warn-app/cwa-app-android <cwa-app-android@noreply.github.com>
Cc: doc-cwa <rainer.ibert@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] No warning in CWA ( 1.11.0) Android even after close contact to risky person for days (#2282)

 

Hello @doc-cwa <https://github.com/doc-cwa> 

There is an FAQ article https://www.coronawarn.app/en/faq/#dissimilar_indication_of_risk_status (or https://www.coronawarn.app/de/faq/#dissimilar_indication_of_risk_status) which tries to explain about this, but it is quite general.

Was exposure logging in the Corona-Warn-App activated on the phone of your wife and your family member before the family member reported their infection through the app? The app only alerts for past contacts and not for current ones.

If I understood right  the general tracking is only considering „exposures “ that happened before the registration of a positive test result. This could well be the reason for the described effect as exposure – log on my wifes mobile was probably not active before registration of the test-result. To be honest for me sounds still a little weird , so if I meet a person today that has been registered yesterday as positive I won’t get any warning ?

Does the application check, if required version of Android ( interface) have been installed on respective mobile ?

Could you explain what you mean about this question? The app sends out Bluetooth signals which are picked up by any other device with the app installed. There is an explanation on https://www.coronawarn.app/en/ of how the app works (or https://www.coronawarn.app/de/ in German). If it is not clear then ask again.

I was referring tot he bug reported on 13.1.2021 
 <https://www.theverge.com/2021/1/13/22228594/google-coronavirus-tracking-app-exposure-notifications-issues-problems> https://www.theverge.com/2021/1/13/22228594/google-coronavirus-tracking-app-exposure-notifications-issues-problems 
and question was if it is possible to technically check on app-side if the required patches have been updated on the respective mobile where the CWA is running.

**Comment by MikeMcC399** [comment] 2021-02-03 20:23
@doc-cwa 
> If I understood right  the general tracking is only considering „exposures “ that happened before the registration of a positive test result. This could well be the reason for the described effect as exposure – log on my wifes mobile was probably not active before registration of the test-result. To be honest for me sounds still a little weird , so if I meet a person today that has been registered yesterday as positive I won’t get any warning ?

The idea is that a person who thinks they might be infected should get tested and **avoid contact with other people**, at least until the result of the test is known. If the result of the test is positive, then RKI recommends isolation (see https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Flyer_Patienten.pdf) so you should not meet an infected person out shopping or on public transport, etc and therefore the app is not expected to warn other people meeting an infected person after they have been confirmed to be infected. It is never a real-time warning in any case, it is always just a historical warning. The app cannot warn in real time **and** preserve privacy.

> https://www.theverge.com/2021/1/13/22228594/google-coronavirus-tracking-app-exposure-notifications-issues-problems

Now I understand the question! No, in fact the app does not check this point, but if the fix is not installed then the risk evaluation does not work at all, and that is quite obvious because the app hangs at the state where it shows "Data is being downloaded.." and it never changes the date of the last update. We also had the question to the Open Source Team / Google about how to check if the fix is installed, but there was no exact answer about this. So, if you are getting a new date being shown for the exposure check update, the fix must be installed.

There is a blog post confirming that the fix was rolled out by Google https://www.coronawarn.app/en/blog/2021-01-14-android-key-matching-issue-fixed/ and you can see the detailed reports in the related issue here #2081. The fix was rolled out by January 14, 2021 and there have not been any reports since that date that the problem was not solved.

Thank you for responding that your question has been answered! You can close this issue yourself if you open it in a web browser and click on the button "Close issue" at the bottom. I am only a Contributor, not a Member (Moderator) so I can't close your issue for you. Sorry!

**Comment by doc-cwa** [comment] 2021-02-03 22:03
Hi Mike,

 

thanks a lot .. philosophy behind understood … I will close the issue 

 

best regards and stay safe 

 

Von: Mike McCready <notifications@github.com> 
Gesendet: Mittwoch, 3. Februar 2021 21:24
An: corona-warn-app/cwa-app-android <cwa-app-android@noreply.github.com>
Cc: doc-cwa <rainer.ibert@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] No warning in CWA ( 1.11.0) Android even after close contact to risky person for days (#2282)

 

@doc-cwa <https://github.com/doc-cwa> 

If I understood right the general tracking is only considering „exposures “ that happened before the registration of a positive test result. This could well be the reason for the described effect as exposure – log on my wifes mobile was probably not active before registration of the test-result. To be honest for me sounds still a little weird , so if I meet a person today that has been registered yesterday as positive I won’t get any warning ?

The idea is that a person who thinks they might be infected should get tested and avoid contact with other people, at least until the result of the test is known. If the result of the test is positive, then RKI recommends isolation (see https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Flyer_Patienten.pdf) so you should not meet an infected person out shopping or on public transport, etc and therefore the app is not expected to warn other people meeting an infected person after they have been confirmed to be infected. It is never a real-time warning in any case, it is always just a historical warning. The app cannot warn in real time and preserve privacy.

https://www.theverge.com/2021/1/13/22228594/google-coronavirus-tracking-app-exposure-notifications-issues-problems

Now I understand the question! No, in fact the app does not check this point, but if the fix is not installed then the risk evaluation does not work at all, and that is quite obvious because the app hangs at the state where it shows "Data is being downloaded.." and it never changes the date of the last update. We also had the question to the Open Source Team / Google about how to check if the fix is installed, but there was no exact answer about this. So, if you are getting a new date being shown for the exposure check update, the fix must be installed.

There is a blog post confirming that the fix was rolled out by Google https://www.coronawarn.app/en/blog/2021-01-14-android-key-matching-issue-fixed/ and you can see the detailed reports in the related issue here #2081 <https://github.com/corona-warn-app/cwa-app-android/issues/2081> . The fix was rolled out by January 14, 2021 and there have not been any reports since that date that the problem was not solved.

Thank you for responding that your question has been answered! You can close this issue yourself if you open it in a web browser and click on the button "Close issue" at the bottom. I am only a Contributor, not a Member (Moderator) so I can't close your issue for you. Sorry!

**Closed** 2021-02-03 22:26 UTC
Labels: bug

**Comment by doc-cwa** [comment] 2021-02-03 22:28
understood the logic behind the implemented code ..
issues closed

**Comment by MikeMcC399** [comment] 2021-02-04 11:18
Hi Rainer @doc-cwa 

Thank you for closing the issue. In case anybody else is reading this later here is some official backup information in German from the RKI:

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html

- Das Robert Koch-Institut empfiehlt und bittet nachdrücklich, dass sich positiv Getestete und damit ansteckende Personen isolieren, um weitere Ansteckungen zu vermeiden.

- Behandlung von positiv getesteten Patientinnen und Patienten mit adäquater Schutzausrüstung* (vorherige Verifizierung über die Corona-Warn-App)
Bei der Arbeit mit Personen, die sich bereits über die Corona-Warn-App als positiver Fall verifiziert haben lassen, werde keine weiteren Codes durch die App ausgetauscht und damit keine neuen Warnmeldungen generiert. Ein erhöhtes Risiko wird ausschließlich für Begegnungen für die letzten 10 Tage vor der Verifikation ausgesprochen. Danach wird die Austauschfunktion der Codes über die App des verifizierten Falls deaktiviert. Demnach wird bei der Arbeit mit verifizierten positiven Fällen dem Personal kein erhöhtes Risiko angezeigt werden und die App kann weiterhin mit vollständigen Funktionen genutzt werden.
(Z.B. Arbeit auf einer Station mit bestätigten COVID-19 Fällen)
