### ISSUE TITLE
Andoid 5.1.1 support

### ISSUE THREAD

**Issue by eberlems** [corona-warn-app/cwa-app-android#1446] opened 2020-10-21 11:10 UTC
Scheinbar ist die bisherige Software ja nur ab Andoid 6.0 verfügbar wegen Exposure Notification API
https://developers.google.com/android/exposure-notifications/exposure-notifications-api die aber auch für 5.0 in ner älteren Version existiert.
Im nahem Umfeld kenne ich alleine 5 Adroid 5.1.1 Geräte und die Besitzer wollen nicht bei Telekom&co was neues kaufen. Ob alle Bluetooth 4.0 oder besser haben weiß ich nicht aber mein Sony Xperia ZR hat es.
Ich habe jetzt auch keinen Nerv mich in Android Programmiersprache einzuarbeiten.

**Comment by dsarkar** [comment] 2020-10-26 11:37
Dear @eberlems,

thank you for your post. As you mention the App requires Android 6.0 or above, see also 
https://www.coronawarn.app/en/faq/#minimum_requirements.

There are already several conversation in same context, which indicate that support of Android versions below 6 are problematic due to several reasons (Exposure notification API, Bluetooth and Energy management issues). Please have a look here:

https://github.com/corona-warn-app/cwa-app-android/issues/489#issuecomment-644577456
https://github.com/corona-warn-app/cwa-app-android/issues/165, 
https://github.com/corona-warn-app/cwa-app-android/issues/530,  
https://github.com/corona-warn-app/cwa-app-android/issues/503, 
https://github.com/corona-warn-app/cwa-app-android/issues/614.

Thanks you for your understanding. 
Best wishes,

DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-10-26 11:37
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/489

**Comment by eberlems** [comment] 2020-10-26 12:08
I don't get why. Seems there is a API version 21 that would work on Android 5.1 and the phone has Bluetooth 4.0. Maybe not the full API verion 23 can be utilized, but just not being able to install?

**Comment by MikeMcC399** [comment] 2020-10-26 16:43
Actually, CWA Android Version 1.5.0 doesn't even compile with minSdkVersion 21. 

`uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc03] `

That module is critical for CWA.

**Closed** 2020-10-27 07:35 UTC
Labels: duplicate, enhancement
