### ISSUE TITLE
Show the number of saved contacts

### ISSUE THREAD

**Issue by Kranberger** [corona-warn-app/cwa-app-android#752] opened 2020-06-25 16:43 UTC
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Currently you see e.g. "9 von 14 Tagen aktiv". It would be very helpful to me, to see the number of contacts already saved also.

## Suggested Enhancement

From my point of view, I would put the number of contacts directly below "9 von 14 Tagen aktiv".

## Expected Benefits

With this information I can estimate how reliable the risk analysis is. If no contacts would be shown (and I'm sure there should be at least the family contacts), then I know that something is wrong.

**Comment by tomjschwanke** [comment] 2020-06-25 17:08
Unfortunately this is info is not provided by the Google Tracing API

**Comment by ironjan** [comment] 2020-06-25 18:04
Duplicate of #689. As stated by in [[0]](https://github.com/corona-warn-app/cwa-app-android/issues/689#issuecomment-647028990) and [[1]](https://github.com/corona-warn-app/cwa-app-android/issues/689#issuecomment-647360606), this feature is also closely related to https://github.com/corona-warn-app/cwa-wishlist/issues/5 

@tkowark , Highlighting you as you were active in #689 ;)

**Comment by tkowark** [comment] 2020-06-25 18:06
Indeed, that‘s a duplicate. Thanks for finding it and tagging me :-)

**Closed by tkowark** 2020-06-25 18:06 UTC
Labels: enhancement
