### ISSUE TITLE
Inaccurate text "Bisher keine Risiko-Begegnungen"

### ISSUE THREAD

**Issue by THausherr** [corona-warn-app/cwa-app-android#1532] opened 2020-11-04 09:24 UTC
## Current Implementation

The text "Bisher keine Risiko-Begegnungen" (no risky contacts) is inaccurate if in the past one had low risk contacts

## Suggested Enhancement

Change the text to "Keine Risiko-Begegnungen innerhalb der letzten 14 Tagen" (no risky contacts within the last 14 days)

## Expected Benefits

Slightly improved accuracy. I know I'm being picky here.

**Comment by MikeMcC399** [comment] 2020-11-04 09:44
Hi @THausherr 
I happy to read that you also think this is not so good!

I reported this issue in https://github.com/corona-warn-app/cwa-documentation/issues/430 in September 2020, in fact. It affects Android and iOS.

**Comment by THausherr** [comment] 2020-11-04 09:59
thanks Mike. My issue can be closed "duplicate" label.

**Comment by dsarkar** [comment] 2020-11-04 10:14
Dear @THausherr,

Thank you for your post. As suggested I will close this issue as a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/430. Thanks.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-04 10:14
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/430.

**Closed by dsarkar** 2020-11-04 10:14 UTC
Labels: enhancement
