### ISSUE TITLE
"Etwas ist schief gelaufen"

### ISSUE THREAD

**Issue by Steffen01** [corona-warn-app/cwa-app-android#913] opened 2020-07-23 06:08 UTC
![Issue](https://user-images.githubusercontent.com/11137458/88256425-9ccf3f80-ccbb-11ea-864f-2e20560b17e9.jpg)

**Comment by SebastianWolf-SAP** [comment] 2020-07-23 08:05
According to the screenshot it seems to be a duplicate of #809, please follow-up there.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-07-23 08:05 UTC
Labels: bug, duplicate
