### ISSUE TITLE
Background update does not work, despite v.1.3.1 and “prioritized background activity”

### ISSUE THREAD

**Issue by Vf97** [corona-warn-app/cwa-app-android#1311] opened 2020-10-05 10:39 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Mobile device:
- Android version:

**Comment by MikeMcC399** [comment] 2020-10-05 12:00
The title of this issue is identical to "Background update does not work, despite v.1.1.1 and “prioritized background activity”" https://github.com/corona-warn-app/cwa-app-android/issues/933 except for the version number.

https://github.com/corona-warn-app/cwa-app-android/issues/933 is open and covers the problem with the current version 1.3.1 (despite the title with v.1.1.1 not having been updated), so this issue (https://github.com/corona-warn-app/cwa-app-android/issues/1311) should be closed as a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/933.

**Closed** 2020-10-05 19:16 UTC
Labels: bug
