### ISSUE TITLE
Android App: PDF generated for event has an awkward poster size, might lead to print errors

### ISSUE THREAD

**Issue by tik-boomer** [corona-warn-app/cwa-app-android#2928] opened 2021-04-23 10:59 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- Android version: 11,   Build RQ2A.210405.005
- App version: 2.03

## Describe the bug

The PDF poster generated for an event has a mismatch in PDF-file propertied between total size, and pages size.

## Steps to reproduce the issue

1. Generate a new event place, under Education / Bildungseinrichtung. 
2. Share the generated QR-code Poster by gmail.
3. download the QR-code poster using Adobe acrobat Reader
4. Start to print the document 
5. In the print dialoge chose actual size ("Tatsächliche Größe")
6. The print window will only include part of the qr-code poster (screenshot included)

## Expected behaviour

When opening the app generated QR-code poster PDF-file for printing, printing at actual size should print the complete image, in actual size, **on an A4 page**.

It seems to me that the document and image were actually generated much large than A4 size, at 508 x 718 mm. This way the local printout has to be scaled down to A4 first. Should not A4 be the standard, and easily printed with all printing presets --
[cwa-qr-code.pdf](https://github.com/corona-warn-app/cwa-app-android/files/6364731/cwa-qr-code.pdf)
![Event-QR print size](https://user-images.githubusercontent.com/66428107/115861664-54ec6d00-a433-11eb-92c6-126469174b88.png)

 and the people needing bigger printouts scale up? In the privacy concerns it is suggested to generate and print a new qr-code every day. Who has a printer of this format for daily routine printing? :-)

## Possible Fix

Simply generate the image and the PDF for full A4 format.

## Additional context

I see this with Android 11, butdo not have a IOS device, so I assume, but can not be sure, that this issue exists in the IOS app, too.

Attachments:
- Screen shot of print dialogue
- PDF file

---
Internal Tracking ID: [EXPOSUREAPP-6696](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6696)

**Comment by Ein-Tim** [comment] 2021-04-23 11:06
I think this is intended since they want the PDF to be high quality even if you print it out to A3. See https://github.com/corona-warn-app/cwa-website/pull/1130#issuecomment-825026491

**Comment by tik-boomer** [comment] 2021-04-23 11:25
Actually the PDF page size assigned does not match a standard print format, it is bigger than A3, but smaller than A2, seems as if it was chosen a bit randomly. So each and every printer needs resizing. :-(

On the other side, if it was done properly (vector image, not bitmap), it scales easily from post stamp to continent size, at full quality.

Therefore it would be easiest for everybody with a standard A4 printer and no real problem for those with special equipment, to simply use the standard, A4. This is why we have standards ;-)

**Comment by dsarkar** [comment] 2021-04-23 11:29
@tik-boomer @Ein-Tim  @tik-boomer  Thanks for reporting and commenting. We will treat this as an wishlist item, since it works as intended. Many thanks.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2021-04-23 11:38
If we move it to the wishlist I suggest to remove the Android from the title, I didn't look into it yet but I'm quite sure iOS is the same here.

**Comment by dsarkar** [comment] 2021-04-23 11:57
@Ein-Tim @tik-boomer Actually I am having second thoughts. The pdf created by iPhone 6s is A4 size.

![image](https://user-images.githubusercontent.com/1409741/115867818-dba54800-a43b-11eb-8f87-61b1cae5009d.png)

**Comment by dsarkar** [comment] 2021-04-23 12:05
Samsung Galaxy A21s

![image](https://user-images.githubusercontent.com/1409741/115868523-e01e3080-a43c-11eb-8218-d2cb149670cd.png)

**Comment by dsarkar** [comment] 2021-04-23 12:13
@Ein-Tim Can you check on different iPhone (not 6s), please? Thanks.

**Comment by dsarkar** [comment] 2021-04-23 12:15
Internal Tracking ID: [EXPOSUREAPP-6696](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6696)

**Comment by Ein-Tim** [comment] 2021-04-23 12:19
@dsarkar 

I'm already on it. Will check on iPhone XR and on another iPhone 6s.

**Comment by mlenkeit** [comment] 2021-04-23 12:48
@tik-boomer you're on Windows, right? At least on Mac, everything seems to work alright and there's no indication that the format is off. I'll try it out on a Windows machine...

**Comment by Ein-Tim** [comment] 2021-04-23 12:59
Mac OS Big Sur 11.2.3, same seize as reported by @dsarkar before. 
QR-Code generated via iPhone 6s/XR.

**Comment by vaubaehn** [comment] 2021-04-23 13:03
Acrobat reader on windows for me automatically picks the option "Übergroße Seiten verkleinern", and the print out works fine on A4. "Tatsächliche Größe" is @tik-boomer 's screenshot.
Tested also on LG G4 with HP printer plug-in: automatically scaled to A4.
I admit I do not fully understand the problem...

**Comment by Ein-Tim** [comment] 2021-04-23 13:32
The only problem I could think of is that someone intends to print out on a A4 sheet of paper but the option "Tatsächliche Größe" is active and gets only this little part of the QR-Code.
But if we change it to A4 and someone intends to print out on a larger poster, like A3 and has "Tatsächliche Größe" aktive, the poster will not be filled completely.

**Comment by tik-boomer** [comment] 2021-04-23 13:37
@vaubaehn From the message trail here I can conclude, that the PDF generated from the iOS app correctly sets the page size and the image size to A4. Whoever receives this on whatever system can easily print it on A4 - or scale it differently if needed for a poster.

Strangely the Android app set the PDF properties differently, to a much bigger page. If this is received for printing, you *may* be lucky, and your default settings *might* print it correctly on A4. This should not be a gamble, in my humble opinion, but should be set to A4 size, like on iOS.

@mlenkeit Did you try with a self generated PDF, or did you use the one I had attached?

**Comment by tik-boomer** [comment] 2021-04-23 13:49
@Ein-Tim I am using Acrobat Reader on Windows. There it's easy to use one of the automatic scaling options, and printing should be fine. 

But there are many other PDF-Tools that might be the tool at hand for an event organizer, e.g. browser integrated viewers, open source tools, shop POS solutions, you name it... By using a "wrong" size you risk printig problems. 

In my opinion, for the Android app, it would be just easy, and clean, and consistent with the iOS app, to set the PDF size to A4 - instead of "518 mm x 718 mm".

**Comment by Ein-Tim** [comment] 2021-04-23 13:52
@tik-boomer 

I agree with you that we should align it to the iOS version. But as said above, both ways can end in "printing problems", either too big, too small, etc. 🙂

**Comment by mlenkeit** [comment] 2021-04-23 13:56
> @mlenkeit Did you try with a self generated PDF, or did you use the one I had attached?

I generated my own, but now compared it with yours. Yours has a resolution of 1440x2035, the one that I created on an Android phone has 841x1190 and the one from an iPhone has 595x842.

Looks like the size also depends on the hardware...

![2021-04-23_15-50-00](https://user-images.githubusercontent.com/2060790/115881505-1b742b80-a44c-11eb-9ec1-01339034e807.png)

**Comment by tik-boomer** [comment] 2021-04-23 14:05
@mlenkeit Thank you very much for this insight. I can understand that the QR code scales to the display resolution - for use on the smartphone display. But it should be normalized (rescaled) to identical resolution and size for the printable PDF.

**Comment by mlenkeit** [comment] 2021-04-23 14:13
@tik-boomer I agree with you, we'll take a look at this to see how to best fix it...

**Comment by dsarkar** [comment] 2021-05-06 13:13
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/3095

**Comment by heinezen** [comment] 2021-06-20 13:24
Dear community,

This has been fixed in CWA release 2.3.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-06-20 13:24 UTC
Labels: Fix 2.3, bug, mirrored-to-jira
