### ISSUE TITLE
all updated, and failure

### ISSUE THREAD

**Issue by Xam40** [corona-warn-app/cwa-app-android#1585] opened 2020-11-12 14:33 UTC
all updated
Samsung s7
Corona app 1.6
Android 8.0

![Screenshot_20201112-125238_Corona-Warn](https://user-images.githubusercontent.com/74357940/98952747-1786c980-24fc-11eb-9c57-fe2cb112788d.jpg)

Thanks

**Comment by heinezen** [comment] 2020-11-12 16:58
Hey @Xam40 ,

Thank you for the feedback. The bug you report is already known and being monitored and investigated by the development team using this issue: https://github.com/corona-warn-app/cwa-app-android/issues/1459 . The recommended workaround is to not open the app for 24 hours and see if the error is gone. If that doesn't help you, please make a new comment in the linked thread.

I will close this issue as a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1459

Regards,
CH


----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-11-12 16:59
Duplicate of #1459

**Closed by heinezen** 2020-11-12 16:59 UTC
Labels: bug
