### ISSUE TITLE
Zero key count - No risk ever detected (false negative)

### ISSUE THREAD

**Issue by bl00dymarie** [corona-warn-app/cwa-app-android#1561] opened 2020-11-09 14:00 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

💡 Updated version is now 1.9.1  (Corona Warn App Android Version)💡 
Since the launch of the app I am using it on my Android v. 7.1.2, Bluetooth and Location turned on. I realized the app has never shown me any risk exposure at all, 0 risk encounters, which makes me believe this cannot be true, based in Berlin taking public transport on a weekly basis.

I am using the app Orbot and wonder if this is causing the app not to work properly, though this probably isn't the problem see this Tweet https://twitter.com/qbi/status/1325797835372187650

## Expected behaviour

I would expect 
* the app to find and get risk encounters
* the app to display found risk encounters

## Technical details

- Mobile device: Wileyfox Swift 2 Plus
- Android version: 7.1.2
- Corona Warn App version: 1.9.1

## Additional context

---
Internal Tracking ID EXPOSUREAPP-4130

**Comment by MikeMcC399** [comment] 2020-11-09 14:43
@bl00dymarie 

Orbot is a VPN app, correct? In which case it should not interfere with the Bluetooth Low Energy signals.
If CWA is not giving any error message and it is showing that it updated today then you can assume that the network connection to the server is working.

It's difficult to know if the app is really working. If you want to check that you are receiving Bluetooth signals, I found that [Beacon Scope](https://play.google.com/store/apps/details?id=com.davidgyoungtech.beaconscanner&hl=en) is easy to use and it shows Exposure Notification beacons from other devices.

**Comment by bl00dymarie** [comment] 2020-11-09 18:14
Will have a look, thanks for the suggestion @MikeMcC399!

**Comment by hackfix** [comment] 2020-11-12 13:12
There might be an issue with Exposure Notifications update and the cause might be the same as reported here #1516 

Could you go to Settings > Google > COVID-19 exposure notifications > Exposure checks and check if there were any updates in the last days.

**Comment by MikeMcC399** [comment] 2020-11-25 09:12
> Could you go to Settings > Google > COVID-19 exposure notifications > Exposure checks and check if there were any updates in the last days.

Normally the app should report if it hasn't been able to do the exposure checks for a while. Nevertheless it's a good idea to check the Google logs and rule out this source of a problem.

**Comment by bl00dymarie** [comment] 2020-11-25 12:18
I used Bluetooth tracking while being on public transport and I can confirm, my phone is tracking and detecting a LOT, see screenshot.

![cwa1](https://user-images.githubusercontent.com/11837431/100226819-8ca4c680-2f20-11eb-8f40-922e6edf118b.jpeg)
![cwa2](https://user-images.githubusercontent.com/11837431/100226822-8f072080-2f20-11eb-9b17-ed2dde572478.jpeg)
![cwa3](https://user-images.githubusercontent.com/11837431/100226827-90d0e400-2f20-11eb-98e5-3070648c29d5.jpeg)

**Comment by bl00dymarie** [comment] 2020-11-25 12:32
:eyes: Looking into Settings > Google > Covid 
Nevertheless I have never received any risk exposure before Sept 26th either... so I am not sure if that's the ONE problem/bug?!

![covid-note0](https://user-images.githubusercontent.com/11837431/100228076-6b44da00-2f22-11eb-8915-5d52a07d779c.jpeg)
![covid-note1](https://user-images.githubusercontent.com/11837431/100228087-6ed86100-2f22-11eb-8e6a-e294f4c955d8.jpeg)

**Comment by MikeMcC399** [comment] 2020-11-25 13:08
@bl00dymarie 
It's good that you added the screen shot, which shows:

"Letzte Überprüfung auf eine mögliche Begegnung mit einer infizierten Person: **26. September um 08:03**"

On my phone I see
"Letzte Überprüfung auf eine mögliche Begegnung mit einer infizierten Person: heute um 02:13"

Could you export the exposure logs and post the file here?

Tap "Überprüfung auf mögliche Begegnungen"
Drei-Punkte-Menü aufrufen
Überprüfungen exportieren

Then add a .txt extension to the file all-exposure-checks.json before you post it here.

**Comment by hackfix** [comment] 2020-11-25 13:09
@bl00dymarie:

gotcha - my device received the latest exposure updates at about the same time. In my case it was on Sept 24th.

Can you tap on "Überprüfung auf mögliche Begegungen" and check if there were any updates in the last days.

**Comment by bl00dymarie** [comment] 2020-11-25 14:10
So it seems the daily updates were done (last 14 days), but the matching functionality (?) might not work!
![cwa](https://user-images.githubusercontent.com/11837431/100238313-596a3380-2f30-11eb-9d32-0a6005af702f.jpeg)
![cwa0](https://user-images.githubusercontent.com/11837431/100238325-5d965100-2f30-11eb-9b8a-ccbcfc6f20dd.jpeg)
![cwa1](https://user-images.githubusercontent.com/11837431/100238330-60914180-2f30-11eb-84f9-61e03c9f1c76.jpeg)

**Comment by bl00dymarie** [comment] 2020-11-25 14:18
thanks for the hint where to find the logs, there is nothing more to see in the logs unfortunately, the most recent log is:

```
{
  "timestamp":"25. November 2020, 03:36",
  "keyCount":0,
  "matchesCount":0,
  "appName":"Corona-Warn",
  "hash":"random-hash"
},
```

**Comment by MikeMcC399** [comment] 2020-11-25 14:41
@bl00dymarie 
I have seen keyCount zero reported on a rooted device before and on an Android 11 emulator.

Is your device rooted by any chance?

You could check your network access to the key by installing the
[Warn-App-Companion](https://play.google.com/store/apps/details?id=org.tosl.warnappcompanion&gl=DE).

Another check would be to open https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date in a browser and see if a list of dates is shown. (You might have to zoom in to read the dates.)

**Comment by bl00dymarie** [comment] 2020-11-25 15:33
Not rooted, no!

**Comment by MikeMcC399** [comment] 2020-11-25 16:22
@bl00dymarie 
CWA Android 1.7.0 is in the process of being released and I expect it will appear on [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en) soon.

There are enough changes between 1.6.1 and 1.7.0 to make it worthwhile you checking whether 1.7.0 works better on your device. (See [details of v1.7.0 release here](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.7.0).)

**Comment by dsarkar** [comment] 2020-11-26 14:03
Dear @bl00dymarie, @MikeMcC399 

Thanks for contributing here. Regarding the update to CWA 1.7.1 (for both iOS and Android): Please note that it is a staged rollout. Over the next two days, 100% of the users should have received the update. 
  
We would appreciate very much your (hopefully positive) feedback regarding this issue over the next few days! Otherwise, we will create an internal tracking number.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by bl00dymarie** [comment] 2020-11-26 14:06
Thanks for the update @dsarkar, will keep you posted as soon as I update the app to 1.7 on my Android.

**Comment by bl00dymarie** [comment] 2020-12-04 15:48
Unfortunately there a no good news, the problem still remains, the status quo is:

New update installed on Nov 26, version is now 1.7.1, the new version now comes with 3x checks per day
Exposure logs are still completely empty, keyCount is still 0 for every single check `"keyCount":0`.

This creates a false feeling of security/safety when in the end the software is not reliable. I would encourage you to look into this, and I am happy to continue to support if needed. Have you tested this on a physical device that is running on Android 7 or/and Android 6 since this is the minimal Android version officially supported?

Thanks!

**Comment by MikeMcC399** [comment] 2020-12-04 16:16
@bl00dymarie 
> New update installed on Nov 26, version is now 1.7.1, the new version now comes with 3x checks per day
Exposure logs are still completely empty, keyCount is still 0 for every single check "keyCount":0.

Since I could reproduce the issue with keyCount=0 on an Android 11 emulator, I submitted this problem as https://github.com/corona-warn-app/cwa-app-android/issues/1752. It may not be the same root cause as on your device, but at least it may be a starting point for investigation.

Did you follow my suggestion in https://github.com/corona-warn-app/cwa-app-android/issues/1561#issuecomment-733747345 about installing [Warn-App-Companion](https://play.google.com/store/apps/details?id=org.tosl.warnappcompanion&gl=DE) or opening https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date ? If yes, what were the results?

**Comment by bl00dymarie** [comment] 2020-12-04 20:34
Thanks for the hints, I did open the t-online URL on my device and it gave me back an array of strings of the last couple of days which doesn't explain the issue here correct me if I'm wrong?!

**Comment by MikeMcC399** [comment] 2020-12-04 20:47
@bl00dymarie 
> Thanks for the hints, I did open the t-online URL on my device and it gave me back an array of strings of the last couple of days which doesn't explain the issue here correct me if I'm wrong?!

That was just a primitive test to check that your device can access the server where the keys are stored. If you saw the array of dates, then it shows that you have basic connectivity. These are the dates currently returned by https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date:
`["2020-11-20","2020-11-21","2020-11-22","2020-11-23","2020-11-24","2020-11-25","2020-11-26","2020-11-27","2020-11-28","2020-11-29","2020-11-30","2020-12-01","2020-12-02","2020-12-03"]`

We have to wait for feedback from the Open Source Team now concerning further troubleshooting.

**Comment by dsarkar** [comment] 2020-12-05 18:32
Dear @bl00dymarie, @MikeMcC399, and community

Thank you all for your contributions. We have updated for the developers the Internal Tracking ID EXPOSUREAPP-4130   (https://github.com/corona-warn-app/cwa-app-android/issues/1752). Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by mucdd** [comment] 2020-12-16 19:32
Dear @bl00dymarie and community, 

same problem here (Lenovo K10 device, Android 6.0): 
"Letzte Überprüfung auf eine mögliche Begegnung mit einer infizierten Person: 24. September um 03:02"
Daily logfiles always show Key Count: 0
Following the svc.90 ... link mentioned above I get all dates of the past 14 days. 
CWA version is 1.7.1, Google Play Services version 20.47.13

**Comment by MikeMcC399** [comment] 2020-12-16 19:46
CWA 1.9.1 is just being rolled out according to https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ although I am not seeing it myself yet in [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en).

CWA 1.9.1 significantly changes the way that exposure checks are done. It will be worth checking to see if the issue here is fixed by this version, even if I haven't seen any feedback from the developers that they found and fixed this issue.

**Comment by hackfix** [comment] 2020-12-17 07:37
There are at least 4 other friends of mine who are affected by the same problem. They only became aware of the problem when I pointed it out to them.I think that a lot of users have this problem as well - but no one notices it.
I find it very dangerous that the app shows a green status despite this problem.
The government has spent a lot of money on an app that does not work properly even after months. Of course, with such a large project there are many challenges and not all requirements can be implemented immediately.
But if we have an app that is not able to communicate a malfunction to the user after this long development time, then there is a fundamental problem.

@bl00dymarie:
I also had the same problems with CWA as you. 
I gave up hunting for this problem and installed an alternative version of CWA: https://codeberg.org/corona-contact-tracing-germany/cwa-android
With this version there are no problems and I was also informed yesterday about a risk exposure.  CWA still does not show any risk....
CCTG is based on the same code base as CWA, but does not use Google's Exposure Notifications API, but uses the free microg library. It seems that CWA is not using the Google API properly...

**Comment by MikeMcC399** [comment] 2020-12-17 08:09
@hackfix
> It seems that CWA is not using the Google API properly...

You can only guess that is the cause.

In any case, as I wrote in https://github.com/corona-warn-app/cwa-app-android/issues/1561#issuecomment-746905810 "CWA 1.9.1 significantly changes the way that exposure checks are done." which means that the calls to the Google API have also been changed to replace Legacy v1 mode with ExposureWindow mode starting with this version.

**Comment by bl00dymarie** [comment] 2020-12-17 09:58
I wholeheartedly agree with you @hackfix!

**Comment by hackfix** [comment] 2020-12-17 10:22
Instead of disqualifying my statement, the developers should finally do their homework.
Some people who (unfortunately) are not getting paid for their work have done what the paid developers are not able to do.

Sorry to be so hard - but this project is burning my taxes too.
Anyone who gets money for a tax-funded project has to take criticism from the taxpayer as well.

**Comment by fynngodau** [comment] 2020-12-17 10:39
Hello @hackfix, as a maintainer of CCTG, I would like to clarify some technical aspects you mentioned:

> It seems that CWA is not using the Google API properly...

* microg provides the same method calls as the Google API. We have not changed how those methods are being called, we only swapped the Google API with the microg implementation. Thus, this seems unlikely to me.

>  With this version there are no problems and I was also informed yesterday about a risk exposure. CWA still does not show any risk....

* [As Marvin explains](https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/20#issuecomment-161401), this can happen because CCTG via microg and CWA via Google Play Services do scan regularly, but not at exactly the same point in time. This means that it could be the case that both apps are working properly even though they are displaying somewhat different risk scores.

**Comment by hackfix** [comment] 2020-12-17 11:30
@fynngodau:
Thanks for your feedback!

>microg provides the same method calls as the Google API. We have not changed how those methods are being called, we only swapped the Google API with the microg implementation. Thus, this seems unlikely to me.

At first glance, I agree with you. But I think we should also take a deeper look.
CWA worked until some months ago (-> #1516). So maybe there's a slight change in Google's API that's making the difference on some devices -> https://developers.google.com/android/exposure-notifications/doc-change-log
And maybe this change also wasn't re-implemented by microg,

> As Marvin explains, this can happen because CCTG via microg and CWA via Google Play Services do scan regularly, but not at exactly the same point in time. This means that it could be the case that both apps are working properly even though they are displaying somewhat different risk scores.

As I highlighted here #1516, on my device CWA is not successfully downloading and/or pushing the diagnosis keys to the Google API.
So without keys I will never get any risk scores from CWA.

**Comment by thomasaugsten** [comment] 2020-12-17 14:34
@hackfix Can you please create a bug report and send it to me. We will forward this google and they will check the issue
https://developer.android.com/studio/debug/bug-report
thomas.augsten@sap.com

**Comment by hackfix** [comment] 2020-12-17 14:56
Absolutely not! Don't get me wrong, but I think you guys should create this bug report. I'm not part of the development team and I'm not getting paid for doing this.

**Comment by thomasaugsten** [comment] 2020-12-17 15:05
@hackfix Google calls his log file bug report. We need this zip file from your device because we cannot reproduce this on our devices. I will handle the communication with Google. We need only your help to create the file and send it via e-mail.

**Comment by thomasaugsten** [comment] 2020-12-17 15:29
@bl00dymarie Maybe you can support us with a log file to find out why the Google ENF is not working your device.

**Comment by bl00dymarie** [comment] 2020-12-17 15:37
> thanks for the hint where to find the logs, there is nothing more to see in the logs unfortunately, the most recent log is:
> 
> ```
> {
>   "timestamp":"25. November 2020, 03:36",
>   "keyCount":0,
>   "matchesCount":0,
>   "appName":"Corona-Warn",
>   "hash":"random-hash"
> },
> ```

**Comment by thomasaugsten** [comment] 2020-12-17 17:33
@bl00dymarie Please follow this manual from google:
https://developer.android.com/studio/debug/bug-report
and send the zip file via e-mail
thomas.augsten@sap.com

**Comment by bl00dymarie** [comment] 2020-12-23 10:54
❗ With the new updated version 1.9.1 on the device the `keyCount` still remains 0 for every single check ❗ 

I put quite some effort into investigating the issue over the last 6 weeks and haven't received any meaningful response from the official dev team, this is why I am hesitant to file a report aka do the extra work as @hackfix has rightly so pointed out already @thomasaugsten. 

As you can see I am developer myself and I understand that work takes time. However no response to a bug that is preventing the very core functionality from working is very frustrating.

I really hope this bug is affecting only a handful of devices, as the app aims to be an essential part of fighting a pandemic.

**Comment by thomasaugsten** [comment] 2020-12-23 10:58
@bl00dymarie as I mentioned Google can only address the issue on your device when you provide us the zip file with the log files. 

It is only pressing a few buttons and sending a email with no text to me. At the moment you are the only persons with the issue. This is the reason we have to ask you for your help.

**Comment by doak** [comment] 2021-01-02 23:03
I have pretty much the same issue: The *Exposure Notifications* screen states `Last checked for potential exposures 16 September at 11:19` and zero keys all the time.
I am on (current) v1.10.1 of CWA and 182045516000 of ENF. It looked like the application worked all the time, though always *Low Risk* and no risk contacts.

A little background about my uncommon setup:
I rolled out CWA on four phones in total. One is working, mine and another not. Don't know about the third one yet. All the same HW (pretty old, Samsung Galaxy S3 LTE (i9305)) with some hacky/custom ROM (supporting transmissions of BLE beacons).
I initially restored a backup of my phone to at least three of the other phones. I am not sure about the one working phone. If I remember correctly, that one was already set-up manually beforehand. Hence that could mean that I just replicated a non-working system to the other two phones.
**Nevertheless, I have at least one working and one not-working system which very similar setup.**

@thomasaugsten , I will try to provide the requested logs in a follow-up post.

**Comment by doak** [comment] 2021-01-02 23:59
@thomasaugsten, unfortunately my phones crashes all the time during generation of the bugreport :(
This is probably caused by the hacky ROM. On the other hand it fails on the system with working CWA as well. I have tried both, `adb bugreport` and the on-device variant.
I managed to get one, though, but I don't know if it helps at all. I have sent it to you nevertheless.
Thanks for looking into it!

Please don't hesitate to contact me if you need more information.
Since this phone is mostly dedicated to CWA, I can practically do everything you want -- besides generating bug reports apperently :(

@bl00dymarie and @hackfix, I don't want to bug you (pun intended), but since my report is probably useless, it would be great if you re-consider if possible ;)

Regards,
doak

**Comment by doak** [comment] 2021-01-03 00:19
Just for the record: The ENF version is slightly different on the phone with the working CWA: `18204713000`

**Comment by doak** [comment] 2021-01-04 14:13
@thomasaugsten, I've sent you two additional bug reports. Although my phone keeps crashing on `adb bugreport`, a second one issued right after the first one succeeds during next boot. I hope that these bug reports include data from the previous session/boot as well. (A quick look into the content looked promising.)

As usual, please let me know if I can help in any way.

Regards,
doak

**Comment by doak** [comment] 2021-01-04 14:37
Btw, after reinstalling the ROM (including updating of Google Play Services) and installing CWA, the issue is gone. Neither wiping *Data* nor anything else I tried helped, though. Although after wiping *Sata* I have to update *Google Play Services* and reinstall CWA as well. (ENF will be updated to `18204516000`, i.e. to the same version it was before the wipe.)

This sounds like something within `/system` is causing the issue. Although mine phone is rooted, @bl00dymarie's is not IIRC. Is it possible that some leftover from previous versions of CWA or ENF is causing the issue?

**Comment by heinezen** [comment] 2021-01-05 12:14
@doak Thank you for digging further on this. We have updated the developers on your findings. 

----
Corona-Warn-App Open Source Team

**Comment by d4rken** [comment] 2021-01-05 14:33
> As you can see I am developer myself and I understand that work takes time. However no response to a bug that is preventing the very core functionality from working is very frustrating.

I totally understand the frustration and wish it would be easier. This is an unusual app and which holds the users privacy in very high regard, so it's sometimes not as easy to debug issues without user participation as it might have been in a "normal" app. Especially for issues that seem to be happening within a 3rd party framework like the ENF.

> Is it possible that some leftover from previous versions of CWA or ENF is causing the issue?

That the system log shows entries means that the CWA has files and submits them, otherwise no submission would have been attempted. So we suspect the issue to be somewhere at the border between the CWA and the ENF.
Initially I would have thought that some kind of file corruption happens to the key packages, causing the ENF to be unable to read the files, but that should have been fixed by the clearing the CWA's data (or just cache, which is where the key pkgs are stored), but for you it wasnt.

So if it's a persistent issue independent of current local data, it might be related to the signature check of the key packages.

I looked at the two bug reports you submitted but they did not contain the `logcat` part (likely due to your custom ROM). So if anyone still affected by this could create another bugreport and mail it to us, it will give everyone a much better chance at understanding the issue. While we have forwarded the bug reports to Google, I'm skeptical that there is much they can figure out without that part of the bug report.

On the off chance that your custom ROM reproduces the issue @doak, maybe you can just pipe `adb logcat` into a file (or use a root app) some time after the system shows that a check with 0 keys has been executed.

I'd bet that the ENF is printing some errors or warnings into the system log when we provide the key files, but without being able to reproduce it or having access to the log :thinking:

**Comment by doak** [comment] 2021-01-05 22:08
@d4rken, thanks a lot for the in-depth information.

Yes, I thought about `adb logcat` as well.
Unfortunately this fails, which is probably the reason why it is not included in the report as well. I fiddled around with this for quite some time, but didn't found a way to fix this without loosing the non-working state. [`adb logcat` works for a fresh install of the ROM, but it gets corrupted after restoring it using an older version of TWRP. My best guess is that exactly that had happen.]
I will have access to the other non-working devices tomorrow. There is the chance that one of them was the "master copy" and `adb logcat` still works ...

Anyway, I will keep trying to get these logs out of mine, but I am currently out of ideas. Any help is appreciated.

**Comment by doak** [comment] 2021-02-16 20:21
I am sorry, I gave up. I had a look into it several times but did not manage to get `logcat` working in any way. Unfortunately none of the other devices in question contained an image with working `logcat` as well. (I was able to track that down to restoring a backup using TWRP v3.0.2.1, in particular of the `system` partition. But I was unable to recover from that :()

**Comment by heinezen** [comment] 2021-03-23 14:43
We cannot reproduce this bug anymore. Also, ENFv2 was introduced in the meantime which might have fixed the problem. Therefore, we are closing this issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-03-23 14:43 UTC
Labels: bug, further input needed, mirrored-to-jira

**Comment by vaubaehn** [comment] 2021-08-24 17:21
Just for the records:

Tracking it down a little bit more in issue #1752 and taking opinions in this issue into account, there are two different possibilities why this could happen:

Either the signature check of the TEK packages fails, like @d4rken wrote some time ago:

> So if it's a persistent issue independent of current local data, it might be related to the signature check of the key packages.

Then ENS will refuse to check anything, and displays 0 keys (and 0 matches) accordingly. From observations on my device I found, that signature check can take a very long time (70 seconds with big packages), which let's me assume, that signature check may also be dependent on JRE (implemented algorithms) and hence can vary between Android versions and manufacturers' customizing.

Or, ENS can't access RPIs. Details: https://github.com/corona-warn-app/cwa-app-android/issues/1752#issuecomment-904754931
