### ISSUE TITLE
After adding a rapid test (Schnelltest), the confirmation screen shows PCR test

### ISSUE THREAD

**Issue by degutant** [corona-warn-app/cwa-app-android#5107] opened 2022-04-21 15:02 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a
- Android version: 12
- App version: 2.21.1

## Describe the bug

I added a rapid test (Schnelltest) by clicking the link the test center sent to me. I confirmed the steps to add the test. After it was added, in the confirmation screen the result appeared, but also there is a copy that incorrectly references the test as a PCR test:

> Ihr PCR-Test wurde hinzugefügt

![Screenshot_20220421-164821](https://user-images.githubusercontent.com/103426152/164487547-a2aa9913-c83c-4589-ae7a-86d1ddc979b3.png)

---
Internal Tracking ID: [EXPOSUREAPP-12906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12906)
covered in 
Internal Tracking ID: [EXPOSUREAPP-12933](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12933)

**Comment by MikeMcC399** [comment] 2022-04-21 15:46
@degutant

If you scan the QR code from the test station with your phone's camera app (not Corona-Warn-App) does it show anything like one of the following under Webadresse or similar:

- "s.coronawarn.app"
- "p.coronawarn.app"
- "localhost"

**Comment by thomasaugsten** [comment] 2022-04-21 19:28
The text on this position is incorrect. We will fix this as soon as possible @dsarkar

**Comment by Ein-Tim** [comment] 2022-04-21 20:48
@thomasaugsten I assume you'll also make sure that iOS is showing everything correct, just to be sure?

**Comment by thomasaugsten** [comment] 2022-04-21 21:02
iOS is correct
![image](https://user-images.githubusercontent.com/6367738/164551705-5dfd1c85-dbd1-4bc0-a918-92f16da78960.png)

**Comment by Ein-Tim** [comment] 2022-04-22 12:37
@thomasaugsten Btw is it intended that the countup was removed in version 2.21?

**Comment by thomasaugsten** [comment] 2022-04-22 12:56
This was intended

**Comment by Ein-Tim** [comment] 2022-04-22 13:00
@thomasaugsten Okay thanks, so the screenshots on https://www.coronawarn.app/de/screenshots/#android_rat are just out of date.

**Comment by larswmh** [comment] 2022-04-22 14:26
Thanks for your report @degutant. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12906)

---
Corona-Warn-App Open Source Team

**Comment by pfeifferch** [comment] 2022-04-23 14:15
Was auch fehlt, ist der 24h Timer für die Gültigkeit und die Uhrzeit der Ergebnisübermittlung 

What is also missing is the 24-hour timer for the validity and the time of the result transmission

**Comment by DerVogel2020** [comment] 2022-04-23 14:18
Yes, only the date is shown.

**Comment by Ein-Tim** [comment] 2022-04-23 14:32
@pfeifferch & @DerVogel2020 

@thomasaugsten confirmed just some comments above that this is intended: https://github.com/corona-warn-app/cwa-app-android/issues/5107#issuecomment-1106487326

**Comment by DerVogel2020** [comment] 2022-04-23 14:34
But how can I prove now that the test is not older than 24 hours?

**Comment by Ein-Tim** [comment] 2022-04-23 15:06
@DerVogel2020 

You need a test certificate to prove anything, see the text "Nachweis-Funktion" in the app, it says: 

> Um den hier angezeigten Befund überprüfbar nachzuweisen, ist ein Digitales Testzertifikat
der EU notwendig. Wenn Sie bei der
Registrierung des Tests ein Digitales Testzertifikat angefordert haben und die Teststelle deren Ausstellung unterstützt, können Sie Ihr Digitales Testzertifikat anhand
des oben angegebenen Links anzeigen. Sie finden das Zertifikat außerdem im Bereich „Zertifikate". [...]

**Comment by MikeMcC399** [comment] 2022-04-25 14:16
> Internal Tracking ID: [EXPOSUREAPP-12906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12906)

- Is there a target version for this fix? 
- Are all Rapid Tests results shown incorrectly as PCR Test results?

**Comment by dsarkar** [comment] 2022-04-25 14:51
@MikeMcC399 no target version yet

**Comment by Ein-Tim** [comment] 2022-04-25 14:52
@thomasaugsten said in https://github.com/corona-warn-app/cwa-app-android/issues/5107#issuecomment-1105670406 that you will fix this as soon as possible, this means that the fix should be delivered with the next version, or not?

**Comment by dsarkar** [comment] 2022-04-25 14:59
@MikeMcC399 Not sure if  all Rapid Tests results are shown incorrectly as PCR Test results, but we could reproduce it at least once, and same in EN.

**Comment by Ein-Tim** [comment] 2022-04-28 11:19
@DerVogel2020 & @pfeifferch Please see https://github.com/corona-warn-app/cwa-app-android/pull/5132.

**Comment by dsarkar** [comment] 2022-05-23 17:30
@MikeMcC399 doesn't seem fixed 

![image](https://user-images.githubusercontent.com/1409741/169875100-23817c88-8192-4b8e-bd97-00ae15d43d2e.png)

**Comment by degutant** [comment] 2022-05-23 23:01
For me it works now. Version 2.22.1
![Screenshot_20220524-005847_Corona-Warn](https://user-images.githubusercontent.com/103426152/169918039-51ea266b-eceb-43ae-989c-3a229b7cb763.jpg)

**Comment by dsarkar** [comment] 2022-05-24 07:48
@degutant @MikeMcC399 Thanks for your feedback. Disregard my comment https://github.com/corona-warn-app/cwa-app-android/issues/5107#issuecomment-1134949925, this was tested on the wrong release candidate. All good.

@degutant We would suggest closing this issue, thanks for our participation! Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by degutant** [comment] 2022-05-24 09:03
Thanks everyone for fixing the bug! 👍 This was my very first contribution on Github.
@dsarkar From my side the issue can be closed. Should I do this by myself?

**Comment by dsarkar** [comment] 2022-05-24 09:09
@degutant I will close this issue now. In general, we encourage contributors from the community to close their issues once they confirmed the fix and gave some feedback. So maybe next time ... ;-) Thanks again, Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2022-05-24 09:09 UTC
Labels: bug, mirrored-to-jira, text issue, ready-to-close, rapid-test, Fix 2.22
