### ISSUE TITLE
What can i do?

### ISSUE THREAD

**Issue by drake123463** [corona-warn-app/cwa-app-android#1509] opened 2020-10-31 10:01 UTC
![Screenshot_20201031_105644_de rki coronawarnapp](https://user-images.githubusercontent.com/73739974/97776456-67fb4000-1b68-11eb-83f4-9f5bf2429e12.jpg)

* [ ] None of the other issue templates apply to this issue.

**Comment by MikeMcC399** [comment] 2020-10-31 10:06
@drake123463 
>What can i do?

First of all check that you are running the latest version of CWA, which is 1.5.1.
Then join the conversation in the hot topic https://github.com/corona-warn-app/cwa-app-android/issues/1459

**Comment by drake123463** [comment] 2020-10-31 10:12
I have the Version 1.5.1

**Comment by MikeMcC399** [comment] 2020-10-31 11:08
@drake123463 
> I have the Version 1.5.1

The best would be if you could:

- follow the suggestion in https://github.com/corona-warn-app/cwa-app-android/issues/1459#issuecomment-715897847 to add your exposure log to the issue https://github.com/corona-warn-app/cwa-app-android/issues/1459
- close this issue (https://github.com/corona-warn-app/cwa-app-android/issues/1509), since the problem is being tracked centrally in #1459 

Also if you updated from an version earlier than 1.5.x like 1.3.1 to 1.5.1 in the last 24 hours, then wait until tomorrow because the quota is reset at 00:00 CET (00:00 UTC) and the condition may clear itself if there is no other underlying cause.

**Comment by heinezen** [comment] 2020-11-01 17:13
Hey @drake123463 

Thanks for the feedback. The issue is already tracked in https://github.com/corona-warn-app/cwa-app-android/issues/1459 . Please follow the recommendations in the first post of the issue thread:

> Please update your CWA App to version 1.5+ and wait up to 24 hours before you post a bug report here.
> Bitte aktualisieren Sie Ihre Corona Warn App auf Version 1.5+ und warten Sie 24 Stunden bevor Sie einen Fehlerbericht schreiben.

If this does not work for you, you can write a comment in https://github.com/corona-warn-app/cwa-app-android/issues/1459 by following the instructions from the first post. I will close your issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-11-01 17:13
Duplicate of #1459

**Closed by heinezen** 2020-11-01 17:13 UTC
