### ISSUE TITLE
Show Date and Time of Risk Contacts

### ISSUE THREAD

**Issue by webermike** [corona-warn-app/cwa-app-android#1536] opened 2020-11-05 05:40 UTC
Please show Date and Time of later on announced risk contacts, even if this leads to still having a green status.

As such contacts might occur only at shopping or eating in a restaurant, one can reconstruct with Date and Time where one habe been and if shopping or queuing anywhere is the risk reason.

This would enhance the analyse and discussion and avoiding of behavior in the future much, when it ia shown if the risk contact was at 8:00 in the bus ir at 12:00 in the McDonalds restaurant or at work at 10:00 o'clock at a certain date/day.

Thanks for implementing that local showup fast.

**Comment by MikeMcC399** [comment] 2020-11-05 07:10
Hi @webermike 

There is a similar proposal in [Wishlist item - Show "Day(s) since Encounter" also for "Low-Risk" Encounters](https://github.com/corona-warn-app/cwa-wishlist/issues/178) you might like to look at and possibly up-vote.

**Comment by dsarkar** [comment] 2020-11-05 10:44
Dear @webermike,

Thank you for your contribution. As mentioned by @MikeMcC399, similar suggestions are currently discussed in different discussion threads, see for example:


Regarding how risk counts/encounters should be displayed:
https://github.com/corona-warn-app/cwa-wishlist/issues/113
https://github.com/corona-warn-app/cwa-wishlist/issues/233
https://github.com/corona-warn-app/cwa-documentation/issues/422
https://github.com/corona-warn-app/cwa-wishlist/issues/206
https://github.com/corona-warn-app/cwa-backlog/issues/23
https://github.com/corona-warn-app/cwa-documentation/issues/433
https://github.com/corona-warn-app/cwa-app-android/issues/1263
https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-690279530

I will close this issue as a duplicate of  https://github.com/corona-warn-app/cwa-wishlist/issues/178, and please, continue any further discussion there.
Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-05 10:44
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/178

**Closed by dsarkar** 2020-11-05 10:44 UTC
Labels: duplicate, enhancement
