### ISSUE TITLE
Checking for test result never stops: test removal impossible

### ISSUE THREAD

**Issue by Oi-sin** [corona-warn-app/cwa-app-android#1594] opened 2020-11-13 07:10 UTC
I was tested at the beginning of October. My negative test result was never transmitted by the lab thus the app was never able to get a result. During the first days after the test the app told me, that no result for the test could be obtained. Roughly two weeks later I wanted to remove the test from the app but the 'Datenabruf' section only displays the rotating circle with 'Das Ergebnis wird aktualisiert'. The button 'TEST ANZEIGEN' is disabled thus I am no longer able to access the page where I could remove the test. This behaviour is independent of whether an internet connection is present or not.

At the current state I would not be able to register another test. 

## Expected behaviour

Checking for the test result should stop after a timeout.

## Steps to reproduce the issue

I just need to start the app. No special action required. Restarting the device does not change anything.

## Technical details

- Mobile device: BQ Aquaris X Pro
- Android version: 8.1.0
- CWA version 1.6.0

**Comment by dsarkar** [comment] 2020-11-13 11:06
Dear @Oi-sin,

Thanks for reporting your issue.
I understand that your test is older than 21 days (Could you please confirm ?) and that this causes the problem. This has been reported several times in the past, see here https://github.com/corona-warn-app/cwa-app-android/issues/1084.

**Comment by Oi-sin** [comment] 2020-11-13 11:56
I am sorry for the duplicate issue. I scrolled through the open issues but did not find anything related. I must have missed it.

Yes indeed, my test is older than 21 days now. I believe it was taken on October 8th.  But I am not sure when this error first appeared. It could well be after October 29th but also some days before that.

Thanks for your fast reply.

**Comment by dsarkar** [comment] 2020-11-17 10:57
Dear @Oi-sin,

Thanks again for your input. For the moment I suggest that you follow this issue https://github.com/corona-warn-app/cwa-app-android/issues/1084 and if necessary contribute there. I will close this issue for the moment as duplicate and we focus on the mentioned thread!

 Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-17 10:58
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1084

**Closed by dsarkar** 2020-11-17 10:58 UTC
Labels: bug, duplicate, in review
