### ISSUE TITLE
QR code scanner does not autofocus

### ISSUE THREAD

**Issue by ossilator** [corona-warn-app/cwa-app-android#4710] opened 2022-01-20 13:50 UTC
## Technical details

- Device name: klte (samsung galaxy s5)
- Android version: lineageOS 18.1
- App version: 2.16.2

## Describe the bug

The QR code scanner does not even try to autofocus the camera, so scans are bound to fail.

This is not a camera issue, as "proper" camera apps work just fine. The CovPass app has the same issue, though, so I guess the problem might be in a shared library.

---
Internal Tracking ID: [EXPOSUREAPP-11496](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11496)

**Comment by Ein-Tim** [comment] 2022-01-20 13:54
CovPass(Check) had the same issue and it was fixed in the last update: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/114

**Comment by larswmh** [comment] 2022-01-20 14:07
Thanks for your report @ossilator. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11496](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11496)

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment] 2022-01-20 14:51
I also got a QR Code for a RAT which is not readable by version 2.16.2.
Until 2.15 the QR Codes I got from the testing site were always readable.
@larswmh should I provide the qr code to you?
Android 8.0, Samsung Galaxy A5 2017.

**Comment by dsarkar** [comment] 2022-01-20 16:13
@DerVogel2020 Thanks again for offering the QR code. Not necessary in this case.

**Comment by ossilator** [comment] 2022-01-20 19:29
> CovPass(Check) had the same issue and it was fixed in the last update

not for me ...

**Comment by Ein-Tim** [comment] 2022-01-20 19:34
@ossilator Okay, thanks for the info.

**Comment by thomaszbz** [comment] 2022-01-20 21:13
CWA: I can confirm that the autofocus does not work any more. 
```
Device name: SM-G900F (klte, Samsung Galaxy S5)
OS version: LineageOS 16.0, Android 9
CWA App version: 2.16.2
```
Please note that a previous version (before 2.16.2) worked perfectly fine when I tried with the very same barcode on 12th of January 2022, that's 8 days before I got 2.16.2 installed via automatic updates.

How does it look like? The QR barcode looks just blurry in the smartphone's display. No wonder can't it be scanned.

If I remember right, I had this issue a long time ago in the early days of the CWA - whereas it was fixed back then.

**Comment by Dokujack52** [comment] 2022-01-20 23:39
Wann wird der Firlefanz endlich mal Behoben das das Scannen wieder Funktioniert ? Hat bei der Einführung wunderbar funktioniert, kaum kommen Updates von irgend so einem Praktikanten geht nichts mehr. Und der Autofokusfehler liegt eindeutig in eurer App also bringt das endlich mal in Ordnung ansonsten fliegt der Mist wieder Runter.

**Comment by ossilator** [comment] 2022-01-20 23:53
immer diese konstruktiven kommentare ... ;)

**Comment by Dokujack52** [comment] 2022-01-20 23:54
Immer diese Dummschwätzer, könnt ich genau so sagen ;)

**Comment by Ein-Tim** [comment] 2022-01-21 05:35
@Dokujack52 

CovPass hat/hatte die gleichen Probleme.
Ich bin mir sicher, dass Team arbeitet mit Hochdruck an einer Lösung.

Wenn du noch andere Probleme mit der App hast, melde die bitte in einem neuen Issue. Danke!

**Comment by thomasaugsten** [comment] 2022-01-21 07:53
@ossilator  
Do you use the latest build from lineageOS 18.1 ?
CovPass App is behaving the same?

**Comment by ossilator** [comment] 2022-01-21 10:07
latest but one (jan 9 instead of jan 16).
no discernible difference from CovPass.

**Comment by thomasaugsten** [comment] 2022-01-21 10:30
ok there is already a ticket for lineageos
https://gitlab.com/LineageOS/issues/android/-/issues/4189

I expect this app is also not working with lineageOS
https://play.google.com/store/apps/details?id=net.sourceforge.opencamera

**Comment by ossilator** [comment] 2022-01-21 10:39
> ok there is already a ticket for lineageos https://gitlab.com/LineageOS/issues/android/-/issues/4189

i see.

> I expect this app is also not working with lineageOS https://play.google.com/store/apps/details?id=net.sourceforge.opencamera

but it does work, just like the stock camera app.

**Comment by thomaszbz** [comment] 2022-01-21 10:56
> ok there is already a ticket for lineageos https://gitlab.com/LineageOS/issues/android/-/issues/4189
> 

In this ticket I do not see any analysis done yet. Basically, that means that nobody has looked into this. It does not necessarily mean that a fix is needed in LineageOS itself. It could also mean that multiple apps should do something differently (e.g. they use the same library and the library is broken).

> I expect this app is also not working with lineageOS https://play.google.com/store/apps/details?id=net.sourceforge.opencamera

As said, it worked before updating to 2.16.2. There must have been a regression in recent time. I cannot use important features of CWA any more since updating go 2.16.2.

I think it is not right to break it and then say that it was broken in LineageOS. I am absolutely sure that I did not install a LineageOS update in the meantime (because my LineageOS version is outdated and does not get any minor version updates any more). So if something is broken in LineageOS then it is broken there for a very long time. If CWA managed to work around such a problem in the past (if there was any), then this workaround is broken now.

I would still argue that this is a regression in CWA because nothing has changed in LineageOS (in my case at least).

**Comment by ossilator** [comment] 2022-01-21 11:06
fwiw, i can confirm that this appears to be a recent-ish regression, as i have scanned a cert some weeks ago and i don't remember problems of any kind. CovPass used to work, too, but i tested that much longer ago. of course, i have the confounding factor of semi-regular OS updates.

**Comment by thomasaugsten** [comment] 2022-01-21 13:42
@DerVogel2020 Do you have with your Android 8 device also a auto focus problem?

**Comment by Dokujack52** [comment] 2022-01-21 13:50
Good morning, have you woken up yet? Everyone who posts here probably has that. omg

**Comment by dsarkar** [comment] 2022-01-21 14:15
Dear @Dokujack52,

I dare to say that pretty much everybody here in the community appreciates the respectful cooperation between all of us. The community is contributing here in a very creative and constructive manner, and we cannot stress enough how much we appreciate everybody willing to participate here, either reporting issues, making suggestions, having questions, providing code, reviews, opinions, etc.

You might want to have a look here: https://github.com/corona-warn-app/cwa-app-android/blob/main/CODE_OF_CONDUCT.md

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment] 2022-01-21 14:40
> @DerVogel2020 Do you have with your Android 8 device also a auto focus problem?

@thomasaugsten No, auto focus is not a problem, I could scan all qr codes from https://www.coronawarn.app/de/screenshots/# and a few I found on Google.
May be it's because of a bad printer quality. But before the update to 2.16.2 I could scan the qr codes from that printer. I'll report after the next RAT.

**Comment by Dokujack52** [comment] 2022-01-21 14:43
Es ist sehr wohl der autofocus daran schuld man sieht ja wie die cam versucht das Bild klar zu bekommen deswegen funktioniert es nicht.

**Comment by Ein-Tim** [comment] 2022-01-21 14:49
@Dokujack52 

@DerVogel2020 scheint kein Problem mit dem Autofocus unter Android zu haben, du nutzt wahrscheinlich auch LineageOS, oder? Nur dort gibt es das Problem mit dem Autofocus.
Nutzer:innen, die Android nutzen, sind nicht von dem Problem betroffen (sonst hätten wir hier und auf Twitter auch deutlich mehr Meldungen).

**Comment by Dokujack52** [comment] 2022-01-21 16:02
Ist sehr wohl ein Autofocus Problem weil man ja sieht wie die cam versucht das Bild klar zu bekommen. Und es hat ja vorher funktioniert gahebt warum jetzt auf einmal nicht mehr ?
Jeder kennt doch den Satz Never change a running system.

**Comment by Ein-Tim** [comment] 2022-01-21 16:08
@Dokujack52 

Ja, es ist ein Autofocus Problem, allerdings nur unter LineageOS und nicht unter Android. 
Unter Android hat man mit dem Update den QR-Code-Scanner deutlich verbessert.

**Comment by MikeMcC399** [comment] 2022-01-21 16:45
@Dokujack52 
Which version of LineageOS are you using? Is it 18.1 (the same as @ossilator reported) or is it a different version?
The same question for hardware. Are you also using a Samsung Galaxy S5?

**Comment by MikeMcC399** [comment] 2022-01-21 17:28
I didn't see anybody mention here about the workaround for scanning issues which is described in the FAQ article [Why does the CWA not scan a QR code? Why does the QR code scanner not respond?](https://www.coronawarn.app/en/faq/#scan_tips) at the bottom, where it says:

"Alternatively, you can try the following: Create a photo/screenshot of your QR code and import this file by selecting 'Open File' in the QR code scanner."

My experience of using this workaround is that it works best if you zoom in with the camera and only capture the QR code (not the rest of the text on the certificate). If the lighting conditions are not so good then activating the flash helps with the quality of the QR code image.

On a Samsung Galaxy A5 (2017) CWA automatically found the correct image under RECENTS. That is probably vendor-specific though. If you get the message "NO QR Code Detected" then most likely the image quality was not good enough to decode the QR code.

**Comment by thomasaugsten** [comment] 2022-01-21 18:26
@ossilator @thomaszbz 
Can you please contact me directly to test an custom apk.
thomas.augsten@sap.com

**Comment by Dokujack52** [comment] 2022-01-21 21:51
@MikeMcC399
""Alternatively, you can try the following: Create a photo/screenshot of your QR code and import this file by selecting 'Open File' in the QR code scanner"
Das hat ja mal Funktioniert, Danke für den Tipp.

**Comment by DerVogel2020** [comment] 2022-01-24 10:12
> > @DerVogel2020 Do you have with your Android 8 device also a auto focus problem?
> 
> @thomasaugsten No, auto focus is not a problem, I could scan all qr codes from https://www.coronawarn.app/de/screenshots/# and a few I found on Google.
> May be it's because of a bad printer quality. But before the update to 2.16.2 I could scan the qr codes from that printer. I'll report after the next RAT.

@thomasaugsten 
A new qr code from that testing site worked fine.

**Comment by elschman** [comment] 2022-03-21 23:07
Still an issue without a solution ?

**Comment by ossilator** [comment] 2022-03-22 11:32
yes. i received a test build which fixed the issue, but it wasn't reliable (probably due to a camera driver bug). apparently, the work was shelved since.

for the time being i resorted to the usual workaround of photographing/scanning the QR code and displaying it full-screen on the computer, from where it can be scanned even with broken autofocus.

**Comment by svengabr** [comment] 2022-06-13 13:59
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> Nothing we can do here.
> 
> Please give the recommendation to make a photo with the normal camera and upload the photo in the CWA Scanner through the upload functionality

> Closing this ticket as we cannot resolve it (at least not based on reasonable efforts).

**Closed by svengabr** 2022-06-13 13:59 UTC
Labels: bug, mirrored-to-jira
