### ISSUE TITLE
Error 39508 for 3 days now

### ISSUE THREAD

**Issue by Muske2020** [corona-warn-app/cwa-app-android#1559] opened 2020-11-09 12:14 UTC
I've got the Error 39058 for 3 days now.

Android version: Android 10, UI 2.0
Mobile device: Samsung Galaxy A50
CWA version: 1.5.1

**Comment by MikeMcC399** [comment] 2020-11-09 12:42
Hi @Muske2020 

Would you like to join the conversation in [🔥 Error 39508 after updating to 1.5](https://github.com/corona-warn-app/cwa-app-android/issues/1459) #1459 and post your Exposure check log there?

**Comment by dsarkar** [comment] 2020-11-10 08:15
Dear @Muske2020,

Thank you very much for your contribution, and that you continue to provide more information on this issue at https://github.com/corona-warn-app/cwa-app-android/issues/1459. I will close this issue as a duplicate. Thanks again.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-10 08:16
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1459

**Closed by dsarkar** 2020-11-10 08:16 UTC
