### ISSUE TITLE
App shows "full vaccination protection" status one day early

### ISSUE THREAD

**Issue by ThoWolv** [corona-warn-app/cwa-app-android#3464] opened 2021-06-16 08:37 UTC
When the European Vaccination Certificate is imported into the App before full vaccination protection is achieved ( 14 days after second vaccination), the App counts down to the day of full vaccination protection ("Vollständiger Impfschutz"). 

### Problem:
This countdown ends one day too early. In the CWA my vaccination status is displayed as "Full Vaccination Protection" while the "CovPass Check" App still considers my certificate invalid.
The official "CovPass" App, on the other hand, correctly shows one day left until full protection.

This could cause weird situations in cases were vaccinated people want to use their certificate from within the CWA and get rejected.

### Steps to reproduce:

- Import valid European vaccination certificate into the app before the 14 days wait period is over
- Scan certificate on the first day the CWA shows it as valid
- Receive "Certificate Invalid!" message from the "CovPass Check" App

This is my first issue posted to GitHub, please notify me should this post be missing important aspects of an issue post.

---
Internal Tracking ID: [EXPOSUREAPP-7831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7831) iOS
Internal Tracking ID: [EXPOSUREAPP-7865](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7865) Android

**Comment by MikeMcC399** [comment] 2021-06-16 08:51
@ThoWolv 
Thanks for reporting this issue. It is however already a known issue which affects both Android and iOS apps. You can follow the progress in https://github.com/corona-warn-app/cwa-documentation/issues/638.

**Comment by dsarkar** [comment] 2021-06-16 09:16
Internal Tracking ID: [EXPOSUREAPP-7831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7831) iOS
Internal Tracking ID: [EXPOSUREAPP-7865](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7865) Android

**Comment by MikeMcC399** [comment] 2021-06-16 09:31
@dsarkar 
I suggest to leave this issue open, even if it is a duplicate of corona-warn-app/cwa-documentation#638 so that other Android uses can find it more easily. That may help prevent further duplicate reports like https://github.com/corona-warn-app/cwa-app-android/issues/3448.

**Comment by dsarkar** [comment] 2021-06-16 10:43
FYI PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/2950

**Comment by dsarkar** [comment] 2021-06-16 11:35
FYI PR Android https://github.com/corona-warn-app/cwa-app-android/pull/3467

**Comment by MikeMcC399** [comment] 2021-07-19 15:34
@dsarkar 
It should be possible to close this issue now. It is flagged as fixed in version 2.4 which was released on June 24, 2021 (see https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/).

Issue https://github.com/corona-warn-app/cwa-documentation/issues/638 was already closed on June 27, 2021.

**Comment by heinezen** [comment] 2021-07-21 03:10
@MikeMcC399 True, we'll close.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-07-21 03:10 UTC
Labels: Fix 2.4, bug, duplicate, mirrored-to-jira
