### ISSUE TITLE
Communication Error with Google API

### ISSUE THREAD

**Issue by AHaumer** [corona-warn-app/cwa-app-android#776] opened 2020-06-28 07:25 UTC
Reason: 3
Something went wrong
Communication Error with Google API(10)

Acer T04, Android 6
Running since 8 days, status not updated since Friday
No mobile data connection, only WLan
Happens sometimes, not always.

**Comment by EmTeedee** [comment] 2020-06-28 09:11
Can you check the error message details to see if this is the same as #737 ?

Look for "Cause: com.google.android.gms.common.api.ApiException: 10: Unable to validate key file signature: Pipe is closed
at ..." (or "Ursache: ..." if your device is set to German).
If the details start with that, the bug it's most likely the one being handled in #737 .

**Comment by stefanbschneider** [comment] 2020-06-28 15:34
Jep, same for me: https://github.com/corona-warn-app/cwa-app-android/issues/602#issuecomment-650734091

**Comment by AHaumer** [comment] 2020-06-28 19:27
If you mean the screenshot of the details in #737, no it seems to be different. My details start with:
Ursache:
com.google.android,gns.common.api.ApiException; 39508 at 
andoid.suppor.v4,media.MediaDescriptionCompatApi21$Builder.setResultOrApiException(MediaDescriptionCompatApi21,java:3)
at ...

Now I get "Risiko-Ermittlung nicht möglich. Ihre Risiko-Ermittlung konnte seit mehr als 24 Stunden nicht aktualisiert werden".

Seems that the App tries to update while I have no data connection. At first (for 6 days) I think the update happened while I was connected to WLan. An no, I'm not going to turn on on mobile data (my contract doesn't include mobile data). I don't need mobile data since I'm most of the time either at home or at the university using WLan. When I'm outdoor, I can live without being online. The App should try to update later (when I'm connected to WLan) - or it's useless for me.

**Comment by AHaumer** [comment] 2020-06-28 19:35
Additional info (don't know if it's related):
If I restart the phone, Android it working for some minutes on "1 von 1 Apps wird optimiert". 
Since this wasn't happening before, it is most likely related to the App.
Sorry I don't het an Android update from Acer. Device is not rooted.

**Comment by jakobmoellersap** [comment] 2020-06-29 06:46
Duplicate of #737

**Closed by jakobmoellersap** 2020-06-29 06:46 UTC
Labels: bug
