### ISSUE TITLE
Showing time of risk encounter

### ISSUE THREAD

**Issue by Timo1993** [corona-warn-app/cwa-app-android#1263] opened 2020-09-30 08:47 UTC
It would be really helpful to show the timestamp of the risk encounter (especially for low risk encounters). 

This might help the user to identify its own location during this time. It should not reduce the privacy.

**Comment by MikeMcC399** [comment] 2020-09-30 09:28
Similar to https://github.com/corona-warn-app/cwa-wishlist/issues/178

**Comment by daimpi** [comment] 2020-09-30 14:31
@Timo1993 I'll quote my reply from [here](https://github.com/corona-warn-app/cwa-documentation/issues/433#issuecomment-698978622):
> The exact timestamp of an encounter is not exposed by the Exposure Notification Framework (ENF) for privacy reasons afaik. Therefore CWA cannot show an exact time but only the day when the exposure occurred (see [here](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-678692630) for more details on the response CWA gets from ENF). If you have a rooted android device you can bypass this restriction e.g. with the [corona-warn-companion-android](https://github.com/mh-/corona-warn-companion-android) though.

Regarding the display of the day of the encounter (for green encounters): This is tracked in the [issue](https://github.com/corona-warn-app/cwa-wishlist/issues/178) @MikeMcC399 mentioned above and hopefully we will soon see some movement on this issue 🤞.

**Comment by stephankn** [comment] 2020-10-07 16:32
I am quite certain that the json you can export on non-rooted phones did contain a timestamp. I had a low-risk contact reported once and was able to identify that I was in the beergarden at that time. given open-air setting and large distance between tables I felt more relaxed.

**Comment by daimpi** [comment] 2020-10-07 16:39
> I am quite certain that the json you can export on non-rooted phones did contain a timestamp.

This is correct. But this timestamp only gives you the time when your phone compared diagnosis keys (DKs) it downloaded from the server with the rolling proximity identifiers (RPIs) it recorded from contact with other phones. This doesn't directly tell you anything about when the actual encounter happened. I've written about this in more detail [here](https://github.com/corona-warn-app/cwa-app-android/issues/1217#issuecomment-697631273) and [here](https://github.com/corona-warn-app/cwa-app-android/issues/1302) if you're interested.

**Comment by heinezen** [comment] 2020-10-08 13:58
Hey @Timo1993 ,

As @MikeMcC399 already pointed out, there already is a wishlist entry for this feature https://github.com/corona-warn-app/cwa-wishlist/issues/178 . Please continue the discussion there and give the issue a 👍 so that we can see how popular the feature request is. This helps the devs to prioritize new features. I'll close this issue as a duplicate.

Thanks.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-08 13:58
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/178

**Closed by heinezen** 2020-10-08 13:58 UTC
Labels: feature request
