### ISSUE TITLE
wrong/bad formulation in "Ihr Risikostatus"

### ISSUE THREAD

**Issue by EikeTS** [corona-warn-app/cwa-app-android#1018] opened 2020-08-13 08:54 UTC
My risk status is low, like you see in the screenshot.
But in the lower text is written, that my status is elevated and there are given advises for an elevated status. 

![Screenshot_20200813-104238_Corona-Warn](https://user-images.githubusercontent.com/69624854/90113599-e3133e00-dd51-11ea-8c94-7e9ad8afcf80.jpg)

**Comment by vaubaehn** [comment] 2020-08-13 10:47
Hi @EikeTS , your bug report is a duplicate of #1006 which is a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/405#issue-677662490. The text is corrected with #1004 and correction will be available with v. 1.2.1 soon :) Happy CWA'ing!

**Comment by GPclips** [comment] 2020-08-13 11:40
Hello @EikeTS,

I will close this issue, since it is a duplicate. Please feel free to follow and participate in the following thread: corona-warn-app/cwa-documentation#405 .
@vaubaehn thanks for your support!

Thank you,
LMM

Corona-Warn-App Open Source Team

**Closed by GPclips** 2020-08-13 11:40 UTC
Labels: bug, duplicate
