### ISSUE TITLE
Text correction needed: Test certificate not in the "Certificates" tab...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#5002] opened 2022-03-29 14:04 UTC
## Avoid duplicates
Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
[?] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
[?] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy Note 10
- Android version: Android 12 (One UI 4.0)
- App version: 2.19.2

## Describe the bug

If a (quick) test result is registered in the CWA without "digital test certificate" / "Digital EU Certificate", the "Verification feature" section will still show the text "You can also find the certificate in the „Certificates“ tab."

Please refer:
![Screenshot_20220329-125327_Corona-Warn](https://user-images.githubusercontent.com/21124877/160623473-932e7ebf-e602-48f7-a614-aa3bbb7e727d.jpg)

In the case of a (quick) test result without a 'digital test certificate', this information is incorrect because the certificate is not displayed under "Certificates" tab.

## Steps to reproduce the issue

Register a new rapid test
Open rapid test
Read Proof-Function

## Expected behaviour

The corresponding text "You can also find the certificate in the „Certificates“ tab." should be changed or deleted.

## Possible Fix

To distinguish whether the test certificate is a 'digital test certificate' or not, the flag `isDccSupportedByPoc` can be used.
In this context, if `isDccSupportedByPoc` is missing, it seems to me questionable whether the entire text in the first section under "Verification feature" is at all appropriate. Or if it rather contributes to the confusion.

## Additional context

Cross-references: Test results with / without "Digital Test Certificate"...  [Missing test certificate under "Certificates" tab...](https://github.com/corona-warn-app/cwa-app-android/issues/5000#issuecomment-1081769407)
There are obviously test centers with words like "incl. Certificate" whose certificate is not a "Digital EU Certificate" / not a "Digital Test Certificate".

-----------------

## Additional question
When selecting a test center / test provider, how can I determine in advance that the "certificate" advertised and offered actually corresponds to the "EU Digital Test Certificate"? Keyword: `isDccSupportedByPoc`. Regardless of whether "find a test option" is carried out via CWA, or a provider is searched for / selected via the Internet and local search / selection.

**Comment by mtwalli** [comment] 2022-03-29 14:17
@CV113 , @KathrinLuecke, could we improve the wording here a bit in order not confuse users ?

**Comment by Ein-Tim** [comment] 2022-03-29 14:21
I would consider this as a duplicate of #3783, which should be moved to the documentation repo as it also affects iOS.

**Comment by Ein-Tim** [comment] 2022-03-30 09:58
@Jo-Achim 
If you also think that this is a duplicate, please close this issue.

**Comment by Jo-Achim** [comment] 2022-03-30 11:50
@Ein-Tim,
no, I will not close. I see a similarity, but more in the sense of handling both issues together.

Also, [Missing explanation that certificate cannot be generated on RAT result screen after result](https://github.com/corona-warn-app/cwa-documentation/issues/878#issue-1186075994) (https://github.com/corona-warn-app/cwa-documentation/issues/878) is available is from July 2021. 

And @mtwalli wrote [here](https://github.com/corona-warn-app/cwa-app-android/issues/5000#issuecomment-1081829571) regarding this topic:  
> Possible, I would suggest to close this issue and create a new one for that ?

**Comment by Ein-Tim** [comment] 2022-03-30 12:12
@mtwalli Probably forgot about the old ticket. I suggest to decide what should happen to this issue.
a) leave it open and here
b) leave it open and transfer to the documentation repo
c) close it with reference to https://github.com/corona-warn-app/cwa-documentation/issues/878

cc @svengabr

**Comment by svengabr** [comment] 2022-04-01 07:25
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/878

It's better to keep the board clean, we already have one open in the documentation repository so I will close this one.

**Closed by svengabr** 2022-04-01 07:25 UTC
Labels: bug
