### ISSUE TITLE
App not available in international Play Store

### ISSUE THREAD

**Issue by 0xA1B2** [corona-warn-app/cwa-app-android#581] opened 2020-06-17 08:04 UTC
The app is not available in international Play Store, so Germans expats who visit their home country are excluded to use this app (about 500K worldwide) same as all tourists who come to Germany for a visit. That makes no sense !

**Comment by tkowark** [comment] 2020-06-17 08:06
Duplicate of #478

**Closed by tkowark** 2020-06-17 08:06 UTC
Labels: bug, duplicate
