### ISSUE TITLE
change language in settings

### ISSUE THREAD

**Issue by nikste** [corona-warn-app/cwa-app-android#556] opened 2020-06-16 17:38 UTC
#94 Change language in settings

An active change language option in settings.

## Problem and motivation
My android system language is set to english. I am german. Since i assume most of the development team is german, I'd prefer to change to German.

## Is this something you're interested in working on
Unfortunately i don't have the time :)

**Comment by marcmuschko** [comment] 2020-06-17 08:45
@nikste thanks for pointing this out! 
This is a duplicate of #483 and #536 and is tracked for both apps in the documentation repository.
Therefore I am closing this issue.
Best,
Marc

**Closed by marcmuschko** 2020-06-17 08:45 UTC
