### ISSUE TITLE
App needs latest GPS, despite latest GPS installed

### ISSUE THREAD

**Issue by Leistungskurve3000** [corona-warn-app/cwa-app-android#542] opened 2020-06-16 13:00 UTC
Hi,

I am trying to get the Corona Warn App running on my device. See my bug report below and please feel free to help, if you know a solution to this behaviour. 

## Describe the bug

When about to activate Exposure Logging, a popup appears from Corona-Warn, stating:
Update Google Play services. Corona-Warn won't run unless you update Google Play Services. Clicking on 'Activate Exposure Logging' has no effect.

I am using the latest Stock Android 10 for my device and have the latest Google Play Services (version 20.18.17) installed on my device, which is a Xiaomi Mi A2 Lite. All apps have been downloaded anonymously from the Aurora Store, since I do not own a Google Account. 

I had no problems finding the Corona-Warn application on the store though, so I guess my problem differs from /issues/478

## Expected behaviour

The app should recognize that I have the latest GPS installed and should enable exposure logging.

## Steps to reproduce the issue

Download and install Aurora Store from F-Droid.
Login via the 'Anonymous' option.
Check that you have the latest Google Play Services installed.
Then search for the Corona Warn App, and download the app.
Launch the app and try to register.
When reaching the step where to turn on exposure logging, before clicking on 'Activate Exposure Logging', a popup disappears. Clicking on Activate Exposure Logging has no effect.

## Technical details

Xiaomi Mi A2 Lite
Stock Android 10, Android security patch level May 1st, 2020.
No Google Account
Download apps from Google Play Store via Aurora Store using the 'Anonymous' account

## Possible Fix

Does Corona Warn App require a Google Account?

## Additional context

Thanks for developing this application.

---
Internal Tracking ID: EXPOSUREAPP-1979

**Comment by v1nc** [comment] 2020-06-16 17:30
I can reproduce this error on a device running latest MIUI 11.0.8 stable, with latest Aurora Store version 3.2.8.

**Comment by jnodev** [comment] 2020-06-16 18:41
I can reproduce this error on a LG G6 with latest stock ROM (Android 9 Patch Level 1. Mai 2019, V30b-EUR-XX) and with Google Play Service version 20.18.17. I am also not using a Google Account with my phone and would also be interested in a clarification if this app requires a Google Account to work properly. Thank you.

**Comment by m-samland** [comment] 2020-06-16 20:14
I can reproduce this error on a OnePlus 3 with Android 9 (OxygenOS 9.0.6, latest available for this phone). Google Play Service version 20.18.17. Contrary to the above users, I do have registered a Google Account on the phone and still encounter the same bug.

**Comment by piratenkatzerrr** [comment] 2020-06-17 00:02
I suggest to update to Google Play Services v20.21.17, if you can.

**Comment by mxmxchere** [comment] 2020-06-17 06:46
I have the same issue as well, also Aurorastore and no Googleaccount. The abbreviation "GPS" was very misleading for me in the first place...

**Comment by jakobmoellersap** [comment] 2020-06-17 08:41
Hi @Leistungskurve3000 , thanks so much for your detailed issue! Sadly, our only supported delivery option is via the official Google Play Store. Is there any way for you to confirm that your issue is not related to your installation being based on Aurora store? Our current assumption is that the GMS inside Google Play Services are using your account data and thus result in errors when using an Anonymous Account with 3rd Party Stores.

**Comment by Leistungskurve3000** [comment] 2020-06-17 16:46
Hi @jakobmoellersap , thank you for getting back at us.

In the meantime, I installed the Corona Warn App on my second device. This device is a LG Nexus 4 with Android 8.1.0 running (LineageOS). Again, I do not have a Google Account on this device either. Therefore, I installed it using the Anonymous login via Aurora Store, just like I did on my Xiaomi Mi A2 Lite. But to the opposite of the Xiaomi phone, the Corona Warn App runs just fine on my LG Nexus 4. There is no popup appearing and exposure tracking is immediately activated.
As a result, I conclude that the issue I opened this topic for is not related to the installation based on the Aurora Store.

However, I suspect that the version of Google Play Services plays a role here: On my Nexus 4, the Google Play Services version is up to date with version 20.21.17 (installed from Aurora Store).
As I mentioned earlier, the latest version that is available for my (newer) Xiaomi Mi A2 Lite is version 20.18.17, which seems odd to me, especially because someone else mentioned I shall try to upgrade to 20.21.17 on my Mi A2 Lite ( @piratenkatzerrr ). I am unable to do that, I do not see any updates.
Also: On both devices I see the option for Covid-19 exposure tracking in Settings -> Google... its actually the first entry right there, so I guess 20.18.17 is not outdated after all.

If you need any more information just let me know.

**Comment by Leistungskurve3000** [comment] 2020-06-18 19:15
I have good news: Just now I received an update of Google Play Services to version 20.21.17 through Aurora Store. Now the Corona Warn App works like intended.
For now, I leave this issue open in case this does not resolve the problem for any other user here.

**Comment by heinezen** [comment] 2020-11-22 17:38
Looks like this solved itself after all affected devices were updated. I'm closing this now.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2020-11-22 17:38 UTC
Labels: bug, community, google, in progress, mirrored-to-jira
