### ISSUE TITLE
Increase screen brightness to 100% when opening QR-codes

### ISSUE THREAD

**Issue by rkw95** [corona-warn-app/cwa-app-android#4606] opened 2021-12-22 15:00 UTC
See https://github.com/corona-warn-app/cwa-wishlist/issues/571, as I could not transfer the issue from the wishlist repo to this repo.

---
Internal Tracking ID: [EXPOSUREAPP-8224](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8224)

**Comment by Ein-Tim** [comment] 2021-12-22 15:04
Is a separate issue for this really necessary?

**Comment by rkw95** [comment] 2021-12-22 15:06
I wanted to implement this feature. In order to reference it easier inside this repo, I created this issue.

**Comment by rkw95** [comment] 2021-12-22 15:16
Can someone with the necessary permissions assign me this issue so I can propose a solution?

**Comment by dsarkar** [comment] 2021-12-22 15:41
Hi @rkw95, thanks for participating here. Are you offering code or even a PR for an implementation on Android? Just to make you aware: Usually in this project parity between iOS and Android is maintained, i.e. there might be a delay in releasing this feature until a corresponding feature for iOS has been prepared.


---
Corona-Warn-App Open Source Team

**Comment by rkw95** [comment] 2021-12-22 16:26
I'm very new to Android / Kotlin programming, (I have other coding experience), but I got it working on my personal phone. So I wanted to share my solution. I do not know if my implementation is also working for iOS.

**Comment by dsarkar** [comment] 2021-12-22 17:03
@rkw95 ok, thanks. I suggest to share your code or PR here in this repository, and then the dev team might have a look at it.

**Comment by rkw95** [comment] 2021-12-22 17:22
@dsarkar how can I push to the repo? I have a local git branch named `feature/increase_scanablity_issue_4606` but I don't have the permission to push it.

**Comment by dsarkar** [comment] 2021-12-22 17:34
@rkw95 

Go to 
https://github.com/YOUR_FORK/cwa-app-android/branches

Next to your new feature branch press "New pull request"

Then choose 
base repository: /corona-warn-app/cwa-app-android
base: branch 2.16.x or later

head repository: /YOUR_FORK/cwa-app-android
compare: your feature branch

**Comment by dsarkar** [comment] 2021-12-22 17:38
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by MikeMcC399** [comment] 2021-12-22 18:00
@rkw95 
I can see that you have a fork https://github.com/rkw95/cwa-app-android , however there is no branch `feature/increase_scanablity_issue_4606` in that fork.

If you have a standard setup you would need to execute
`git push origin feature/increase_scanablity_issue_4606`
from the command line.

There is a typo in your branch name. You might want to rename the branch before you push it. 
scanablity => scanability

**Comment by rkw95** [comment] 2021-12-22 18:05
@dsarkar Thanks for your help!

@MikeMcC399 Thanks for pointing out the typo. The branch was still local, I now pushed it and I will create a merge request.

**Comment by MikeMcC399** [comment] 2021-12-22 18:17
@rkw95 
You will need to rebase on 2.16.x
`git rebase release/2.16.x feature/increase_scanability_issue_4606`
then
`git push origin  feature/increase_scanability_issue_4606 --force`
otherwise your pull request will not be right.

**Comment by rkw95** [comment] 2021-12-22 18:35
Ok, I rebased and created a pull request. :)

**Comment by dsarkar** [comment] 2021-12-23 07:22
Good morning @MikeMcC399, Thanks for assisting here!
Good morning @rkw95, Thanks for the PR!

**Comment by MikeMcC399** [comment] 2022-02-06 10:46
@rkw95 

Congratulations on getting your PR accepted! It was rolled out with version 2.16.

I tested it on CWA Android 2.16.2 and I confirmed it still works in 2.17.2.

1. Depending on device, set brightness to 1/4 full and disable autobrightness
2. Scan 2/2 vaccination certificate
3. From Status screen, tap on Certificates
4. Tap on QR code
5. Scroll down to Vaccination Certificate and tap on it
6. Tap on QR code
7. Confirm that full-screen QR code is shown and that the display is bright


Would you like to close this issue now that it is resolved and rolled out?

**Comment by eltos** [comment] 2022-02-13 11:25
Hi everyone,  
while #4624 is really nice, I think this can be improved even further for everyday usage of the app:  

Usually people will just go to the certificate tab and present the QR codes already displayed there when asked for. If the brightness is insufficient, I suspect people will click through steps 4-7 (if they are even aware of this possibility), and instead just increase the brightness from the notification bar (which is faster and much more intuitive).

Therefore I propose to add a toggle action item to the toolbar in the Certificates tab (as in the screenshot below). This will allow to quickly increase the screen brightness with only a single tap if required. This has several advantages:
- Intuitive to the user
- Fast (which is especially important to reduce queuing at entrance controls)
- Not disturbing, since it's not enabled by default

<details><summary>Screenshot</summary>

![20220213_121852](https://user-images.githubusercontent.com/19860638/153750661-00eac141-bb5c-4eb3-b67c-c9e0253ed176.jpg)

</details>

**Comment by MikeMcC399** [comment] 2022-03-16 09:51
@rkw95 
Since the original issue has been resolved, it probably makes sense to close this one.

For clarity, the suggestion from @eltos in https://github.com/corona-warn-app/cwa-app-android/issues/4606#issuecomment-1038033376 would more easily be tracked in a new issue.

**Comment by eltos** [comment] 2022-03-16 18:42
> For clarity, the suggestion from @eltos in [#4606 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/4606#issuecomment-1038033376) would more easily be tracked in a new issue.

I agree, please see #4942 @MikeMcC399

**Comment by MikeMcC399** [comment] 2022-05-04 09:33
@rkw95 / @dsarkar 

Will either of you be closing this issue?

**Closed** 2022-05-04 09:35 UTC
Labels: enhancement, mirrored-to-jira, ready-to-close, Fix 2.16, eu dcc
