### ISSUE TITLE
Inconsistent information

### ISSUE THREAD

**Issue by XTrandi** [corona-warn-app/cwa-app-android#1006] opened 2020-08-12 12:56 UTC
Risk is labeled as "Niedriges Risiko". But the paragraph below says "Die Infektionswahrscheinlichkeit wird daher als erhöht für Sie eingestuft..." which are in my opinion two contradictory statements.

![Screenshot_20200812-123629_Corona-Warn](https://user-images.githubusercontent.com/23012360/90017607-1602f680-dcac-11ea-8839-89e382023c09.jpg)

Is this supposed to happen? And more importantly: What's the actual risk level?

Samsung Galaxy A8
Android-Version 9
App-Version 1.2.0

**Comment by vaubaehn** [comment] 2020-08-12 14:01
Hi @XTrandi , this is a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/405#issue-677662490 and was obviuosly addressed with https://github.com/corona-warn-app/cwa-app-android/pull/1004

**Closed** 2020-08-12 15:35 UTC
