### ISSUE TITLE
What does this error mean? Not updating risk status >24h. Issue with API? Insufficient storage recently resolved, App up to date.

### ISSUE THREAD

**Issue by Watzefack04** [corona-warn-app/cwa-app-android#1030] opened 2020-08-18 01:02 UTC
![Screenshot_20200818-024943](https://user-images.githubusercontent.com/69828219/90458631-3ba25c80-e0ff-11ea-8d9d-e58d72adc31b.png)
![Screenshot_20200818-024931](https://user-images.githubusercontent.com/69828219/90458638-3d6c2000-e0ff-11ea-89fb-2edb5ef1999b.png)

## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

---
Internal Tracking ID: EXPOSUREAPP-2241

**Comment by Watzefack04** [comment] 2020-08-18 01:05
Text of error notification: CAUSE: 3 Something went wrong [.....] then link to deleted FAQ page (404 error).

**Comment by s-martin** [comment] 2020-08-18 06:56
Same error here since yesterday. This is the first error I received, before CWA always worked flawless.

Moto G6 Plus, Android 9, CWA 1.2.1

**Comment by kbobrowski** [comment] 2020-08-18 07:30
This seems to be similar issue to #1021 . @Watzefack04 @s-martin I think it would be quite useful if you shared when exposure checks happened, like I did in original issue, just to confirm the same behavior (Settings -> Google -> COVID-19 exposure notifications -> Exposure checks -> three dots in upper-right corner -> Export exposure checks)

**Comment by not-a-feature** [comment] 2020-08-18 07:49
Same problem here on a Moto G7 Play, Android 10, CWA 1.2.1

Here the exported exposure checks:
`[{"timestamp":"August 12, 2020 02:18","keyCount":2290,"matchesCount":0,"appName":"Corona-Warn","hash":"dCtVfMM0AnZYHNokm\/MpdNohanNgipPHynGvZ4De27E="},{"timestamp":"August 12, 2020 02:18","keyCount":2520,"matchesCount":0,"appName":"Corona-Warn","hash":"8JD364tR2WBkyNBCZ7D03SUYhLqI4vYCdYo3E8WXujY="},{"timestamp":"August 12, 2020 02:18","keyCount":1575,"matchesCount":0,"appName":"Corona-Warn","hash":"Icn\/SxaXPAydSKjbN9coAU9Bgn\/nRVEeAfrmg1ic3\/4="},{"timestamp":"August 12, 2020 02:18","keyCount":1405,"matchesCount":0,"appName":"Corona-Warn","hash":"Vq9k1G0xEzO4zuBDCgt++HygT8Q2mqcZZ0972\/6MMKo="},{"timestamp":"August 12, 2020 02:18","keyCount":1385,"matchesCount":0,"appName":"Corona-Warn","hash":"pzl9NwNk1xYSGCEOme6sAQNolM7lVSxdkr5kTDPToN0="},{"timestamp":"August 12, 2020 02:18","keyCount":1645,"matchesCount":0,"appName":"Corona-Warn","hash":"gzYWx\/BxpliMJ8q1WoF\/X\/+CekMv6VFdn5LMdGgkE3E="},{"timestamp":"August 12, 2020 02:18","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 12, 2020 02:18","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 12, 2020 02:18","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 12, 2020 02:18","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 12, 2020 02:18","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 12, 2020 02:18","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 17, 2020 02:00","keyCount":1645,"matchesCount":0,"appName":"Corona-Warn","hash":"gzYWx\/BxpliMJ8q1WoF\/X\/+CekMv6VFdn5LMdGgkE3E="},{"timestamp":"August 17, 2020 02:00","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 17, 2020 02:00","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 17, 2020 02:00","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 17, 2020 02:00","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 17, 2020 02:00","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 17, 2020 02:00","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 17, 2020 02:00","keyCount":2380,"matchesCount":0,"appName":"Corona-Warn","hash":"JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="},{"timestamp":"August 17, 2020 02:00","keyCount":2285,"matchesCount":0,"appName":"Corona-Warn","hash":"oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="},{"timestamp":"August 17, 2020 02:00","keyCount":3800,"matchesCount":0,"appName":"Corona-Warn","hash":"O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="},{"timestamp":"August 17, 2020 02:00","keyCount":3940,"matchesCount":0,"appName":"Corona-Warn","hash":"mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="},{"timestamp":"August 17, 2020 02:00","keyCount":3020,"matchesCount":0,"appName":"Corona-Warn","hash":"wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="},{"timestamp":"August 17, 2020 02:00","keyCount":2675,"matchesCount":0,"appName":"Corona-Warn","hash":"GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="},{"timestamp":"August 14, 2020 01:59","keyCount":1575,"matchesCount":0,"appName":"Corona-Warn","hash":"Icn\/SxaXPAydSKjbN9coAU9Bgn\/nRVEeAfrmg1ic3\/4="},{"timestamp":"August 14, 2020 01:59","keyCount":1405,"matchesCount":0,"appName":"Corona-Warn","hash":"Vq9k1G0xEzO4zuBDCgt++HygT8Q2mqcZZ0972\/6MMKo="},{"timestamp":"August 14, 2020 01:59","keyCount":1385,"matchesCount":0,"appName":"Corona-Warn","hash":"pzl9NwNk1xYSGCEOme6sAQNolM7lVSxdkr5kTDPToN0="},{"timestamp":"August 14, 2020 01:59","keyCount":1645,"matchesCount":0,"appName":"Corona-Warn","hash":"gzYWx\/BxpliMJ8q1WoF\/X\/+CekMv6VFdn5LMdGgkE3E="},{"timestamp":"August 14, 2020 01:59","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 14, 2020 01:59","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 14, 2020 01:59","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 14, 2020 01:59","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 14, 2020 01:59","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 14, 2020 01:59","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 14, 2020 01:59","keyCount":2380,"matchesCount":0,"appName":"Corona-Warn","hash":"JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="},{"timestamp":"August 14, 2020 01:59","keyCount":2285,"matchesCount":0,"appName":"Corona-Warn","hash":"oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="},{"timestamp":"August 14, 2020 01:59","keyCount":3800,"matchesCount":0,"appName":"Corona-Warn","hash":"O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="},{"timestamp":"August 15, 2020 02:34","keyCount":1405,"matchesCount":0,"appName":"Corona-Warn","hash":"Vq9k1G0xEzO4zuBDCgt++HygT8Q2mqcZZ0972\/6MMKo="},{"timestamp":"August 15, 2020 02:34","keyCount":1385,"matchesCount":0,"appName":"Corona-Warn","hash":"pzl9NwNk1xYSGCEOme6sAQNolM7lVSxdkr5kTDPToN0="},{"timestamp":"August 15, 2020 02:34","keyCount":1645,"matchesCount":0,"appName":"Corona-Warn","hash":"gzYWx\/BxpliMJ8q1WoF\/X\/+CekMv6VFdn5LMdGgkE3E="},{"timestamp":"August 15, 2020 02:34","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 15, 2020 02:34","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 15, 2020 02:34","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 15, 2020 02:34","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 15, 2020 02:34","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 15, 2020 02:34","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 15, 2020 02:34","keyCount":2380,"matchesCount":0,"appName":"Corona-Warn","hash":"JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="},{"timestamp":"August 15, 2020 02:34","keyCount":2285,"matchesCount":0,"appName":"Corona-Warn","hash":"oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="},{"timestamp":"August 15, 2020 02:34","keyCount":3800,"matchesCount":0,"appName":"Corona-Warn","hash":"O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="},{"timestamp":"August 15, 2020 02:34","keyCount":3940,"matchesCount":0,"appName":"Corona-Warn","hash":"mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="},{"timestamp":"August 15, 2020 02:34","keyCount":3020,"matchesCount":0,"appName":"Corona-Warn","hash":"wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="},{"timestamp":"August 18, 2020 02:33","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 18, 2020 02:33","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 18, 2020 02:33","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 18, 2020 02:33","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 18, 2020 02:33","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 18, 2020 02:33","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 18, 2020 02:33","keyCount":2380,"matchesCount":0,"appName":"Corona-Warn","hash":"JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="},{"timestamp":"August 18, 2020 02:33","keyCount":2285,"matchesCount":0,"appName":"Corona-Warn","hash":"oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="},{"timestamp":"August 18, 2020 02:33","keyCount":3800,"matchesCount":0,"appName":"Corona-Warn","hash":"O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="},{"timestamp":"August 18, 2020 02:33","keyCount":3940,"matchesCount":0,"appName":"Corona-Warn","hash":"mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="},{"timestamp":"August 18, 2020 02:33","keyCount":3020,"matchesCount":0,"appName":"Corona-Warn","hash":"wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="},{"timestamp":"August 18, 2020 02:31","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 18, 2020 02:31","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 18, 2020 02:31","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 18, 2020 02:31","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 18, 2020 02:31","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 18, 2020 02:31","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 18, 2020 02:31","keyCount":2380,"matchesCount":0,"appName":"Corona-Warn","hash":"JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="},{"timestamp":"August 18, 2020 02:31","keyCount":2285,"matchesCount":0,"appName":"Corona-Warn","hash":"oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="},{"timestamp":"August 18, 2020 02:31","keyCount":3800,"matchesCount":0,"appName":"Corona-Warn","hash":"O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="},{"timestamp":"August 16, 2020 03:37","keyCount":1385,"matchesCount":0,"appName":"Corona-Warn","hash":"pzl9NwNk1xYSGCEOme6sAQNolM7lVSxdkr5kTDPToN0="},{"timestamp":"August 16, 2020 03:37","keyCount":1645,"matchesCount":0,"appName":"Corona-Warn","hash":"gzYWx\/BxpliMJ8q1WoF\/X\/+CekMv6VFdn5LMdGgkE3E="},{"timestamp":"August 16, 2020 03:37","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 16, 2020 03:37","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 16, 2020 03:37","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 16, 2020 03:37","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 16, 2020 03:37","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 16, 2020 03:37","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 16, 2020 03:37","keyCount":2380,"matchesCount":0,"appName":"Corona-Warn","hash":"JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="},{"timestamp":"August 16, 2020 03:37","keyCount":2285,"matchesCount":0,"appName":"Corona-Warn","hash":"oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="},{"timestamp":"August 16, 2020 03:37","keyCount":3800,"matchesCount":0,"appName":"Corona-Warn","hash":"O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="},{"timestamp":"August 16, 2020 03:37","keyCount":3940,"matchesCount":0,"appName":"Corona-Warn","hash":"mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="},{"timestamp":"August 16, 2020 03:37","keyCount":3020,"matchesCount":0,"appName":"Corona-Warn","hash":"wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="},{"timestamp":"August 16, 2020 03:37","keyCount":2675,"matchesCount":0,"appName":"Corona-Warn","hash":"GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="},{"timestamp":"August 13, 2020 02:48","keyCount":2520,"matchesCount":0,"appName":"Corona-Warn","hash":"8JD364tR2WBkyNBCZ7D03SUYhLqI4vYCdYo3E8WXujY="},{"timestamp":"August 13, 2020 02:48","keyCount":1575,"matchesCount":0,"appName":"Corona-Warn","hash":"Icn\/SxaXPAydSKjbN9coAU9Bgn\/nRVEeAfrmg1ic3\/4="},{"timestamp":"August 13, 2020 02:48","keyCount":1405,"matchesCount":0,"appName":"Corona-Warn","hash":"Vq9k1G0xEzO4zuBDCgt++HygT8Q2mqcZZ0972\/6MMKo="},{"timestamp":"August 13, 2020 02:48","keyCount":1385,"matchesCount":0,"appName":"Corona-Warn","hash":"pzl9NwNk1xYSGCEOme6sAQNolM7lVSxdkr5kTDPToN0="},{"timestamp":"August 13, 2020 02:48","keyCount":1645,"matchesCount":0,"appName":"Corona-Warn","hash":"gzYWx\/BxpliMJ8q1WoF\/X\/+CekMv6VFdn5LMdGgkE3E="},{"timestamp":"August 13, 2020 02:48","keyCount":2813,"matchesCount":0,"appName":"Corona-Warn","hash":"\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="},{"timestamp":"August 13, 2020 02:48","keyCount":2415,"matchesCount":0,"appName":"Corona-Warn","hash":"jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="},{"timestamp":"August 13, 2020 02:48","keyCount":3050,"matchesCount":0,"appName":"Corona-Warn","hash":"00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="},{"timestamp":"August 13, 2020 02:48","keyCount":2210,"matchesCount":0,"appName":"Corona-Warn","hash":"Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="},{"timestamp":"August 13, 2020 02:48","keyCount":1655,"matchesCount":0,"appName":"Corona-Warn","hash":"JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="},{"timestamp":"August 13, 2020 02:48","keyCount":565,"matchesCount":0,"appName":"Corona-Warn","hash":"9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="},{"timestamp":"August 13, 2020 02:48","keyCount":2380,"matchesCount":0,"appName":"Corona-Warn","hash":"JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="},{"timestamp":"August 13, 2020 02:48","keyCount":2285,"matchesCount":0,"appName":"Corona-Warn","hash":"oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="},{"timestamp":"August 13, 2020 02:48","keyCount":3800,"matchesCount":0,"appName":"Corona-Warn","hash":"O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="}]`

Cheers,

**Comment by kbobrowski** [comment] 2020-08-18 08:23
@not-a-feature thanks, I've posted reformatted log and some comment here in the original issue: https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-675335397

**Comment by Watzefack04** [comment] 2020-08-18 10:54
content://com.google.android.gms.fileprovider/nearby_connections_files/all-exposure-checks.json
Last check yesterday (Monday), 2am

**Comment by MikeMcC399** [comment] 2020-08-18 11:20
Hi @Watzefack04 

What version of the Google Exposure Notification System is running on your mobile device?
Settings > Google > COVID-19 exposure notifications, then scroll to bottom of page.

What Android version and which mobile device do you have?

It looks like the Google Play services might have been reset to an early factory installed version.

**Comment by not-a-feature** [comment] 2020-08-19 06:57
Follow-up to previous comment:
https://github.com/corona-warn-app/cwa-app-android/issues/1030#issuecomment-675318432

As mentioned about 24h ago I had the same issue. On todays exposure check everything seems fine. The app says "Aktualisiert Heute 2:04".
Yesterday I opened the app several times and killed the process once.

If needed I'll provide the log,
Cheers

**Comment by GPclips** [comment] 2020-08-19 09:10
Hello @Watzefack04,

thank you for reaching out. Please, as @MikeMcC399 asked you, share the Android version as well as the ENF version with us. I also kindly like to ask you, if you please could share the steps to reproduce the issue. If there are no specific steps, please just describe what you did right before this error did occur, even if it is just that you have opened the app. @not-a-feature and @s-martin , can you also please share your steps to reproduce?

In the meantime, I will get in touch with our development team.

thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by not-a-feature** [comment] 2020-08-19 09:23
Hi @GPclips ,
the steps to reproduce were straight forward,
System: Moto G7 Play, Android 10, CWA: 1.2.1

1) App was installed since day 1 without any errors and was opened almost every day at least once
2) Open the App –> Green panel says: „Aktualisiert: Gestern 02:00“
3) Tap on the green panel –> Error Message pops ups „Cause 3“
4) Close the App
5) Reopen, immediately the error message pops up
6) Killed the app
7) Reopen, immediately the error message pops up
8) After 24h the error seems to be resolved

**Comment by MikeMcC399** [comment] 2020-08-19 10:21
Hi @not-a-feature 

Did you have the same stack trace as @Watzefack04 ? If not, then the root cause is probably different.

The play-services-base@@17.3.0:2 made me suspicious about the Google Play services version installed.

**Comment by not-a-feature** [comment] 2020-08-19 10:30
Due to the magic disappearance of the bug and the blocking of screenshots i can't recall that. Sorry for that.

I have the Google Play Services Version 20.26.14 installed which is the newest version (for my device at least)

**Comment by vaubaehn** [comment] 2020-08-19 11:13
Hi @MikeMcC399 ,

> The play-services-base@@17.3.0:2 made me suspicious about the Google Play services version installed.

they're quite new -> [here](https://developers.google.com/android/guides/releases#june_01_2020)

Hi @not-a-feature , 
if you at last could provide your ENF-version, like discribed -> [here](https://www.coronawarn.app/de/faq/?search=enf#ENF_version) , could be helpful to find out, if maybe the initialization of a new ENF-version could have caused that error (in the latest days, there were at least 2 different new versions rolled out, shortly one after the other).

Hi @GPclips ,
i think Jira ID: EXPOSUREAPP-2241 is duplicate of ID: EXPOSUREAPP-2213.

**Comment by not-a-feature** [comment] 2020-08-19 11:32
Sure: ENF Version: 16203302004

**Comment by MikeMcC399** [comment] 2020-08-19 18:49
Hi @vaubaehn 
> > The play-services-base@@17.3.0:2 made me suspicious about the Google Play services version installed.
> 
> they're quite new -> [Google API release June 1, 2020](https://developers.google.com/android/guides/releases#june_01_2020)

Thank you very much for your correction. My mistake! I was confusing the play-services-base version with the Google Play services version. Not the same thing!

**Comment by MikeMcC399** [comment] 2020-08-19 21:09
We haven't heard back from @Watzefack04 but just by coincidence I think I just had exactly the same error. I left a secondary mobile device at home whilst I was away for 5 days. The device was switched on, not connected to a charger. Also coincidentally my WLAN router wasn't connecting to the internet correctly. When I returned, the battery of the mobile device was flat, so I connected it to a charger and switched it on. I also restarted my WLAN router which cleared the WiFi issues.
The Android mobile device Settings > Google > COVID-19 Exposure Notifications showed that it had tried 13 times at 12:48 and 7 times at 06:57 (total of 20 times) today to do an exposure check.

The first error screen said
CAUSE: 3
Something went wrong.
<string name="errors_google_api_error">"The Corona-Warn-App is running correctly, but we cannot update your current risk status. Exposure logging remains active and is working correctly. For further information, please see our FAQ page: https://www.coronawarn.app/en/faq/(39508)"</string>

The [FAQ page](https://www.coronawarn.app/en/faq/(39508)) explains that it is due to the API being called too often and it should resolve itself in 24 hours.

The detail stack trace in https://github.com/corona-warn-app/cwa-app-android/issues/1030#issue-680613826 shows the ApiException 39508, so this is exactly the case covered by the [FAQs](https://www.coronawarn.app/en/faq/(39508)). I had a stack trace on my device which looked very, very similar.

@not-a-feature 
Your detailed exposure checks you listed in https://github.com/corona-warn-app/cwa-app-android/issues/1030#issuecomment-675318432 show that there were 20 checks on Aug 18, 2020, so it seems that your device also exceeded the quota for number of checks.

(Sorry to all for my false alarm about the version of play-services-base! I was not at my home base for several days and I didn't have access to my usual reference and test resources.)

**Comment by svengabr** [comment] 2020-08-26 14:16
Hello everyone,

thank you all for your feedback so far. Since there are currently several issues with exactly the same problem, I need to close this issue to move the discussion to a central place. 

Please continue the discussion here: https://github.com/corona-warn-app/cwa-app-android/issues/1021

I will link the existing findings in Jira so the information on this ticket wont get lost.

Duplicate of #1021 

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment] 2020-08-26 14:16
Duplicate of #1021

**Closed by svengabr** 2020-08-26 14:16 UTC
Labels: bug, mirrored-to-jira, question
