### ISSUE TITLE
Unable to submit form to warn others with specific "first day of symptoms" selected

### ISSUE THREAD

**Issue by mvnrhd** [corona-warn-app/cwa-app-android#5255] opened 2022-06-02 10:48 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy M30s
- Android version: 11
- App version: 2.22.1
 
## Describe the bug

After selecting the day of first symptom appearance to warn others, I'm unable to submit the form. The button is enabled but nothing happens after hitting the submit button (and no error is shown). Strangely, after closing the app and opening it again, I'm unable to access the "warn others" area anymore because the according button below my positive test is missing. Therefore I'm not able to provide a screenshot, unfortunately. 

## Steps to reproduce the issue
 With a positive test result
1. Go to "warn others" 
2. Proceed to the last page where the first day of symptom appearance can be selected
3. Select a day
4. Click submit ("Fertig") 
5. Nothing happens

## Expected behaviour

Some feedback that the form is submitted. Since I can't access the "warn others" area anymore, I assume that it has already happened now, but I can't be sure. 

---
Internal Tracking ID: [EXPOSUREAPP-13178](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13178)

**Comment by dsarkar** [comment] 2022-06-02 10:55
@mvnrhd Thanks a lot for your report. Internal Tracking ID: [EXPOSUREAPP-13178](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13178)
Any further development on this topic will be published here. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment] 2022-06-08 14:23
It looks like a problem the user cannot access the keys after finishing the symptoms.
Cannot reproduce this at the moment.

We are still collecting feedback through multiple channels since we also got feedback from the Play Store channels.

**Comment by seyfahni** [comment] 2022-06-28 10:56
I have the same issue and maybe have a hint that could help reproduce this issue: I entered that dialog via the notification as opposed to opening the app and selecting the test.

**Comment by retonap** [comment] 2022-07-28 08:18
I have the same issue using Samsung s22ultra, CWA 2.24.2.
If I choose the first day 25.7., then when pushing 'continue' button, nothing happens

I restarted CWA to try again but then I was not able to get into the feedback dialog for the PCR Test.
Unfortunately I cannot make a screenshot now.

**Comment by dsarkar** [comment] 2022-07-28 09:35
@retonap @seyfahni Thanks for reporting. Your information is forwarded to the dev team. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by retonap** [comment] 2022-07-28 10:17
Thanks. So there is at least one advantage for the people out there when a GitHub er is having the coronavirus ;-)

**Comment by mlenkeit** [comment] 2022-07-28 13:20
FYI, we have received an error report of a device where this happened, analysis is on-going

**Comment by mlenkeit** [comment] 2022-08-08 07:15
We expect https://github.com/corona-warn-app/cwa-app-android/pull/5405 to fix this problem. Please note that we have detailed information about this issue only from one occurrence, so there's a bit uncertainty.. The fix will most likely be included in 2.26.

**Comment by mvnrhd** [comment] 2022-09-10 12:59
> @mvnrhd this issue has been fixed in 2.26 , could you please check and close the issue ?

Would like to test it 🙂 but not sure how without a positive test result. 🤔

**Comment by mtwalli** [comment] 2022-09-12 08:26
I will close it for now , please reopen if you face it again

**Closed by mtwalli** 2022-09-12 08:26 UTC
Labels: bug, mirrored-to-jira, Fix 2.26

**Comment by mtwalli** [comment] 2022-09-12 09:26
@MikeMcC399 In this case, author can request to open it again or open a new one. We can't provide Tan or positive tests to verify the fix. From our side issue has been fixed and verified by testers and has been shipped to end user. if end user is not able to verify it for different reasons doesn't mean it is not resolved.
