### ISSUE TITLE
Make this app available to the Google Play store in the USA

### ISSUE THREAD

**Issue by rlundy** [corona-warn-app/cwa-app-android#3942] opened 2021-08-18 14:48 UTC
Hi.  I've read the FAQ.

The FAQ makes clear that the app is only available in limited countries.

Sorry, but I still don't get it.  Would you please speak about the specific reasons that this app isn't available in the US Google Play Store?

I'm an American.  I live in Germany.  But my phone uses the US Play store, and that makes me unable to use this app, despite my geographic location.  I'm fully vaccinated, but now I can't use the standard app to prove it.

Given that you can easily _geographically_ restrict use of the app, what legal issues, exactly, prevent you from releasing it in the US Play store?

**Comment by Ein-Tim** [comment] 2021-08-18 14:52
Related issue: https://github.com/corona-warn-app/cwa-wishlist/issues/41

**Comment by heinezen** [comment] 2021-08-19 20:11
Hey @rlundy ,

The issue is already discussed in https://github.com/corona-warn-app/cwa-wishlist/issues/41 . 


----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-08-19 20:11
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/41

**Closed by heinezen** 2021-08-19 20:11 UTC
Labels: bug
