### ISSUE TITLE
Improve wording for "no exposures"

### ISSUE THREAD

**Issue by nicktar** [corona-warn-app/cwa-app-android#672] opened 2020-06-19 14:40 UTC
## Current Implementation
Currently the text for low risk reads "No exposures up to now", which is misleading and might promote dangerous behaviour. 

## Suggested Enhancement
Replace the text by "No known exposures up to now".

## Expected Benefits
For an exposure to show up in the app there is a couple of additional requirements that don't change the risk of an infection like the infected needs to use the app, has to be tested and has to share the test results. While the numbers will hopefully improve, this gives an estimated probability of an exposure to show up in the app of currently below 10%. Stating "no exposures" might lead to the wrong conclusion of "the app told me I'm not infected" and probably reduced safety measured because of that.

**Comment by tomjschwanke** [comment] 2020-06-19 15:51
I think you should suggest it in #332, as this issue deals with text changes.

**Comment by marcmuschko** [comment] 2020-06-19 16:16
Hello @nicktar,

thank you for bringing this up. As you are not the only one that has suggestions on this and as this is also valid for our corresponding iOS app, please move this discussion to the [documentation repository issue 175](https://github.com/corona-warn-app/cwa-documentation/issues/175) for general suggestions. You can of course also suggest this in #332 (thanks @tomjschwanke =))!

Since this seems to be a duplicate of #640, I am closing this issue.
Best,
Marc

**Closed by marcmuschko** 2020-06-19 16:16 UTC
Labels: enhancement
