### ISSUE TITLE
Wrong font in risk explanation and transnational screen

### ISSUE THREAD

**Issue by Bananeweizen** [corona-warn-app/cwa-app-android#2013] opened 2020-12-30 18:34 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: One Plus One
- Android version: 10
- App version: 1.10.1

## Describe the bug

The app uses the same font everywhere, but in 2 places it uses much more letter spacing, making the text harder to read.

## Steps to reproduce the issue

Open the transnational screen or the risk explanation screen and compare fonts in different areas. If you don't see a difference immediately, then please compare identical words like the highlighted "Ermittlung". In the wide letter-spacing variant, the space between the characters is much wider than the character "lowercase L", while in the normal font the space is roughly as wide as "lowercase L".

Screenshot 1
![Screenshot_20201230-191359_Corona-Warn](https://user-images.githubusercontent.com/406876/103373477-5d601700-4ad5-11eb-965d-4dae881804de.png)

Screenshot 2
![Screenshot_20201230-191330_Corona-Warn](https://user-images.githubusercontent.com/406876/103373355-fb071680-4ad4-11eb-8487-f878dcf7fd53.png)

## Expected behaviour

Same font used everywhere.

---
Internal Tracking ID: [EXPOSUREAPP-4489](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4489)
PR #2304

**Comment by dsarkar** [comment] 2020-12-30 18:51
Hi @Bananeweizen, 

Thanks for reporting.  We will have a look at this.

  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-12-31 08:02
- Reproduced on Samsung Galaxy A21s / Android 10 / CWA 1.10.0
- NOT reproduced on iPhone6s / iOS 14.3 / CWA 1.10.1

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-12-31 08:07
Dear @Bananeweizen,

Thanks again. We have created a ticket for the bug in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4489](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4489)

**Comment by PhilippNowak96** [comment] 2020-12-31 09:26
The "normal" sections use `@style/subtitle` and the "wide letter-spacing" ones use `style/body1`. I would fix that but I guess your designers need to clarify what the intended way was/is first before changing both to `body1` for example.

**Comment by dsarkar** [comment] 2020-12-31 09:33
@PhilippNowak96 message forwarded to devs. Thanks.

**Comment by dsarkar** [comment] 2021-02-10 13:54
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2304

**Comment by MikeMcC399** [comment] 2021-03-07 10:23
@Bananeweizen 
CWA Android 1.13.2 has been released now. Would you like to check if the fonts now look right to you?

**Comment by heinezen** [comment] 2021-03-16 12:59
This was fixed in 1.13.2 which has been released a while ago. Therefore, we are going to close this issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-03-16 12:59 UTC
Labels: Fix 1.13, bug, mirrored-to-jira, ready-to-close
