### ISSUE TITLE
activity duration string formatting

### ISSUE THREAD

**Issue by kremeyer** [corona-warn-app/cwa-app-android#585] opened 2020-06-17 09:07 UTC
## Description

The duration of exposure logging string is not correctly formatted. 
In my case the Risk of Infection panel reads:

No exposures up to now
**1 of days active**
Updated: Today, 9:00 AM

![image](https://user-images.githubusercontent.com/40638974/84880200-84508180-b08c-11ea-8570-cb4d8b25e1c2.png)

## Expected behaviour
I expect a second integer between **of** and **days**, e. g.
**1 of 3 days active**

## Technical details

Oneplus 3T
Android 9
Oxygen OS 9.0.6
Build Number ONEPLUSA3003_28_191104

## Additional context

I am using the english version of the app. The tracking has been active for 28 hours. I disabled bluetooth for roughly one hour during this time.

**Comment by jakobmoellersap** [comment] 2020-06-17 09:22
Duplicate of #569

**Closed by jakobmoellersap** 2020-06-17 09:22 UTC
Labels: bug
