### ISSUE TITLE
Keine Verbindung zum Server 

### ISSUE THREAD

**Issue by NixAlsVerdruss** [corona-warn-app/cwa-app-android#983] opened 2020-08-06 14:19 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Mobile device: Samsung Galaxy S8
- Android version: 9

**Comment by DE-Max-42** [comment] 2020-08-06 18:25
@NixAlsVerdruss 

Hey, but I don't think anyone can help with your "bug".
Can you provide a little more information about the "bug"?

Maybe you can explain how you can reproduce the error.

Did you have a working internet connection, do you use a VPN etc.?

**Comment by NixAlsVerdruss** [comment] 2020-08-06 18:32
I start the app by doubleclicking it.
The immediately the error window pops up.
Obviously the app does not get the appropriate connection to its server.


DE_Max_42 <notifications@github.com> schrieb am Do., 6. Aug. 2020, 20:25:

**Comment by DE-Max-42** [comment] 2020-08-06 19:00
@NixAlsVerdruss 
It may seem a bit stupid of me, but do you have an active internet connection?
(have you turned on wifi / mobile data?)
can you access this web page [svc90.main.px.t-online.de](https://svc90.main.px.t-online.de) and see a white empty page or do you see an error message like this? :
![image](https://user-images.githubusercontent.com/55098805/89570012-d9f01180-d825-11ea-831f-3ac573e8aafe.png)

if you can see a white page, your connection to the Corona-Warn-App servers works, and the problem is something else. But it may be that the problem is not necessarily with the app, but with your internet connection.

**Comment by MikeMcC399** [comment] 2020-08-06 21:05
Normally the Corona Warn App V1.1.1 shows the status
"KEINE INTERNETVERBINDUNG" at the top of the screen if there is no Internet connection available when the app is opened.

I can't find any string "Keine Verbindung zum Server" in
https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/res/values-de/strings.xml
so I don't know where this error message might be coming from.

**Comment by NixAlsVerdruss** [comment] 2020-08-07 05:22
Yes, I am connected to internet all the time. Wifi-connection is working.
Mobile data are working too. At least that's what all those funny little
symbols tell me.
The address you sent me shows a white empty page.
Normally my browsers reach every web page. But I cannot say if there are
some secret barriers.

I got AdGuard to filter advertises, but put the CoronaApp on the whitelist
( exceptionlist, apps which aren't filtered), later even deactivated
AdGuard. Nope. CoronaApp always shows the same error at the beginning  (no
connection to server, reason 2001, I saw ).
I want to keep AdGuard anyway, as it is useful. There are no conflicts with
any other apps up to now.

Best regards, Ingrid




DE_Max_42 <notifications@github.com> schrieb am Do., 6. Aug. 2020, 21:00:

**Comment by gagamail** [comment] 2020-08-07 06:25
> CoronaApp always shows the same error at the beginning (no connection to server, reason 2001, I saw ).

@NixAlsVerdruss It is the same error than this one #968 ?

**Comment by NixAlsVerdruss** [comment] 2020-08-07 07:12
Maybe?

gagamail <notifications@github.com> schrieb am Fr., 7. Aug. 2020, 08:25:

**Comment by NixAlsVerdruss** [comment] 2020-08-07 08:10
I send the screenshots.
Today I tried again.
When trying to activate the warning the error occurs.
No filters, no restrictions, WiFi is online, 4G too.


gagamail <notifications@github.com> schrieb am Fr., 7. Aug. 2020, 08:25:

**Comment by SonaliDK** [comment] 2020-08-07 08:33
Hi @NixAlsVerdruss ,

Thank you for reporting this issue. As mentioned by @gagamail, this error has been addressed via #968 . Our team is working on it. Therefore, I will close this issue as duplicate and you can follow the issue #968 for further updates.

Best regards,
SD
Corona Warn-App Open Source Team

**Closed by SonaliDK** 2020-08-07 08:33 UTC
Labels: bug
