### ISSUE TITLE
No background replication with V1.3.1 on Android 

### ISSUE THREAD

**Issue by tynfr** [corona-warn-app/cwa-app-android#1374] opened 2020-10-09 18:38 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Describe the bug
Error message "Ursache 3" (39508) is coming up each time the replication is manually started.
Automatically even nothing happens. Issue seems to be connected with being mobile, before that staying in a WiFi @ home the app did run ok.

## Expected behaviour

Automatic background replication
## Technical details

- Mobile device: SM-A300FU
- Android version:6.0.1

**Comment by MikeMcC399** [comment] 2020-10-09 19:22
This problem is mentioned in the [FAQs](https://www.coronawarn.app/de/faq/#API39508) and you can follow it in the open issue [CAUSE: 3 Something went wrong. ApiException: 39508](https://github.com/corona-warn-app/cwa-app-android/issues/1021) https://github.com/corona-warn-app/cwa-app-android/issues/1021.

**Comment by vaubaehn** [comment] 2020-10-09 20:13
Hi @tynfr ,
could you please elaborate:
- what is your mobile provider (we had seen issues in the past)
- what is your type of mobile connection: edge? 3g? 4g? Ltr?

**Comment by heinezen** [comment] 2020-10-10 15:51
Hello @tynfr ,

Ursache 3 (59508) is a known issue and should be discussed in https://github.com/corona-warn-app/cwa-app-android/issues/1021 as @MikeMcC399 already pointed out. You can also have a look at the [FAQ entry](https://www.coronawarn.app/de/faq/#API39508) for workarounds and further instructions. If you have more questions about the bug or want to answer @vaubaehn 's questions, please continue to post in #1021, so we can better track the bug there. I'll close this issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-10 15:52
Duplicate of #1021

**Closed by heinezen** 2020-10-10 15:52 UTC
Labels: bug
