### ISSUE TITLE
CWA doesn't update risk status - error 39508 still there after > 24 hours

### ISSUE THREAD

**Issue by pathmapper** [corona-warn-app/cwa-app-android#1065] opened 2020-08-23 05:13 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
**Bug is mentioned but according to the FAQ it should be gone after 24 hours which is not the case.**
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
**I'm not sure.**

## Describe the bug
Since two days CWA doesn't update risk status despite the ENF gets daily updates.  
CWA doesn't update risk status - error 39508 still there after > 24 hours

Here's a screen recording from today Aug 23:
[20200823_064258.zip](https://github.com/corona-warn-app/cwa-app-android/files/5113530/20200823_064258.zip)

## Expected behaviour

CWA updates risk status using the latest ENF data.

## Technical details

Model: Motorola Moto G 3
OS: Android: 6.0.1
CWA: 1.2.1
ENF: 16203302004

---
Internal Tracking ID: EXPOSUREAPP-2339

**Comment by pathmapper** [comment] 2020-08-24 09:24
Update:
Yesterday I've switched the phone off and today, after more than 26 hours, I turned it on again.
Now everything is fine again, the risk status of the CWA has been updated.

For me the issue is solved, please feel free to close this issue (might still be something wrong with the risk status update routine, as the issue described above existed for >24h).

**Comment by daimpi** [comment] 2020-08-24 11:06
You might have experienced the same as this user [here](https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-675638186). They also had their app closed for 24h and the first time the problem didn't disappear. But after doing it for a 2nd time the issue was fixed…

Not really sure why it sometimes only seems to work the 2nd time 🤷. 

Feel free to close the issue 🙂.

**Comment by MikeMcC399** [comment] 2020-08-24 17:46
The Google documentation: [API for Exposure Notifications, Implementation Guide](https://developers.google.com/android/exposure-notifications/implementation-guide) has an interesting section [Best practices for background work](https://developers.google.com/android/exposure-notifications/implementation-guide#create-background-work) including the following note:

> Note: The periodic work execution time is not precise and depends on the constraints applied to the [WorkRequest](https://developer.android.com/reference/androidx/work/WorkRequest) and on the power restrictions of the devices (such as if it is in [Doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby)). Read more at [Power management restrictions](https://developer.android.com/topic/performance/power/power-details).

If the Android device is not connected to a charger then doze mode may cause background tasks to be delayed significantly. When I accidentally left a mobile phone running unattended for several days without being connected to a charger it also ran into the 39508 error - see https://github.com/corona-warn-app/cwa-app-android/issues/1030#issuecomment-676704970

I am guessing that Doze mode may also delay recovery from the 39508 error. It would be interesting to see if connecting to a charger helps recover from 39508. Too late for this test on the device from @pathmapper though, since it has already recovered,

**Comment by GPclips** [comment] 2020-08-25 07:24
Hello @pathmapper,

thank you for reaching out to us!
I just checked your video and took the following screenshot: 
![image](https://user-images.githubusercontent.com/14160706/91143817-636f6280-e6b3-11ea-9c1d-efc76da13893.png).
Besides the error description, which points to https://www.coronawarn.app/de/faq/(39508), we have the error message which says Cause 3/Ursache 3, something went wrong/etwas ist schiefgelaufen.

I will contact our development team to help you as fast as possible.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by NKarolak** [comment] 2020-08-25 18:30
I am facing this issue too. Until recently, my app ran always fine; the data update in the background worked also well.

Chronology:
3 days ago, I opened the app while my internet connection was poor for a moment. The start screenn was frozen, then the error was raised.
Out of curiosity ;-) , I've opened the app earlier than 24 hours later.
After that try, I've waited more than 24 hours before opening again, and it still does not work.
Note also that I shut down my phone every night.

![grafik](https://user-images.githubusercontent.com/34504100/91213191-8597cd80-e711-11ea-935b-8921a5cbe7dd.png)

Settings: everything is on.
![grafik](https://user-images.githubusercontent.com/34504100/91213249-9a746100-e711-11ea-83ec-c5e8933936a5.png)


Details:
![grafik](https://user-images.githubusercontent.com/34504100/91212901-276aea80-e711-11ea-81d4-573dcc40b46f.png)
![grafik](https://user-images.githubusercontent.com/34504100/91212956-36ea3380-e711-11ea-881b-f6f7782d1117.png)

**Comment by marcohabeck** [comment] 2020-08-26 05:51
Same Problem..
BQ Aquaris X Pro Android 8.1.0

**Comment by GPclips** [comment] 2020-08-26 08:00
@NKarolak and @marcohabeck,

thanks for sharing. @NKarolak this looks similar to https://github.com/corona-warn-app/cwa-app-android/issues/1030. Both issues have been addressed at the development team for further investigation.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by pathmapper** [comment] 2020-08-26 08:25
> Note also that I shut down my phone every night.

This is also what I did last night. I turned it on today around 08:00 am and now

`Ursache 3` / `39508`

is back again. CWA shows last update yesterday, 11:56 am.

Anyone has an idea why `Ursache 3` / `39508` appears in this scenario?

I'm curios if the error is gone after 24h, I'll keep you informed.

**Comment by svengabr** [comment] 2020-08-26 14:13
Hello everyone,

thank you all for your feedback so far. Since there are currently several issues with exactly the same problem, I need to close this issue to move the discussion to a central place. 

Please continue the discussion here: https://github.com/corona-warn-app/cwa-app-android/issues/1021

I will link the existing findings in Jira so the information on this ticket wont get lost.

Best regards,
SG

Corona-Warn-App Open Source Team

**Closed by svengabr** 2020-08-26 14:13 UTC
Labels: bug, mirrored-to-jira

**Comment by svengabr** [comment] 2020-08-26 14:15
Duplicate of #1021
