### ISSUE TITLE
404 error page in 'Häufige Fragen' 

### ISSUE THREAD

**Issue by DE-Max-42** [corona-warn-app/cwa-app-android#593] opened 2020-06-17 11:50 UTC
## Describe the bug

A HTTP 404 error occurs when klicking on 'Häufige Fragen'

## Expected behaviour

A functioning page for example https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392

## Steps to reproduce the issue

1. Open the App and click on 'Häufige Fragen'
![image](https://user-images.githubusercontent.com/55098805/84894590-532e7c00-b0a1-11ea-8161-12faedf8ba83.png)

2. Load the Page 

3. See a 404 Error Page

4. Link to https://www.bundesregierung.de/breg-de/themen/coronavirus/corona-warn-app-faq-1759130

## Technical details
App version: 1.0.0
- Samsung Galaxy S8 Plus (Virtual Device)
- Moto G5s Plus
Date/Time  13:35 Mittwoch, 17. Juni 2020 (MESZ) Error Page Screenshot

## Possible Fix

Replace the link https://www.bundesregierung.de/breg-de/themen/coronavirus/corona-warn-app-faq-1759130 with for example https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392

## Additional context

![image](https://user-images.githubusercontent.com/55098805/84892618-304e9880-b09e-11ea-8961-8d8abd79e705.png)
(The 404 Page)

**Comment by corneliusroemer** [comment] 2020-06-17 11:54
Excellent spot. Why is there a number at the end anyways? Is this for versioning?

Shouldn't we be linking to the non-Bundesregierung, that is project website, instead? At least the links need to be non-breaking on Bundesregierung.

**Comment by kolyaopahle** [comment] 2020-06-17 12:03
Hello,
as you can see here https://github.com/corona-warn-app/cwa-app-android/blob/cacf64a4611c37bb062e7ee4d08822f9ba9d2662/Corona-Warn-App/src/main/res/values-de/strings.xml#L188
the link opened by the app does not contain any of these url markings. 
The 404 you are receiving is caused by something on the `bundesregierung.de` website and not by the app.

**Comment by DE-Max-42** [comment] 2020-06-17 12:08
Okay, this is very strange. I just tested the app on a new virtual device and the error no longer occurs.

**Comment by harambasicluka** [comment] 2020-06-17 12:23
As this is resolved I'll close this issue. Thanks for your contributing! :)

**Closed by harambasicluka** 2020-06-17 12:23 UTC
Labels: bug, in review

**Comment by corneliusroemer** [comment] 2020-06-17 16:08
It may be worth for the SAP team to ping the Bundesregierungs-Website team.
Just because an error that sometimes occurs disappears for the person who reports doesn't mean the root cause has been fixed.
Maintainers, your feedback is requested :) @SebastianWolf-SAP @tkowark @jakobmoellersap @harambasicluka

**Comment by kolyaopahle** [comment] 2020-06-17 17:13
This has been passed on to the appropriate people :)

**Comment by corneliusroemer** [comment] 2020-06-17 17:25
Thank you @kolyaopahle!

**Comment by Constantin-Init** [comment] 2020-07-21 15:16
Hi,

I'm one of the developers working on the CMS for www.bundesregierung.de and I looked into this issue.

As noted by @kolyaopahle the app doesn't access this URL directly, but uses a 'prettier' URL that gets redirects to the real URL by our CMS. This was done for two reasons: 1) the content structure and therefore the URL wasn't finalized when we collaborated with RKI/SAP on this, 2) it allows the editorial staff to change the content more easily without having to update the the URL in the app.

The numbers in the final URLs are actually not for load balancing, but are content-IDs, and the URL ending with -1759130 is actually the ID of a placeholder document that was used in the CMS before the App went Live, and hasn't been accessible since June 15th, so I was quiet surprised to see that this URL made it out "into the wild".

Bad news: It seems we used a 301 return code instead of a 302 for the redirect, and somehow the pre-launch URL was accessed and cached somewhere - either by @DE-Max-42's device himself or some proxy/caching infrastructure that he is accessing. Unfortunately neither the App nor the CMS can do anything to clear those cached entries, if they exist. 

Good news: There doesn't seem to be a significant number of calls to the outdated URL. (according to our server logs less than 10 requests in the past 48h, with most of them seeming to come from this very github issue)

We will keep an eye on the access logs to see if there is still a significant amount of requests to the the outdated URL and if so, add a special redirect for this URL to the correct URL. And we will also change our redirect logic to send 302s instead of 301s (or add a cache-control header with a sensible ttl) so that they will no longer be cached.
