### ISSUE TITLE
Same keyCount as yesterday

### ISSUE THREAD

**Issue by kereng5** [corona-warn-app/cwa-app-android#1691] opened 2020-11-23 10:45 UTC
When the exposure check starts very early, it shows the same number of keys as the day before.
There should be a different keyCount every day.
I cannot reproduce the issue, because I cannot start the exposure check at 1 am.

- Mobile device: Motorola 3. Generation
- Android version: 6.0.1
- CWA 1.6.1
- ENF version 18204217000

## Possible Fix
I guess the exposure check starts too early, when the server still has the data of the day before.

## Additional context
[all-exposure-checks_20201123.txt](https://github.com/corona-warn-app/cwa-app-android/files/5582316/all-exposure-checks_20201123.txt)

On Nov. 19 the CWA started at 1 am. The ENF timestamp was 01:03 and the keyCount was 323911, same as on Nov. 18.
Today (Nov. 23) it started at 01:03, ENF says 01:06, and the keyCount is 311179, same as yesterday.
On Nov 22 it started at 01:03 too, but the keyCount was ok.

---
Internal Tracking ID: EXPOSUREAPP-3957

**Comment by dsarkar** [comment] 2020-11-24 10:47
Dear @kereng5 ,

Thanks for your contributions.

We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-3957) in the internal tracking system. The developers will look into this issue now. Any further developments will be notified here in this Github issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment] 2020-11-24 18:09
I also faced the problem, that I felt forced to deactivate Exposure Logging for the night to be sure to download "fresh keys" in the morning by manually enabling Exposure Logging again (which led to find me issue #1598).

The problem is, that Google's ENF WakeUpService fires anytime after 0:00 UTC and triggers CWA to run in the background (and to download the diagnosis keys from server for checking). If WakeUpService fires at 0:03 UTC but the new keys are deployed after that time, then we're just stuck to the yesterday's keys...

For the time being, there would be 4 approaches to circumvent that problem:
1. ENF WakeUpService would need to trigger later. But as this would mean, that Google would need to change ENF, which affects all contact tracing apps relying on ENF globally, there is probably no chance that our devs would be successfull with such a request towards Google.
2. The fresh diagnosis keys would need to be deployed before 0:00 UTC, maybe somewhere between 23:45 and 23:55 UTC to have a security buffer. No idea, if this is possible.
3. CWA would need to check the time before download. If it's between 0:00 UTC and 0:15 UTC, the download and exposure checking should be aborted and delayed until the next start of CWA.
4. CWA would need to check, if there are "fresh" keys on the sever. Either by requesting a hash from server before the download and compare with the last downloaded one, or by downloading the keys and afterwards comparing hashes, if the downloaded file was already downloaded (and subsequently abort checking, if this is the case).

Or are there other ideas on how to solve this issue?
But probably the problem will be solved/is already WIP with planned implementation of checking more frequently throughout the day?

**Comment by d4rken** [comment] 2020-11-25 10:39
> But probably the problem will be solved/is already WIP with planned implementation of checking more frequently throughout the day?

I wouldn't call it solved. Due to checking multiple times per day with 1.7, the symptoms would no longer be an issue, as with hour packages there shouldn't be a "too early" :thinking: . I'll check with the team.

**Comment by vaubaehn** [comment] 2020-11-26 17:19
> I wouldn't call it solved. Due to checking multiple times per day with 1.7, the symptoms would no longer be an issue, as with hour packages there shouldn't be a "too early" thinking . I'll check with the team.

@d4rken thanks for your reply and having a look into it!

**Comment by d4rken** [comment] 2021-01-05 13:42
@kereng5 I could unfortunately not reproduce this on my end. While that does not mean that it was not an issue, the related code was completely rewritten for unrelated reasons (hourly with 1.7, ENFv2 with 1.8).

Can you still observe this issue, if not, would you be okay with closing this?

**Comment by kereng5** [comment] 2021-01-05 13:55
@d4rken
The problem did not occur after Nov.23.
And the app did not start that early again. It started at 01:07 on Dez 22, but the keyCount was ok.
Feel free to close this issue!

**Comment by d4rken** [comment] 2021-01-05 14:07
Thanks for the quick feedback @kereng5 . I'm sorry that we were not able to provide a satisfying conclusion to this issue, but I'm happy that the app is now correctly for you.

**Closed by d4rken** 2021-01-05 14:07 UTC
Labels: bug, mirrored-to-jira
