### ISSUE TITLE
[EN-Google] Different update time in CWA and Google

### ISSUE THREAD

**Issue by sandoxy** [corona-warn-app/cwa-app-android#2119] opened 2021-01-15 20:05 UTC
Last update at: settings->google->covid->check:
today 18:02

Last updaze shown in CWA:
today 10:12

Phone restart did not change anything.

Yesterday the status updated after the fix from google.

My question ist, whether CWA calculates the risk?

Xiaomi Redmi Note 9S
Android 10
CWA 1.10.1
ENF 18204714000

----
Internal Tracking ID: [EXPOSUREAPP-4592](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4592)

**Comment by MikeMcC399** [comment] 2021-01-15 20:36
@sandoxy 
Take a look at the explanation in https://github.com/corona-warn-app/cwa-app-android/issues/2061#issuecomment-757908373

I was seeing the same problem as you a few days ago, but then after I did a factory reset on the device I couldn't reproduce the issue https://github.com/corona-warn-app/cwa-app-android/issues/2061 so I closed it.

It seems there is a broadcast communications problem between the Google Exposure Notification System and the app. I guess if the app is not showing the latest exposure check timestamp that Google is showing, then it means that the app will not have received the information back from Google, so it can't calculate a new risk. Maybe @d4rken can help here again if there is anything which can be checked?

**Comment by heinezen** [comment] 2021-01-17 13:46
Hey @sandoxy ,

As you said, this should have been fixed by the fix rolled out by Google. Please monitor the situation and notify us if the problem persists as of today. We will the reinvestigate the issue.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by sandoxy** [comment] 2021-01-17 13:51
The problem disappeared with the next CWA-datacheck at the same day. The times are the same again. Thank you for your help. Shall I close the topic?

**Comment by dsarkar** [comment] 2021-01-17 14:16
@sandoxy, Thanks for contributing here. We think you can close this issue. Our understanding is that it was related to the EN-Google issue mentioned above. Should you experience any further issues we will appreciate your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-01-17 14:16
@MikeMcC399 Thanks also to you.

**Comment by heinezen** [comment] 2021-01-17 14:29
@sandoxy Thanks for the follow up! Great that it works reliably for you again. I will close the issue for you

----
Corona-Warn-App Open Source Team

**Comment by sandoxy** [comment] 2021-01-18 09:05
Today the isssue appered again.

Last update at settings->google->covid->check:
Today 09:39 a.m.

Last updaze shown in CWA:
Yesterday 10:10 p.m.

**Comment by dsarkar** [comment] 2021-01-19 07:58
@sandoxy Any updates, issue persists?

**Comment by sandoxy** [comment] 2021-01-19 17:13
> @sandoxy Any updates, issue persists?
The issue persists:
Last update at settings->google->covid->check:
Today 16:05 a.m.

Last update shown in CWA:
Today  09:36 a.m.

**Comment by MikeMcC399** [comment] 2021-01-19 18:04
@sandoxy 
> Today 16:05 a.m.

That looks like a typo, since if it shows a.m. the hours cannot be more than 12 in a 12 hour clock (instead of a 24 hour clock).

**Comment by sandoxy** [comment] 2021-01-19 18:09
> @sandoxy
> 
> > Today 16:05 a.m.
> 
> That looks like a typo, since if it shows a.m. the hours cannot be more than 12 in a 12 hour clock (instead of a 24 hour clock).

Sorry, that`s my fault. There is neither a.m. nor p.m. on the display, just the time in 24 hour mode.

**Comment by dsarkar** [comment] 2021-01-19 20:16
@sandoxy Thanks for the feedback. We will forward your information to the developers.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-01-19 20:16
@sandoxy Ideally, could you provide us with screenshots, please?

**Comment by sandoxy** [comment] 2021-01-19 20:34
> @sandoxy Ideally, could you provide us with screenshots, please?

The next CWA-datacheck made the times equal again. I will provide the screenshots as soon as the problem appears again.

**Comment by sandoxy** [comment] 2021-01-19 20:34
> @sandoxy Thanks for the feedback. We will forward your information to the developers.
> 
> Best wishes,
> DS
> 
> Corona-Warn-App Open Source Team

Thank you!

**Comment by dsarkar** [comment] 2021-01-20 11:15
@sandoxy Thanks for the feedback.

**Comment by sandoxy** [comment] 2021-01-28 08:59
> @sandoxy Ideally, could you provide us with screenshots, please?

Here we go

**Comment by sandoxy** [comment] 2021-01-28 09:02
> @sandoxy Ideally, could you provide us with screenshots, please?

Here we go:

![Screenshot_2021-01-28_09-40-53](https://user-images.githubusercontent.com/38521726/106114375-c75cf200-614f-11eb-837a-7e0e8ae143d4.png)
![Screenshot_2021-01-28-09-52-50-039_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/106114376-c7f58880-614f-11eb-8795-3cee6b5c0223.jpg)

**Comment by sandoxy** [comment] 2021-01-28 09:55
I see, the issue is marked as "solved". But it keeps appearing.

**Comment by dsarkar** [comment] 2021-01-28 11:51
@sandoxy thanks for the info. We will forward your observation to the devs.

**Comment by dsarkar** [comment] 2021-01-28 11:53
Your issue seems related to a different problem than the original one reported here. This specific thread dealt mainly with an issue of the ENF from Google, which was fixed by Google themselves.

**Comment by dsarkar** [comment] 2021-01-28 11:57
@sandoxy, if you tap on the green card, does it update the time? Although not nice from the user perspective (a display issue), at least it seems that the risk calculation takes place, since it appears so in the Android/Google EN.

**Comment by MikeMcC399** [comment] 2021-01-28 12:06
@dsarkar 
> Your issue seems related to a different problem than the original one reported here. This specific thread dealt mainly with an issue of the ENF from Google, which was fixed by Google themselves.

I don't think that is correct. The Google issue which affected all users was described in https://github.com/corona-warn-app/cwa-app-android/issues/2081 and there was no update being done at all for about one day.

In this issue a new update is being logged in the Google log and sometimes it is being reported into the CWA app and sometimes it is not being reported. That leads to a newer timestamp in the Google log than in the CWA log.

**Comment by MikeMcC399** [comment] 2021-01-28 12:09
@dsarkar 
> Although not nice from the user perspective (a display issue), at least it seems that the risk calculation takes place, since it appears so in the Android/Google EN.

If the risk calculation has been done by Google's ENS but the timestamp is not shown in CWA then it most likely means that the calculation completion broadcast has not been received by CWA, so it will not have received any new risk data to display if there has been a change in risk status. This is more than a cosmetic issue unfortunately.

**Comment by dsarkar** [comment] 2021-01-28 12:10
@MikeMcC399 @sandoxy ok. In any case I will bring this to the devs. 

@MikeMcC399 We had this frequently reported on Samsung devices. Are you aware of another related thread in this repo? Thanks !

**Comment by dsarkar** [comment] 2021-01-28 12:12
@MikeMcC399 actually your own https://github.com/corona-warn-app/cwa-app-android/issues/2061

**Comment by MikeMcC399** [comment] 2021-01-28 12:21
@dsarkar 
> @MikeMcC399 actually your own #2061 but also related to EN-Google 

😄 Yes, I mentioned this one earlier on in the thread! We never found the root cause because I did a factory reset and then it didn't happen again.

In the upcoming release 1.11 there is a new function "Error Report" which might help to diagnose this issue better.

**Comment by dsarkar** [comment] 2021-01-28 12:21
Related https://github.com/corona-warn-app/cwa-app-android/issues/1516

**Comment by dsarkar** [comment] 2021-01-28 12:31
@sandoxy, 

- if you tap on the green card, does it update the time? Or can you somehow trigger an update? Opening (swipe away) and closing CWA?
- Does this issue occur often (every day/week/ once per month)?

**Comment by sandoxy** [comment] 2021-01-28 13:54
> @sandoxy,
> 
>     * if you tap on the green card, does it update the time? Or can you somehow trigger an update? Opening (swipe away) and closing CWA?

I tried every mentioned method and did also a system restart. Nothing solved the problem.

>     * Does this issue occur often (every day/week/ once per month)?

I did not recognize any regularity. From the start of the thread it happened apprx. 4 times. Maybe it happenes, when wifi was turned of and then was turned on again e.g. when a returned home or after the night. But it happens not every time when wifi was off. But this idea is new. I cannon tell it for sure.

**Comment by sandoxy** [comment] 2021-02-03 23:16
It happened again.

![Screenshot_2021-02-04_00-11-50_1](https://user-images.githubusercontent.com/38521726/106821809-2ce43d80-667e-11eb-8d8c-72cf95774b0d.png)
![Screenshot_2021-02-04-00-12-16-319_de rki coronawarnapp_1](https://user-images.githubusercontent.com/38521726/106821810-2d7cd400-667e-11eb-9bbe-67eed7884984.jpg)

**Comment by MikeMcC399** [comment] 2021-02-10 10:10
@dsarkar 
Perhaps the label Fix 1.10 should be removed too if the issue is still occurring?

**Comment by sandoxy** [comment] 2021-02-15 09:52
It happens sometimes, after wifi was off and was turned on again.
![Screenshot_2021-02-15_10-39-55](https://user-images.githubusercontent.com/38521726/107930778-b7c91000-6f7b-11eb-97c1-ddd32589b806.png)
![Screenshot_2021-02-15-10-45-06-984_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/107930780-b861a680-6f7b-11eb-9981-c4c2e3263b09.jpg)

**Comment by sandoxy** [comment] 2021-02-15 10:00
And the energysaving is turned off:
![Screenshot_2021-02-15-10-54-09-467_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/107931667-e398c580-6f7c-11eb-9c28-23634f6d9c92.jpg)
![Screenshot_2021-02-15_10-54-45](https://user-images.githubusercontent.com/38521726/107931669-e4315c00-6f7c-11eb-9013-21d82c86da54.png)
![Screenshot_2021-02-15_10-55-22](https://user-images.githubusercontent.com/38521726/107931672-e4c9f280-6f7c-11eb-9ecd-030083da166c.png)

**Comment by MikeMcC399** [comment] 2021-02-15 10:01
@sandoxy 

In your screenshot it shows "STANDORTDIENSTE DEAKTIVIERT".

Are you aware that if you don't have "STANDORTDIENSTE" activated, then Bluetooth Low Energy is deactivated and it cannot exchange signals with other mobile devices that are close by? 

If you tap on the status line "STANDORTDIENSTE DEAKTIVIERT" the next screen will show "Risiko-Ermittlung
Gestoppt" and if you scroll down it says:

"**Standort-Verwendung erlauben**"
with additional explanation.

**Comment by sandoxy** [comment] 2021-02-15 10:07
@MikeMcC399 

Thank you for the information. But I always turn bluetooth and gps on, when I leave home and turn it back off, when I come back. This way it should work, doesn`t it?

**Comment by MikeMcC399** [comment] 2021-02-15 10:36
@sandoxy 
> ... I always turn bluetooth and gps on, when I leave home and turn it back off, when I come back. This way it should work, doesn`t it?

If you only disable Bluetooth, then CWA says the status is "Eingeschränkt"
If you only disable location, CWA says the status is "Gestoppt"
If both Bluetooth and location are deactivated, the CWA status is also "Gestoppt"
If both Bluetooth and location are activated, the status is "Aktiv"

I didn't do any test to find out what happens with the exposure log in each of the cases. I expect that "Gestoppt" means completely stopped though.

**Comment by sandoxy** [comment] 2021-02-15 10:49
@MikeMcC399 

Bluetooth and GPS off:
![Screenshot_2021-02-15-11-38-34-830_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/107936410-eeeeef80-6f82-11eb-9ff8-1bd7916b59cd.jpg)

Bluetooth on and GPS off:
![Screenshot_2021-02-15-11-39-02-386_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/107936486-0332ec80-6f83-11eb-942f-0275e2b85045.jpg)

Bluetooth off and GPS on:
![Screenshot_2021-02-15-11-39-20-085_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/107936541-12199f00-6f83-11eb-94d1-0ab323215bb7.jpg)

Bluetooth and GPS on:
![Screenshot_2021-02-15-11-39-29-189_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/107936604-2198e800-6f83-11eb-9b8f-589f861ecd77.jpg)

Could those options cause my issue or is this addition information for me?

**Comment by MikeMcC399** [comment] 2021-02-15 11:01
@sandoxy 
> Could those options cause my issue or is this addition information for me?

I don't think that the options are causing your issue. I will set up a test phone with a clean install of CWA 1.12.0, then disable Bluetooth and location (with WLAN on and connected to a charger) and I will see what happens the next 24 hours.

I think in any case that the timestamp in the app should be aligned to the timestamp in the Google exposure checks log.

I will let you know what I find out.

**Comment by sandoxy** [comment] 2021-02-15 12:32
@MikeMcC399 

Thank you for testing!

**Comment by dsarkar** [comment] 2021-02-15 13:50
@MikeMcC399 I just remembers you comments https://github.com/corona-warn-app/cwa-app-android/issues/2061#issuecomment-758518015, https://github.com/corona-warn-app/cwa-app-android/issues/2061#issuecomment-758862276.

Do you think there might be a context? Leaving aside of course, that it is usually not an option for the user to factory reset.

**Comment by MikeMcC399** [comment] 2021-02-15 14:05
@dsarkar 
> Leaving aside of course, that it is usually not an option for the user to factory reset.

I only did a factory reset because it was a test device and I wanted to make sure I had a clean base to test on. For a regular user this would be a last resort, because all stored keys from the last 14 days are lost (in addition to all the effort of reinstalling and reconfiguring all other apps). If a device is doing a lot of unexplained things then factory reset may be good. I wouldn't recommend it here in general though.

**Comment by dsarkar** [comment] 2021-02-15 14:07
Yes, I agree.

**Comment by MikeMcC399** [comment] 2021-02-15 16:14
@sandoxy

I got a surprising result and I think that Bluetooth / location are not influencing your problem.

WLAN is on, Bluetooth is off, location is off, device is connected to a charger
CWA Android 1.12.0, ENS 18210214000, Android 8

Google > COVID-19-Benachrichtigungen says
Inaktiv/Tippen, um das Problem zu beheben

on the next page

**Bluetooth und Standortermittlung müssen aktiviert sein**
Die Funktion ist inaktiv, bis die Einstellungen aktiviert werden

Now tap the three-dot icon (top right), select "Überprüfung auf mögliche Begegnungen" and in the log history it is showing an exposure check 4 hours after I disabled Bluetooth and location. The timestamp on the check in the Google log is 15:52 and in the CWA app it is 15:53 (so they are almost the same).

So that says to me that exposure checking has continued, even though the app says "Risiko-Ermittlung Gestoppt". It also shows that it is possible to get the same timestamp in the app as in the Google logs even if Bluetooth and location are disabled.

**Comment by sandoxy** [comment] 2021-02-15 18:59
@MikeMcC399 

Ok, my bluetooth and gps is always off at home and the cwa and google timestamps are the same. But ones in a wile it fails, I think after wifi was off for some time.

**Comment by MikeMcC399** [comment] 2021-02-15 19:10
@sandoxy 
> Ok, my bluetooth and gps is always off at home and the cwa and google timestamps are the same. But ones in a wile it fails, I think after wifi was off for some time.

If WiFi is off then CWA tries to use mobile data every 24 hours. With WiFi available it tries about every 4 hours or more.

How long has WiFi been switched off when it fails? Do you have a mobile data connection available on your device? If yes, is it normally a good connection in your location or is it slow / unreliable?

**Comment by sandoxy** [comment] 2021-02-15 19:25
@MikeMcC399 
I have a strong mobile connection, which is always on, when wifi is off. I only turn every internet-connection off  over night. And the issue came up two or three times after I tirned wifi on after a night. But two times the issue came up, when I returned home and connected to wifi. It seem like google gets the keys from server very fast and cwa tries and tries to get them. Than it stops trying and shows an old timestamp.

**Comment by ndegendogo** [comment] 2021-02-15 22:55
@sandoxy did you always see Google ENS log time **later** than cwa, or is it sometimes the other way round?

@MikeMcC399 do we know if the timestamp in Google ENS log is from **start** of their calculation or at the **end**?
Could it be that after this timestamp an error condition or timeout occurred and prevented cwa to finish its risk calculation successfully?

*Some kind if error log would be helpful in such cases ...*

**Comment by MikeMcC399** [comment] 2021-02-16 09:54
@sandoxy 
Thank you for filling in a bit more of the details about when you are getting the problem!

> It seem like google gets the keys from server very fast and cwa tries and tries to get them. Than it stops trying and shows an old timestamp.

Google doesn't get the keys directly from the server. It is the task of the app to do that and then the app passes the keys to Google's Exposure Notifications System. The diagram in the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) document should help to visualize.

There is a detailed explanation from @d4rken in https://github.com/corona-warn-app/cwa-app-android/issues/2061#issuecomment-757908373 about how the timestamps are linked (which should help answer @ndegendogo's question as well)

> Some kind if error log would be helpful in such cases ...

I completely agree as much of this troubleshooting is like wandering around in the dark! Perhaps @d4rken could weigh in here if there is anything additional which could be observed in order to get to the bottom of the issue?

I also added https://github.com/corona-warn-app/cwa-app-android/issues/2301#issuecomment-779711455 to the issue #2301 regarding the different Exposure Logging status for Bluetooth and location, for completeness, although I don't think it will help solving the issue here.

**Comment by sandoxy** [comment] 2021-02-16 10:06
> @sandoxy did you always see Google ENS log time **later** than cwa, or is it sometimes the other way round?
> 
The timestamp-difference is alway one way.

**Comment by ndegendogo** [comment] 2021-02-16 11:22
> detailed explanation from @d4rken in #2061 (comment) about how the timestamps are linked

@MikeMcC399 thanks for the link with the explaination, this is indeed helpful.

If I understand correctly, a successful risk assessment will always include a call to ENS, yes? So any time differences can be caused only by:
- a delay after starting the risk procedure (e.g. during download the keys from the server), but still finished successfully, **or**
- any unsuccessfull risk procedure started meanwhile, that triggered ENS logging, but then aborted for whatever reason. 

*Right?*

> The timestamp-difference is alway one way.

This makes then perfectly sense.

**Comment by MikeMcC399** [comment] 2021-02-16 12:18
@ndegendogo 
Small times differences of one or two minutes are not worrying and are covered in the long-running open issue https://github.com/corona-warn-app/cwa-app-android/issues/948.

The question is if ENS is supposed to log an unsuccessful attempt to check exposure. If it does log unsuccessful as well as successful attempts, then the focus needs to shift onto why an ENS attempt is failing. I can't see us progressing here without the help of the Open Source Team, possibly with support from Google.

**Comment by dsarkar** [comment] 2021-02-16 13:32
@ndegendogo @sandoxy @MikeMcC399 

I will create a separate internal ticket for this specific case. The original ticket handled the EN-Google issue some weeks ago.

**Comment by sandoxy** [comment] 2021-02-22 09:23
Today CWA keeped checking for about 20 minutes and that it showed an older timestamp again. This is the first time after my last report.

![Screenshot_2021-02-22-10-17-25-702_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/108688143-df7a2400-74f7-11eb-9881-77fba37644cd.jpg)
![Screenshot_2021-02-22_10-04-05](https://user-images.githubusercontent.com/38521726/108688148-e012ba80-74f7-11eb-989e-e5d0398feeb9.png)

**Comment by MikeMcC399** [comment] 2021-02-22 11:31
@sandoxy 
Could you please report if your version numbers are the same as below? 
Three-dot icon > App-Informationen

![App Informationen DE versions](https://user-images.githubusercontent.com/66998419/108702583-c1b5ba80-7509-11eb-909a-b118bc59663b.jpg)

**Comment by sandoxy** [comment] 2021-02-22 11:35
@MikeMcC399 

CWA: 1.12.0
ENF:   18210214000

**Comment by sandoxy** [comment] 2021-03-05 11:21
No change so far:

![Screenshot_2021-03-01_10-58-57](https://user-images.githubusercontent.com/38521726/110108971-2516d680-7dad-11eb-8825-48b2c17b73b0.png)
![Screenshot_2021-03-01-12-02-22-974_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/110108974-26480380-7dad-11eb-9acb-4429b0442844.jpg)

![Screenshot_2021-03-05_11-31-13](https://user-images.githubusercontent.com/38521726/110109010-31029880-7dad-11eb-8543-d4cfdc868e13.png)
![Screenshot_2021-03-05-11-47-23-740_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/110109014-319b2f00-7dad-11eb-9ec1-b4dc8a1069f5.jpg)

**Comment by MikeMcC399** [comment] 2021-03-05 11:56
@sandoxy 
>No change so far

Were you expecting it to change? Have you for instance already been able to update to the new 1.13.x version?
https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

[Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp) isn't offering me 1.13.x yet, so I haven't been able to try it out myself so far.

**Comment by sandoxy** [comment] 2021-03-12 09:31
Sorry for the delayed answer. I have updated to 1.14.3 and today the error appeares again. I just hoped, that the bug was already fixed with one the updates.

**Comment by sandoxy** [comment] 2021-03-18 09:58
Today the the difference ist two unit
![Screenshot_2021-03-18-10-51-59-141_de rki coronawarnapp](https://user-images.githubusercontent.com/38521726/111607692-c7d14b00-87d8-11eb-9c44-cec64b7b9cd5.jpg)
![Screenshot_2021-03-18_10-52-51](https://user-images.githubusercontent.com/38521726/111607696-c869e180-87d8-11eb-9b97-94455ac223c1.png)

**Comment by dsarkar** [comment] 2021-03-18 10:36
Hi @sandoxy thanks for the feedback. We will bring this again to the devs.

**Comment by sandoxy** [comment] 2021-03-18 11:33
@dsarkar Thank you! I hope they will find a solution.

**Comment by vaubaehn** [comment] 2021-03-18 12:42
This is really kind of mysterious. Either the intent from ENF to CWA is blocked for some reason (seems to be specific for this phone model), or CWA is being woken up only partially, or too slow to handle the intent...

@sandoxy : So, today you opened CWA to find the difference again. Do you remember the last time before today you opened CWA? Was it yesterday? Or more than 24 hours? Exact duration in hours/days could be helpful to exclude any issues with OS resource management. Also, how would you compare your phone's responsiveness (speed it opens apps usually) to other phones? Fast, or much more slow?

**Comment by sandoxy** [comment] 2021-03-18 13:05
> @sandoxy : So, today you opened CWA to find the difference again. Do you remember the last time before today you opened CWA? Was it yesterday? Or more than 24 hours?

- I opened the app yesterday around 11 p.m. the last time. I usually open the app around 5 times a day.

> Also, how would you compare your phone's responsiveness (speed it opens apps usually) to other phones? Fast, or much more slow?

- I would say, my phone is average fast. It opens apps withing 1 sec or faster. It is quit new.

As I told it usually happens, when I turn on wifi at the morning. I tried already folliwing methods:
1. Starting CWA immidiatelly after turning on wifi.
2. Waiting a wile after turnng on wifi and then starting CWA.
In both cases the problem occured and did not iccure.

**Comment by vaubaehn** [comment] 2021-03-18 13:37
@sandoxy thanks for your responses, I assume that will help the devs to exclude some of the possible causes (again).
Anyway, I'm quite confused, how wifi state could cause your problem: in either case (on or off) CWA should be 'informed' by the ENF that TEK matching was finished and results are available. As soon as CWA receives that information (intent), your risk status (including timestamp) should be displayed correctly... Mysterious, mysterious... 👻 👽

**Comment by vaubaehn** [comment] 2021-03-18 13:48
One last time from me to @sandoxy : Summing up everything again, it seems for me that your OS is not reliably managing intents. Do you have slightly different problems with other apps, e.g. being notified late of incoming chat massages, emails and alike?

From CWA 1.15 on, you will be easily able to create a debug log and send it to the devs directly. Maybe this can help to find or at least narrow the focus down to the root cause.

**Comment by sandoxy** [comment] 2021-03-18 21:35
> One last time from me to @sandoxy : Summing up everything again, it seems for me that your OS is not reliably managing intents. Do you have slightly different problems with other apps, e.g. being notified late of incoming chat massages, emails and alike?
- Actually all notifications from other apps work perfectly well.
> Let's hope that a debug log feature will soon be available. You then will be able to create a debug log easily and send it to the devs directly. Maybe this will help then to find or at least narrow the focus down to the root cause.
- Great! Maybe this will help.

**Comment by sandoxy** [comment] 2021-04-03 08:39
> > Let's hope that a debug log feature will soon be available. You then will be able to create a debug log easily and send it to the devs directly. Maybe this will help then to find or at least narrow the focus down to the root cause.

Is this feature already planned?

**Comment by vaubaehn** [comment] 2021-04-04 20:19
@sandoxy 
Actually, the feature is already implemented, but not switched on yet. Even though the devs invested incredible effort in data privacy (there is a special backend where the log data is going to be uploaded with strict access control), obviously the legal department/stakeholders might be still concerned of data protection, as the log data mau be considered as health data. That is the only plausible conclusion I can draw from the current state.

Dear stakeholders, as a person that is very concerned about data privacy: the log data is safe. Please trust the community and the devs. Please allow to turn it on.

**Comment by dsarkar** [comment] 2021-04-06 12:41
@sandoxy @vaubaehn The debug log upload feature is to come (most probably), but not in version 2.0. This feature will hopefully also help to understand the issue reported here.

**Comment by sandoxy** [comment] 2021-04-18 14:19
Today the problem occured without wifi being turned off and on again. The problem came up with the second checkup today.

CWA shows 09:03 a.m.
Google shows 09:02 a.m. and 03:44 p.m.

**Comment by vaubaehn** [comment] 2021-04-18 15:57
Hi @sandoxy ,
I'd like to verify something, could you do me a favor, and copy the hashes of the last 4 matched diagnosis keys packages, please?
You'll find them in the 'Überprüfungen auf mögliche Begegnungen' screen inside the ENF, when you tip onto the logged times. Thanks very much in advance!

**Comment by sandoxy** [comment] 2021-04-18 16:11
@vaubaehn 
Of course:

18.04. 15:44
FZx9g1s1OZg/lHZP3szb898HsUfT28AlTEqUnBbEO1k=

18.04. 09:22
1kNzrZZgWodidMpi246hk72+ebodzpomDbXF3v/d6Rw=

17.04. 20:40
VzQV11VBofK5nC2W3Hgo/RMP2E8EUwnzHwvHOT8tyh4=

17.04. 15:38
AbDr3gZwfMCcmau5/nvxVDQKZO1ZMHTko6CBL4LaClY=

**Comment by vaubaehn** [comment] 2021-04-18 16:49
@sandoxy 
Thank you, I could exclude one problem for you that I'm currently experiencing, and that could have been related. Have a nice rest of the weekend.

**Comment by sandoxy** [comment] 2022-05-29 21:37
The problem did not occure for a very long time. I thing it was solved with one of the updates and I would close this issue.

**Closed** 2022-05-29 21:37 UTC
Labels: bug, mirrored-to-jira, google

**Comment by dsarkar** [comment] 2022-05-30 08:07
Hi @sandoxy, thanks for your feedback! Best wishes, DS

---
Corona-Warn-App Open Source Team
