### ISSUE TITLE
Risiko Ermittlung nicht möglich "Ursache 3"

### ISSUE THREAD

**Issue by falkorichter** [corona-warn-app/cwa-app-android#1304] opened 2020-10-04 22:51 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

Risc assessment stopped working 

## Expected behaviour

Risc assessment should work. 

## Steps to reproduce the issue

1. Open app
2. Turn risc assessment off and on again 

## Technical details

- Mobile device: pixel 4
- Android version: android 11
```
com.google. android.gms.common.ap i.ApiException: 10: Unable to validate key file signature: no public key found for package de.rki. coronawarnapp at
android.support. v4.media.Media Descr iptionCompatApi21$Builder.setResult OrApiException (Media DescriptionCom patApi21.java:3)
at
com.google. android.gms. internal. near by.zzaf.onResult(com.google. android .gms:play-services-nearby@@18.0.3 -eap:5)
at
com.google. android.gms.common.api .internal. IStatusCallback$Stub .zaa(com.google. android.gms:play -services-base@@17.3.0:2)
at
com.google. android.gms.internal.bas e.zaa.onTransact(com.google.android .gms:play-services-base@@17.3.0:3) at
android.os.Binder. execTransactinterna I(Binder.java:11 59)
at
android.os.Binder. exec Transact(Binde r iava:1123)
```
![Screenshot_20201004-195640](https://user-images.githubusercontent.com/50506/95028931-80308a00-06a4-11eb-9fa3-bc9220b3d25e.png)
![Screenshot_20201004-195626](https://user-images.githubusercontent.com/50506/95028936-86bf0180-06a4-11eb-8714-69b9157da071.png)
![Screenshot_20201004-195336](https://user-images.githubusercontent.com/50506/95028943-92aac380-06a4-11eb-84e8-3d0d41e4b854.png)

## Additional context

It continued to work this evening

**Comment by MikeMcC399** [comment] 2020-10-05 11:36
Hi @falkorichter !

Your issue has been reported previously
> com.google.android.gms.common.api.ApiException: 10: Unable to validate key file signature: no public key found for package de.rki. coronawarnapp ...

in https://github.com/corona-warn-app/cwa-app-android/issues/1085 and https://github.com/corona-warn-app/cwa-app-android/issues/817 . Both these issues are closed. Perhaps your issue is sporadic or related to Android 11?

I assume that you are using latest versions of CWA (1.3.1) and Exposure Notifications System but maybe you could just confirm the versions for the record? There are [FAQ instructions in German](https://www.coronawarn.app/de/faq/#ENF_version) about how to find the ENF version or [here for the English language instructions](https://www.coronawarn.app/en/faq/#ENF_version).

Related to your report there are some other issues shown:

- "Risk determination not possible" - wrong info" https://github.com/corona-warn-app/cwa-app-android/issues/1081
- "Extra space in FAQ link stops selection of specific FAQ entry" https://github.com/corona-warn-app/cwa-app-android/issues/1199
- If the link space were to be removed from the link https://www.coronawarn.app/de/faq/ (10) making it https://www.coronawarn.app/de/faq/(10), it produces an HTTP 404 error.
- Changing the link https://www.coronawarn.app/de/faq/(10) to the new format https://www.coronawarn.app/de/faq/#API10 brings up the section which says:
>Der Fehler (10) in Zusammenhang mit der fehlenden Risiko-Ermittlung wird aktuell gemeinsam mit Google behoben. 

which is slightly confusing about whether it is already fixed or not. If the error is still occurring though (on Android 11) then the information is no longer accurate and may need updating. https://github.com/corona-warn-app/cwa-app-android/issues/1081 and https://github.com/corona-warn-app/cwa-app-android/issues/1199 are open issues and hopefully these will be addressed.

**Comment by abro1i** [comment] 2020-10-06 09:46
Hi @falkorichter,

thanks for reporting this. As @MikeMcC399  already commented, this issue has been reported several times. 

Lets continue the discussion here #1021

Best regards,

ABB

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment] 2020-10-06 09:46
Duplicate of #1021

**Closed by abro1i** 2020-10-06 09:46 UTC
Labels: bug

**Comment by MikeMcC399** [comment] 2020-10-06 10:05
Hi @abro1i 

https://github.com/corona-warn-app/cwa-app-android/issues/1021 is a different issue. It is 
"CAUSE: 3 Something went wrong. ApiException: 39508", whereas this issue is 
"CAUSE: 3 Something went wrong. ApiException: **10**"

It may make sense to re-open this one (https://github.com/corona-warn-app/cwa-app-android/issues/1304) to cover the API exception 10.

**Comment by thomasaugsten** [comment] 2020-10-08 13:27
The issue is related to Android 11 and GMS. 20.26.XX it will fixed in the next Google Play Service release

**Comment by PapaBravo** [comment] 2020-10-22 06:11
Coming from #1021, I think I am experiencing this bug now.

Pixel 3, Android 11, App-Version 1.5.0
Google Play Services 20.39.15

**Comment by MikeMcC399** [comment] 2020-10-22 09:05
@PapaBravo 

Could you confirm that the error message you are seeing is the same as in the screen shots from the original submission https://github.com/corona-warn-app/cwa-app-android/issues/1304 of @falkorichter ?

If not, it may be better to open a new issue, since this one is closed.

**Comment by thomasaugsten** [comment] 2020-10-22 17:06
@PapaBravo please create a new ticket if the error still persists and please provide me a bug report via email
thomas.augsten@sap.com
https://developer.android.com/studio/debug/bug-report
