### ISSUE TITLE
Cannot remove old rest result

### ISSUE THREAD

**Issue by zeus24** [corona-warn-app/cwa-app-android#1470] opened 2020-10-24 14:11 UTC
Hi,
I had around 20 days ago a Corona Test and the result was negative and pushed to the App.
When I now start the App the GUI is stuck on the "Datenabruf / "Das Ergebnis wird aktualisiert" and nothing happens anymore (only the circle going). I also cannot add a new Corona Test or remove the old test result. 

I guess, that the lab (Berlin) has removed the test result from the server. Now either the server produces a error code, which the app doesn't recognize. Or the App cannot deal with the circumstances that a once negative corona test doesn't exist anymore.

Device: Essential Phone, Android 10. App 1.5.0

**Comment by MikeMcC399** [comment] 2020-10-24 15:23
Hi @zeus24 

There is a posting https://github.com/corona-warn-app/cwa-app-android/issues/1084#issuecomment-714326433 from @svengabr from the Open Source Team that this issue is going to get fixed.

>The latest feedback in Jira is from today morning:
>
>>[...] is currently preparing a new state with the information that the test is expired and a delete Button to delete the Test. UI Design will be attached soon

Also there is a workaround from @daimpi in https://github.com/corona-warn-app/cwa-app-android/issues/1084#issuecomment-702193741, that suggests resetting the app, which you could try.

Your issue was reported also in #1435 which was closed as a duplicate of #1084, so if these other issues in your opinion cover your question, you're free to close this issue.

**Comment by heinezen** [comment] 2020-10-25 17:24
Hey @zeus24 ,

Thanks for your feedback. This problem is already discussed in https://github.com/corona-warn-app/cwa-app-android/issues/1084 as @MikeMcC399 already pointed out. The developers are currently working on a fix on the problem, buut I ave currently no information when the fix is going to be integrated. Therefore, please follow the linked thread for updates. I'll close your issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-25 17:24
Duplicate of #1084

**Closed by heinezen** 2020-10-25 17:24 UTC
