### ISSUE TITLE
Release apps for users of non-german app store

### ISSUE THREAD

**Issue by schuhmi2** [corona-warn-app/cwa-app-android#479] opened 2020-06-16 05:46 UTC
Right now, the Android app is not available to users who have their Google Play Store not set as Germany. A test ran with the store country set to 'United Kingdom' or 'France' returns the result 'This item is not available in your region'.

For increasing the coverage, foreign nationals, such as foreign military, diplomats, frontier workers, tourists, etc, should also have the opportunity to download, install, use and contribute to both their own safety, and that of others.

**Comment by tomjschwanke** [comment] 2020-06-16 05:56
Duplicate of #478

**Comment by SebastianWolf-SAP** [comment] 2020-06-16 06:02
Closing as it's a duplicate of #478 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-16 06:02 UTC
Labels: duplicate, enhancement
