### ISSUE TITLE
Error 39508 since 2020-08-19

### ISSUE THREAD

**Issue by Matzgitz** [corona-warn-app/cwa-app-android#1240] opened 2020-09-26 14:17 UTC
I got the error 39508 since 2020-08-19. Several app updates and OS Updates did not fix the issue. Running Android 10.
![Screenshot_20200926-081541266](https://user-images.githubusercontent.com/33512627/94331890-8487e380-ffd0-11ea-8670-7c9606af9d9b.jpg)

![Screenshot_20200926-081551315](https://user-images.githubusercontent.com/33512627/94331893-89e52e00-ffd0-11ea-8308-e8c2be36efd9.jpg)

Freezing the App (or not opening like explained an FAQ) does not fix the issue.

**Comment by heinezen** [comment] 2020-09-26 14:18
Duplicate of #1021

**Closed** 2020-09-26 14:17 UTC
