### ISSUE TITLE
Add permanent Notification allowing to see if the 'Exposure Tracking' is active or not

### ISSUE THREAD

**Issue by sascha10000** [corona-warn-app/cwa-app-android#540] opened 2020-06-16 12:52 UTC
## Current Implementation
Open the App to see the state at the top; stating 'Exposure Logging Active'.

## Suggested Enhancement
A permanent Notification that enables to see if the service is still running. See: [Android API Notification Builder](https://developer.android.com/reference/android/app/Notification.Builder.html#setOngoing%28boolean%29)

## Expected Benefits
The user transparently is aware that the app is running and tracking. If it may crash or the service gets killed somehow, it will be shown in the notification bar and the user may take actions to restart the app. Additionally the user gets a feeling of safety by seeing that the service is still running.

**Comment by fdellwing** [comment] 2020-06-16 13:08
Please make this default to false, otherwise you need to manually hide this notification.

**Comment by tkowark** [comment] 2020-06-16 14:13
This is a duplicate of #535

**Closed by tkowark** 2020-06-16 14:13 UTC
Labels: duplicate, enhancement

**Comment by sascha10000** [comment] 2020-06-16 14:52
Thanks, I assume it wasn't there the moment I opened the issue. I looked through all existing ones.

**Comment by tkowark** [comment] 2020-06-16 15:30
Yes, those came in in a very tight time window. No worries, always happy to answer :)
