### ISSUE TITLE
App not Working on Huawei Devices

### ISSUE THREAD

**Issue by xpcone** [corona-warn-app/cwa-app-android#490] opened 2020-06-16 07:14 UTC
Despite  #474 /  #484  there is also to be noticed, that the App is not useable on devices with HMS.

 All newer Huawei devices are banned from Goolge/PlayStore due to a presidential order. Without an apk or a upload to the Huawei store, there'll be approx. 1M Users not able to use this app.

**Comment by mat-l** [comment] 2020-06-16 07:44
Same problem for me, although I have installed Google Play Services besides Huawei Mobile Service: https://github.com/corona-warn-app/cwa-app-android/issues/478#issuecomment-644553948

**Comment by Nokius** [comment] 2020-06-16 08:02
@Huawei implimented an own framework called [HMS Core Contact Shield](https://developer.huawei.com/consumer/en/doc/development/Contact-Shield-V1/introduction-0000001050738511-V1). This could be may implemented for users with Google Serivce baned Huawei devices.

**Comment by henning-schild** [comment] 2020-06-16 08:25
In fact the app should be available as `.apk` in https://github.com/corona-warn-app/cwa-app-android/releases
That version should later be extended to update itself without the need for a store or google.

It could also be added to other stores like i.e. https://f-droid.org/. That is where true FOSS goes ... not "don't be evil"

**Comment by textvrbrln** [comment] 2020-06-16 08:32
+1
Otherwise people will download your standalone APK from sources like https://apkpure.com/de/corona-warn-app/de.rki.coronawarnapp/download?from=details and you probably don't want that.

**Comment by henning-schild** [comment] 2020-06-16 08:46
https://github.com/corona-warn-app/cwa-documentation/issues/5

**Comment by SebastianWolf-SAP** [comment] 2020-06-16 10:41
The respective information, especially the issue https://github.com/corona-warn-app/cwa-documentation/issues/5 has already been posted. We are closing this issue now...

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-16 10:41 UTC
Labels: bug

**Comment by mat-l** [comment] 2020-06-16 10:51
@SebastianWolf-SAP will there be an implementation of HMS services in your app? Currently it means all phones of Huawei are not supported at all. By closing this issue, all Huawei, Honor, and so on will be left out to participate in the app pogamme and therefore in taking care of our health.

**Comment by Nokius** [comment] 2020-06-16 10:58
@mat-l As @SebastianWolf-SAP  linked the [decision](https://github.com/corona-warn-app/cwa-documentation/issues/5#issuecomment-627860999) is to use the API from Google and Apple.
As there is a stupid trade war between the OS creature country and the handset makers one. You are for now in pity as well as all other non iOS/Google Service Android users. 
Welcome to the walled garden called monopoly!

**Comment by carlos22** [comment] 2020-06-16 11:06
@Nokius yes and we the tax-payers of Germany payed about 20 Million Euros to SAP (and apparently Telekom) for this solution. So one could expect a solution that does not limit users for the stupid wars other countries and companies fight. But we are obligated to clap our hands that this stuff is open source.

**Comment by mat-l** [comment] 2020-06-16 11:07
@SebastianWolf-SAP @Nokius yeah its the trade war, I commented as well over here: https://github.com/corona-warn-app/cwa-app-android/issues/510#issuecomment-644693694
In my opinion there must be support for HSM as well!

**Comment by corneliusroemer** [comment] 2020-06-16 11:21
@SebastianWolf-SAP Stop closing issues with unrelated references.
A link to the documentation is not sufficient. Please update your FAQs and general public facing documents to mention which phones are not supported rather than deeplinking complicated documentation.

This issue was about Huawei, not F-Droid. In your link I can't find a Huawei mention.

**Comment by s-martin** [comment] 2020-06-16 11:39
> @Nokius yes and we the tax-payers of Germany payed about 20 Million Euros to SAP (and apparently Telekom) for this solution. So one could expect a solution that does not limit users for the stupid wars other countries and companies fight. But we are obligated to clap our hands that this stuff is open source.

Ok, how would you expect that SAP or German government would resolve the ongoing trade conflict between USA and China (Google and Huawei, respectively) for a tiny Corona warn app?

**Comment by mat-l** [comment] 2020-06-16 11:44
@s-martin they can't stop it, but they should provide an solution that fits all, that means also to implement HMS Core services, which I wrote here: https://github.com/corona-warn-app/cwa-app-android/issues/510#issuecomment-644693694

**Comment by s-martin** [comment] 2020-06-16 11:48
The Exposure Notification API is provided by Google via Play Services, so there's no workaround at this point.

**Comment by Nokius** [comment] 2020-06-16 12:11
@carlos22  I agree with you it's tax payers money used here. 
Personally I'm very happy to see that public money has turn into public code. 
But 20 Million are not covering corner cases. 
Like: 
*  non smartphone users with feature phones
* gray market devices with no Google Services
* alternative OS/ROM's
* Android devices with no Google Services
* ...

As we both found out it's open source so you or anyone else can modify the code and open a PR. What about you @Huawei wanna get you users under the corona-warn-app umbrella?

**Comment by corneliusroemer** [comment] 2020-06-16 12:18
Huawei has a market share of 16% in Germany - that is quite significant. It's more than half of Apple's. So it can be considered worth it's own app - if the changes required aren't huge. Marginal costs per marginal benefit could be lower than for Apple with only 30% market share.
https://gs.statcounter.com/vendor-market-share/mobile/germany

**Comment by Nokius** [comment] 2020-06-16 12:31
@corneliusroemer is it now 16% or 17%. Anyway I don't thinks all of them are without Google Service. If so it's still a user choose and not the fool of the app developer(s).

**Comment by corneliusroemer** [comment] 2020-06-16 12:48
@Nokius Not sure how many devices are affected. But Huawei has significant market share. Same can be said about Apple, why doesn't everyone use Android. Sure Huawei doesn't offer the API, so that's Huawei's fault. Not sure if there's a workaround possible.

**Comment by jlnprssnr** [comment] 2020-06-16 12:52
Huawei will offer an API as @Nokius mentioned above.

**Comment by henning-schild** [comment] 2020-06-16 13:38
Did anyone bother telling google about the problem and maybe ask them to make that code available? 
That would allow for a truly free implementation, which would suddenly also cover huawei devices and not just lineageOS and friends. Who knows, they might be willing to help out.

**Comment by carlos22** [comment] 2020-06-16 18:20
> The Exposure Notification API is provided by Google via Play Services, so there's no workaround at this point.

Yes but that is the essential part. Which I would have expected to be implemented by this app. But software development today means you pay a lot of money for people making nice UIs and really using FAANG frameworks. Thats like giving up.

**Comment by carlos22** [comment] 2020-06-16 18:31
> Did anyone bother telling google about the problem and maybe ask them to make that code available?
> That would allow for a truly free implementation, which would suddenly also cover huawei devices and not just lineageOS and friends. Who knows, they might be willing to help out.

They sure will not. Google Play Services are essential to what keeps them having full control over Android. Very clever people at Google found this loophole to make sure everybody still likes Android because it is open source but still are able to make contracts with OEMs and ship code to every smartphone. They will never give you anything that is inside of Play Services.g that is inside of Play Services.

**Comment by corneliusroemer** [comment] 2020-06-16 18:49
@SebastianWolf-SAP I think you should reopen this issue here - it's unrelated to F-Droid. It asks specifically for compatibility with a Huawei API that is TBA.

There should be special regards for Huawei while the issue is not resolve - if ever. Doesn't harm to have one issue that acts as a reminder that Huawei support is know to be limited.

**Comment by Nokius** [comment] 2020-06-16 19:40
@corneliusroemer As I linked earlier today, currently the implementation is only for Apple and Android ( Google Service API). [Here](https://github.com/corona-warn-app/cwa-documentation/issues/5#issuecomment-627860999) again the link to the developer mentioning it.

If you like to see support for an minority group of users, create fork, read the [Huawei documentation](https://developer.huawei.com/consumer/en/doc/development/Contact-Shield-V1/introduction-0000001050738511-V1), code, create a PR -> provide *profit* for the group of users. Looks like you are effected and you have the ability to solve it it's open source and *you* can make it happen.

**Comment by Nokius** [comment] 2020-06-16 19:45
@henning-schild come on google is aware of this 'issue' and they do it (from my point of view) on purposes. Google will never give up on users data as they are an ad company.  So the google services are imported for them.

**Comment by SebastianWolf-SAP** [comment] 2020-06-16 19:49
Dear @corneliusroemer,

we have stated repeatedly, also in our FAQ and also in the official communication that only iOS and Android devices running Google Play Services are supported and we are not aware of additional plans. Moreover, there is currently no sign that the German Federal Government and/or the Robert Koch Institute will contract us to implement the app on other platforms. 

We cannot state more clearly than what we've already done. And to be even more precise: We're the wrong contacts for such questions. Requests to implement the app on other platforms need to be ordered by the government **or implemented by the community** as @Nokius said.

So either somebody starts doing the work here (and announce that accordingly such as the folks in #75 for a free implementation of Google Play) or we will keep this issue closed with the label 'wontfix'.

Thank you for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by henning-schild** [comment] 2020-06-17 19:42
I personally also believe that google is aware and they are locking things down on purpose. But that does not rule out talking to them! Until somebody does that we are just working on assumptions here.

And with "somebody" i am thinking of SAP and Telekom with the COVID health mission, they might have some leverage. They should at least ask instead of refusing/ignoring true FOSS ... maybe based on the same assumptions that others already mentioned here.

To be honest i could not care less about the app ... i just see the leverage as a potential to open up android. That would be a good tax invest with or without the virus

**Comment by Nokius** [comment] 2020-06-18 08:59
@henning-schild For sure the Federal Republic of Germany in person as RKI can try to contact Google so they may will debundle the Proximity Tracing API from the Google Services. *BUT* how Android will get the API then? To add it directly to the AOSP base or the deviates OEM/Manufacture create will take month/years or never happens as this will not push out Updates anytime soon.
Also the User who not install this OS Updates are may bigger then User who avoid Application Updates which in fact Google services are.

From my point of view Europe should wake up *now* and start an European driven mobile OS. So we [Europe / Federal Republic of Germany] could find solutions and not try to bargain with 'ruler'.

**Comment by henning-schild** [comment] 2020-06-19 17:43
@Nokius i would not day "Europe" because there is no reason to limit the scope of a liberation, maybe the pressure and funding could initially come from there.

The media seemed to focus more on availability on older devices, which just boils down to the same problem. Even if things will take a lot of time and this app will not get its fast solutions ... getting google to open up and loose control would be a step in the right direction. Maybe for the next pandemic or simply the next federal effort to release FOSS apps, which will hopefully happen after this one.
