### ISSUE TITLE
Don't publish statements "new version available" when the staged rollout hasn't finished yet

### ISSUE THREAD

**Issue by treysis** [corona-warn-app/cwa-app-android#3698] opened 2021-07-13 07:57 UTC
Every time there's a new version, news statements are being pushed out, despite the release hasn't been completely published. This is a bit annoying. Many users see no updates until the staged rollout is complete and thus suspect they're doing something wrong or think something is broken.

Statements should either make clear that the update will not be immediately available to everyone, or even better you should wait to publish statements until the rollout is done.

I posted this in the android repo because the way staged rollouts are handled are different in GooglePlay and Apple's AppStore. For Apple, when using staged rollout, new users will immediately see the new app, only existing users will continuously be upgraded. For Google, it's the reverse: the new version won't be available to new users until the staged rollout reaches 100%. So on Android you're stuck with the old version and it's very confusing for returning users when they think "ah, that's a feature I'd like to use" and upon installing the app realize that the advertised features aren't even available.

**Comment by Ein-Tim** [comment] 2021-07-13 08:05
> Statements should either make clear that the update will not be immediately available to everyone, or even better you should wait to publish statements until the rollout is done.

Both, the [blog post](https://www.coronawarn.app/de/blog/2021-07-12-cwa-version-2-5/) (version 2.5 as an example) and the Twitter Account [@coronawarnapp](https://twitter.com/coronawarnapp?s=21) mentions ([here](https://twitter.com/coronawarnapp/status/1414499174037532675?s=21) on Twitter and in the last paragraph of the blog) that there's the staged rollout and that it takes time. 

Could you give me an example where you see room for improvement?

**Comment by dsarkar** [comment] 2021-07-13 09:41
@treysis Thanks of your comments. As @Ein-Tim already mentioned, the staged rolled-out is mentioned usually. Please let us know where the new version was mentioned without mentioning the staged roll-out and we will check if there is something we can do about it.


Thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-07-13 11:23
@dsarkar 
The [primary CWA app FAQ](https://www.bundesregierung.de/corona-warn-app-faq), hosted by the Presse- und Informationsamt der Bundesregierung, does not mention any rollout delay. The URL is https://www.bundesregierung.de/corona-warn-app-faq.

With locale set to German, open CWA, tap three-dot symbol, select "App-Information" then "Häufige Fragen", scroll down to "Was ist mit den Updates besser geworden?", expand and read.

CWA Version 2.5 is described, with no mention of a 48 hour delay for Google Play Store subscribers.

The issue is not apparent with locale set to English, because the primary app FAQ still describes the previous version 2.4 (although with this version it also did not mention any rollout delay either).

**Comment by wattenre** [comment] 2021-07-13 13:05
@dsarkar 
The NINA warning app also does not refer to the staged roll-out. At the time of the push notification, the update is therefore usually not yet available.

**Comment by dsarkar** [comment] 2021-07-13 13:08
@MikeMcC399 @wattenre Thanks for the info. I will forward it.

**Comment by treysis** [comment] 2021-07-13 13:47
I believe it should be mentioned in the headline or very mich in the beginning. I mean I personally know about the staged rollout (though I only learned that 2 or 3 months ago). But I hear from many ppl around me that it's annoying.

I think you should either wait to publosh the release until the rollout is finished or mention it in the very beginning that a new version is coming, not that it's already there. Though I suspect news outlets will just miss that note anyways.

**Comment by Jo-Achim** [comment] 2021-07-14 09:17
Yes, I also think that the time lag on Google is 'a bit long'.

Here (https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.5.1) you can only read roughly that the release 2.5.1 was released _two days ago_ ... but up to now (_07/14/2021 11:15 a.m._) the new release is neither distributed via Google updates nor can it be downloaded from Google Play (here: v 2.4.3).
And ... it's not the first time.

**Comment by DerVogel2020** [comment] 2021-07-14 09:26
I created https://github.com/corona-warn-app/cwa-wishlist/issues/585 so everybody can calculate when the update should be available to everyone.

**Comment by heinezen** [comment] 2021-07-15 16:03
> Statements should either make clear that the update will not be immediately available to everyone, or even better you should wait to publish statements until the rollout is done.

Unfortunately, we can only lose in that regard as long as most people don't know what a rollout is.

* If we publish the statement after the rollout is finished, we have no official communication available while the release is deployed. Additionally, It would probably be a lot more confusing since some people would wonder why they didn't get an update when others have already received one.
* Even if we make clear to everyone that the update is not immediately available (which we already do), some users don't read those. They hear about the update from social media or from friends. This is not something we can easily solve.
* It is very unlikely that we can change the way rollouts are done on Android. Other, much larger actors have tried and were rejected. That's not great, but the advantages of a rollout still make it worth they extra explaining.

Flawed communication is better than no communication in this case.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-12-21 08:28
In my experience with receiving previous Android CWA releases, it has always taken 48 - 49 hours before I received the release. I have almost never been one of the random users chosen to get a new release earlier. So it seems that the manual control of the staged rollout has kept the percentage of addressed and subscribed users on the Google Play Store at a low number, then after 48 hours it goes to 100% and everybody has access.

Maybe when the staged rollout has completed, the corresponding blog could be updated to note that the Android app release is completely available? The Twitter channel is very active these days. That could also be a place where the full roll-out for Android could be confirmed.

**Comment by Jo-Achim** [comment] 2021-12-21 09:39
> @MikeMcC399 wrote:
> In my experience with receiving previous Android CWA releases, it has always taken 48 - 49 hours before I received the release. I have almost never been one of the random users chosen to get a new release earlier. So it seems that the manual control of the staged rollout has kept the percentage of addressed and subscribed users on the Google Play Store at a low number, then after 48 hours it goes to 100% and everybody has access.

The time from which everyone has access seems to me to coincide with the time when the current version is also made available in the Google Play Store.
Currently (December 21, 2021 10:30 a.m.): 2.14.1 in the Google Play Store and on my smartphone.

In other words: the general rollout for everyone seems to be the same as the time of general availability.

**Comment by MikeMcC399** [comment] 2021-12-21 13:03
@Jo-Achim 
Your view into the Google Play Store depends on whether Google has released the app to you or not. Different users see different information until the staged-rollout has reached 100%, after which time all users see the same information.

My account has not yet been selected for 2.15.1 rollout so I see the following on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp

![image](https://user-images.githubusercontent.com/66998419/146932862-937c9296-8a36-4535-aa1f-4bcf327a29c7.png)

We know from @dsarkar's comment in https://github.com/corona-warn-app/cwa-website/issues/2216#issuecomment-998020989 and the blog https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/ that the rollout of CWA 2.15.1 started at about 08:00 on Monday, December 20, 2021. The updated timestamp of 15 December 2021, which I am seeing in the Google Play Store, corresponds to the date of the last release candidate for this version [v2.15.1-RC3](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.15.1-RC3). The final release [v2.15.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.15.1) is technically identical to the release candidate (they are tags on the same commit https://github.com/corona-warn-app/cwa-app-android/commit/f5fe6617411dcd436abebace99352a942660dc68).

So in fact the Google information is a little confusing, as it is showing me the old version (2.14.1) with the updated date when  the new version 2.15.1-RC3 was submitted (15 December 2021). I expect that will change tomorrow morning and I will see 2.15.1 instead.

**Comment by MikeMcC399** [comment] 2021-12-23 18:19
Since yesterday morning I see now:

![image](https://user-images.githubusercontent.com/66998419/147278105-1d4e26dc-30a4-4800-8bde-356532444546.png)

I assume that the rollout of CWA Android 2.15.1 has now reached 100%, but in fact only somebody with access to the [Google Play Console](https://play.google.com/console/about/) for the CWA account can say for sure.

**Comment by dsarkar** [comment] 2021-12-23 18:24
@MikeMcC399 100% Rollout at 22.12.2021 07:02

**Comment by treysis** [comment] 2021-12-23 22:28
> but in fact only somebody with access to the [Google Play Console](https://play.google.com/console/about/) for the CWA account can say for sure.

You can just open PlayStore in an incognito window. It won't show the new version until 100% are reached.

**Comment by MikeMcC399** [comment] 2022-01-19 11:04
@dsarkar 

It seems that the Android 2.16 rollout is delayed. I'm not seeing it on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp yet and it is now 50 hours past the projected deadline of 48 hours counted from the timestamp of 10 Uhr Jan 17, 2022 on https://www.coronawarn.app/en/blog/2022-01-17-cwa-2-16/.

**Comment by Jo-Achim** [comment] 2022-01-19 14:59
Just manually downloaded CWA v.2.16.2 from Google Play Store.

2G+ should now work with a test certificate.
But unfortunately not yet with "Full Vaccination" (= "Basic Immunization" + "Booster); see: [Beim RKI gelten zweifach Geimpfte nicht länger als „vollständig geimpft“](https://www.welt.de/politik/deutschland/article236323765/RKI-Zweifach-Geimpfte-gelten-nicht-laenger-als-vollstaendig-geimpft.html) / "At the RKI, people who have been vaccinated twice are no longer considered to be “fully vaccinated”.

**Comment by dsarkar** [comment] 2022-01-19 16:08
@MikeMcC399 Roll out of Android 2.16.2 was set to 30% 19.01.2022 07:42, probably later today to 100%.

**Comment by MikeMcC399** [comment] 2022-01-19 16:20
@dsarkar 
>  Roll out of Android 2.16.2 was set to 30% 19.01.2022 07:42, probably later today to 100%.

I appreciate the update! Thank you. 

The blog says:

"The new version of the Corona-Warn-App will be available to users within the next 48 hours."

so in future:
- either the time frame should not be stated in such an exact number of hours or
- if there is a delay past the stated time-frame of 48 hours, then the blog should be updated with a new forecast for the time of rollout completion

**Comment by MikeMcC399** [comment] 2022-01-19 16:54
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp is now showing 2.16.2 in Incognito mode. I can update to it now, and I assume that we are now at 100% rollout.

**Comment by MikeMcC399** [comment] 2022-01-19 16:55
@Jo-Achim 
> Regarding "At the RKI, people who have been vaccinated twice are no longer considered to be “fully vaccinated”" I assume that the developers have already received this information. Or?

I will open a new issue for this point, as it does not belong in this thread.

**Comment by MikeMcC399** [comment] 2022-01-19 17:27
@Jo-Achim 
I researched the point you mentioned. I could not see any change to the legal definition of "vollständig geimpft" according to www.pei.de/impfstoffe/covid-19.

The RKI Excel sheet of [Tabelle mit den gemeldeten Impfungen nach Bundesländern und Impfquoten nach Altersgruppen](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquotenmonitoring.html) uses the term "grundimmunisiert" whereas the RKI graphic on [Digitales Impfquotenmonitoring zur COVID-19-Impfung](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html) uses the terms:
- Mind. einmal geimpft
- Vollständig geimpft
- Auffrischimpfungen

So in some places RKI now writes "grundimmunisiert" instead of "vollständig geimpft".

At this time I don't think this is problem. I will not open a new GitHub issue after all.

**Comment by Jo-Achim** [comment] 2022-01-19 17:37
Yes @MikeMcC399, I also wanted to find a suitable RKI link and add it, but I haven't found anything at the moment. Either Prof. Lauterbach was too fast or the RKI was too slow. ;-)

**Comment by dsarkar** [comment] 2022-01-20 07:37
Good morning @MikeMcC399 

> 
> so in future:
> 
> either the time frame should not be stated in such an exact number of hours or
> if there is a delay past the stated time-frame of 48 hours, then the blog should be updated with a new forecast for the time of rollout completion


I will forward your suggestion.

**Comment by Ein-Tim** [comment] 2022-02-01 10:00
@Jo-Achim 

Regarding https://github.com/corona-warn-app/cwa-app-android/issues/3698#issuecomment-1016550366, I suggest you take a look at https://github.com/corona-warn-app/cwa-app-ios/pull/4155. "Vollständig geimpft" will be changed to "Grundimmunisiert".

**Comment by MikeMcC399** [comment] 2022-02-01 10:39
@Ein-Tim

Thanks for noticing the PR! The issue is separately tracked in https://github.com/corona-warn-app/cwa-documentation/issues/816 where I noted that it should be fixed in 2.18.

**Comment by dsarkar** [comment] 2022-02-04 09:31
@MikeMcC399  FYI https://twitter.com/coronawarnapp/status/1489523975331930113?s=21

**Comment by MikeMcC399** [comment] 2022-02-04 10:10
@dsarkar 
It's good to see that the Twitter account is being used to provide updated information about the state of the rollout. If this is going to be a reliable way to get up-to-date information on the rollout, then the blog making the announcement of a new version could even mention the Twitter account https://twitter.com/coronawarnapp as a "real-time" source of information for the rollout. That would be ideal!

I am also impacted and did not yet receive CWA Android 2.17.x.

**Comment by MikeMcC399** [comment] 2022-02-06 09:13
The [Twitter news](https://twitter.com/coronawarnapp/status/1489523975331930113?s=21) was helpful, although not accurate, since version 2.17.2 was not available to all users until today, Sunday, Feb 6, 2022 at about 10 am, which was around 96 hours after the original blog post [Project team publishes CWA version 2.17](https://www.coronawarn.app/en/blog/2022-02-02-cwa-2-17/) dated Wednesday, Feb 2, 2022. The blog post predicted Android rollout within 48 hours, which would have been Friday, Feb 4, 2022 at 10 am.

![image](https://user-images.githubusercontent.com/66998419/152674276-49f926ba-1d29-4aee-b536-e94ec3644e7c.png)

**Comment by MikeMcC399** [comment] 2022-03-16 09:14
@treysis 

The blog announcement for CWA 2.19 https://www.coronawarn.app/en/blog/2022-03-16-cwa-2-19/ includes the following text:

"Version 2.19, like previous versions, will be rolled out to all users in stages over 48 hours. iOS users can now download the latest app version manually from the Apple Store. The Google Play Store does not offer the option of triggering a manual update. The new version of the Corona warning app will be available to users here within the next 48 hours.

Up-to-date information on the status of the roll-out can be found on the Twitter channel of [#coronawarnapp](https://twitter.com/coronawarnapp) (German only)."

That is probably the best that we can hope for according to the staged-rollout process defined by the Google Play Store. The begin of the rollout is announced in the blog (and on [Twitter](https://twitter.com/coronawarnapp/status/1504021220307652612?s=20&t=KS1Y_iO8jtXT6bPNTbJMPQ)) and the progress is updated on [Twitter](https://twitter.com/coronawarnapp).

**Comment by Ein-Tim** [comment] 2022-03-31 10:51
FYI: 2.20 rollout has been stopped without information on Twitter.

**Comment by MikeMcC399** [comment] 2022-03-31 11:16
@Ein-Tim 

> FYI: 2.20 rollout has been stopped without information on Twitter.

- How do you know that the CWA Android 2.20 rollout has stopped?

- I guess you are referring to the rollout of [releases/tag/v2.20.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.20.1)?

- After reading the comments in https://github.com/corona-warn-app/cwa-app-ccl/issues/65 it would not surprise me if the CWA Android 2.20.1 rollout has been interrupted waiting for a fix e.g. [releases/tag/v2.20.3-rc.0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.20.3-rc.0).

- According to the blog announcement on https://www.coronawarn.app/en/blog/2022-03-30-cwa-2-20/ the rollout started yesterday Mar 30, 2022 at 10.00 am. If there is a delay and the expected deadline of Friday Apr 1, 2022 10.00 am for Android rollout completion can't be met, then the [CWA Twitter channel](https://twitter.com/coronawarnapp) should be informing users. You might prefer to be informed immediately, others users might prefer just being informed as soon as there is reliable new information about how long the rollout will take. Going by @thomasaugsten's https://github.com/corona-warn-app/cwa-app-ccl/issues/65#issuecomment-1083354170 that information should be available this afternoon, Thursday, Mar 31, 2022.

**Comment by thomasaugsten** [comment] 2022-03-31 11:33
iOS 2.20.2 is available in the AppStore
Android Hotfix review is expected in the next hours and the rollout will then continued

**Comment by Ein-Tim** [comment] 2022-03-31 11:38
@MikeMcC399 

> How do you know that the CWA Android 2.20 rollout has stopped?

See: https://twitter.com/moortaube/status/1509448443789557764?s=21&t=H3gDI0ftoZ_vsjNiSUcyFA
I'm trying to get this verified at the moment. 

> I guess you are referring to the rollout of releases/tag/v2.20.1?

Yep

> After reading the comments in Twitter reports: "DCC_RI_PIN_MISMATCH" error when attempting to reissue certificates cwa-app-ccl#65 it would not surprise me if the CWA Android 2.20.1 rollout has been interrupted waiting for a fix e.g. releases/tag/v2.20.3-rc.0.

Me neither, I just wanted to make the point that the Twitter channel does **not** inform about stopped rollouts.

**Comment by Ein-Tim** [comment] 2022-03-31 11:39
Thanks to @thomasaugsten for confirming.

**Comment by MikeMcC399** [comment] 2022-03-31 11:42
@Ein-Tim 
Since the Google Play Store is giving out the information that the CWA Android 2.20.1 rollout is interrupted, then that should also be put out on the Twitter channel.

Thanks for providing the background information!

**Comment by thomasaugsten** [comment] 2022-03-31 16:02
The rollout for both OS is continued sorry for the delay

**Comment by MikeMcC399** [comment] 2022-03-31 16:21
I'm seeing [v2.20.3](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.20.3) as release in GitHub for Android now.

**Comment by MikeMcC399** [comment] 2022-03-31 16:53
Twitter https://twitter.com/coronawarnapp/status/1509567135441371136?s=20&t=a9fwotvsEG_Q2XsmH57B0g says

"Wir mussten aufgrund eines Fehlers den Rollout der neuen Version 2.20 für kurze Zeit stoppen. Das Problem ist jetzt behoben.

Entschuldigt bitte die Verzögerung!"

It wasn't clear whether that means the expected completion of CWA Android 2.20 is still tomorrow, Friday, Apr 1, 2022 10.00 am or whether that is also delayed.

**Comment by MikeMcC399** [comment] 2022-04-01 09:49
CWA Android 2.20.3 has not yet completed its rollout, as can be seen on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp (Incognito window), which still shows 2.19.2 as the current version.

I haven't seen any new information on https://github.com/corona-warn-app giving users a new date/time for completion of this rollout.

**Comment by MikeMcC399** [comment] 2022-04-02 11:12
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp is showing version 2.20.3 in an Incognito window. In the past this meant that the correspnding roll-out had completed.

**Comment by MikeMcC399** [comment] 2022-04-21 08:33
The rollout for CWA Android 2.21.1 seems to have completed according to https://play.google.com/store/apps/details?id=de.rki.coronawarnapp.

The blog https://www.coronawarn.app/en/blog/2022-04-19-cwa-2-21/ is timestamped "CWA-Team, 10 am, on April 19, 2022" with the text "The new version of the Corona-Warn-App will be available to users here within the next 48 hours."

I observed that it was not available after 48 hours, although after another 20 minutes on top of that I was able to download it. I don't know where the inaccuracy comes in. Perhaps there are manual operations involved? Maybe the statement for the future should say "will be available to users here **approximately** within the next 48 hours."? Or maybe the Android rollout could be started a hour before the timestamp on the blog?

**Comment by dsarkar** [comment] 2022-04-21 10:55
@MikeMcC399 Yes, I think the stages of the roll out are triggered manually. I forwarded your suggestion.

**Comment by MikeMcC399** [comment] 2022-05-12 12:39
The rollout for CWA Android 2.22.1 was completed within 48 hours of the announcement https://www.coronawarn.app/en/blog/2022-05-04-cwa-2-22/ May 4, 2022 at 18:00 CEST. :+1:

"Version 2.22, like previous versions, will be rolled out to all users in stages over 48 hours. iOS users can now download the latest app version manually from the Apple Store. The Google Play Store does not offer the option of triggering a manual update. The new version of the Corona-Warn-App will be available to users here within the next 48 hours."

**Comment by MikeMcC399** [comment] 2022-09-20 13:52
@treysis 

I suggest to close this issue now, since:

- The blog announcements of new versions include the information that the rollouts are staged e.g. "Version 2.26, like previous versions, will be rolled out to all users in stages over 48 hours. iOS users can now download the latest app version manually from the Apple Store. The Google Play Store does not offer the option of triggering a manual update. The new version of the Corona-Warn-App will be available to users here within the next 48 hours."

- The last few Android releases have all managed to complete the rollout within the specified 48 hours.

**Closed** 2022-09-20 23:30 UTC
Labels: enhancement
