### ISSUE TITLE
Conflicting information on the availability of COVID-19 Exposure Notifications 

### ISSUE THREAD

**Issue by Raupinger** [corona-warn-app/cwa-app-android#543] opened 2020-06-16 13:11 UTC
This might be related to #499 
Quick explanation of my setup:
I don’t want to have a google account. My phone OEM uses a fairly stock android with google Play Services. A use an alternative Play Store client ([Aurora Store, F-Droid Page](https://f-droid.org/en/packages/com.aurora.store/)). Google Play Services version is 20.18.17

**What I did:**
Installed the App and updated Google Play Services. Accepted the privacy policy.
**Expected Behavior:**
When tapping "Risiko-Ermittlung aktivieren" the setup wizard continues, no errors.
**Observed behavior:**
After tapping on "Risiko-Ermittlung aktivieren" I get a notification:  "Google Play-Dienste aktualisieren Corona-Warn wird nur ausgeführt, wenn du die Google Play-Dienste aktualisiert" 
After some time I also get error messages in the App (cf. screenshot 2)
**What I tried:**
Reinstalling the App. Rebooting the phone.
**Additional notes:**
COVID-19 Exposure Notifications are available according to system settings (cf. screenshot 1). Note that when tapping on "COVID-19 Exposure Notifications" I get a white screen.

Screenshot 1:
![IMG_9466](https://user-images.githubusercontent.com/29229062/84778370-32075600-afe3-11ea-87e6-96b82ef3066f.png)
Screenshot 2:
![IMG_9464](https://user-images.githubusercontent.com/29229062/84778555-74309780-afe3-11ea-975e-9e7511add8fc.jpeg)

---
Internal Tracking ID: EXPOSUREAPP-1979

**Comment by mxmxchere** [comment] 2020-06-16 13:48
I have exactly the same behaviour here. I also don't have a Googleaccount and updated Playservices through Aurora.

**Comment by BjoernPetersen** [comment] 2020-06-16 14:16
I reproduced this on a Google Pixel XL. If the user is not logged in to a Google Account, the app cannot be used and prompts you to update the Google Play services. This is especially problematic as the app is marketed claiming that "no account is required".

**Comment by mxmxchere** [comment] 2020-06-16 14:19
Yes it seems to be something account related. I am still logged out and tried to redownload Google Play Services with Spoofed Location (Germany) from Aurora, but the issue remains the same.

**Comment by BjoernPetersen** [comment] 2020-06-16 14:50
I have to row back on my previous confirmation. The app works just fine on the Pixel XL without a Google Account. What solved it was uninstalling and reinstalling the Play Services, although seemingly the same version got installed. I tried clearing the data/cache of the Play Services before, which didn't work.

**Comment by mxmxchere** [comment] 2020-06-16 20:50
Really? That would be great. Can you explain the steps in more detail?

For example i can't really uninstall the Google Play Services, i can only disable them or upgrade them. Where did you download the Google Play Services from and which version do you have installed right now? Thanks for your input.

**Comment by BjoernPetersen** [comment] 2020-06-17 07:50
I'm sorry, I didn't phrase that clearly enough: I didn't uninstall the Play Services completely, as that would be pretty hard on most devices, but I did indeed disable them (which, if you do it in the Play Store App, it still calls uninstalling). When an app is disabled, its updates are uninstalled and it's reverted to the factory state. If you re-enable it afterwards, you can install the latest update again. 

My guess is that either reinstalling the latest update solved the issue or the new version of the Play Services I got is actually different from the old one with the same version identifier.

**Comment by mxmxchere** [comment] 2020-06-17 08:50
So do i understand this correctly: You downloaded Google Play Services and the corona-app via the Google Play Store but you are not signed in in the Google Play Services Menu (Settings -> Google)? Is that even possible, i thought when you enter your google-credentials once  in one of the google-apps they are used by all of them.

**Comment by BjoernPetersen** [comment] 2020-06-17 09:02
Sorry, I skipped that part. I installed the app and the Play Services while still being logged in with a Google Account, then completely removed the account from the device before opening the app for the first time. I didn't think about making the steps reproducible for people with no Google Account, so that's on me.

The problem I'm seeing right now is that some devices don't allow you to disable/partially uninstall the Play Services in the system settings. The option is available on the Pixel XL, but the button is disabled on my Moto G7 Power. Does anybody know of a user-friendly way to disable it anyway without third-party apps or the Play Store app?

**Comment by dsarkar** [comment] 2020-11-20 13:11
Dear @Raupinger, @mxmxchere, @BjoernPetersen,

In order to follow up on this old issue, can you please confirm that you are running successfully the actual CWA version 1.6.1? Thanks! Best regards,
DS

---
Corona-Warn-App Open Source Team

**Comment by Raupinger** [comment] 2020-11-20 17:38
I can confirm that. I'm currently running 1.6.1 with google play services 20.42.17. I recently had an issue where CWA showed a similar error, but that was resolved by updating google play services and rebooting.

**Comment by mxmxchere** [comment] 2020-11-20 17:45
I run CWA 1.6.1 and Google Play Services 20.30.19 without any issues.

**Comment by dsarkar** [comment] 2020-12-04 13:22
@Raupinger, @mxmxchere, thanks for the feedback. We will close this issue now! Many thanks for contributing. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-12-04 13:22 UTC
Labels: bug, further input needed, mirrored-to-jira
