### ISSUE TITLE
Corrupt certificate export PDF

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5370] opened 2022-07-20 15:53 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
This problem was mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/5350#issuecomment-1184514377

## Technical details

- Device name: Pixel 3a emulator and Samsung Galaxy A52 5G
- Android version: 12
- App version: 2.24.2 and 2.26.x

## Describe the bug

Directly after updating to 2.24.2 an exported certificate is corrupt and cannot be read by Adobe Acrobat DC, which outputs the error message:

"There was an error processing a page. There was a problem reading this document (109)."

When this error occurs on 2.24.2, the exported PDF file has a size of 676 KB (same size as on 2.23.2), otherwise it has a size of 121 KB.

## Steps to reproduce the issue

The problem occurs directly after a version update from CWA Android 2.23.2 to 2.24.2

1. Install 2.23.2
2. Single certificate export to Google Drive (PDF is 676 KB and good)
3. Leave 2.23.2 open and update to 2.24.2
4. Single certificate export to Google Drive (PDF is 676 KB and unreadable)
5. Repeat single certificate export to Google Drive (PDF is 120 KB and readable)

Detailed steps below:

On Desktop

1. Use Android Studio Device File Explorer to transfer German EU vaccination certificate PDF to the emulator

In CWA App

2. Tap Scan
3. Tap Open File
4. Navigate to vaccination certificate in File app and tap on file, tap "Continue"
5. Tap three-dot symbol
7. Select Display Print Version, tap "Next"
8. Tap Share symbol
9. Tap Drive symbol
10. Tap Save

On Desktop

11. Open Drive https://drive.google.com/drive/my-drive
12. Download
13. Attempt to open saved PDF with Adobe Acrobat DC
In some cases an error message "There was an error processing a page. There was a problem reading this document (109)." is displayed, in other cases there is no problem.

## Expected behavior

An exported certificate should always be readable.

---
Internal Tracking ID: [EXPOSUREAPP-13673](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13673)

**Comment by Ein-Tim** [comment] 2022-07-20 16:46
@mlenkeit / @mtwalli 

With all these issues reported with the new way certificates are exported, would it make sense to roll back the change in 2.25?

What are the advantages of creating the printout from a SVG (what 2.24 does) over creating it from a PDF (what versions pre 2.24 did)?

**Comment by mtwalli** [comment] 2022-07-20 17:06
@Ein-Tim  using an SVG instead of raw PDF (bitmap) generates:
1- smaller PDF in terms of size 
2-  higher quality PDF (try to zoom in) in PDF generated before 2.24, PDF will show pixels in big zooms

We moved to this approach ,since generating multiple certificates would required optimisation in the size.

`CovPassApp` is using approach also.

@MikeMcC399  I can't tell what is the issue with the information you provided, 
- could you please tell whether you were trying to export single or multiple certificates?
- what version do you have of WebView on the emulator ?
- does it happen on real devices ? (emulators are not always reliable)

**Comment by MikeMcC399** [comment] 2022-07-20 17:33
@mtwalli 

> I can't tell what is the issue with the information you provided,
> 
> * could you please tell whether you were trying to export single or multiple certificates?

This is a single certificate export. See steps 5. & 6. 

> * what version do you have of WebView on the emulator ?

`Android System WebView` on the Pixel 3a emulator is up-to-date from the Google Play Store with version 103.0.5060.71

> * does it happen on real devices ? (emulators are not always reliable)

I have also seen it happen on a real device (Samsung Galaxy A52 with Android 12). Unfortunately I haven't found a way to reliably reproduce the issue, neither on an emulator, nor on a physical device.

**Comment by MikeMcC399** [comment] 2022-07-20 17:36
@Ein-Tim 

> With all these issues reported with the new way certificates are exported, would it make sense to roll back the change in 2.25?

Apart from this sporadic issue of corrupt export PDFs, all the other certificate issues are cosmetic. If the app were to be rolled back to 2.23.2 functionality then the new function of exporting multiple certificate would be lost. I have not seen anybody else report about corrupt certificates. Have you seen any reports about this from other people?

**Comment by Ein-Tim** [comment] 2022-07-21 05:16
@MikeMcC399 

I was only thinking about rolling back the change due to
- #5370
- #5369
- #5356
- #5350

But if these issues will all be fixed soon, rolling back the change doesn't seem necessary.

**Comment by MikeMcC399** [comment] 2022-07-21 06:12
@mtwalli 

I managed to reproduce the error. I thought it was strange that 2.24.2 was producing a PDF with the same size (676 KB) as the file produced by 2.23.2, when the correct PDFs from 2.24.2 are only 120 KB large.

The repro steps are:

1. Install 2.23.2
2. Single certificate export to Google Drive (PDF is 676 KB and good)
3. Update to 2.24.2
4. Single certificate export to Google Drive (PDF is 676 KB and unreadable)
5. Repeat single certificate export to Google Drive (PDF is 120 KB and readable)

It looks like there may be a buffer or temporary storage which is not getting cleared out after the version update.

**Comment by dsarkar** [comment] 2022-07-21 10:23
@MikeMcC399 Thanks, your findings were documented in the internal ticket.

**Comment by MikeMcC399** [comment] 2022-07-21 11:28
The issue is also reproducible upgrading from deviceForTesters-debug build 2.23.2-RC0 to the latest 2.26.0-RC0.

In 2.26.0 after exiting the "Print Version" screen, going back to the QR code then re-selecting "Display Print Version" followed by Share will clear the condition.

So the mitigation is simply to try again from the beginning. The issue should still be looked at, even though it probably will not affect many users. There is something unclean going on.

**Comment by mtwalli** [comment] 2022-08-10 15:04
@MikeMcC399 I was able to reproduce the issue, I think for end user this case won't be possible. As you mentioned already user should  stay on the preview screen of the PDF and then update app either from Android studio or using command line to push the new APK. 

BTW we clear the PDF while leaving the preview screen, in this case the event where generated PDF is cleaned  up did not get the change to execute ,because the App got killed.

I will close it as you suggested

**Closed by mtwalli** 2022-08-10 15:04 UTC
Labels: bug, mirrored-to-jira, certificates
