### ISSUE TITLE
Risk is not updating

### ISSUE THREAD

**Issue by westernheld** [corona-warn-app/cwa-app-android#697] opened 2020-06-21 09:07 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue
(Not on the first view)

## Describe the bug

For me it is shown updated: Vorgestern, 12:39
Right below it is written, that it should update Daily. Sadly i am not allowed to take a screenshot.

## Expected behaviour

Daily update
## Technical details

- Mobile device: Samsung S10
- Android version: 10

**Comment by queequac** [comment] 2020-06-21 09:16
Duplicate of #693

**Comment by westernheld** [comment] 2020-06-21 09:23
Not completely, my risk is shown as "low risk", so it did do something, but now it stopped. Thats why I opened a new issue. But maybe it is the same root cause.

**Comment by DannySchumann** [comment] 2020-06-22 06:08
Duplicate of #621

**Comment by jakobmoellersap** [comment] 2020-06-22 07:17
Hi! Thanks for your issue description. Could you check the Version of the App. There might be an update that solves the issue for you with 1.0.4

**Comment by westernheld** [comment] 2020-06-22 08:02
I guess it was 1.0.2 but PlayStore Auto-Updated it sadly tonight to 1.0.4
At least it updated today now

**Closed** 2020-06-22 08:05 UTC
Labels: bug
