### ISSUE TITLE
Statistics data outdated

### ISSUE THREAD

**Issue by jimmycd** [corona-warn-app/cwa-app-android#3075] opened 2021-05-04 20:40 UTC
All data for current infections are not updated. See screenshot.
![Screenshot_20210504-223347](https://user-images.githubusercontent.com/9625872/117066961-b2cd5e80-ad29-11eb-82de-478f7bc1388a.jpg)

**Comment by MikeMcC399** [comment] 2021-05-04 20:54
@jimmycd 

I see the date stamp of 17.04.2021 on the statistics tile. This is what you are saying is outdated. Is that correct?

How is your device connected to the Internet? Do you have a firewall on your device or between your device and the Internet? Are you on a private or a corporate network?

https://www.coronawarn.app/en/faq/#access-list gives some advice about domains to allow in firewall settings.

If that does not help, then please say which device you are using, which version of Android and which version of the CWA app.

**Comment by jimmycd** [comment] 2021-05-05 05:45
Hello, yes that was the issue. 4th of May data from 17. April.   
  
today I checked again and the information is up to date... I looked for a manual way to refresh the info but apparently there is no way (pull down, button, menu item,...)   
  
Sorry I was very short in my incident report...   
  
I am in a private network with no special settings, android device (one plus nord, android 11).
  
App version is up to date too (2.1.2) and permissions all granted permanently.   
  
Best Jürgen   
  

  

  

  
  
  
  
  
>

**Comment by MikeMcC399** [comment] 2021-05-05 05:54
Hi Jürgen @jimmycd 

If your problem is solved, you can close this issue.

There is no manual way to update the statistics. They refresh themselves periodically when an Internet network connection is available. (See also https://www.coronawarn.app/en/faq/#further_details.)

For anybody else reading this: to check the connectivity manually you can try to open https://svc90.main.px.t-online.de/version/v1/stats in a web browser and it should offer a file stats.zip to download.

**Comment by jimmycd** [comment] 2021-05-05 06:14
Hi,   
  
The question if it is solved.. I will check periodically to see if it happens again.   
  
Any idea for the root cause?   
  
Best.   
  
Jürgen   
  

  

  

  
  
  
  
>

**Comment by MikeMcC399** [comment] 2021-05-05 06:28
@jimmycd 
> Any idea for the root cause?

I'm not aware of any other similar reports, so it is most likely something in your specific environment. The root cause is probably lack of connectivity between your device and the domain svc90.main.px.t-online.de and the URL https://svc90.main.px.t-online.de/version/v1/stats. Without having a current error condition to investigate that is however just conjecture.

**Comment by MikeMcC399** [comment] 2021-05-05 06:33
@jimmycd 
Would you like to edit your title to say something like "Statistics data outdated", so that other people might find this issue if they have a similar problem?

**Comment by jimmycd** [comment] 2021-05-05 13:42
> @jimmycd
> Would you like to edit your title to say something like "Statistics data outdated", so that other people might find this issue if they have a similar problem?

done

**Comment by jimmycd** [comment] 2021-05-05 20:11
Problem occurred again. Data is from yesterday though I can download the zip from url mentioned. Even after the download no refresh triggered.
  
Or is it a feature that the data may be outdated?   
  
  

    
 Best   

  

  

  
  
  
  
  
>

**Comment by Ein-Tim** [comment] 2021-05-05 20:20
@jimmycd 

So you see "Gestern 18.034" on the first tile?

**Comment by MikeMcC399** [comment] 2021-05-05 21:18
@jimmycd 

To follow-on from what @Ein-Tim wrote, you can do a cross-check of the data on the "Confirmed New Infections" / "Bestätigte Neuinfektionen" tile with the data on the https://www.esri.de/corona dashboard. The dashboard shows yesterday's total and the complete total figures (but not the 7-day total).

---
Dashboard display
![image](https://user-images.githubusercontent.com/66998419/117209423-98ad8200-adf6-11eb-8cc5-9812fba32b46.png)

---
App display
![image](https://user-images.githubusercontent.com/66998419/117209847-37d27980-adf7-11eb-9254-d3bc9a210026.png)

---

In the past weeks the app has been updating the "Confirmed New Infections" / "Bestätigte Neuinfektionen" data somewhere around 07:00 to 08:30 and then it shows "Yesterday" / "Gestern" as datestamp for the rest of the day. From midnight to the next morning it will show the date numerically until it updates again. The RKI dashboard website typically updates earlier in the day. Sometimes you will see something like 03:00 or 05:00 as update timestamp.

So if you are seeing the datestamp "Gestern" everything is working fine. 👍🏻

**Comment by MikeMcC399** [comment] 2021-05-10 13:06
@jimmycd 
We haven't heard back from you for a few days. If your statistics are getting updated reliably on a daily basis, you may consider now closing this issue.

**Comment by MikeMcC399** [comment] 2021-11-11 10:36
@jimmycd / @dsarkar 

This issue should be closed now. Statistics are updated regularly in the Android app and this issue is more than 6 months old.

**Comment by vaubaehn** [comment] 2021-11-11 12:44
There are still some reports currently in Google Play Store though, complaining about outdated statistics.
This is just a gut feeling: are app config and diagnosis keys at the same time? For me it looks like as if these complaints are rising in times with high incidence rates...
In this case it might help to increase the timeout for the download, if it happens for affected users while on a slow/bad connection.

cc: @thomasaugsten

**Comment by MikeMcC399** [comment] 2021-11-11 12:55
@vaubaehn 

If there are still concrete problems could you give details?

Which statistics were out of date?
What date / time did this happen?

Note there was a data feed problem on the [Analysis page](https://github.com/corona-warn-app/cwa-website/issues/2024) on the web site last week (see https://github.com/corona-warn-app/cwa-website/issues/2024) which is now solved.

**Comment by jimmycd** [comment] 2021-11-11 13:07
Hi,

Looks good to me now (version 2.13.2 Android)

**Comment by MikeMcC399** [comment] 2021-11-11 13:22
Hi @jimmycd 
> Looks good to me now (version 2.13.2 Android)

I'm happy to hear that everything is well! You have the option to close the issue yourself if you access this issue via a web browser or the GitHub app.

**Comment by vaubaehn** [comment] 2021-11-11 13:52
@MikeMcC399 @dsarkar 

These are reports from 07.11.2021 until today from Google Play Store reviews.
I can only be concrete as the reports are...
(8) is the best pointer to a download problem. Experience from my phone show, that net detection ("do we have wifi or metered connection?") causes the biggest problems/delays.

11.11.2021 [(1)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOFWwFeczu68Gg_gSLlp1KPuaH1L1g93iSAIXgdf9Z588zZdbZxtDXTrrgKVclOOPrOlSK8826U_Y2igNg)
> Aktualisiert Ned steh noch beim 09.11.2021 bitte um Aktualisierung

10.11.2021 [(2)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOFg45MebPZQfbVVbAn5ofFxzQzPPydbUBkWasuQB4OadQK0fWQ3Jb4esESDv0Y4w3qCezB-z6K7BgOBsA)
> Leider funktioniert die App seit einiger Zeit nicht richtig. Obwohl die aktuelle Version 2.13.2 installiert ist, werden die aktuellen Zahlen erst mit Verzögerung angezeigt! Heute (09.11.) werden die Zahlen vom 07.11. angezeigt - nicht sehr hilfreich... Aktualisiert 10.11.'21: Es betrifft alle angezeigte Zahlen.

10.11.2021 [(3)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOGwUDXz4_556E6vFVyGII1UO8kowpoA3ckUGv90exblhoObTvVNOcDjTuUnIoK7LEdcUsBfVsON-jVuUQ) - Please see also "Bearbeitungsverlauf"
> Die Werte der Daten sind vom 19.+20.10.2021. Neustart der App und des Handys ändern nichts. Die Daten sollten die aktuellen Werte anzeigen. Leider seit Wochen nicht möglich

09.11.2021 [(4)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOH6iXfkbG4vsZYYtzqvEhimbvce6lmZJdaqPWHJAjzIPBo4UQof4o4BFo-tcL68nzfwqk5L1Hm0oM5ouw)
> War bis zum Update nicht schlecht. Seit dem 05.11. werden die Inzidenz Zahlen und Impfzahlen nicht mehr aktualisiert. Seit Ihr Tolle Programmierer. Bugs beheben und gleich neue Einbauen. Ihr wart bestimmt vorher bei KleinWeich.

08.11.2021 [(5)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOGKDl_I3sZdKg-8rhnl5EC7FX4y1PMe8UZmaSn8U_t67eKS_kOGv74b_m94t184fx4i7JGCMDQHimHXyw) - Different symptoms, but root cause could be similar
> Die "Statistikzeile" geht manchmal und manchmal nur stark verkürzt. Das ist seit mehreren Wochen so. Fragt sich nur warum?

08.11.2021 [(6)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOERlB6fOqihhxthLmrEQgY28PsmMwtk00-xsYehcmIk1dd5ZxMPFoRBHNsd1LnpjHEcr0AsPhfcHrm87w)
> Die App zeigt heute am 8.11. die Inzidenzen vom 1.10.22 oder 3.10. (Lokal und Bund).

08.11.2021 [(7)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOE4L3R5BsZtjC5LZVmgb6n7DFgRML06CkIRm-ktFP5nLEKu6gvWrlRkRJQkvURiXIucprRHuDFfH6FRaw) - This is about risk contacts, but may have the same root cause if app config + diagnosis keys have a download problem
> Ich finde ebenfalls den Dauereinsatz im Bluetooth enervierend und unnötig. Seit längerem stelle ich fest, dass der Zeitraum meiner Risikokontakte konstant ist, was mich derart irritierte, dass ich bereits einmal komplett de- und neuinstallierte. Jedoch legt sich die App weiterhin auf den 16. Sept. 2021 fest, was mir mehr als unmöglich erscheint, wenn man bedenkt, wie die Infektionszahlen gerade wieder durch die Decke gehen. Fazit: unglaubwürdig, nutzlos, wird deinstalliert!

07.11.2021 [(8)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&reviewId=gp%3AAOqpTOF23HzvopGw3mn72e6KTYN4IzfPbqxbsEfc7hPisMgn7a7Q7MLx7a9mUWJed08UI-zXZqYHecF8ru0-ng)
> Aktualisierung der Pandemieparameter seit den letzten Update bei Wlan Verbindung nur sehr sporadisch bis gar nicht. Wird Wlan abgeschaltet erfolgt die Aktualisierung sofort. Ist eigentlich das gleiche Problem die das Galaxy A6 auch mit der Nina hatte. Auch da erfolgte bei bestehender Wlan Verbindung keine Erneuerung der Daten.

**Comment by MikeMcC399** [comment] 2021-11-12 13:53
@vaubaehn 

I don't know how much we can do about these users. I assume that you cannot contact them yourself, although I guess that the support team monitoring the stores could do that.

There are no current data feed issues to the server, judging by the fact that all the data I'm seeing in my app is up to date to yesterday (which is the latest to be expected), so any issues would be between the server and other users' individual devices.

We could possibly add some troubleshooting steps to the FAQs for instance, as I mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/3075#issuecomment-832431142, basic connectivity to the server could be checked in a browser by trying to access https://svc90.main.px.t-online.de/version/v1/stats, otherwise support would probably need access to a submission of an app Error Report to look at what transmission attempts are happening.

Would you mind editing out the derogatory parts of the quotes from the store? They don't add to a technical understanding and they are against the [Code of Conduct](https://github.com/corona-warn-app/cwa-app-android/blob/main/CODE_OF_CONDUCT.md). I'm sure that these are not your opinions.

**Comment by vaubaehn** [comment] 2021-11-15 12:41
@MikeMcC399 
 
> I don't know how much we can do about these users. I assume that you cannot contact them yourself, although I guess that the support team monitoring the stores could do that.

That seems to be true.

> There are no current data feed issues to the server, judging by the fact that all the data I'm seeing in my app is up to date to yesterday (which is the latest to be expected), so any issues would be between the server and other users' individual devices.

This seems to be correct, otherwise I expected much more reports.

> We could possibly add some troubleshooting steps to the FAQs for instance, as I mentioned in [#3075 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/3075#issuecomment-832431142), basic connectivity to the server could be checked in a browser by trying to access https://svc90.main.px.t-online.de/version/v1/stats, otherwise support would probably need access to a submission of an app Error Report to look at what transmission attempts are happening.

Yes, additional troubleshooting tips for the FAQ may help in some users.
But in general I favor that devs have another deeper look (again) to evaluate how behavior of app config can be made more resilient/reliable. For me it still looks like that larger download packages for diagnosis keys and app config (due to higher incidence rates and extensions to app config) may cause timeouts and/or race conditions.

> Would you mind editing out the derogatory parts of the quotes from the store? They don't add to a technical understanding and they are against the [Code of Conduct](https://github.com/corona-warn-app/cwa-app-android/blob/main/CODE_OF_CONDUCT.md). I'm sure that these are not your opinions.

Yes, you're true - the personal opinions/attitudes in the cited reports are by far not my opinions. Following my comments here on Github you will see, that I'm taking the Code of Conduct very serious, and that my texts are friendly and constructive in general. I'm also sad about the expression of affected users in the reports that I cited. I agree that these parts of the reports do not add to a technical understanding.
However, I actually _do_ mind editing out the potentially derogatory parts in these reports for following reasons:
- They underline that users feel bothered about unreliable functionality, and it can help to evaluate which priority the project team should (re-)assign for this issue.
- Editing potentially derogatory parts would mean that I need to decide what is derogatory and what is not. Is "Fazit: unglaubwürdig, nutzlos, wird deinstalliert!" already derogatory or still an acceptable opinion? And is "Seit Ihr Tolle Programmierer. Bugs beheben und gleich neue Einbauen. Ihr wart bestimmt vorher bei KleinWeich." already a harassement? I am valuing freedom of expression/freedom of speech as one of the highest goods we have. So I do not want to be the judge who decides what is derogatory and what not in cases cited above. I do have red lines, though. But for me they have not been crossed in these citations.

Therefore I suggest that @dsarkar has a look and should decide whether and which parts should be edited.
Feel free to leave your editing suggestions for @dsarkar here.

Thanks for your understanding and have a nice day.

**Comment by MikeMcC399** [comment] 2022-03-30 15:45
There hasn't been any movement on this issue for the last 4 months. No new reports and no further investigation. The original submitter @jimmycd confirmed in https://github.com/corona-warn-app/cwa-app-android/issues/3075#issuecomment-966287807 last year that the issue was resolved for him.

I suggest to close this issue.

**Closed** 2022-04-01 07:23 UTC
Labels: bug
