### ISSUE TITLE
Error 9002 when scanning QR code

### ISSUE THREAD

**Issue by Zaelnorth** [corona-warn-app/cwa-app-android#1122] opened 2020-09-07 12:55 UTC
I'm running 1.3.0 on Xiaomi Mi 9 and the app used to work in exactly the same use-case last week without a problem.

I got tested this morning and tried to scan the QR code, but nothing happens and after a while an error 9002 appears with text: SSL Handshake Timeout.

Please help

**Comment by thomasaugsten** [comment] 2020-09-07 13:16
Did you try this in a different WiFi again?

**Comment by Zaelnorth** [comment] 2020-09-07 13:58
I wasn't on WiFi, I was on LTE (Vodafone.de via Lidl Connect MVNO). I'm on WiFi now and it works. So seems like some kind of small-time bug?!

**Comment by svengabr** [comment] 2020-09-08 09:20
Hey @Zaelnorth, thanks for your input. There is already one issue regarding 9002 and the behavior looks like the timeout issue that is already discussed here: https://github.com/corona-warn-app/cwa-app-android/issues/998

We already know that the error 9002 exists and it is currently a task with very high priority.

However, I would kindly ask you to close this issue and add your problem to the existing discussion.

Thank you very much!

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment] 2020-09-08 09:20
Duplicate of #998

**Closed** 2020-09-08 09:41 UTC
Labels: duplicate

**Comment by vaubaehn** [comment] 2020-09-21 21:06
Related to #1188 
EXPOSUREAPP-2784
