### ISSUE TITLE
Risk display wrongly show low risk for a few seconds before changing

### ISSUE THREAD

**Issue by simon-anders** [corona-warn-app/cwa-app-android#1185] opened 2020-09-19 12:47 UTC
A few days ago, i got an exposure notification.

Now, when I open the app, the following happens:

- a green screen,  entitled "low risk" is shown (screenshot 1), with a wrong notification of "no exposures" according to an update "yesterday" -- even though yesterday's update already showed the exposures.

- after a few seconds, the screen switches to red (screenshot 2), showing the same update time stamp, but now notifying me of 2 exposures.

Obviously, a user who only briefly looks at the app will only see the green screen and get a wrong all-clear.

Frequency: seems to happen only the first time of opening the app per day

Version: 1.3.0

Android version: EMUI 9.1.0 on Huawei ANE-LX1

# Screenshot 1:
![Screenshot_20200919_110044_de rki coronawarnapp](https://user-images.githubusercontent.com/12886712/93667530-e56e6380-fa86-11ea-8c38-1d451335b039.jpg)

# Screenshot 2:
![Screenshot_20200919_110048_de rki coronawarnapp](https://user-images.githubusercontent.com/12886712/93667542-ffa84180-fa86-11ea-8fe2-b6d4c7bb7f98.jpg)

----
Internal Tracking ID: EXPOSUREAPP-2873, EXPOSUREAPP-2270

**Comment by thomasaugsten** [comment] 2020-09-19 12:50
Hi can you provide the export of the exposure log in the Android exposure notification settings?

**Comment by simon-anders** [comment] 2020-09-19 13:23
Exposure check log:
https://drive.google.com/file/d/1iFhnnksCH6KOurmpUXheZtYBoK-N0UdI/view?usp=drivesdk

**Comment by akuckartz** [comment] 2020-09-19 13:44
I had similar effects when I had "Low Risk" encounters. The displayed nummer was changing about half a second after the Initial display whenever I opened the app.

**Comment by daimpi** [comment] 2020-09-19 15:28
@simon-anders 
> seems to happen only the first time of opening the app per day

Looking at your ENF log and your screenshots, it looks like the update today happened exactly when you opened CWA at 11:00. This might explain why it took a few seconds to update to screen 2 (but it doesn't explain why screen 1 was green in the first place). Probably when you open your app now, it shows you "Updated: Today, 11:00" with two matches and a red screen immediately, right?

Looking further into your log it seems that the timestamps when an update was performed are all over the place in general. This could indicate, that automatic background updates are [not working properly](https://github.com/corona-warn-app/cwa-app-android/issues/933) on your phone and the updates therefore only happen once you open CWA manually.

Does it sound plausible to you that you might have manually opened CWA in the past few days at the following times?

Date | Time
--     | --
19.9.2020 | 11:00
18.9.2020 | 13:03
17.9.2020 | 02:45
16.9.2020 | 13:15
15.9.2020 | 12:20
14.9.2020 | 16:12

Btw: do you have "Prioritized Background Activity" enabled in your CWA settings?

**Comment by simon-anders** [comment] 2020-09-19 15:35
Yes, that might be plausible.
And, yes, "prioritized background activity" is on, and "battery optimization" i "not allowed" for CWA

**Comment by daimpi** [comment] 2020-09-19 16:05
@simon-anders 
Ok, thanks for the info 🙂. 

This means it's quite plausible that background updates are indeed not working properly on your device in which case your problem might be related to what @vaubaehn laid out [here](https://github.com/corona-warn-app/cwa-app-android/issues/1081#issuecomment-693335476): 
> **1) The mainView/risk card is not completely refreshed, when**
> 
>   - the automatic background update has not been carried out for the current day, and
> 
>   - CWA is openend by the user, and
> 
>   - the diagnostic keys are exchanged in the background at the same time.
> 
> 
> In this case @Jo-Achim can see the message "Risiko-Ermittlung nicht möglich, Risiko-Ermittlung einschalten", even the update succeeded. In my case, I see a green risk card, showing last update was done yesterday.
> When you then navigate to a different screen/view, no matter whether inside or outside CWA, on return/onResume, the mainView is refreshed, and the correct status is displayed in the risk card.
> 
> **Possible fix:**
> 
>   - Take care, that risk card shows "updating", when ProvideDiagnosisKeys is called during a foreground process.
> 
>   - Make sure, that on receiving broadcast [Action_Exposure_State_Updated](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#public-static-final-string-action_exposure_state_updated) app is in foreground, mainView is active, and refresh the view.
> 
>   - If the above listener is not sufficient, additionally create a listener for [Action_Exposure_Not_Found](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#public-static-final-string-action_exposure_not_found) (as far as I could see from the code, no listener is set yet.) and refresh view on retrieval.

And the act of taking the screenshots (which usually involves a context switch) might have been enough to trigger a screen update subsequently.

Not sure why your screen 1 is green though, as your app already showed a red screen yesterday 🤷. 

If you want to test something: maybe tomorrow you could try to open CWA and don't interact with your phone afterwards (except for preventing screensaver) for ~1 min and check whether your app stays stuck on screen 1 for this time?

Btw: what is the behavior if you open the app now i.e. after today's update has been performed?

**Comment by heinezen** [comment] 2020-09-24 19:10
@simon-anders Thank you for reporting the issue. We have created an internal Jira ticket (EXPOSUREAPP-2873) for the bug. If there are any updates on the status of the bug, you will get notified here.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by GPclips** [comment] 2020-09-29 12:07
This issue has been marked as obsolete and will be closed now.

**Comment by daimpi** [comment] 2020-09-29 12:23
@GPclips 
> This issue has been marked as obsolete and will be closed now.

Could you elaborate on why this has been marked as "obsolete"? Has this issue been fixed and if so could you kindly provide a link? 🙂

**Comment by GPclips** [comment] 2020-09-29 15:20
Hello @daimpi ,

I just checked and the issue now will be tracked in the following item: EXPOSUREAPP-2270. This one is still in the status analyzing. I will go on and update the task.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-03-09 14:54
Hello everyone,

We cannot reproduce this anymore in the latest CWA versions. The issue last occured in CWA 1.7 for us. This means that the problem should hopefully be gone for everyone. We will therefore close this issue.

If you are still experiencing this problem, please make a comment in this thread.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-03-09 14:54 UTC
Labels: bug, mirrored-to-jira
