### ISSUE TITLE
Risk assessment does not work.

### ISSUE THREAD

**Issue by sabrinaspiess** [corona-warn-app/cwa-app-android#755] opened 2020-06-25 22:50 UTC
Error message: ENErrorDomain 5

What does this message mean, I am using an IPhone 7. 

![FD5B1976-A9D3-4EE3-9D05-62F886F63239](https://user-images.githubusercontent.com/67443383/85803233-fb4de000-b746-11ea-92da-c5d1fb5ba4eb.png)
The` app worked fine for 3 days until the error occurred.

**Comment by tegutistgut** [comment] 2020-06-26 07:27
Das ist die iOS App. Das musst du hier melden:  https://github.com/corona-warn-app/cwa-app-ios

**Comment by jakobmoellersap** [comment] 2020-06-26 09:07
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/766

**Closed by jakobmoellersap** 2020-06-26 09:07 UTC
Labels: bug
