### ISSUE TITLE
App on playstore is region locked preventing expats from downloading. Solution -> host compiled APK link in official github page 

### ISSUE THREAD

**Issue by reisepass** [corona-warn-app/cwa-app-android#498] opened 2020-06-16 08:11 UTC
## Your Question

* Source File:
* Line(s):
* Question:
A significant number of people residing in Germany do not have their google account registered to Germany. There can be many reasons for this :  subscription payments linked to previous country, other  apps region locked to their home countries, or simply because there is a limit on how often you can switch your google accounts location.  Reducing the number of people who can install the app artificially unnecessarily reduces effectiveness of the system. 

Possible short term solution  :  Host the compiled APK here on the trusted github account for anyone to download. 
Suggested long term solution :  Remove region lock in the play store (and possibly also apple store but I can not verify the situation there).

**Comment by tomjschwanke** [comment] 2020-06-16 08:16
Duplicate of #478

**Closed** 2020-06-16 09:32 UTC
Labels: question

**Comment by corneliusroemer** [comment] 2020-06-16 09:47
Well I don't think it's an exact duplicate. The problem is the same, but this can be viewed as an enhancement request. I would reopen it @reisepass 

I have a similar request, extending to pre-release versions for beta testing.
#514 #477
