### ISSUE TITLE
Upload App as Appbundle to Google Play Store to reduce download and final app size

### ISSUE THREAD

**Issue by Hgamo** [corona-warn-app/cwa-app-android#2808] opened 2021-04-12 12:35 UTC
## Current Implementation
At the moment the app is uploaded as normal APK files to the Play Store.

## Suggested Enhancement
Submit the app as Appbundle to the Play Store to reduce download and final app size.

## Expected Benefits
- Smaller download size (form approximately 25 Mb to 15 Mb)
- Faster download time on slower internet connections
- Users with limited storage space on their device can uninstall larger apps to free up storage space. Google Play also takes app size into account when the service suggests users uninstall apps to make room for other apps.

---
Internal Tracking ID: [EXPOSUREAPP-6379](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6379)
Internal Tracking ID: [EXPOSUREAPP-3400](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3400)

**Comment by MikeMcC399** [comment] 2021-04-12 12:57
@Hgamo 

You might be interested in an open community PR "Use vector drawables support library (COMMUNITY)" https://github.com/corona-warn-app/cwa-app-android/pull/2800 which could also reduce the app size.

**Comment by Hgamo** [comment] 2021-04-12 13:53
> @Hgamo
> 
> You might be interested in an open community PR "Use vector drawables support library (COMMUNITY)" #2800 which could also reduce the app size.

Thank you, I saw the PR "Use vector drawables support library (COMMUNITY)" #2800 already.
But I think that using an appbundle is a way which requires no code changes and therefore a smaller risk to break the app. It also allows further optimizations by google and as mention in [this article](https://android-developers.googleblog.com/2020/08/recent-android-app-bundle-improvements.html) appbundle are necessary later   this year.

**Comment by dsarkar** [comment] 2021-04-12 14:05
@Hgamo Thanks for the proposal. Internal Tracking ID: EXPOSUREAPP-6379

---
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment] 2021-04-14 14:59
Using Android App Bundles (AAB) requires the developer of the app to upload their private signing key to Google ([ref](https://medium.com/google-developer-experts/exploring-google-play-app-signing-b4d296f4ee9)), for pretty much no reason (as it would also be possible to generate all possible APKs and to sign them locally). This is to be seen very critically, as there's no good reason for Google to have access to this key.


This is technically a duplicate of #606.

**Comment by dsarkar** [comment] 2021-04-14 15:03
@fynngodau Thanks for the comment, we will add it to the internal ticket.

**Comment by jlnprssnr** [comment] 2021-04-16 06:54
The mentioned ticket #606 was closed in favor of #482, which was then closed as won't do. We're moving in circles here

**Comment by MikeMcC399** [comment] 2021-05-03 17:52
@Hgamo 

> ... It also allows further optimizations by google and as mention in [this article](https://android-developers.googleblog.com/2020/08/recent-android-app-bundle-improvements.html) appbundles are necessary later this year

The article says: "we intend to require new apps and games to publish with the Android App Bundle on Google Play in the second half of 2021." Do you think that the Corona-Warn-App would be classed as a new app although it was released in June 2020?

CWA Android 2.1.2 is showing on Google Play Store https://play.google.com/store/apps/details?id=de.rki.coronawarnapp with size 16M so a significant size reduction has already been achieved, due to https://github.com/corona-warn-app/cwa-app-android/pull/2800 from @fynngodau. 👍🏻 

Do you know what further reduction could be achieved if [Android App Bundle](https://developer.android.com/platform/technology/app-bundle) would be applied on top of the current release?

**Comment by heinezen** [comment] 2021-07-22 21:12
Hello everyone,

This feature has been declined for the same reasons as listed in https://github.com/corona-warn-app/cwa-app-android/issues/482#issuecomment-793979607

> The development team has decided to not pursue the matter of size reduction further. Reasons are that
> * the size of the app is still relatively small compared to other apps
> * the decreased size is not worth the effort that would have to be put in by the dev team

We will therefore close this issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-07-22 21:12 UTC
Labels: declined, enhancement, mirrored-to-jira
