### ISSUE TITLE
Make it easier to get and use the App to see test results on devices were it can't warn.

### ISSUE THREAD

**Issue by spth** [corona-warn-app/cwa-app-android#1587] opened 2020-11-12 16:08 UTC
My only smartphone runs on LineageOS.

It seems those responsible for the App still just see it as a contact-tracing tool. But the reality is that for many people it also is the only way to see their test results. Even people that do not use a Google or Apple account should be allowed to see their tests results.

On Saturday morning, I did a test at the Koblenz test center. On the forms and in person, I told them that I do not have a phone on which the Corona App works. I gave them my telephone number and email address. They never contacted me about the result. I also wrote an email to the Gesundheitsamt there asking about my result, but did not get a reply.

In the end I was able to see my result, but it wasn't obvious:

* Install the App in a complicated way (installed Aurora Store via F-Droid (had to make some settings changes since the Aurora default tokenizer is down), then the Corona App via Aurora store) since it is not available on F-Droid and no apk is available.
* Launch the app and click through many error messages about the app not working due to missing services. And finally get through to the scan functionality. Which apparently worked and showed me my test result.

**Comment by heinezen** [comment] 2020-11-12 16:53
Hey @spth ,

Thanks for sharing you experience. I think a better place to discuss this is https://github.com/corona-warn-app/cwa-wishlist/issues/192 which is the feature request for Lineage OS support and also a place to discuss how to get the app to run. Therefore please continue the discussion there and upvote the issue for extra visibility. I will close your issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-11-12 16:53
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/192

**Closed by heinezen** 2020-11-12 16:53 UTC
Labels: enhancement

**Comment by rugk** [comment] 2020-11-12 16:59
Interesting case, but TBH it's a problem of the process at that testing center. They should certainly not require a smartphone at all to see a test result - though that would nudge people into actually scanning and submitting the result in the app, but anyway...
That said, as for https://github.com/corona-warn-app/cwa-app-android/issues/1483#issuecomment-726180515 it's still a good argument, because well.... as we see such cases can happen. 🙂
