### ISSUE TITLE
[Add] more Information about Contacts

### ISSUE THREAD

**Issue by thomas-repo** [corona-warn-app/cwa-app-android#671] opened 2020-06-19 13:46 UTC
Hi, thanks up and for all for this nice app.

I would like to ask if it is possible to add to the main-screen some verbose information about the actual tracking.
For example, number of meet beacons/contacts or even allow extended access to the list of beacons and the distance and time which was logged by the app. 
Therefore some private evaluation of the data would be possible without messing with the app itself.

Thanks in advance, greetings
Thomas

**Comment by realansgar** [comment] 2020-06-19 13:54
Duplicate of #518, https://github.com/corona-warn-app/cwa-documentation/issues/270 and more. Refer to https://github.com/corona-warn-app/cwa-documentation/issues/270 for future discussion of this.

**Comment by agowa338** [comment] 2020-06-21 02:25
>Therefore some private evaluation of the data would be possible

This is exactly why google limits access to the api and does not allow the full list to be accessed.
This would allow you to identify all other users you're having contact with...

**Comment by tkowark** [comment] 2020-06-22 09:32
Yes, this is indeed a duplicate, but the main discussion issue has now been moved to the wishlist: corona-warn-app/cwa-wishlist#5

**Closed by tkowark** 2020-06-22 09:32 UTC
Labels: feature request
