### ISSUE TITLE
App not updating and showing several "ENErrorDomain-Fehler 5" dialogs 

### ISSUE THREAD

**Issue by Frintrop** [corona-warn-app/cwa-app-android#758] opened 2020-06-26 12:23 UTC
## Avoid duplicates
* [ X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ X] Bug is not already reported in another issue

## Describe the bug

After starting or reopening the app several "ENErrorDomain-Fehler 5" dialogs appear. Reproducable after closing and restarting the app.
App is not refreshing it´s update date. Last update was before 2 das.

## Expected behaviour

No error dialog and updating status.

## Steps to reproduce the issue

Start app. 3-5 error dialogs appearing  "ENErrorDomain-Fehler 5" 

## Technical details

- Mobile device: iphone xs, latest updates.
-

**Comment by jakobmoellersap** [comment] 2020-06-26 12:35
Duplicate of corona-warn-app/cwa-app-ios#766

**Closed by jakobmoellersap** 2020-06-26 12:35 UTC
Labels: bug
