### ISSUE TITLE
Error 9002 on startup

### ISSUE THREAD

**Issue by JoTheHannes** [corona-warn-app/cwa-app-android#731] opened 2020-06-23 20:10 UTC
## Describe the bug

After 1-2 days of usage, app closes immediately when opened. If app stays open or can be opened after multiple attempts, app is in the mode when first opened with setup assistant. After stepping through the assistant when authorizing “Risiko-Ermittlung aktivieren" error 9002 is displayed:
File is not a database, while compiling: select count(*) from sqlite_master;

App will only work when local app data and cache is deleted. Restarting the phone is not necessary but will not prevent future failures. 

## Expected behaviour

App continue to monitor my exposure to Sars-Covid-2

## Steps to reproduce the issue

See above. 
Huawei power saving options for this app were all set to be managed manually. 

## Technical details

- Mobile device: Huawei P20 Pro CLT-L29
- Android version: 8.1.0

## Possible Fix
Manual power options in Huawei battery settings were already alll set to manual. 

Deleting the app data and cache or restarting the phone do not prevent the error to reoccur after 1-2 days.

**Comment by jakobmoellersap** [comment] 2020-06-24 06:50
Duplicate of #642

**Closed by jakobmoellersap** 2020-06-24 06:50 UTC
Labels: bug

**Comment by vaubaehn** [comment] 2020-08-13 12:02
Hi @JoTheHannes  , it's quite a while since you reported this bug:
**"Ursache 9002 - File is not a database: ,while compiling: select count (*) from sqlite_master;"**

As far as I know, the root source for this exception is not known yet.
I came across the information, that the problem often occurs with Huawai and Honor devices.
One similar feauture of many of these devices is the PrivateSpace feature (Huawai/Honor specific privacy app & data storage container; see [here](https://consumer.huawei.com/de/support/content/de-de00746116/), [here](https://consumer.huawei.com/de/support/content/de-de00722628/), [here](https://www.giga.de/smartphones/huawei-mate-9/specials/top-10-tipps-zur-emui-5.0/page/2/), or [here](https://www.honornews.de/tweaks/privatespace-fur-mehr-privatsphaere/)).

Did you ever use or ever enable PrivateSpace for your phone, or might it have been preconfigured to be active when you bought it?

Are you still using CWA, with the newest version 1.2.0? If yes, is the error still persisting for you? Or is it gone?

A reply to these questions may help to get an idea, if PrivateSpace might be related to the issue you experienced.

Thanks very much in advance, kind regards,
V.
