### ISSUE TITLE
Data retrieval tile and result tile are shown simultaneously

### ISSUE THREAD

**Issue by not-a-feature** [corona-warn-app/cwa-app-android#1063] opened 2020-08-22 09:22 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

On the main page of the app the tile "Data retrieval" is displayed, although the data retrieval of the test was already done and is successfully displayed. It is to note that this bug does not occur every time. Sometimes the retrieving tile is only shown for a few milliseconds.

<img src="https://user-images.githubusercontent.com/25013642/90952928-b6ed7080-e467-11ea-80e9-6aa82e94ba35.png" height=500></img>

## Expected behaviour

The second tile should not be visible.

## Steps to reproduce the issue

1) Open the App
2) Add a test via QR-Code
3) Wait until the result is available (in my case only 4h :partying_face: )
4) View the Result
5) Close the App
6) Reopen it
7) The result tile and the data retrieval tile are shown simultaneously.
    It is to note that this bug does not occur every time. Sometimes the retrieving tile is only shown for a few milliseconds.

## Technical details

- Mobile device: Motorola Moto G7 play
- Android version: 10
- CWA: 1.2.1
- ENF Version: 16203302004

**Comment by abro1i** [comment] 2020-08-27 14:00
Duplicated by https://github.com/corona-warn-app/cwa-app-android/issues/1084

**Comment by abro1i** [comment] 2020-08-27 14:01
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1084

**Comment by abro1i** [comment] 2020-08-27 14:04
Hi @not-a-feature,

thanks for your feedback. Theres another issue regarding this problem.

Lets continue discussing this issue here: https://github.com/corona-warn-app/cwa-app-android/issues/1084

Best regards, 

ABB 

Corona-Warn-App Open Source Team

**Closed by abro1i** 2020-08-27 14:04 UTC
Labels: bug
