### ISSUE TITLE
Visualize numbers of contacts 

### ISSUE THREAD

**Issue by gehlsdorf** [corona-warn-app/cwa-app-android#721] opened 2020-06-17 06:49 UTC
## Feature 

I’d like to be able to see in the app how many contacts my app/phone has been in contact with.

**Comment by ironjan** [comment] 2020-06-23 09:19
@daniel-eder This issue is most likely a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/689 and conseuently a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/5

**Comment by daniel-eder** [comment] 2020-06-23 10:07
Thank you @ironjan that is indeed a duplicate. I will close this issue, please refer to corona-warn-app/cwa-wishlist#5 for a discussion of this topic.

**Closed by daniel-eder** 2020-06-23 10:07 UTC
