### ISSUE TITLE
[HELP WANTED][README] Text / Translations 

### ISSUE THREAD

**Issue by marcmuschko** [corona-warn-app/cwa-app-android#332] opened 2020-06-10 08:30 UTC
Dear contributers,

as we are getting into the final stage regarding all texts and translations within the app, we would appreciate your support in this area!
If you spot anything unsual within the German / English text files, **please report your findings as a comment in this issue.**

Since the texts and translations are not provided by the development team but by a dedicated stream and have to be approved by the stakeholders first (depending on the change), it is easier for the stream to check this issue for findings and provide fixes when necessary. 
Please don't create pull requests directly, the string files will be overwritten when we import changes from our translation stream.

**Edited (after we noticed several findings within legal texts and we aspire to be as transparent as possible):**
Please be aware that all legal texts including their translations (Terms of Use, Publication Details, Data Privacy Information, Legal Notices) are handled separately, 
Neither developers nor the text / translation stream have any influence on spelling or wording, as these texts require dedicated approval. 
We will certainly collect your suggestions and pass them on, but it can take time until improvements are included (if at all).

Thank you for your your help! 
Best regards,
Marc

**Comment by marcmuschko** [comment] 2020-06-10 08:33
Referencing [findings](https://github.com/corona-warn-app/cwa-app-android/issues/72#issuecomment-641032935) from issue #72

**Comment by mh-** [comment] 2020-06-10 11:15
[Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf):
"..., versendet Ihr Smartphone per Bluetooth Low Energy kontinuierlich zufallsgenerierte Kennnummern, auch als Zufallscodes **zu** bezeichnet" - remove the word "zu"

**Comment by mh-** [comment] 2020-06-10 11:27
Link to Privacy Notice in [Terms](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/assets/terms_de.html) does not work: 
```
Die separate Datenschutzerklärung (siehe <strong>[<em>Link</em>]</strong>) ist
Bestandteil dieser Nutzungsbedingungen. 
```

**Comment by bocops** [comment] 2020-06-10 11:52
The abbreviation "CWA" is only used once in user-facing strings, in 

`<string name="main_overview_body_glossary_keys">"Die Zufallscodes sind zufällig erzeugte Zahlen- und Buchstabenkombinationen. Sie werden zwischen benachbarten Smartphones ausgetauscht. Zufallskennungen lassen sich nicht einer bestimmten Person zuordnen und werden nach 14 Tagen automatisch gelöscht. Eine Corona-positiv getestete Person kann ihre Zufallscodes der letzten bis zu 14 Tage freiwillig mit anderen CWA-Nutzern teilen."</string>`

Unexplained abbrevations can be confusing.

**Suggestion:** change last part to "[...] freiwillig mit anderen Nutzern der Corona-Warn-App teilen."

**Comment by dadosch** [comment] 2020-06-11 09:22
`    <string name="risk_card_body_tracing_off">"Aktivieren Sie die Risiko-Ermittlung, um Ihre heutige Risikostatus zu berechnen."</string>`

`heutige` should be `heutigen`

**Comment by jschleus** [comment] 2020-06-11 10:20
As the project is entering the final phase, I would like to point out that similar to the description in the issue [cwa-app-ios#149](https://github.com/corona-warn-app/cwa-app-ios/issues/149) there exists on the FOSS server [fossies.org](https://fossies.org) also a regularly updated [codespell](https://github.com/codespell-project/codespell) [report](https://fossies.org/features.html#codespell) for "cwa-app-android":

&nbsp;&nbsp;https://fossies.org/linux/test/cwa-app-android/codespell.html

That analysis checks not only the user visible output strings but also the code itself and according comments. But it is simply dictionary based (English only) and just word oriented.

Only few errors were found (the word `tage` wasn't yet excluded as a FP since it seems a German spelling error -> `Tage`).

By the way, skimming manually over the file [Corona-Warn-App/src/main/res/values/strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values/strings.xml) I found German misspellings, missing spaces and sometimes vowels in place of the expected mutated vowels ("umlauts"). But all that errors are corrected in the corresponding German specific file [Corona-Warn-App/src/main/res/values-de/strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values-de/strings.xml)  (that seems to have still much more `ihre` -> `Ihre` errors than those already mentioned in the previous comment).

**Comment by jenderny** [comment] 2020-06-11 22:25
The error dialogue that pops up when someone has entered an invalid or already used QR code or TAN tells the user where to find the the hotline (`App-Informationen → Technische Hotline`).
The user might have problems to find this information, because it's a little hidden in a submenu on another page.
For better user experience the dialogue should get an additional button that links directly to the page `Technische Hotline`.

The dialogue text could than be shortened to

`Der QR-Code / Die TAN ist ungültig oder wurde schon verwendet. Bitte versuchen Sie es erneut oder kontaktieren Sie die technische Hotline.`
with the buttons
`Zur technischen Hotline`                `Zurück`

**Comment by mlenkeit** [comment] 2020-06-12 05:45
https://github.com/corona-warn-app/cwa-app-android/blob/cd6d6af76f06da6a56962fe2217b4ec036997536/Corona-Warn-App/src/main/res/values-de/strings.xml#L638
should be "[...] in **dem** Rahmen [...]" unless there are multiple "Rahmen"

**Comment by julianw10** [comment] 2020-06-12 14:09
https://github.com/corona-warn-app/cwa-app-android/blob/970e8b859cff3c8beeca83ac83e9ed534927107a/Corona-Warn-App/src/main/res/values-de/strings.xml#L358

- [ ] The colon in 
"Der Aktivierung der Risiko-Ermittlung und der damit im Zusammenhang stehenden Datenverarbeitung stimmen Sie mit Antippen des Buttons: Risiko-Ermittlung aktivieren zu." 
doesn't really fit to the sentence in my opinion, quotation marks could be better: 
"Der Aktivierung [...] stimmen Sie mit Antippen des Buttons „Risiko-Ermittlung aktivieren" zu "

- Um die Risiko-Ermittlung nutzen zu können müssen Sie zudem auf Ihrem Smartphone die von Google bereitgestellte Kontaktaufzeichnungs-Funktion „Benachrichtigungen zu möglicher Begegnung mit COVID-19-Infizierten“ aktivieren und für die Corona-Warn-App freigeben."
missing comma after "Um die Risiko-Ermittlung nutzen zu können"

**Comment by JeWe94** [comment] 2020-06-12 19:57
https://github.com/corona-warn-app/cwa-app-android/blob/970e8b859cff3c8beeca83ac83e9ed534927107a/Corona-Warn-App/src/main/res/values-en/strings.xml#L358

The String "onboarding_tracing_body_consent" is missing its English translation. In the iOS App it already seems to be translated:
https://github.com/corona-warn-app/cwa-app-ios/blob/9b7601e37009c0baafeaea90d197a277e3b9d632/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L189

**Comment by jkoendev** [comment] 2020-06-12 21:01
> 
> 
>     * [ ]  Dativ: should be "[...] in **dem** Rahmen [...]" unless there are multiple "Rahmen"
>       https://github.com/corona-warn-app/cwa-app-android/blob/cd6d6af76f06da6a56962fe2217b4ec036997536/Corona-Warn-App/src/main/res/values-de/strings.xml#L638

innerhalb des Rahmens?

**Comment by sschuett** [comment] 2020-06-15 20:44
<string name="onboarding_body">"Machen Sie Ihr Smartphone zum Corona-Warn-System. Überblicken Sie Ihren Risikostatus und erfahren Sie, ob in den letzten 14 Tagen Corona-positiv getestete Personen in Ihrer Nähe waren."</string>

(should be "in **I**hrer Nähe" instead of "in **i**hrer Nähe")

**Comment by timoguentner** [comment] 2020-06-16 06:42
In terms_de.html:

> Sie besagt lediglich, dass sie während der letzten 14 Tage eine [...]

Should be: "Sie besagt lediglich, dass Sie während der letzten 14 Tage eine [...]"

> Bitte prüfen Sie in den Einstellungen ihres Endgeräts, ob diese Funktionen

Should be: "Bitte prüfen Sie in den Einstellungen Ihres Endgeräts, ob diese Funktionen"

**Comment by Bananeweizen** [comment] 2020-06-16 07:43
German translation uses "nun" 2 times in the introduction for things that will happen in the future. The introduction says

> ...Personen...erhalten **nun** eine Warnung...

which can easily be misread as "an alert is sent right now". Just replace "nun" by "dann" to avoid the confusion.

Affected lines:
https://github.com/corona-warn-app/cwa-app-android/blob/c3416440e644a918f4001489de85f203c7681099/Corona-Warn-App/src/main/res/values-de/strings.xml#L386
https://github.com/corona-warn-app/cwa-app-android/blob/c3416440e644a918f4001489de85f203c7681099/Corona-Warn-App/src/main/res/values-de/strings.xml#L388

**Comment by fusselkater** [comment] 2020-06-16 08:55
The text "Wurden Sie getestet?" should be something like "Wurden Sie positiv getestet?", I was wondering if I have to send my negative test result.

**Comment by julianw10** [comment] 2020-06-16 09:11
> The text "Wurden Sie getestet?" should be something like "Wurden Sie positiv getestet?", I was wondering if I have to send my negative test result.

Maybe you _should_ share your test result regardless of its result

**Comment by fusselkater** [comment] 2020-06-16 10:00
> > The text "Wurden Sie getestet?" should be something like "Wurden Sie positiv getestet?", I was wondering if I have to send my negative test result.
> 
> You probably _should_ share your test result regardless of its result

That makes no sense and would block resources on the hotline

**Comment by FWCologne** [comment] 2020-06-16 10:20
Concerning my pull request mentioned above: in Corona-Warn-App/src/main/assets/terms_de.html it says in line 462

> Bitte prüfen Sie in den Einstellungen ihres Endgeräts, ob diese Funktionen aktiviert und für die Verwendung der App freigegeben sind.

"ihres" should start with a capital "I".

**Comment by bartim** [comment] 2020-06-16 10:55
In your data privacy policy, you write "*Den Datenschutzbeauftragten des RKI erreichen Sie unter der oben genannten Anschrift (zu Händen "Behördlicher Datenschutzbeauftragter") und per E-Mail an: datenschutz@rki.de)*"

That second closing bracket does not match.

**Comment by orrc** [comment] 2020-06-16 10:56
While installing the app, I noticed this slight inconsistency in the onboarding flow.

There's a big button called "Activate Exposure Logging", however the text above refers to it as simply the "Enable" button:
> By tapping on the “Enable” button, you agree to …

https://github.com/corona-warn-app/cwa-app-android/blob/c3416440e644a918f4001489de85f203c7681099/Corona-Warn-App/src/main/res/values/strings.xml#L365-L368

The German version looks fine (i.e. the body text and button title match).

**Comment by nohn** [comment] 2020-06-16 11:08
Clarify "Mundschutz". Should be "Mund-Nasen-Schutz".

**Comment by designrDevelopr** [comment] 2020-06-16 11:43
When copying text from a PDF into a text editor, ü gets copied as ü, which looks the same in most font faces, but is a u and ¨.
In the text editor this is indistinguishable, but in the webfont, it is displayed wrong (can’t attach screenshot, due to screenshot-restrictions).
There are 14 occurences of ü in the strings.xml (13 lowercase, 1 uppercase)
https://github.com/corona-warn-app/cwa-app-android/compare/master...designrDevelopr:patch-1#diff-401494227159003b37a3e9f24a5b2d78

**Comment by Umar0th** [comment] 2020-06-16 12:54
The "wir" in
https://github.com/corona-warn-app/cwa-app-android/blob/cacf64a4611c37bb062e7ee4d08822f9ba9d2662/Corona-Warn-App/src/main/res/values-de/strings.xml#L165
and
https://github.com/corona-warn-app/cwa-app-android/blob/cacf64a4611c37bb062e7ee4d08822f9ba9d2662/Corona-Warn-App/src/main/res/values-de/strings.xml#L299
suggests that the risk isn't calculated on the device but somewhere else. I think this should be changed to something like
"... konnte für Sie kein Infektionsrisiko berechnet werden."

**Comment by opatut** [comment] 2020-06-16 13:44
I have to say, this app contains *mostly* gender neutral and inclusive language, which is refreshing and suprising. Thank you!

Looking through it, I just found a few more things that need adjustment.

1. The following translation strings contain only masculine form of certain nouns or pronouns referencing people in the german translation texts (mainly "Nutzer", "sein"):

* `main_overview_body_glossary_keys`
* `onboarding_tracing_body_consent`
* `submission_positive_other_warning_privacy_body`

I understand that some of these are legal texts, which may take longer to process and that process might already be underway. If not, please consider changing those as well.

Note: The first key (main_overview_body_glossary_keys) was referenced [in a comment above](https://github.com/corona-warn-app/cwa-app-android/issues/332#issuecomment-641952009) because it contains an abbreviation that is not referenced or explained. Make sure to apply gender neutral language to the suggested change in that comment as well :)

2. Some descriptions of illustrations use the words "Mann" and "Frau" or "sein" to reference humans in the picture. While those people may be drawn in a stereotypically male or female way, it is not generally possible to link people's gender or sex to their appearance. It is therefore not required to reference them in the caption as such, and doing so instead propagates the wrong assumption that third persons could perform such assignments. "Eine Person" would be a sufficient description of the characters in the illustrations:

* `submission_done_illustration_description`
* `information_contact_illustration_description`
* `main_share_illustration_description`
* `onboarding_privacy_illustration_description`
* `onboarding_notifications_illustration_description`
* `settings_notifications_illustration_description_active`
* `settings_notifications_illustration_description_inactive`
* `information_privacy_illustration_description`

**Comment by mh-** [comment] 2020-06-17 13:24
I think that English translation "Exposure Logging" for "Risiko-Ermittlung" is very problematic.
The problem is that the user will think that by disabling "Logging", the data collection of the mobile device is stopped. 
But it is not, only the efforts of the app to estimate risk are stopped.
This should rather be translated by "Risk Estimation".

**Comment by ironjan** [comment] 2020-06-18 11:15
Phone in English.

1. Go to "app information" - "publication details"

"Telefon" under "Contact" has not been translated. As most texts on this screen are translated, I expected this one too.

The same is true for "vertreten durch den Präsidenten" in "Published by". However, this could potentially be explained by legal requirements.

Affected lines:
 *  https://github.com/corona-warn-app/cwa-app-android/blob/4e20ee89ea5c7bfab37abffd50b48b2ce78bf00b/Corona-Warn-App/src/main/res/values-en/strings.xml#L580
 * https://github.com/corona-warn-app/cwa-app-android/blob/4e20ee89ea5c7bfab37abffd50b48b2ce78bf00b/Corona-Warn-App/src/main/res/values-en/strings.xml#L584

**Comment by bersbersbers** [comment] 2020-06-19 06:36
> Clarify "Mundschutz". Should be "Mund-Nasen-Schutz".

Consider "Munde-Nasen-Bedeckung, compare https://github.com/corona-warn-app/cwa-app-android/issues/618#issuecomment-645774002

**Comment by mlaue-tech** [comment] 2020-06-19 09:44
`   <string name="submission_dispatcher_qr_card_text">"Registrieren Sie Ihren Test, indem Sie den QR-Code ihres Test-Dokuments scannen."</string>
`
Should be:
Registrieren Sie Ihren Test, indem Sie den QR-Code **Ihres** Test-Dokuments scannen.

The "I" in "ihres" should be in capital letters.

**Comment by nicktar** [comment] 2020-06-19 17:59
From #672:

For an exposure to show up in the app there is a couple of additional requirements that don't change the risk of an infection like the infected needs to use the app, has to be tested and has to share the test results. While the numbers will hopefully improve, this gives an estimated probability of an exposure to show up in the app of currently below 10%. Stating "no exposures" might lead to the wrong conclusion of "the app told me I'm not infected" and probably reduced safety measured because of that.

Proposed change of wording "No known up to now" => "No known exposures up to now"

And from #640 
"Low Risk" in home screen suggest that the app can guarantee safety. Rather use "App did not detect a source of risk" or similar instead.

**Comment by MilesTeg97** [comment] 2020-06-26 09:50
simple typo in [terms_en.html](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/terms_en.html):

line 408: "The App **muss** must be running on your device [...]"

should be:  "The App must be running on your device [...]"

**Comment by kaluju** [comment] 2020-07-02 09:37
> [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf):
> "..., versendet Ihr Smartphone per Bluetooth Low Energy kontinuierlich zufallsgenerierte Kennnummern, auch als Zufallscodes **zu** bezeichnet" - remove the word "zu"
> 
> [Privacy notice in Android app](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/assets/privacy_de.html) has not yet been updated.

**--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by kaluju** [comment] 2020-07-02 09:38
> Link to Privacy Notice in [Terms](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/assets/terms_de.html) does not work:
> 
> ```
> Die separate Datenschutzerklärung (siehe <strong>[<em>Link</em>]</strong>) ist
> Bestandteil dieser Nutzungsbedingungen. 
> ```
> 
> (Other links don't work either: `Weiterführende Informationen zur App finden Sie unter folgendem Link: <strong>[<em>Link</em>]</strong>`)
> 
> Emphasis wrong:
> 
> ```
> In regelmäßigen Abständen holt sich die App über die CWA-Dienste eine Liste der Zufallscodes (<em>t</em> <em>emporary exposure keys</em>)
> ```
> 
> The text contains symbols (emoticons?) that cannot be displayed by all devices
> 
> ```
> � - Waschen Sie sich regelmäßig für mindestens 20 Sekunden die Hände
> ```
> 
> There's a text block in the middle of the Terms that apparently ends the 'official' part:
> 
> ```
> Diese weiterführenden Informationen dienen lediglich Ihrer Information und 
> sind nicht Bestandteil dieser Nutzungsbedingungen.
> ```
> 
> but I don't think that's intended, because a lot of important points follow.
> It's completely unclear when the "weiterführenden Informationen" end.

**--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by kaluju** [comment] 2020-07-02 09:38
> The [Terms](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/assets/terms_de.html) text gives incorrect statements about the app:
> 
> ```
> Hintergrund
> Die App läuft auf dem Endgerät im Hintergrund und speichert automatisiert
> und verschlüsselt die Zufallscodes (<em>rolling proximity identifier</em>)
> anderer in der Nähe befindlicher Endgeräte. In regelmäßigen Abständen holt
> sich die App über die CWA-Dienste eine Liste der Zufallscodes (<em>t</em> <em>emporary 
> exposure keys</em>) der Personen, die sich freiwillig infiziert gemeldet haben, und vergleicht 
> diese mit den gespeicherten Zufallscodes im Gerät, um eine Risiko-Begegnung zu ermitteln.
> ```
> 
> a) The word "Zufallscodes" is translated to two different things (RPI and TEK).
> b) The app does not save RPIs of other devices. The Google/Apple framework does that.
> c) At least the Google framework **does not save the RPIs encrypted**. Access to them is restricted, but they are not encrypted; the Terms should make a correct statement about that, or no statement at all.
> 
> My proposal for this text would be:
> 
> ```
> Hintergrund
> Die App aktiviert die Kontaktaufzeichnungs-Funktion Ihres Smartphones, 
> die automatisiert abgeleitete Zufallscodes (<em>rolling proximity identifiers</em>) 
> anderer in der Nähe befindlicher Endgeräte speichert. 
> In regelmäßigen Abständen holt sich die App über die CWA-Dienste eine Liste von 
> Zufallscodes (<em>temporary exposure keys</em>) der Personen, die sich freiwillig 
> infiziert gemeldet haben, und übergibt sie der Kontaktaufzeichnungs-Funktion Ihres 
> Smartphones, welche durch Vergleiche mit den im Gerät gespeicherten Zufallscodes 
> ermittelt, ob Risiko-Begegnungen stattgefunden haben.
> ```

**--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by kaluju** [comment] 2020-07-02 09:40
> The abbreviation "CWA" is only used once in user-facing strings of the Android app, in
> 
> `<string name="main_overview_body_glossary_keys">"Die Zufallscodes sind zufällig erzeugte Zahlen- und Buchstabenkombinationen. Sie werden zwischen benachbarten Smartphones ausgetauscht. Zufallskennungen lassen sich nicht einer bestimmten Person zuordnen und werden nach 14 Tagen automatisch gelöscht. Eine Corona-positiv getestete Person kann ihre Zufallscodes der letzten bis zu 14 Tage freiwillig mit anderen CWA-Nutzern teilen."</string>`
> 
> Unexplained abbrevations can be confusing.
> 
> **Suggestion:** change last part to "[...] freiwillig mit anderen Nutzern der Corona-Warn-App teilen."

**--> changed to App-Nutzern**

**Comment by kaluju** [comment] 2020-07-02 09:43
> * `    <string name="risk_card_body_tracing_off">"Aktivieren Sie die Risiko-Ermittlung, um Ihre heutige Risikostatus zu berechnen."</string>` :`heutige` should be `heutigen`, and `Ihre` `Ihren`
> * In `submission_contact_step_1_content`: "Es gelten die Preise ihres Telefonanbieters." should be "Es gelten die Preise **I**hres Telefonanbieters." **--> text no longer exists**
> * In `submission_done_further_info_bullet_points`: "wie sich ihre Krankheitszeichen entwickeln." should be "wie sich **I**hre Krankheitszeichen entwickeln." **--> changed to "Ihre"**

**Comment by kaluju** [comment] 2020-07-02 09:51
> The Terms make incorrect statements about how to disable Exposure Notifications.
> 
> ```
>     Wenn Sie die App
>     nicht starten, ausschalten oder beenden, speichert die App keine
>     Begegnungen mit anderen Personen und erzeugt keine Zufallscodes zur
>     Speicherung durch andere Personen. 
> ```
> 
> Obviously the lawyer intended to inform users who don't properly run the app, that they might miss notifications.
> But users who are later concerned about their privacy and want to disable the feature could also think that just stopping the app could achieve that. But it doesn't, they would need to explicitly stop Exposure Notifications.
> And it's anyway not the App that does all that. So the text should read:
> 
> ```
>     Wenn Sie die App
>     nicht starten, ausschalten oder beenden, speichert _das Gerät möglicherweise_ keine
>     Begegnungen mit anderen Personen und erzeugt _möglicherweise_ keine Zufallscodes zur
>     Speicherung durch andere Personen. 
> ```

**--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by opatut** [comment] 2020-07-02 10:56
> **--> changed to App-Nutzern**

This is unfortunately not gendered appropriately. Please change to `Nutzerinnen und Nutzern der App` or similar.

**Comment by kaluju** [comment] 2020-07-08 11:08
> simple typo in [terms_en.html](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/terms_en.html):
> 
> line 408: "The App **muss** must be running on your device [...]"
> 
> should be: "The App must be running on your device [...]"

**--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by kaluju** [comment] 2020-07-08 11:10
> * [ ]  Zufallscodes vs. Zufalls-ID vs. Zufalls-Kennung: all are used, should be reviewed and potentially harmonized **
--> Unfortunately, this inconsistency concerns legal texts and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

> * [ ]  Ellipsis vs. three dots: should be reviewed
**--> Unfortunately, our translation system can't deal with unicode characters correctly, that's why there is an inconsistency**

> * [ ]  Corona-Virus (with dash) vs. Coronavirus (no dash) 
**--> Unfortunately, this inconsistency concerns legal texts and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by kaluju** [comment] 2020-07-08 11:12
> * [ ]  Um die Risiko-Ermittlung nutzen zu können müssen Sie zudem auf Ihrem Smartphone die von Google bereitgestellte Kontaktaufzeichnungs-Funktion „Benachrichtigungen zu möglicher Begegnung mit COVID-19-Infizierten“ aktivieren und für die Corona-Warn-App freigeben."
>   missing comma after "Um die Risiko-Ermittlung nutzen zu können"
**--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by kaluju** [comment] 2020-07-08 12:04
@marcmuschko  I tried to answer all the feedback we got and I incorporated it. In my opinion, we could close this issue.

**Comment by nicktar** [comment] 2020-07-08 12:09
> 
> 
> @marcmuschko I tried to answer all the feedback we got and I incorporated it. In my opinion, we could close this issue.

Is there any response to https://github.com/corona-warn-app/cwa-app-android/issues/332#issuecomment-646794139?

**Comment by opatut** [comment] 2020-07-08 12:20
>  I tried to answer all the feedback we got and I incorporated it. In my opinion, we could close this issue.

I still don't see an answer to my suggestions and/or the changes incorporated into [the `dev` branch](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/res/values-de/strings.xml). Also some [other people's suggestions](https://github.com/corona-warn-app/cwa-app-android/issues/332#issuecomment-652904743) that I checked are not included. Is `dev` the right branch to look on? If so, where are these changes?

**Comment by ironjan** [comment] 2020-07-08 12:37
@opatut the `dev` branch would be the correct one. However, based on @kaluju's comments and the previous procedure for text changes, I assume something like the following process:
 1. "Bugs" in the texts are collected via #332
 2. The suggested changes are processed internally (which may or may not involve the legal department, based on the type of text)
 3. The changes are then applied to the app internally
 4. A final review on the all or only the changed texts marks them as "good"
 5. The translations are updated and reviewed (essentially 2-4 again)
 6. All texts are updated into `dev` at once

Steps 2-5 are most likely done via an internal toolchain which explains the many comments in the string files (e.g. the comment [`XBUT: risk card - update […]`](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/res/values-de/strings.xml#L149) denotes that the text is on a `button` within a `risk card` that triggers the `update […]` action - this is important information for the language department which perhaps does not work on the code directly).

**Comment by MikeMcC399** [comment] 2020-11-01 09:43
I have submitted a translation error issue under https://github.com/corona-warn-app/cwa-documentation/issues/457 
"Bad translation for roaming charges in EU under Transnational Exposure Logging"

**Comment by MikeMcC399** [comment] 2020-11-03 20:41
@janetback 
There is a typo in
https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values/legal_strings.xml
`onboarding_tracing_body_consent`

"If you would like to use the **exosure** logging feature again, you can toggle the feature back on or reinstall the app."

That should be "exposure" not "exosure".

**Comment by janetback** [comment] 2020-11-05 06:53
Hi @MikeMcC399, thanks for pointing this out. Have just fixed it for 1.7.

**Comment by MikeMcC399** [comment] 2020-11-09 08:50
Hi @janetback 
https://github.com/corona-warn-app/cwa-documentation/issues/424 / EXPOSUREAPP-2632
seems to have got overlooked. It's a very minor point. On the other hand it should be very easy to correct. There are full stops missing at the end of two German text strings.

[https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values-de/strings.xml](values-de/strings.xml)
Line 333 risk_details_subtitle_period_logged "Dieser Zeitraum wird berücksichtigt"
Line 335 risk_details_information_body_period_logged "Die Berechnung des Infektionsrisikos kann nur für die Zeiträume erfolgen, an denen die Risiko-Ermittlung aktiv war. Die Risiko-Ermittlung sollte daher dauerhaft aktiv sein"

in Android app.

### Describe the issue
risk_details_subtitle_period_logged and risk_details_information_body_period_logged are missing full stops (periods) at the end of the sentence in the German translation. The English text is correctly punctuated.

**Comment by MikeMcC399** [comment] 2020-11-09 19:59
@janetback 
Here is another translation issue that I logged under https://github.com/corona-warn-app/cwa-documentation/issues/457

interoperability_configuration_second_section
"The daily download of the list with the random IDs is usually free of charge for you – you will not be charged for the data used by the app in this context, **will roaming charges** apply for this in other EU countries."

... does not make sense. I think it should be:

"The daily download of the list with the random IDs is usually free of charge for you – you will not be charged for the data used by the app in this context, and no roaming charges apply for this in other EU countries."

**Comment by MikeMcC399** [comment] 2021-02-12 08:57
There is a regression documented in https://github.com/corona-warn-app/cwa-documentation/issues/526
where `statistics_card_submission_bottom_text` in the English language version was corrected before the release of 1.11 to read
"through Corona-Warn-App"
and now in 1.12.0 it has gone back to the incorrect text:
<string name="statistics_card_submission_bottom_text">"About Corona-Warn-App"</string>
affecting both Android and iOS releases.

**Comment by dsarkar** [comment] 2021-02-12 09:21
@MikeMcC399  Thanks. It is currently being analysed.

**Comment by bartim** [comment] 2021-06-10 13:30
https://github.com/corona-warn-app/cwa-app-android/blob/4855156f60b40cd9851e19e04a2044dbd24760c9/Corona-Warn-App/src/main/res/values-de/strings.xml#L1016

This should probably be "QR-Code-Scan" (notice the hyphen), see [German Wikipedia to "Leerzeichen in Komposita"](https://de.wikipedia.org/wiki/Leerzeichen_in_Komposita)

**Comment by veyndan** [comment] 2021-08-14 16:48
The following text is shown above a period of time, so it should be "Result available for" instead ([source](https://dictionary.cambridge.org/grammar/british-grammar/for-or-since)).

https://github.com/corona-warn-app/cwa-app-android/blob/bd2b989daff48881949402dbbc8827a1d3806425/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L117

**Comment by Marcono1234** [comment] 2021-08-23 23:44
`person_overview_no_certificates_image_description` is not translated into German:
https://github.com/corona-warn-app/cwa-app-android/blob/97fbc95b71db96ed637af3eaa35118eb705a1611/Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml#L23

**Comment by gitlab-nickfreeman** [comment] 2022-01-04 12:40
There is a duplicate '.' in risk_details_behavior_body_stay_home.
See https://gitlab.com/nickfreeman/cwa-app-android/-/commit/4621a33a377096b0f886973d9c1ea9f17b7d593a

**Comment by Ein-Tim** [comment] 2022-01-04 12:46
@gitlab-nickfreeman 

Related: https://github.com/corona-warn-app/cwa-app-ios/pull/4035

**Closed** 2022-09-09 05:40 UTC
Labels: help wanted, maintainers, text issue

**Comment by MikeMcC399** [comment] 2022-09-09 06:09
@mtwalli 

Closing this issue means that you also need to remove the reference to it in https://github.com/corona-warn-app/cwa-app-android#known-issues:

"Strings including translations are handled separately, for suggestions / findings please have a look at issue https://github.com/corona-warn-app/cwa-app-android/issues/332"

and in https://github.com/corona-warn-app/cwa-app-android/blob/main/.github/pull_request_template.md

"The PR can not contain changes in localization files, e.g. values-[LANGUAGE-CODE]/strings/* and / or assets/* (see https://github.com/corona-warn-app/cwa-app-android/issues/332 for further information)."

**Comment by mtwalli** [comment] 2022-09-09 06:49
@MikeMcC399  Thanks for pointing this out I will update the respective docs
