### ISSUE TITLE
Corona WarnApp not Updating after changing the Date of the device

### ISSUE THREAD

**Issue by msobotzi** [corona-warn-app/cwa-app-android#4770] opened 2022-02-02 12:20 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung M31
- Android version: 11
- App version: 2.16.2

## Describe the bug

I changed the date on my device to April in order to test my own app. However during this testing the corona warn app performed a risk status update. However since I changed the date back to automatic, the app does not update the status anymore. This happened a few days ago. Tests are still working. I got tested today and it says that the test is 2 hours old. So that works. But the app apparently does not update the risk status anymore. It still states April 1st 16:13

## Steps to reproduce the issue
1. Change the date of the device to something in the future.
2. Update the risk status
3. change the date back
4. Try to update the risk status (not working on my device)

## Expected behaviour

I expected that the "update" should still work. It should just fetch the newest data and then show that time and date.
## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)

Relates issues:
https://github.com/corona-warn-app/cwa-app-android/issues/3629	
https://github.com/corona-warn-app/cwa-app-android/issues/4303	
https://github.com/corona-warn-app/cwa-app-android/issues/4660	
https://github.com/corona-warn-app/cwa-app-android/issues/4770	
https://github.com/corona-warn-app/cwa-app-ios/issues/4040

**Comment by Ein-Tim** [comment] 2022-02-02 12:24
Same as https://github.com/corona-warn-app/cwa-app-android/issues/4303.

**Comment by dsarkar** [comment] 2022-02-02 12:29
Hi @msobotzi 

I am afraid your app will not recover and resume normal operation until the date shown (1. April apparently in your case). This could be acceptable if it was one day or so, but in this case it is far from ideal. Most probably, either resetting the app or re-installing it will help in this case. If you do so, make sure that you have a backup of your certificates (paper, pdf, screenshot), and if applicable of your CWA contact journal. Also note, if you have registered a PCR or RAT test, it cannot be scanned again!

Best wishes, DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)

**Comment by MikeMcC399** [comment] 2022-03-11 15:55
@msobotzi 
Have you reset the Corona-Warn-App or are you just going to wait until April 1, 2022 for exposure logging to start working again?

**Comment by msobotzi** [comment] 2022-03-11 16:05
@MikeMcC399 I reseted the app and everything worked fine again.
Thank you

**Comment by MikeMcC399** [comment] 2022-03-11 16:13
@msobotzi 
> I reseted the app and everything worked fine again.

That is good to hear! 

Would you like to close this issue in that case? You should see a button below to do this.

The problem is already been tracked in other issues which @dsarkar mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/4770#issuecomment-1027893322 (also listed below), so there would not be any benefit it keeping this individual issue open if you have sorted out your own device.

- https://github.com/corona-warn-app/cwa-app-android/issues/3629
- https://github.com/corona-warn-app/cwa-app-android/issues/4303
- https://github.com/corona-warn-app/cwa-app-android/issues/4770

**Closed** 2022-03-11 16:19 UTC
Labels: bug, mirrored-to-jira, risk-check
