### ISSUE TITLE
Doesn't allow to download based on region specific restriction

### ISSUE THREAD

**Issue by ParthaEth** [corona-warn-app/cwa-app-android#735] opened 2020-06-24 08:06 UTC
Hi I live in Germany for my PhD studies since 2.5 years now. However I get this error trying to install this app.
![covid_restricted_download](https://user-images.githubusercontent.com/10944728/85519776-4a3e2d00-b602-11ea-8354-677a4d3ed255.jpeg)

**Comment by meyerj** [comment] 2020-06-24 09:28
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/478.

**Comment by trevor87** [comment] 2020-06-24 12:07
Hi I would suggest #670 as a workaround.

**Comment by SebastianWolf-SAP** [comment] 2020-06-24 12:22
Dear @ParthaEth,

the respective earlier issues have already been mentioned, please see https://www.coronawarn.app/en/faq/#international for details. See also https://github.com/corona-warn-app/cwa-wishlist/issues for the already requested countries.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-24 12:22 UTC
Labels: bug, duplicate
