### ISSUE TITLE
Add an option to pin a shortcut widget icon to the Vaccination Pass to the Homescreen

### ISSUE THREAD

**Issue by lorisobi** [corona-warn-app/cwa-app-android#3501] opened 2021-06-18 14:23 UTC
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
The digital vaccination pass is accessible from the CWA Start Menu

## Suggested Enhancement
The digital vaccination pass should be openable from the Android Home Screen. I would suggest via an 1x1 icon widget.

## Expected Benefits
The digital vaccination pass would be openable more quick.

**Comment by Ein-Tim** [comment] 2021-06-18 14:30
Related to: 
- https://github.com/corona-warn-app/cwa-wishlist/issues/13 (Android Home Screen widget)
- https://github.com/corona-warn-app/cwa-wishlist/issues/26 (iOS Home Screen widget)

**Comment by heinezen** [comment] 2021-06-20 14:46
Hey @lorisobi 

Thank you for making a proposal to improve the app. However, the same request was already made by someone else in https://github.com/corona-warn-app/cwa-wishlist/issues/504. We suggest you look into the discussion threre.

I'll close your issue as a duplicate. Please continue the discussion in https://github.com/corona-warn-app/cwa-wishlist/issues/504

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-20 14:46
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/504

**Closed by heinezen** 2021-06-20 14:46 UTC
Labels: enhancement
