### ISSUE TITLE
Exposure check did not check since 2020-09-30 (error 39508)

### ISSUE THREAD

**Issue by AnOtherMuenchner** [corona-warn-app/cwa-app-android#1397] opened 2020-10-14 05:20 UTC
On my Samsung S5 mini the last exposure check has been successfully done on 2020-09-30. Since this day, I get every day the error 39508. When I look in the log, I can see 20 twenty checks every day. It seems that the checks is done, but the app does not get the result. When opening the app the second time, it starts with the check next time, leading to this error.

**Comment by vaubaehn** [comment] 2020-10-14 07:14
Hi @AnOtherMuenchner ,
Please see https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-707879303 second paragraph about the causes and what you can try for the moment. Good luck!

**Comment by AnOtherMuenchner** [comment] 2020-10-14 07:47
Hi @vaubaehn,

the linked description reads like this could really be the source of the error. I can try it tomorrow. 

But to be honest: This all can only be a bad joke and not a serious application. In my case this means that the application consumes since two weeks lot of battery power without advantage for me. 👎 Also for other users this means that they trust on a notification mechanism which does not work.

**Comment by vaubaehn** [comment] 2020-10-14 08:04
> I think, the major part of users won't realize errors like this and look for workarounds. Unfortunately this error occurs in a time, in which the functionality of the app without errors becomes more and more important.

As we can see in the Google Play Store reviews, one not working workaround that users try, is to re-install the app. Unfortunately, all collected RPIs and TEKs are then lost, which makes risk assessment for the past 2 weeks impossible. This is specifically sad, as the error here is usually temporary (until now...)

Dear @svengabr , maybe it's important, that the Google Play Store support team instructs help seeking users to NOT UNINSTALL the app for these reasons. In July, when we saw error API 10, Play Store Support was already doing so.
Please, let's try to preserve as many RPIs/TEKs, as possible. Would you kindly refer that information to support team (and maybe also technical helpline?), Sven?

**Comment by abro1i** [comment] 2020-10-15 09:25
Hi @vaubaehn,

thanks, I forwarded this information to my colleagues from the Play Store Team.

Best regards,
ABB

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-15 13:00
Hey everyone,

I'll close this issue as a duplicate now. Please continue the discussion in the main issue thread (#1021 )

Thanks

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-15 13:01
Duplicate of #1021

**Closed by heinezen** 2020-10-15 13:01 UTC
Labels: bug
