### ISSUE TITLE
Google play store on spanisch Sim : download in your country not available!??!?

### ISSUE THREAD

**Issue by tompatric** [corona-warn-app/cwa-app-android#587] opened 2020-06-17 09:22 UTC
## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by jakobmoellersap** [comment] 2020-06-17 09:24
Hi @tompatric . Please describe the bug more detailed. From what I can see, you have a Spanish sim but we would need information on the Play Store Location and some context would be really helpful to resolve the issue.

**Comment by dalbre** [comment] 2020-06-17 09:51
Hello,
I think the OP's problem is quite clear. It's not about the SIM card, but the play store country setting. I'm located in Brussels and have the same issue. The play store reply is "the app is not available in your country" ...

I think this should be easy to solve and should be solved quickly. The cwa should be available to foreign visitors to Germany for installation prior to visiting and also without changing the play store country location.

**Comment by tkowark** [comment] 2020-06-17 10:02
duplicate of #478

**Closed by tkowark** 2020-06-17 10:02 UTC
Labels: bug

**Comment by tompatric** [comment] 2020-06-19 14:24
Hi,Yes it is the play store....And if you believe its easy t o solve ....listening!??Am 17.06.2020 11:51 schrieb dalbre <notifications@github.com>:
Hello,
I think the OP's problem is quite clear. It's not about the SIM card, but the play store country setting. I'm located in Brussels and have the same issue. The play store reply is "the app is not available in your country" ...
I think this should be easy to solve and should be solved quickly. The cwa should be available to foreign visitors to Germany for installation prior to visiting and also without changing the play store country location.

**Comment by tompatric** [comment] 2020-06-19 14:29
Hi,Spanisch Sim,play store in german ,does obviosly not mean the play store is afiliate to Germany.Since im registered citizen in Spain, all permisions must be accepted by google in spain..( ???!!!!) And they do not want you to install this app?!Am 17.06.2020 11:25 schrieb Jakob Möller <notifications@github.com>:
Hi @tompatric . Please describe the bug more detailed. From what I can see, you have a Spanish sim but we would need information on the Play Store Location and some context would be really helpful to resolve the issue.
