### ISSUE TITLE
Distance and time of exposure in increased risk notification

### ISSUE THREAD

**Issue by gabriele16** [corona-warn-app/cwa-app-android#1233] opened 2020-09-25 10:22 UTC
Upon receiving the notification of increased risk, where can one find the details on the average distance between the person at risk and the infected user and the duration of the contact? 

I can only see that I am at increased risk because I was in contact with 1 infected person 6 days ago but I would like to know what that means exactly. For instance, was I for 10/20/30 minutes at 1 meters distance or 1/2 meters distance etc?

Also, I would like to suggest to provide a value for the probability of infection (e. g. In percent) along with the information on low risk and increased risk. It should be possible to extract the probability of infection corresponding to a given status of low risk and increased risk from the data gathered up until now, perhaps the value of the probability is already known. 

Thanks.

**Comment by daimpi** [comment] 2020-09-25 12:19
> Upon receiving the notification of increased risk, where can one find the details on the average distance between the person at risk and the infected user and the duration of the contact?

The answer is that you cannot get this information unless your device is rooted, in which case you can use @mh-'s [corona-warn-companion](https://github.com/mh-/corona-warn-companion-android) to get more details.

> I can only see that I am at increased risk because I was in contact with 1 infected person 6 days ago but I would like to know what that means exactly. For instance, was I for 10/20/30 minutes at 1 meters distance or 1/2 meters distance etc?

Agreed. It would be nice if CWA exposed this information to the user, but unfortunately the issue with this request has been closed for some reason: https://github.com/corona-warn-app/cwa-wishlist/issues/100. 
(@svengabr could you answer my question [there](https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-695343684) on why this issue was closed?)

> It should be possible to extract the probability of infection corresponding to a given status of low risk and increased risk from the data gathered up until now, perhaps the value of the probability is already known.

This is something the app unfortunately will not be able to do. There are too many factors - which have a significant impact on the infection probability and which the app can't know about - to reliably give an percentage estimate for infection probability for any individual exposure. The way the app currently discriminates between the two rough categories "low risk" and "increased risk" is described [here](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md).
Also: data gathering by RKI for CWA has been quite lacking so far imho.

**Comment by svengabr** [comment] 2020-09-25 12:41
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/100

**Comment by svengabr** [comment] 2020-09-25 12:42
We got an official statement from the Robert Koch Institute:

**German**
>Als Herausgeber der Corona-Warn-App bedankt sich das Robert Koch-Institut für die vielen Rückmeldungen zur Risikostatusanzeige auf dem HomeScreen. Diesem Dank schließen wir uns als Entwicklerteam der App an. Nach Abwägung aller Argumente und in Abstimmung mit dem Bundesministerium für Gesundheit hat das RKI entschieden, die zweistufige Risikodarstellung (grün und rot) beizubehalten.

>Die App muss möglichst einfach und allgemeinverständlich in der Anwendung sein. Durch die Unterscheidung von niedrigem und erhöhtem Risiko können den Nutzerinnen und Nutzern auf ihren Risikostatus abgestimmte Handlungsempfehlungen gegeben werden. Die zusätzliche Anzeige von Begegnungen, die bestimmte Kriterien erfüllen, erhöht die Transparenz. Für alle diejenigen, die sich mit der Risikobewertung und ihren Parametern eingehender beschäftigen möchten, haben RKI und Entwicklerteam detaillierte Beschreibungen auf GitHub zur Verfügung gestellt.

>Die Texte in der Corona-Warn-App werden wir unter Berücksichtigung Ihres Feedbacks weiter anpassen. Mit einem anstehenden Update werden wir weitere Erläuterungen zum besseren Verständnis der angezeigten Risikobegegnungen geben. Zudem wird geprüft, ob mit einem späteren Update eine Risikobegegnungshistorie in der App dargestellt werden kann.

>Auch zukünftig werden wir Anregungen und Vorschläge zur Verbesserung der Corona-Warn-App aufgreifen, diskutieren und, soweit sinnvoll und möglich, umsetzen. Wir freuen uns, wenn Sie sich weiter mit konstruktivem Feedback beteiligen.

---

**English**
>As the publisher of the Corona-Warn-App, the Robert Koch-Institute as well as the development team would like to thank you for the many feedbacks on the risk status display on the HomeScreen. After weighing up all arguments and in coordination with the Federal Ministry of Health, the RKI has decided to keep the two-level risk display (green and red).

>The app must be as simple and generally understandable as possible in its application. By differentiating between low and increased risk, users can be given recommendations for action based on their risk status. The additional display of encounters that meet certain criteria increases transparency. For those who want to take a closer look at risk assessment and its parameters, RKI and the development team have provided detailed descriptions on GitHub.

>We will further improve the texts in the Corona-Warn-App and we will continue to listen for feedback of the community. With an upcoming update, we will provide further explanations to help you better understand the risk encounters displayed. In addition, we will check whether a later update will allow a risk encounter history to be displayed in the app.

>In the future, we will continue to take up, discuss and, where reasonable and possible, implement suggestions and proposals for improving the Corona Warning App. We would be pleased if you continue to contribute with constructive feedback.

Further text improvements are being introduced in the upcoming hotfix release 1.3.1.

RC1 of 1.3.1 is already available:
https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.1-SNAPSHOT-RC1
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.3.1-RC1

Since the decision from the RKI is final, I will close this issue now.

Best regards,
SG

Corona-Warn-App Open Source Team

**Closed by svengabr** 2020-09-25 12:42 UTC

**Comment by MikeMcC399** [comment] 2020-09-25 13:39
@svengabr 
> RC1 of 1.3.1 is already available:
> https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.1-SNAPSHOT-RC1
> https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.3.1-RC1

I'm seeing https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.1 available on github (later than 1.3.1 RC1). I'm not seeing version 1.3.1 yet on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp though (at this moment it is showing 1.3.0) and I assume it is just a question of time before the Android 1.3.1 version of CWA appears in the Google Play Store.

**Comment by svengabr** [comment] 2020-09-29 08:39
@MikeMcC399 can you look again, please? I am seeing 1.3.1 released on the Play Store. iOS is currently running on 1.3.2

**Comment by MikeMcC399** [comment] 2020-09-29 08:56
@svengabr 
>can you look again, please? I am seeing 1.3.1 released on the Play Store. iOS is currently running on 1.3.2

Indeed, Android CWA 1.3.1 is now showing on Google Play Store
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp .
