### ISSUE TITLE
Google APIException (10): Unable to validate key file signature: no public key found

### ISSUE THREAD

**Issue by rzo1** [corona-warn-app/cwa-app-android#1085] opened 2020-08-27 20:35 UTC
## Describe the bug

Similar to #817 ~~and #737~~

![Screenshot_20200827-215316](https://user-images.githubusercontent.com/13417392/91491886-0642ff00-e8b5-11ea-8aed-31ed3cecb469.png)

![Screenshot_20200827-215321](https://user-images.githubusercontent.com/13417392/91491899-0b07b300-e8b5-11ea-9715-aabc0b9805a8.png)

## Technical details

- Mobile device: Pixel 3A
- Android version: 10 with Security Updates from 5th August 2020
- CWA Version: 1.2.1
- ENF Version:

![Screenshot_20200827-220604](https://user-images.githubusercontent.com/13417392/91491959-1fe44680-e8b5-11ea-97aa-63f92de1698f.png)

- Auto Updates enabled...

---
Internal Tracking ID: EXPOSUREAPP-2410

**Comment by vaubaehn** [comment] 2020-08-27 21:18
Hi @rzo1 , I think your issue is indeed similar to #817 (no public key found), but likely different from #737 (pipe is closed?).

Could you maybe export and provide the Exposure log:
Settings > APIs > google > Covid-19 Benachrichtigungen > Überprüfung auf mögliche Begegnungen > ... Menu up right > export

Interesting co-incidence: #817 reported by @eriktews was also on Pixel 3-series on Android 10. For him the error resolved itself the next day, if I remember right.

**Comment by eriktews** [comment] 2020-08-27 22:37
> Interesting co-incidence: #817 reported by @eriktews was also on Pixel 3-series on Android 10. For him the error resolved itself the next day, if I remember right.

More or less yes, so maybe it started to work again after I rebooted the device and of course I had automatic updates enabled in the Play Store, so maybe some component was updated on the phone that solved the issue for me.

**Comment by rzo1** [comment] 2020-08-28 06:37
**Interesting detail:**

My wife also uses a Pixel 3a. Her CWA in **v1.2.1** is working fine. ENF version **16203302004**. 
Same Android Version: 10 with Security Updates from 5. August 2020.

Last successful "Risiko-Ermittlung" on my phone was on 25.08.2020 @ 20:42 

@vaubaehn here is the exposure log of my phone pretty formatted. 


<details>
```

[
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 2380,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 2285,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 3800,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 3940,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 3020,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 2675,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 1790,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "booypFvg7FHjJaXzqOe1uaSzp2byyy33MnRqvb3\/A\/A="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 2785,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "PME9jnNe74+zeEXwwhL6lHIwA0LgI3CtiyH7cgDw8KI="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 3749,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Q71tl1xX2vOOpXCXXD4Nbb59n3UOoyQ6+EqlUgMaLYE="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 3970,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "j5X5KZl49Z6TjPij64zo33ZRiDWkXubkMlD5wg6Ga90="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 4740,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "MyxqsqBxRQqp7KXS1jP\/Xfr40hbcFhkb7ssAnlUIA5s="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 3550,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Dn2IhRyGtT+QVK7pqXiojVhDnmOM2G17NLw9VZi7Ovw="
  },
  {
    "timestamp": "23. August 2020, 20:41",
    "keyCount": 3393,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "fXS+VRiOZt9yK5fnwYIqpomT6sy\/Wx+FJvdq5NAyBpY="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 2285,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3800,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3940,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3020,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 2675,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 1790,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "booypFvg7FHjJaXzqOe1uaSzp2byyy33MnRqvb3\/A\/A="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 2785,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "PME9jnNe74+zeEXwwhL6lHIwA0LgI3CtiyH7cgDw8KI="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3749,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Q71tl1xX2vOOpXCXXD4Nbb59n3UOoyQ6+EqlUgMaLYE="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3970,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "j5X5KZl49Z6TjPij64zo33ZRiDWkXubkMlD5wg6Ga90="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 4740,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "MyxqsqBxRQqp7KXS1jP\/Xfr40hbcFhkb7ssAnlUIA5s="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3550,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Dn2IhRyGtT+QVK7pqXiojVhDnmOM2G17NLw9VZi7Ovw="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3393,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "fXS+VRiOZt9yK5fnwYIqpomT6sy\/Wx+FJvdq5NAyBpY="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 2535,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "tJ5DISc2xYrTCEEWjGyMDZ\/4\/OD7kcsEEcE0j66uwHs="
  },
  {
    "timestamp": "25. August 2020, 20:42",
    "keyCount": 3165,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "E9\/3fPP1VumROWc8ld+ekBISji7vVM4Fa8tUsZVVOmg="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 3050,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 2210,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 1655,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 565,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 2380,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 2285,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 3800,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 3940,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 3020,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 2675,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 1790,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "booypFvg7FHjJaXzqOe1uaSzp2byyy33MnRqvb3\/A\/A="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 2785,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "PME9jnNe74+zeEXwwhL6lHIwA0LgI3CtiyH7cgDw8KI="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 3749,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Q71tl1xX2vOOpXCXXD4Nbb59n3UOoyQ6+EqlUgMaLYE="
  },
  {
    "timestamp": "20. August 2020, 20:38",
    "keyCount": 3970,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "j5X5KZl49Z6TjPij64zo33ZRiDWkXubkMlD5wg6Ga90="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 2415,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 3050,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 2210,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 1655,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 565,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 2380,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 2285,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 3800,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 3940,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 3020,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 2675,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 1790,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "booypFvg7FHjJaXzqOe1uaSzp2byyy33MnRqvb3\/A\/A="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 2785,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "PME9jnNe74+zeEXwwhL6lHIwA0LgI3CtiyH7cgDw8KI="
  },
  {
    "timestamp": "19. August 2020, 20:36",
    "keyCount": 3749,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Q71tl1xX2vOOpXCXXD4Nbb59n3UOoyQ6+EqlUgMaLYE="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 1655,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 565,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 2380,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 2285,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 3800,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 3940,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 3020,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 2675,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 1790,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "booypFvg7FHjJaXzqOe1uaSzp2byyy33MnRqvb3\/A\/A="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 2785,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "PME9jnNe74+zeEXwwhL6lHIwA0LgI3CtiyH7cgDw8KI="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 3749,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Q71tl1xX2vOOpXCXXD4Nbb59n3UOoyQ6+EqlUgMaLYE="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 3970,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "j5X5KZl49Z6TjPij64zo33ZRiDWkXubkMlD5wg6Ga90="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 4740,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "MyxqsqBxRQqp7KXS1jP\/Xfr40hbcFhkb7ssAnlUIA5s="
  },
  {
    "timestamp": "22. August 2020, 15:05",
    "keyCount": 3550,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Dn2IhRyGtT+QVK7pqXiojVhDnmOM2G17NLw9VZi7Ovw="
  },
  {
    "timestamp": "18. August 2020, 20:36",
    "keyCount": 2813,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "\/BGlkC6K9rDVU\/o+\/hd\/5Y8nTIucL4zYWZznMdPZQDM="
  },
  {
    "timestamp": "18. August 2020, 20:36",
    "keyCount": 2415,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "jJsXULhBwEOPWd6KJKdXxgcpPhQ1E4lbLevrI2X1\/8A="
  },
  {
    "timestamp": "18. August 2020, 20:36",
    "keyCount": 3050,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "00VFOX48zqpjJBvjRtVdg6s\/XIuEFGSncBE4s+Azt1Y="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 2380,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 2285,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 3800,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 3940,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 3020,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 2675,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 1790,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "booypFvg7FHjJaXzqOe1uaSzp2byyy33MnRqvb3\/A\/A="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 2785,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "PME9jnNe74+zeEXwwhL6lHIwA0LgI3CtiyH7cgDw8KI="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 3749,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Q71tl1xX2vOOpXCXXD4Nbb59n3UOoyQ6+EqlUgMaLYE="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 3970,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "j5X5KZl49Z6TjPij64zo33ZRiDWkXubkMlD5wg6Ga90="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 4740,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "MyxqsqBxRQqp7KXS1jP\/Xfr40hbcFhkb7ssAnlUIA5s="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 3550,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Dn2IhRyGtT+QVK7pqXiojVhDnmOM2G17NLw9VZi7Ovw="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 3393,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "fXS+VRiOZt9yK5fnwYIqpomT6sy\/Wx+FJvdq5NAyBpY="
  },
  {
    "timestamp": "24. August 2020, 20:43",
    "keyCount": 2535,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "tJ5DISc2xYrTCEEWjGyMDZ\/4\/OD7kcsEEcE0j66uwHs="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 2210,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Zqlj9HPKYuSuJywVkrLEX3re9Hobn+gs1321mIeIqiM="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 1655,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JsjhbWbw\/BZ5vPmpcYMzev2FTNcr9JOOxDst9M6u5fI="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 565,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 2380,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "JUqtJgYkSpsO6UjX9SnO+C6w1518Rna9Ay1y1HeQtcQ="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 2285,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "oY6Abxzv9ZQ6k6GtQFcoYgnlm3swzWJ9v2ldXeXqW8I="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 3800,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "O9EDIHgcHnHYRK14fHtfO\/NPyawZ7k3bhav2c2ss++s="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 3940,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "mDTgBack7CLecOLMQ+Oi1Km47u++WBnbgQbbwoLjF0c="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 3020,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "wqu9Lt\/gthQrJ2dy3HgnlwvafRxdsKKbs7kyQWjK\/aI="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 2675,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "GBcCZg9QMzBbNuNPAUMi0dduyGzzeOrx9uNqrdiJLYk="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 1790,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "booypFvg7FHjJaXzqOe1uaSzp2byyy33MnRqvb3\/A\/A="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 2785,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "PME9jnNe74+zeEXwwhL6lHIwA0LgI3CtiyH7cgDw8KI="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 3749,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "Q71tl1xX2vOOpXCXXD4Nbb59n3UOoyQ6+EqlUgMaLYE="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 3970,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "j5X5KZl49Z6TjPij64zo33ZRiDWkXubkMlD5wg6Ga90="
  },
  {
    "timestamp": "21. August 2020, 20:37",
    "keyCount": 4740,
    "matchesCount": 0,
    "appName": "Corona-Warn",
    "hash": "MyxqsqBxRQqp7KXS1jP\/Xfr40hbcFhkb7ssAnlUIA5s="
  }
]
```

</details>

**Comment by svengabr** [comment] 2020-08-28 13:07
Hello @rzo1 and thank you for reaching out. The initial problem with `no public key found` was closed end of July because it was fixed with a new ENF version. I will recreate an issue for this topic so the developers can have a look at your logs.

 

Best regards,
SG

 

Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment] 2020-08-28 17:58
Hi @rzo1 and @svengabr ,

> The initial report in #737 shows the same exception / stacktrace (cf. attached PDF in #737) . It might be linked somehow :)

The report of #737 (attached PDF) is not _exactly_ the same: #737 is API(10): Unable to validate... : **Pipe is closed**
(by the way: putting the phone to a flatbed scanner or a copy machine to scan the stracktrace in the lack of a screenshot ability is brilliant in my opinion! love it! :heart: )
"Pipe is closed" was amazingly tracked down by @kbobrowski , and turned out to be a difference in implementations of Java for Android >= 6 and Android 7+. Google corrected the ENF accordingly later. Only Android 6 devices were affected. So, #737 could be closed accordingly.

Your report and #817 is: API(10): Unable to validate... : **no public key found**
which seems to be nearly the same at first, but may have a completely different root source. Obviously, for now, Android 10 devices are affected. However, I don't have any clue what it was caused by, maybe a time out somewhere? As this is a different bug, should be left open.

I had a look to your exposure log:
- you still have the 100-line output, hence "the old configuration" of ENF. Think it will be updated for you soon, that you also have complete log accessible.
- For August 18 there are only 3 lines, for August 19, one line is missing. This may be an artifact of cutting 100+ lines, whereas I'm curious, why one line for August 19 is missing. Do you remember, if you had a green risk status inside CWA on that day?
- In general, your logs have a different sorting than mine, that gets more and more similar to mine with increasing date (the last days were matching with mine, the others were different. The later the date, the more entries had similar order) -> guess, this may also be related to 'the configuration change', as we have similar ENF versions.
- one interesting point: your hashes are a little bit different compared to mine with regard to slashes "/": When ever there is a slash in my log, it is preceeded by a backslash, like this "\/". Your log only shows slashes, but not backslashes "/". I don't think that this is of importance here, yould be an artifact by prettifiying your exposure log (escape character), or maybe due to different Android versions? But as some exposure checks succeded with different hash format, I don't think it's related.
Last point:
- On August 23, your log is missing this entry: "23. August 2020,   08:55 | 565 | 0 | 9ySZZ6kFhIpBqlbEuZvvxaR2P4hjX\/qJyXJWdSGH\/ow=" Do you remember if on that day exposure checks were successfull for you? If they were not, then at that day already a time out (or API 10?) may have occured.

**Comment by rzo1** [comment] 2020-08-28 18:11
@vaubaehn Thanks for the details - I must admit, that I did not check the stacktrace in 737 exactly. I have updated my initial bug report. In addition, I have attached the original JSON file of my exposure log: 
[all-exposure-checks.json](https://github.com/corona-warn-app/cwa-app-android/files/5143540/all-exposure-checks.json.txt)

Interesting side-note:

I checked another Pixel 3a (same versions as shown above), which has no problems at all. Weird.

**Comment by mtb77** [comment] 2020-08-28 21:17
@rzo1 can you please also check the Google Play Services Version installed on your device? 
-> Settings, then Apps & notifications, Google Play services
Obviously the #817 was fixed with GPS 20.26.14. 

Thanks,

Sascha

Corona-Warn-App Open Source Team

**Comment by rzo1** [comment] 2020-08-29 06:11
Hi @mtb77,

here is the "Google Play Dienste" version 

![Screenshot_20200829-080822.png](https://user-images.githubusercontent.com/13417392/91630083-d9830a80-e9ce-11ea-8f41-0194f5e505a1.png)

 (on all Pixel 3a devices similar...)

Best,
Richard

**Comment by mtb77** [comment] 2020-08-29 08:36
Hi @rzo1 

thanks for the update! 

Sascha

Corona-Warn-App Open Source Team

**Comment by rzo1** [comment] 2020-09-07 07:38
As a follow-up: the issue on my Pixel 3a is gone: Google Play Services still 20.30.19, CWA: 1.3.0

**Comment by svengabr** [comment] 2020-09-07 09:01
Thank you very much for your feedback. I am happy to hear the error is gone with the latest version of our app!

Best regards,
SG

Corona-Warn-App Open Source Team

**Closed by svengabr** 2020-09-07 09:01 UTC
Labels: bug, mirrored-to-jira

**Comment by dsarkar** [comment] 2020-12-01 08:07
Please, see https://github.com/corona-warn-app/cwa-app-android/issues/1645#issuecomment-736297560.
