### ISSUE TITLE
Proposed workaround to install app as a foreigner in germany

### ISSUE THREAD

**Issue by trevor87** [corona-warn-app/cwa-app-android#670] opened 2020-06-19 13:01 UTC
Hello,

I would have posted this solution in the original bug report but since it is locked this is not possible.

A way to install the app in Germany while having a phone with a foreign Google play account is this:

1. Create a new Google account on the computer (while in Germany) 

2. Add the new account to the phone under Settings > Accounts > Add account > Google

3. Go to the play store and select the new account by clicking on your account picture in the top right of the play store screen. Select the new account.

4. Install the app.

For my friend this worked. Hope it helps to support this cause!

Edit: Just for clarification: This will install a second Google account, so you will still keep your old one without changes.

**Comment by corneliusroemer** [comment] 2020-06-19 13:20
The fact that these issues keep getting opened show how big the problem is. Friendly reminder that it would be certainly be very much appreciated if maintainers could provide an update on the status of #478 - if I remember correctly the last update was Tuesday morning saying legal difficulties, but no further explanation what legal issue exactly. I don't want to reopen the discussion - just point out the importance and that an update of any form would be appreciated.

**Comment by tkowark** [comment] 2020-06-19 14:30
Thank you very much for the workaround. We check whether we can add this to the FAQ. 

Since we unfortunately still not have any news to share about availability in other Play Stores other than the german one, we also have to continue to ask for your patience on that matter.

**Comment by akuckartz** [comment] 2020-06-19 17:29
@tkowark It should be possible to explain what kind of legal issue is involved. If the App helps to save lifes than this legal issue might cost lives. Who is responsible? SAP? Google? RKI? Mr. Spahn? Ms. Merkel?

**Comment by trevor87** [comment] 2020-06-19 17:56
> Thank you very much for the workaround. We check whether we can add this to the FAQ.
> 
Cool, I think that would be a good idea! Also, it might be useful to post the workaround or a link to this issue in the ticket #478 at the end so that people can find it.

**Comment by fhajji** [comment] 2020-06-19 23:36
Thank you for this workaround. This was indeed helpful and resolved the problem I had in #478. I still hope that the app will become available globally in all Google Play stores soon, as not everyone impacted by this bug will see the FAQ and will eventually just give up.

Keep up the good work, and stay safe and healthy.

**Comment by roberthoenig** [comment] 2020-06-23 07:56
According to [German news](https://www.br.de/nachrichten/deutschland-welt/kanzleramtsminister-corona-warn-app-bald-im-ausland-nutzbar,S2iRxD7):
> Kanzleramtsminister Helge Braun (CDU) rechnet damit, dass die Corona-Warn-App noch vor der Hauptreisezeit auch in anderen Ländern nutzbar sein wird.

Does this mean that there is an update on this issue (and in particular on #478)?

**Comment by SebastianWolf-SAP** [comment] 2020-06-24 10:53
Dear colleagues,

I'm sorry to tell you that we can't add such a workaround to our official FAQ - legal distribution reasons. You can also find some additional information in the updated FAQ on the release of the app in international stores, see https://www.coronawarn.app/en/faq/#international and https://www.coronawarn.app/de/faq/#international 

> After a detailed examination of the situation it was determined that for legal reasons any publication of the Corona-Warn-App in App Stores outside of Germany is currently only possible after a case-by-case assessment. Legal consultations have shown that in the case of publication in international App Stores, the law of the respective country must be considered and applied to the Corona-Warn-App. This applies in particular to data protection, any necessary claims for information by local authorities and other contractual and consumer protection regulations.
>
> The Robert Koch-Institute as publisher of the app will trigger this check for the respective countries and release the app after successful legal examination. In a first step, the RKI will release the app for some European countries. These are: Netherlands, Belgium, Luxembourg, France, Austria, Czech Republic, Poland, Denmark, Romania and Bulgaria. It may still take a few hours to a few days until the app is available for the individual countries. We kindly ask you for your patience.
>
> More countries are currently being checked and will be released in the App Stores step by step. The Robert Koch-Institute asks for your understanding that it cannot provide any information on specific countries and the status of their release during the ongoing review process.

As said above now we have the following countries:

- Netherlands
- Belgium 
- Luxembourg 
- France
- Austria
- Czech Republic
- Poland
- Denmark
- Romania
- Bulgaria

We will close this issue, but we will keep one issue open in our backlog repository, this is https://github.com/corona-warn-app/cwa-backlog/issues/9. See the comment https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-648745301 how to show your support for additional countries.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-24 10:53 UTC
Labels: documentation

**Comment by trevor87** [comment] 2020-06-24 12:13
@SebastianWolf-SAP Thank you for this update.

I think for people looking for an answer to this problem in #478 it would still be good to post the solution at the end of the issue. After all, every person that can install the app due to a workaround helps.

Also to be clear on the way the workaround works: It does not require to add the app to a foreign app store. Instead foreigners create a German play account and add it additionally. This does not seem to contradict the legal requirements to only host the app in the German app store.
