### ISSUE TITLE
risk state remains "Risk Unknown"

### ISSUE THREAD

**Issue by Buntelrus** [corona-warn-app/cwa-app-android#632] opened 2020-06-18 09:48 UTC
## Describe the bug

I've installed the app more than 48h ago and my risk state is still "Risk Unknown".
In the first night I toggelt offline mode but the second day I've kept everything turned on. 

## Expected behaviour

Show me my Risk state + days active + last updated time

## Steps to reproduce the issue

Install the App on Xiaomi Mi9 Phone.

## Technical details

Phone: Xiaomi Mi9 (latest update),
App: from Play Store

**Comment by gizmo21** [comment] 2020-06-18 10:11
Could be related https://github.com/corona-warn-app/cwa-app-android/issues/621

**Comment by brokkoli71** [comment] 2020-06-18 11:35
same on Xiaomi 9T pro

**Comment by thecloudseeker** [comment] 2020-06-18 16:54
Same on Huawei P20. Even manually deactivated battery optimisations

**Comment by marcmuschko** [comment] 2020-06-18 18:49
Hi @Buntelrus,

thank you for reaching out to us! 
If I understand your description correctly, then you have installed the app on June 16th and since then your status is "Unknown risk" which is unexpected, especially since you opened the app yesterday and today. Or are you maybe now seeing the card containing "Risk calculation not possible", described in #637 ?

Could you provide some more details that might be relevant in this case, e.g. 
* did you update the app to 1.0.2 since the original installation on June 16th (if not, please disable battery optimization - I think you already did -, update the app to 1.0.2 and check the result tomorrow)
* did you change your bluetooth status from on / off, 
* have you been offline for a longer amount of time (except the first night June 16th - June 17th you already mentioned), 
* do you have apps installed that might impact battery management in addition to the default os behavior? 

Hope we can sort this out together! 
Thanks and best,
Marc

**Comment by thecloudseeker** [comment] 2020-06-18 18:55
Hi,
I not @Buntelrus but experiencing the same issue. 
For me it still states "Unknown Risk", the app is updated to 1.0.2, my bluetooth status is always on, and internet is on. And other than the system's there are no additional battery management installed.

**Comment by marcmuschko** [comment] 2020-06-18 18:58
@thecloudseeker when did you do the app update and when was the original installation?

**Comment by thecloudseeker** [comment] 2020-06-18 19:01
@marcmuschko original installation was on 16th of June and update was 11 hours ago

**Comment by corneliusroemer** [comment] 2020-06-18 19:13
May be related, wrong notification after failure to download exposure keys due to lack of internet.
https://github.com/corona-warn-app/cwa-app-android/issues/603#issuecomment-646197640

**Comment by marcmuschko** [comment] 2020-06-18 19:31
@thecloudseeker alright, thank you! As the app update today can affect the behavior of background activity, could you please monitor the behavior of the device until tomorrow evening and check if the status changes? After you lifted the battery restrictions and updated the app, the problem might be solved for you already.
I assume this is related to #637 and will be solved with our fix (in progress), but I would like to make sure this is not something different. If you can provide an update tomorrow, I'd really appreciate that :)

**Comment by Buntelrus** [comment] 2020-06-18 19:52
@marcmuschko
> If I understand your description correctly, then you have installed the app on June 16th and since then your status is "Unknown risk" which is unexpected, especially since you opened the app yesterday and today. Or are you maybe now seeing the card containing "Risk calculation not possible", described in #637 ?

This is correct. I see the card "Risk Unknown". I opened the app multiple times per day and checked if something has changed. But it has not.

> * did you update the app to 1.0.2 since the original installation on June 16th (if not, please disable battery optimization - I think you already did -, update the app to 1.0.2 and check the result tomorrow)

yes I did. Today I also set Settings->Apps->Manage Apps->Corona Warn->**Battery Saver** from "Battery saver (recommended)" to "No restrictions"

> * did you change your bluetooth status from on / off,

I played with it right after the installation and then I left it turned on. Expect offline mode in the night June 16th to 17th, on June 17th I turned off Location for a few Seconds.

> * have you been offline for a longer amount of time (except the first night June 16th - June 17th you already mentioned),

No

> * do you have apps installed that might impact battery management in addition to the default os behavior?

No

**Comment by Buntelrus** [comment] 2020-06-18 20:08
Risk Unknown card:
![image](https://user-images.githubusercontent.com/26169329/85066816-ec4bb880-b1af-11ea-8c85-bbf15eeb3c0e.png)
This is maybe also interesting. I can see that exposure logging has been active for 2 days:
![image](https://user-images.githubusercontent.com/26169329/85066843-f8377a80-b1af-11ea-9fdb-eeb0a36dd4ff.png)

**Comment by brokkoli71** [comment] 2020-06-18 21:30
I have exactly the same behaviour on my mi 9T pro.
- installed and activated on Tuesday 2am then Bluetooth switched off untill 10am. Afterwards Bluetooth, GPS and Internet activated alle the time.
- tried out all different battery options in system settings
- got exactly the same screen as shown in the screenshots from @Buntelrus 
- no additional battery-saving apps
- updated to 1.0.2
- Android Q

**Comment by thecloudseeker** [comment] 2020-06-19 07:31
@marcmuschko  I just checked the app, now it shortly shows unknown risk and then refreshes to low risk. So for the bug is fixed :)

**Comment by wuttkea** [comment] 2020-06-19 18:11
Same problem here. Other also discuss the problem on twitter.

Deactivated automatic management of the app which is often a problem for Huawei. But didn't help. 

Android 10
Mate 20 Pro
Tried to turn on off bluetooth
Tried to turn on off risk detection
Tried to restart phone after that
Internet connection and Bluetooth was almost always on
Update installed
no additional apps for battery management

**Comment by Buntelrus** [comment] 2020-06-19 19:40
### Update: Maybe there was a reboot required
I just enabled "Autostart" for Corona Warn App and rebooted my phone. After that I opened the App again. First exposure logging has changed its state to active and short time later risk status changed to low as you would expect. Before I rebooted my phone risk state was still unknown.

**Comment by brokkoli71** [comment] 2020-06-20 09:45
unfortunately this didn't work for me :(

**Comment by tkowark** [comment] 2020-06-21 12:12
In the meantime, the team identified a workaround that solved the problem at least for some users: https://www.coronawarn.app/de/faq/#no_risk_update. Would be great if you can let us know whether it worked for you as well.

Of course, the team is nevertheless still working on a proper solution for the issue.

**Comment by github-normalnutzer** [comment] 2020-06-21 14:08
Don't work for me, as i wrote here: #693

Happend on two Honor 9 devices, 
since installing the app 5 Days ago,
it stays at "Unbekanntes Risiko" 
No error warnings, all asked permissions are granted.
Including camera access, which i don't understand the need right now.
Accu optimizations for the app are checked and turned off.
APP Start options already set to "Manuell verwalten" 
and all three Options (Auto Start/Sekundärer Start/Im Hintergrund) are ON

I have noticed that for example, in the accuusage screen,
 WhatsApp stays as activ in the system after swiping it out.
Instead of the Corona App which shows inactive after swiping it out.

Don't know what to check next?

**Comment by jakobmoellersap** [comment] 2020-06-22 07:28
Also, could you check the Version of the App? There might be an update that solves the issue for you with 1.0.4

**Comment by brokkoli71** [comment] 2020-06-22 11:24
1.0.4 works for me just fine

**Comment by Buntelrus** [comment] 2020-06-22 11:58
As far as I could monitor, the App works now fine for me.

**Comment by tkowark** [comment] 2020-06-23 15:06
Since the issue is resolved for the issue creator, we'll close this one. If anybody else from the thread still has issues, please check the other open issues for similar setups/devices.

**Closed by tkowark** 2020-06-23 15:06 UTC
Labels: bug
