### ISSUE TITLE
2G plus-sign is wrapped to next line

### ISSUE THREAD

**Issue by fscholdei** [corona-warn-app/cwa-app-android#4720] opened 2022-01-21 19:28 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a
- Android version: 12
- App version: 2.16.2

## Describe the bug
I think this screenshot describes the problem quite well. 
![cwa-bug](https://user-images.githubusercontent.com/45232454/150587577-bfeeddf4-3f79-4f41-b169-e28fa5cb4e07.png)
The plus-sign in the status on the detail view after clicking on the QR code is wrapped to the next line.

## Steps to reproduce the issue
1. Go to 'Zertifikate'
2. Click on 'Digitales COVID-Zertifikat der EU'
3. Scroll down to 'Status-Nachweis'

## Expected behaviour
`2G+` instead of `2G<br />+`

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-11428](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11428)

**Comment by Ein-Tim** [comment] 2022-01-21 19:32
Twitter user confirming this issue: https://twitter.com/n_hamacher/status/1484086940534255617?s=20

**Comment by thomasaugsten** [comment] 2022-01-21 19:44
@fscholdei  Do you have any special font-size or accessibility feature active on the device active?

**Comment by MikeMcC399** [comment] 2022-01-21 20:18
@thomasaugsten 

A very similar issue is reproducible in Android Studio with default font-size.

Pixel 3a emulator
Android 11
Settings > Display > Advanced
Font size: Default
Display size: Default

Run Corona-Warn-`App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt`

View file `PersonDetailsFragment_cwa.png`

![PersonDetailsFragment_cwa](https://user-images.githubusercontent.com/66998419/150594247-0d0ce5ce-3869-429e-aee6-3f0f9ebf7859.png)

Setting Font size to small works around the issue.

**Comment by fscholdei** [comment] 2022-01-21 21:05
Font, size etc are all default.

![cwa-bug2](https://user-images.githubusercontent.com/45232454/150597683-6de71fbd-2504-4ddc-8ad2-451040a013f6.png)
The component seems to be rendered differently on the overview and can be displayed without problems.

**Comment by MikeMcC399** [comment] 2022-01-22 08:37
- It looks like this issue is already fixed in PR https://github.com/corona-warn-app/cwa-app-android/pull/4702 for the 2.17 version.

**Comment by MikeMcC399** [comment] 2022-01-22 11:42
@dsarkar 
The fix works well on Pixel 3a with font size: default. 

Unfortunately the fix does not cover all cases.

I tried on some other devices, setting the font size to the maximum possible. This did not always cause a problem, but on a Samsung Galaxy A52 Android 11, with font size set a bit higher then not even "2G" is displayed correctly in 2.17.x.

This device has 8 font size settings from the smallest to the largest, which I will call 1 (smallest) and 8 (largest). Font sizes 6-8 fail to display "2G" correctly.

Here is an example with font size 6:

![2G not shown](https://user-images.githubusercontent.com/66998419/150636926-52c020c6-f9b3-45e9-b439-0333574d1263.jpg)

The badge should show "2G", not just "2". Luckily the text shows the correct information, and it is only the badge which is not displaying correctly under all font-size settings.

**Comment by dsarkar** [comment] 2022-01-22 23:24
@MikeMcC399 Thanks for testing. I forwarded you findings to the internal ticket.

**Comment by MikeMcC399** [comment] 2022-01-24 11:47
@dsarkar 

## Suggested solution

https://github.com/corona-warn-app/cwa-app-android/blob/0f6f7f655f23cbcfb74006f45593c173bbdf0cff/Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml#L36-L37

Change badge height to `android:layout_height="wrap_content"` in L37 of `confirmed_status_card.xml`.

**Comment by dsarkar** [comment] 2022-01-24 11:53
@MikeMcC399 Thanks, will forward it to the internal ticket.

**Comment by dsarkar** [comment] 2022-01-24 11:56
@jurajkusnier see https://github.com/corona-warn-app/cwa-app-android/issues/4720#issuecomment-1020014035

**Comment by MikeMcC399** [comment] 2022-01-24 12:18
@dsarkar / @jurajkusnier 

I may have made a mistake in my testing. I need to re-check this. Sorry for any inconvenience!

**Comment by MikeMcC399** [comment] 2022-01-24 15:08
@dsarkar / @jurajkusnier 

There is still an issue in release/2.17.x

Samsung Galaxy A52 5G (SM-A526B/DS), Android 12

Settings > Display > Font size and style
set to largest possible
Settings > Screen zoom
set to smallest possible

1. Tap Scan
2. Scan 2/2 vaccination certificate
3. From Status view, tap Certificates
4. Tap QR code
5. Scroll down to "Proof of Status" (under CHECK VALIDITY FOR TRAVEL)

Results for
CWA 2.16.2
"2G" is not displayed, only part of "2"

CWA 2.17.0-RC2 (d8da2f883)
"2G" is not displayed fully, "2G" is cut off at the bottom

CWA 2.17.0-RC2 (d8da2f883) + suggested fix
Change badge height to `android:layout_height="wrap_content"` in L37 of confirmed_status_card.xml.
"2G" is displayed completely inside blue badge background.

**Comment by dsarkar** [comment] 2022-01-24 17:56
@MikeMcC399 Thanks a lot for the analysis, I forward this to the internal ticket.

**Comment by jurajkusnier** [comment] 2022-01-25 10:35
@MikeMcC399 @dsarkar 
thanks, I don't have a Samsung phone and I'm not able to reproduce it on other phones but feel free to test this PR https://github.com/corona-warn-app/cwa-app-android/pull/4733
I hope it fixes the issue

**Comment by MikeMcC399** [comment] 2022-01-25 11:02
@jurajkusnier 
- Thanks for the PR #4733! This fixes the issue that I was seeing with the "2G" display.

**Comment by MikeMcC399** [comment] 2022-01-25 18:06
- The additional fix https://github.com/corona-warn-app/cwa-app-android/pull/4733 has also been merged into [release/2.17.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.17.x).

The label [Fix 2.17](https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202.17) is already applied and we should be good for resolution when 2.17 is released.

**Comment by MikeMcC399** [comment] 2022-02-06 09:17
@fscholdei 

Are you able to check `2G+` with the latest version CWA Android 2.17.2?

I checked that `2G` was displayed correctly with large font size set.

**Closed** 2022-02-18 08:01 UTC
Labels: bug, mirrored-to-jira, ready-to-close, Fix 2.17, certificates

**Comment by dsarkar** [comment] 2022-02-18 09:26
@fscholdei Thanks for reporting and your feedback!
