### ISSUE TITLE
More prominent presentation regarding location services & BLE usage

### ISSUE THREAD

**Issue by chrjsorg** [corona-warn-app/cwa-app-android#488] opened 2020-06-16 06:51 UTC
## Current Implementation
Many users complain in the reviews that the app allegedly uses the tracking services. This is because BLE probably only works in conjunction with the location tracking services (I hope I get this correct). 
Although there is already a reference to this in the privacy policy, it would probably be useful to place this reference more visibly.

## Suggested Enhancement
Place this information "better" to create more confidence.

## Expected Benefits
Create a better understanding for the user and thus increase acceptance.

**Comment by SebastianWolf-SAP** [comment] 2020-06-16 06:52
This is a duplicate of #262. Please see this issue for details.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-16 06:52 UTC
Labels: duplicate, enhancement

**Comment by corneliusroemer** [comment] 2020-06-16 07:14
No this is not a duplicate. The referenced issue asked for in-app explanation.

This issue asks for better clarification BEFORE installation.
