### ISSUE TITLE
Publication details: neither mail nor phone number can be copied/clicked

### ISSUE THREAD

**Issue by ironjan** [corona-warn-app/cwa-app-android#636] opened 2020-06-18 11:16 UTC
## Describe the bug
Under "app information" - "publication details", the app shows contact information, i.e. mail and phone number.

## Expected behaviour
It should be possible to actually *use* the displayed information. Normal behavior for email addresses and phone numbers is to be interactable: I can click them and the appropriate action (start email client, start phone app) happens. This is not possible.

## Steps to reproduce the issue

1. Go to "app information" - "publication details"
2. Tap the mail address. Tap the phone number. 
3. Nothing happens.

1. Go to "app information" - "publication details"
2. Long tap mail address. Long tap phone number.
3. Nothing happens. Normally, text would get selected.

## Possible Fix

This issue is closely related to #616 and #633 . 

The root cause for these issues is the same: things that usually are clickable have been designed in a way that prevents these actions.

## Additional context

I am not interested in working on this issue. I am not sure if #564 already fixes this problem.

**Comment by ironjan** [comment] 2020-06-18 11:17
@eliaszemanek I did not review your PR - could you take a quick look at this issue and tell me if the problem is already fixed by your PR #564? If it is solved, I'll close the issue again.

**Comment by eliaszemanek** [comment] 2020-06-18 11:42
@ironjan Yes it will fix the issue. With autoLink enabled on the layouts you can click on links, addresses, telephone numbers and they will open in the right app. But you can't copy them within the app. 

Duplicate of #633

**Closed** 2020-06-18 11:49 UTC
Labels: bug
