### ISSUE TITLE
False high-risk warning (false positive)?

### ISSUE THREAD

**Issue by floriankuc** [corona-warn-app/cwa-app-android#1582] opened 2020-11-12 08:22 UTC
## Describe the bug

I have received a high-risk warning from the app. The encounter the app is referring to can't have occurred the way it's being described in the app ("Sie haben ein erhöhtes Infektionsrisiko, da Sie zuletzt vor 3 Tagen mindestens einer nachweislich Corona-positiv getesteten Person über einen längeren Zeitraum mit einem geringen Abstand begegnet sind.")

My app updates at night. I am unsure which exact date/24h span the app is referring to by stating "3 Tage seit der letzten Begegnung" instead of a specific date. Therefore I am considering a tolerance of +/- 1 days.

On the day of the supposed encounter (+/- 1 days) I was either:

1. Alone in my flat
2. In person A's flat with only me and person A present. Person A has not submitted a positive test result to the app.
3. Outdoors for a few hours, however: Never stationary for even 5 minutes (walking, jogging) and also together with the same person A who also has her app active at all times

Therefore I was either stationary for >= 10 mins with a person who hasn't submitted a positive test or I encountered potentially infectious people outside but only <= 10 mins while walking/jogging past them. Both conditions at the same time haven't met.

Attempted explanation from the local corona hotline: A positive-tested person must have followed us outside behind us and triggered the warning. The counter argument is person A who was right next to me at all times not having received any new warnings.

I am attaching my own log file and the person A's. The warning message was received on 11 Nov where it jumps from 3 to 8 encounters.

Is this a possible bug or is there another explanation for the app functioning the way it did? I spoke to a person from the technical hotline who encouraged me to open this issue.

## Steps to reproduce the issue

Log files of the corona app are attached.
[log_files.zip](https://github.com/corona-warn-app/cwa-app-android/files/5529124/log_files.zip)

## Technical details

- Mobile device: Samsung Galaxy A41
- Android version: 10

---
Internal Tracking ID: EXPOSUREAPP-3805

**Comment by thomasaugsten** [comment] 2020-11-12 13:43
"3 Tage seit der letzten Begegnung" means the last encounter was 09.11.20. But because you have 8 encounters it was not necessarily the last high risk encounter the last encounter. At the moment we are not able to show the days since the last high risk encounter but we will improve this in the next versions. Because of the missing information when exactly the high risk exposure was we cannot recreated the encounter situation. But you can check every day the app when the high risk encounter disappears then the encounter was 14 days ago.

**Comment by not-a-feature** [comment] 2020-11-12 15:32
If you have a rooted device, you can inspect your "high-risk-contact" using the app "Corona-Warn-Companion"
See: https://github.com/mh-/corona-warn-companion-android
or: https://play.google.com/store/apps/details?id=org.tosl.warnappcompanion

**Comment by Tradeturner** [comment] 2020-11-13 09:08
14 days ago my app turned red telling me: "Sie haben ein erhöhtes Infektionsrisiko, da Sie zuletzt vor 3 Tagen mindestens einer nachweislich Corona-positiv getesteten Person..." Than everyday this number turned up. 4 days ago, five days ago and so on. Yesterday it suddendly said 3 days ago again, implying that there must have been other High Risk Encounter and not a Low Risk Encounter. Today it turned green. How is this possible? @thomasaugsten you said about @floriankuc  issue"...you had 8 encounters it was not necessarily the last high risk encounter the last encounter." If this is true, it does leave me very angry. If this is true the warning text in the app "Sie haben ein erhöhtes Infektionsrisiko, da Sie zuletzt vor 3 Tagen mindestens einer nachweislich Corona-positiv getesteten Person über einen längeren Zeitraum mit einem geringen Abstand begegnet sind." is not only missleading but simply wrong, because it does state that the High Risk Encounter has been 3 days ago. Thank you.

**Comment by floriankuc** [comment] 2020-11-13 09:38
I need to provide a quick update about how my case developed. Today, one day later and after an update from 1.5.x to 1.6.0 the following happened. The behaviour still feels wrong and might be related to what @Tradeturner wrote.

1. I received a notification about my high-risk encounter having been **14 days ago** now instead of **Monday** and that my risk is being reevaluated back to "low".

![2ada7055-0815-4123-af82-48953b4a5c3d](https://user-images.githubusercontent.com/59569310/99056642-e6110b00-259a-11eb-9d60-f7cc03b8df8d.jpeg)

2. However, the current state of my app even after restarting both the app and my mobile device still looks like this. Still red and still I am led to believe my high-risk-encounter (which cannot have happened to begin with I believe) supposedly occured 4 days ago.

![92502d69-7c56-4d6d-881d-16b26c10bc9c](https://user-images.githubusercontent.com/59569310/99056677-f1fccd00-259a-11eb-9ddb-a88917e497de.jpeg)

Summing it up:
- 2 - 3 green encounters for the past weeks in my app until Wed, 11 Nov.
- On 11 Nov: Switched to red, switched from 3 to 8 encounters (again, while being inside/alone/or outdoors but constantly moving), says there was high-risk encounter 2 days ago (Monday, 9 Nov)
- On 12 Nov: Lost one encounter, down to 7 from 8, still red, still points to Monday for last high-risk encounter (3 days ago)
- On 13 Nov: Still 7 encounters, still red but tells my a high-risk encounter happened 14 days ago and therefore my risk is set back to "low" **but** still displays red, still states my high-risk encounter happened on Monday (4 days ago).

At this point as a user I am clueless about how this happened, what the app measured and/or what it's trying to tell me. No matter how you look at it, something feels off.

**Comment by gachewurzn** [comment] 2020-11-16 11:03
I have the exact same behaviour. A high risk encounter on a day where I didn't leave the apartment and a couple of days later an incorrect notfication of a low-risk / green status update. The app still shows high-risk / red and the alleged high-risk contact was five days ago according to the app.
(Samsung Galaxy S9+ / App Version 1.6.0)

**Comment by ThomasMM20** [comment] 2020-11-16 17:26
For your info, regarding numbers of days since last high-risk contact: I have a quite similar behavior, but technical hotline told us, up to now there is no high validity in the numbers of "days shown since your last encounter". Was told you can easily add 2 more days to it. Which makes perfectly sense because for this timeline ("2 days ago" displayed, plus 2 more days added) I had the only possible contact >10 mins and <2 meters since weeks. But then, 1 day later, the app now tells me the status has changed because the encounter is now more than 14 days back. What?

**Comment by vaubaehn** [comment] 2020-11-16 17:44
Hi @ThomasMM20 ,

> technical hotline told us, up to now there is no high validity in the numbers of "days shown since your last encounter". Was told you can easily add 2 more days to it.

I don't know if there was probably any misunderstanding, or there is a problem with the helpline... But the information you received is not correct.
It's as simple like this: either your device records any contact or not. If it is recorded, the timestamp of the encounter is also recorded. If the contacts is tested positive later, and shares the test result, then the exact timestamp is used to compute and  report the "days since last encounter".



> But then, 1 day later, the app now tells me the status has changed because the encounter is now more than 14 days back. What?

This means, that it took 13 days after your encounter for your contact to get tested, to receive the test result and to finally share the test result that you could have get warned. For me it's not surprising, as we could read in the past weeks, that laboratories had problems in getting their tests done in a timely manner. So, if your encounter was 13 days ago, five days later the contact felt sick, went to doctor 2 more days later, and then probably received the test result 5 or six days later, then it's rather possible that you have been warned that late.

So, probably the guy from the helpline meant, was referring to the delay of the upload/sharing of the test result, that you can easily add 2 days, until you get the warning (after the upload).
But the "days since last encounter" should always be correct.

Regards, v.

**Comment by ThomasMM20** [comment] 2020-11-16 18:48
Hi Vaubaehn,

thanks for your effort indeed. 
> This means, that it took 13 days after your encounter for your contact to get tested ...

But but but: The message shown does not talk about numbers of days since positive testing, it talks about numbers of days since contact. The encounter I am thinking about I only met once, 4 days ago. So your mathematics about plenty of days backwards does not seem plausible to me.
Kind regards,
T.

**Comment by vaubaehn** [comment] 2020-11-16 19:50
Hi again @ThomasMM20 ,

> But but but: The message shown does not talk about numbers of days since positive testing, it talks about numbers of days since contact.

Yes, yes, yes: like I wrote in the later edited part of my comment (which had not been part of the e-mail notification), I overlooked that 2/4-days-ago-contact. However, what you described would technically only make sense, when you had a high risk contact about 13 (now 14) days ago, and a low risk contact 2 (3) days ago, and both contacts uploaded their positive test in the same day 1 (2) days ago. By that, you would get a red warning from the old contact, but the "days since encounter" would reflect the low risk encounter though. After 14 days the contacts are deleted from your device. Then the high risk encounter would disappear, and the low risk encounter warning (without any "days since encounter") would persist. But to validate, if it was the case, we would need to have a look into your ENF-log:
Could you go to Android settings > Google > COVID-19 exposure notifications > exposure checks. Then use the three dot menu to export the ENF log. Before uploading, rename the file extension from .json to .txt, and then attach it to your comment.
We probably won't find the high risk encounter anymore, because it should already be erased from the log, but maybe we can find out about the last encounter a couple of days ago.

**Comment by vaubaehn** [comment] 2020-11-16 20:07
@ThomasMM20 : what I also forgot to ask: is your risk card still red, like other users experienced above?

**Comment by thomasaugsten** [comment] 2020-11-16 20:16
The issue is here the Google ENF is returning on long exposure check a 0 result but a few  seconds later the correct result with the high risk is returned. This leads to this wrong notification we are in contact with google fix this or to recognise this wrong intermediate result

**Comment by ndegendogo** [comment] 2020-11-16 20:48
> But the "days since last encounter" should always be correct

@vaubaehn Do we know how ENF is rounding the time difference to days? For me, "yesterday" and "one day ago" are the same, but they might round it down to 0 days if it is < 12 hours (or even < 24 hours?)
Also if the check was yesterday, but I look at cwa today, I see again one day less than I would expect naively.

**Comment by ThomasMM20** [comment] 2020-11-16 20:51
Hi all,

thanks for your comments & help.
Attached the download file. Looks like there are 3 matches throughout the last 3 days and  nothing before, as expected.
And yes, the risk card is still red.

Take care,
T.
[all-exposure-checks-sorted.txt](https://github.com/corona-warn-app/cwa-app-android/files/5549571/all-exposure-checks-sorted.txt)

**Comment by vaubaehn** [comment] 2020-11-17 14:13
@thomasaugsten hi, and thanks for your clarification! This will save us some time and efforts to investigate further...

@ThomasMM20 hi, and thanks for your ENF log. With your log, your description and @thomasaugsten 's clarification, it's now clear that it's a bug and not some rare 'technical situation'. So, let's sit and wait for the fix.

@ndegendogo hi :) 

> Do we know how ENF is rounding the time difference to days?

Tbh, I don't know... But if I was coding it, I would base it on full UTC days (in coherence with all other time operations, like resetting API call counter, etc.). So I would expect, if it's 11/17/2020 2:00am UTC, and the contact was 30 hours ago, the result should be "2 days since encounter". But if it's really handled like this by the ENF, I don't know.
At least, there are some hints that it could be handled differently by ENF: when the timestamp of the encounter is transcoded to a time span ("days") on the fly at the moment when the Exposure Summary is requested from ENF by the app. Then it would depend on the rounding algorithm how much days would be 30 hours like in the example above (1 day by cutting the decimals or rounding down? 2 days by always rounding up?). If that was applied here, and CWA is always fetching an exposure summary every time it is opened/resumed, then perceptions like in #1358 would make sense: If one preceeding match/encounter is outdated after 336 hours (14 days), and the exposure summary in enf is refreshed during the course of the day (by CWA requesting a 'new' summary), then it could be, that in the morning there is a higher number of matches than in the afternoon. But this would require CWA to call `refreshRequiredData()` and to subsequently to call `tracingRepository.refreshExposureSummary()` with every `onCreate()` or every `onResume()` - and if this is the case has not been answered by the devs yet :wink:.

**Comment by dsarkar** [comment] 2020-11-24 08:35
Dear community,

We have recent feedback from the developers. They have reviewed this issue here, and confirm that the expected behavior is to show the red card

**Comment by aelteach** [comment] 2020-11-27 06:20
Dear community, 

my app shows the same bug and I have tried to follow your discussion as much as I can, but I couldnt quite figure out whether @ThomasMM20 did indeed have a high risk encounter or if this was a false alarm.
I did get tested because of the app and Im waiting for my results now, but Im a teacher and it is very important for me to know if I infected my students and the other teachers at my school.

**Comment by dsarkar** [comment] 2020-11-27 10:57
Dear @aelteach,

Many thanks for contributing. Could you please prove some more detailed information, please.

- Android Version:
- CWA version: 
- Mobile device:
- Upload ENF files.
- Screenshots

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by aelteach** [comment] 2020-11-27 11:48
Dear @dsarkar, 

thank your for your reply! 
My android version is 10
the version of CWA is 1.6 (I couldn't find the most recent update in the Playstore)
my mobile device is a Samsung Galaxy M30s
I'm afraid I don't know what ENF files are
and attached you'll find my warning messages from yesterday and today. 
This morning I also received the same message that @floriankuc had received regarding "Änderung Ihres Risikostatus", saying that my high-risk encounter had expired. Within seconds however the app switched back to red, saying the high-risk encounter occurred three days ago (which is impossible). 

![Screenshot_20201126-092246_Corona-Warn](https://user-images.githubusercontent.com/75111017/100446084-77f63900-30ae-11eb-8077-fb340ed19fb9.jpg)
![Screenshot_20201127-122307_Corona-Warn](https://user-images.githubusercontent.com/75111017/100446096-7b89c000-30ae-11eb-8484-6a090c86265e.jpg)

**Comment by dsarkar** [comment] 2020-11-27 12:42
Dear @aelteach, Thanks!

- Unrelated to this issue, could you do me a favor, please. Can you upload a screenshot(s) similar to the first one, but showing also the lower part with the explanation 'Verhalten'. Thanks.

- Thanks for all the feedback. See this comment, please: https://github.com/corona-warn-app/cwa-app-android/issues/1582#issuecomment-732742456. Will be resolved.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by aelteach** [comment] 2020-11-27 13:17
Dear @dsarkar , 
I'm glad the bug will be resolved with the update, but my question is on the nature of the bug (that's what I didn't get from your discussion above). Is it that the app displays a high-risk encounter although I haven't had any of those? Or is it rather that my app is wrong saying that I had met this person 3 days ago? 

But thank you for your help and attached you'll find the screenshot with the "Verhalten" 


![Screenshot_20201127-135841_Corona-Warn](https://user-images.githubusercontent.com/75111017/100453002-85b1bb80-30ba-11eb-8c7c-27a6c7237200.jpg)

**Comment by dsarkar** [comment] 2020-11-27 13:53
@aelteach, 

- can you down on that screen, and make a screenshot, or is it not possible? Thanks
- In this specific case, my understanding is that your high-risk encounter his in the past and has expired and it should be green. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by aelteach** [comment] 2020-11-27 14:35
@dsarkar 
This is what I find below the "Verhalten" 
![Screenshot_20201127-152013_Corona-Warn](https://user-images.githubusercontent.com/75111017/100459297-8c91fb80-30c5-11eb-8540-61b2a9b1dfe2.jpg)
![Screenshot_20201127-152020_Corona-Warn](https://user-images.githubusercontent.com/75111017/100459300-8dc32880-30c5-11eb-8292-921a8e901b9e.jpg)

Thank you for your help! It's a big relief to hear that this might be a false alarm :-)
Best wishes

**Comment by dsarkar** [comment] 2020-11-27 14:44
@aelteach, Thanks for sceenshot.

**Comment by ndegendogo** [comment] 2020-11-27 21:12
@dsarkar sorry, but now I am confused.
@thomasaugsten mentioned [in his comment](https://github.com/corona-warn-app/cwa-app-android/issues/1582#issuecomment-728300098) a bug in Google ENS that leads to conflicting messages in cwa

> The issue is here the Google ENF is returning on long exposure check a 0 result but a few seconds later the correct result with the high risk is returned. This leads to this wrong notification we are in contact with google fix this or to recognise this wrong intermediate result

which I understand the notification is wrong and the red card is correct ...
So is this comment outdated? Have there been more insights on this meanwhile?

**Comment by heinezen** [comment] 2021-02-09 14:36
This cannot be reproduced anymore from our side, so I assume we can close the issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-02-09 14:36 UTC
Labels: bug, mirrored-to-jira
