### ISSUE TITLE
Checkout Button in QR-Page overlaps

### ISSUE THREAD

**Issue by nicolajlerch** [corona-warn-app/cwa-app-android#2998] opened 2021-04-28 16:26 UTC
How to reproduce:
Create QR Code for educational purpose.
Let's anyone check-in (checkout button visible)

![Screenshot_20210428-182135](https://user-images.githubusercontent.com/48556806/116438852-2ca7a880-a84f-11eb-9551-1e5d027a1c4b.jpg)

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- Android version:
- App version:

**Comment by MikeMcC399** [comment] 2021-04-28 16:36
@nicolajlerch 

This error has been reported previously, however each time the issue has been closed before a fix has been released!

See https://github.com/corona-warn-app/cwa-app-android/issues/2896 and https://github.com/corona-warn-app/cwa-app-android/issues/2849.

It is scheduled to be fixed in the upcoming 2.1 release.

**Comment by MikeMcC399** [comment] 2021-04-28 16:58
The issue is tracked under the internal ID EXPOSUREAPP-6534 and the fix is in the PR https://github.com/corona-warn-app/cwa-app-android/pull/2826 which has been merged already into the [release/2.1.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.1.x) branch as part of the [v2.1.0-RC0 release candidate](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.1.0-RC0).

**Comment by MikeMcC399** [comment] 2021-04-28 17:19
@nicolajlerch 
I suggest that you close this issue, since it is a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/2849.

https://github.com/corona-warn-app/cwa-app-android/issues/2849 has been reopened, so it is now clearer that the fix has not yet been released.

**Comment by nicolajlerch** [comment] 2021-04-28 18:50
Fixed in other ticket

**Closed** 2021-04-28 18:49 UTC
Labels: bug

**Comment by dsarkar** [comment] 2021-04-29 06:49
Hi @nicolajlerch Many thanks for contributing here in any case.
@MikeMcC399 Thanks for pointing out the duplicate!

Best, DS 
---
Corona-Warn-App Open Source Team
