### ISSUE TITLE
android.process.media is suddenly using more of the processor

### ISSUE THREAD

**Issue by Bumblebee38** [corona-warn-app/cwa-app-android#598] opened 2020-06-17 13:42 UTC
## Describe the bug

After installing the app and turning on the "Risiko-Ermittlung", I saw that the battery of my phone drains way faster than usual and is also heating up really fast. After letting the app in the background for a few hours I looked up what drained the most of my battery. 

The Corona-Warn-App itself did not drained really much from the battery.
![Corona Warn](https://user-images.githubusercontent.com/49358620/84904007-18cbdb80-b0af-11ea-9645-79a675108bbb.png)

Instead, the system process "android.process.media" drained really much by using around 25% of my phones CPU in average which seems to be the reason why my phone is getting hot so quickly! 
![android process media](https://user-images.githubusercontent.com/49358620/84903815-da362100-b0ae-11ea-928b-c538a1f1f3b8.png)

This was still happening after several times of restarting my phone. 

## Expected behaviour

Instead of heating up by using so much of the processor, it should use a little bit of resources. 
Usually it does not heat up like this because there is no process on my phone which would use so much resources in the background. 
![normal day](https://user-images.githubusercontent.com/49358620/84904616-cd65fd00-b0af-11ea-9661-3fc6cf067daf.png)
_This is a picture of how the battery and the processor are being used on a normal day of usage before installing the Corona-Warn-App._

## Steps to reproduce the issue

1. Turn on "Risiko-Ermittlung"
2. Close the app as everything else is happening on its own

## Technical details

- Sony Xperia Z2
- Android 6.0.1

## Possible Fix

It would make sense to me if this is happening because the random keys of other phones are written to the memory of my phone. But instead it should be written to the memory in a lower frequency (if this is the problem) to reduce the usage of the processor and the heat and fast draining because of the high usage.

## Additional context

I think that the sudden high usage of this process is because of the Corona-Warn-App. To see if this is true, I would like to help with creating log files if there are needed. If any logs or anything else are needed, please let me know and please let me know how to go on to create such things.

It can be of course because of any other reason which would be not because of the app. But it would make sense since it started to behave like that after I activated the "Risiko-Ermittlung".

**Comment by jakobmoellersap** [comment] 2020-06-17 14:00
Hi @Bumblebee38 and thanks so much for your detailed issue description. Could you provide us with a consumption profile while Risiko-Ermittlung is turned off? It is highly unlikely that we have key writing problems to memory, so we would need as much information as we can get.

BR,
Jakob

**Comment by coder66** [comment] 2020-06-17 14:32
On my Huawei Mate 20 Pro (Android10), I have also noticed a battery drain issue with the 1.0.0 version of the app. The phone battery drops more quickly after I installed and activated the app. In the battery usage the actual Corona Warn app is only showing with low usage, but something is draining the battery.

![Screenshot_20200617_162859_com huawei systemmanager](https://user-images.githubusercontent.com/14278231/84911117-05713e00-b0b8-11ea-856d-4b3a5d7eebb7.jpg)

**Comment by jakobmoellersap** [comment] 2020-06-17 14:47
Could it be that other apps that previously were not able to use Bluetooth and or Location Services now are able to use these properly and thus drain your battery? As you can see in both screenshots, our App really does not have a major impact on battery life. We are constantly monitoring your feedback and will react as soon as we see an issue that is directly correlating with our Application Battery Consumption.

**Comment by coder66** [comment] 2020-06-17 14:57
Location services were on prior to installing the app. The device has BT 5.0 LE, and there are 3 other devices saved in BT connected devices, but these are all not actively connected. On Android 10 you can set to give apps only location access when they run in foreground, which I have done with all apps asking for this permission. The Corona Warn app does not ask for location service access.

**Comment by jakobmoellersap** [comment] 2020-06-17 15:29
Thanks for your detailed description of the context. Regarding your issue @coder66: What Apps / Processes actually do consume energy though? Also android.process.media like mentioned above?

**Comment by Bumblebee38** [comment] 2020-06-17 20:52
I turned "Risiko-Ermittlung" off while Bluetooth was on for six hours (I changed the setting at around 3pm). At the beginning of this time I did not use my phone. Then at around 6pm I used it with a moderate CPU usage so that it consumes resources from the CPU while a process was in the foreground so that I have scenarios of how I would use my phone to test the produced heat, the battery consumption and the CPU usage. 

After turning off "Risiko-Ermittlung" and Bluetooth on to test if other applications were using Bluetooth, I felt that my phone did not heat up and the battery consumption was really low. After looking up, I saw that the CPU usage in average was quite low because of android.process.media which was not active in the background the whole time using 25% of the CPU. 

While android.process.media was active in the background, the battery went in six hours from 100% to 25%. After turning off "Risiko-Ermittlung" it went in six hours from around 100% to around 50% which is a way better result. 

![Screenshot_20200617-222804](https://user-images.githubusercontent.com/49358620/84947207-1dfa4c00-b0ea-11ea-9bdf-1bbf770f08a5.png)

The battery consumption of the Corona-Warn-App itself was still the same. 
![Screenshot_20200617-222907](https://user-images.githubusercontent.com/49358620/84947210-1f2b7900-b0ea-11ea-8ce1-ac40c4228232.png)

But this could now mean that there is something between the Corona-Warn-App and android.process.media at least on my device, right? And because I let Bluetooth on while testing and the heat as well the battery consumption as well the CPU usage were not high as before, this would mean that at least in my test case there was no process which would be using more CPU resources by using Bluetooth while being active in the background.

**Comment by jakobmoellersap** [comment] 2020-06-18 13:05
We are in contact with Google about this and hopefully cannot update soon.

**Comment by coder66** [comment] 2020-06-18 13:28
A friend of mine with an iPhone has also told me that since he has the app installed, the battery drain has gone up. iOS does not have android.process.media but perhaps there is an equivalent module?

**Comment by jakobmoellersap** [comment] 2020-06-18 14:55
For this issue I would ask your friend to open up something separate on the iOS Repo. 

Also, I highly suspect something like a 3rd party process that results in this behaviour, as we only make use of the native frameworks for tracking. Additionally, we have no read/write intensive code during the exposure tracking, nor heavy network traffic inside the app that could result inside this amount of CPU Consumption. From our standpoint this is simply an unrealistic amount of resource consumption.

For me this makes the issue possible and not invalid, but instead not reproducible. I would ask for more context of other apps running on your phone that could interfere with the Corona-Warn-App to make sure that it really is our App that is at fault.

**Comment by coder66** [comment] 2020-06-18 14:59
Okay, will do that. I know, without reproduction the issue is not an issue ;).

Btw, yesterday Corona app 1.0.2 dropped and also Google Play Services had an update to 20.24.13 (I am enrolled in the beta program). The battery drain seems to be normal today, just as always. Just thought I'd mention it, but as there were two updates I am not sure how the relation is.

**Comment by jakobmoellersap** [comment] 2020-06-18 16:42
I will close this issue as not reproducible as a result of the discussion.

**Closed by jakobmoellersap** 2020-06-18 16:42 UTC
Labels: bug, in progress
