### ISSUE TITLE
Can't remove test

### ISSUE THREAD

**Issue by Frederik-FJ** [corona-warn-app/cwa-app-android#1435] opened 2020-10-19 18:53 UTC
## Describe the bug

I had a Covid-Test a long time ago. I never got the result in the app due to some complications in the covid-test-station. I never removed the test and now I can't remove it without deleting all informations.

## Expected behaviour
That I could just go into the test-tab an delete the test there
![image](https://user-images.githubusercontent.com/47251513/96498320-31f6bb80-124c-11eb-8d84-13fd6d452794.png)

## Steps to reproduce the issue

1. Register a test
2. Don't delete it for a long time

## Technical details

- Mobile device: Samsung Galaxy A6
- Android version: 10

**Comment by parttimehorse** [comment] 2020-10-19 19:15
I believe this is a duplicate of Bug #1084 - unfortunately, that bug has been around for a while now and the fix isn't exactly in sight yet. I experienced the same issue, and there is a workaround. 

Open the CWA, tap on the three dots in the upper right corner, go on Settings and tap "Reset App". Now, this does **not** delete your stored collected keys of the last 14 days (do not reinstall the app, that DOES delete those). But it will reset the timer of how long exposure logging has been active and remove the defunct test. It might set your risk status to unknown for 24 hours but if someone you encountered has tested positive, you will be warned.

**Comment by daimpi** [comment] 2020-10-19 21:26
@Frederik-FJ I second what @parttimehorse said ^

Regarding
> It might set your risk status to unknown for 24 hours […]

If you want there is even a workaround which will give you "14 days active" status right after resetting the data if this is something you care about: https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690615473

**Comment by svengabr** [comment] 2020-10-20 08:24
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1084

**Comment by svengabr** [comment] 2020-10-20 08:28
@Frederik-FJ Thank you for your feedback! As already mentioned this issue is a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1084 so I need to close this one. 

I am glad the workaround mentioned by @daimpi did help you in the short term. However, the developers are still working on a real solution at the moment,

Please move the discussion to the main issue.

Thank you for your understanding!

Best regards,
SG

Corona-Warn-App Open Source Team

**Closed by svengabr** 2020-10-20 08:28 UTC
Labels: bug, duplicate
