### ISSUE TITLE
Vaccination certificate validation time uses UTC+0 timezone

### ISSUE THREAD

**Issue by mawis** [corona-warn-app/cwa-app-android#3562] opened 2021-06-28 07:05 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Poco F2 Pro
- Android version: 11
- App version: 2.4.2
- Time zone of the device: Europe/Berlin

## Describe the bug

I was vaccinated the second time at June 13th. As it was confirmed in #3561 that means the certificate should get valid June 28th. Looking at the app at 1:08 a.m. the certificate was still in the state where it isn't valid yet. Looking at it again at 7:00 a.m. the certificate was valid.
Looking at the code, it seems to me that calculations were done in UTC, so probably the state changed at 2:00 a.m. Being in Germany under German jurisdiction the correct timezone to do the calculations probably should be Europe/Berlin.

## Steps to reproduce the issue

1. Get a certificate for a second vaccination, that is not valid yet
2. Import it to the CWA
3. Check the counter of days remaining for the certificate to become valid
4. Verify that the number of days does not change at midnight in Germany but at a later moment during the night.

See also the following screenshot taken at 2021-06-28 at 01:08+0200:
![](https://matthias-wimmer.de/CWA_Problem.jpeg)

## Expected behaviour

Calculated remaining days as well as the change of the certificate status should happen at midnight German time.

---
Internal Tracking ID: [EXPOSUREAPP-8121](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8121)

**Comment by Ein-Tim** [comment] 2021-06-28 07:10
Please check the behavior under iOS here. 

Maybe @DerVogel2020 could do this (by changing the system time)?

**Comment by DerVogel2020** [comment] 2021-06-28 07:31
> @Ein-Tim 
> Maybe @DerVogel2020 could do this (by changing the system time)?

No, that's not possible.

**Comment by Ein-Tim** [comment] 2021-06-28 07:33
@DerVogel2020 

Okay, then the devs have to check this.
Thank you anyways.

**Comment by dsarkar** [comment] 2021-06-28 07:43
@mawis Thanks for reporting. Issue is being analysed by the developers currently.

**Comment by Ein-Tim** [comment] 2021-06-28 14:23
FYI: PR: #3567

**Comment by MikeMcC399** [comment] 2021-06-28 14:53
@Ein-Tim 
Thanks! It looks like PR https://github.com/corona-warn-app/cwa-app-android/pull/3567 is being prepared as a hotfix for 2.4.x.

**Comment by MikeMcC399** [comment] 2021-07-01 11:56
I'm seeing [CWA Android 2.4.3](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.4.3) released and available in the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp).

PR #3567 is included in this release.

**Comment by DerVogel2020** [comment] 2021-07-01 13:23
Works for me now!

**Comment by mawis** [comment] 2021-07-01 21:07
Thanks for the update!

**Comment by dsarkar** [comment] 2021-07-02 09:03
Dear community, dear @mawis thanks for contributing and reporting this issue.
@DerVogel2020 confirmed the fix. We will close this issue now. 


Thanks, Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed** 2021-07-02 09:06 UTC
Labels: Fix 2.4.3, bug, mirrored-to-jira
