### ISSUE TITLE
Indefinite "Datenabruf..." of old test

### ISSUE THREAD

**Issue by PostmanLee** [corona-warn-app/cwa-app-android#1411] opened 2020-10-15 10:58 UTC
I had a test about a month ago. The result was shown correctly for about two weeks.
Now the tile shows "Datenabruf ... Das Ergebnis wird aktualisiert" forever and I do not have an option to delete the test without resetting the whole app data including the contacts.

So: As a user, I want to be able to delete old tests, so I can add new ones when needed.

**Comment by MikeMcC399** [comment] 2020-10-15 11:11
Hi @PostmanLee 

This is the same as the issue reported in https://github.com/corona-warn-app/cwa-app-android/issues/1084.

**Comment by heinezen** [comment] 2020-10-15 12:56
Hey @PostmanLee ,

As pointed out by @MikeMcC399 your issue seems to be the same as #1084. Updates oon the progress of fixes and workarounds are posted in the linked thread to make it better to track for everyone. Please continue the discussion there.

I will now close this issue as a duplicate. If you still think the behaviour you experienced is different from the one in #1084, you can comment here and we will reopen this issue.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-15 12:56
Duplicate of #1084

**Closed by heinezen** 2020-10-15 12:56 UTC
Labels: bug
