### ISSUE TITLE
Device stops sending beacons

### ISSUE THREAD

**Issue by michaelwingender** [corona-warn-app/cwa-app-android#858] opened 2020-07-12 13:12 UTC
I have accidentally found out that there seem to be devices that stop sending beacons. I was playing around with RamBLE and saw only one device sending out beacons for exposure notification. There were devices where I expected to see beacons. Asking the people they confirmed that they both have the app installed. Checking the status on the devices both were showing activated state. After finding out which device was not sending beacons by checking RSSI, "Risikoermittlung" was deactivated and activated again. Immediately the device start sending beacons. So the mechanism seems not be very reliable. The device was Nokia 6.1 with latest available updates. You should implement some mechanism, which gives the user the possibility to see whether his device is working correctly or not. It should not be necessary for normal user to ask some "cracks" with "hacker apps" to confirm correct functionality of their device. According to some entries in Caschys blog there seem to be other users with similar issues. They claim that they have installed the app on four devices but they only see beacons for two devices. Therefore they think RamBLE is not able to identify devices with installed CWA.

---
Internal Tracking ID: EXPOSUREAPP-1933

**Comment by tkowark** [comment] 2020-07-17 15:22
Thanks for reporting this issue, @michaelwingender 

Just as a hunch, this could be somewhat related to https://github.com/corona-warn-app/cwa-app-android/issues/858 but further investigations would be needed to clarify.

Regardless of the underlying root cause (which we most likely cannot fix from within the app, but it requires an OS level fix), would the following _mitigation_ be sufficient from your point of view?:
* As soon as any change in the system disables the exposure logging, a notification outside the app should be created to make the user aware of that fact

If this notification then reappears frequently due to some OS bug, at least it is clear where the root cause resides...

The general idea of providing more feedback about whether the app works as expected is captured in this wishlist item: https://github.com/corona-warn-app/cwa-wishlist/issues/5

**Comment by heinezen** [comment] 2021-01-12 11:59
There haven't been similar reports for this in a while, so we are closing this issue. The app has also gained additional features to detect faulty behaviour (e.g. the dead man notification). If this problem still occurs, please open a new issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-01-12 11:59 UTC
Labels: bug, mirrored-to-jira
