### ISSUE TITLE
"all-exposure-checks"-File does not match exposure event (Risko-Begegenung-Counter) in CWA 

### ISSUE THREAD

**Issue by jeschket** [corona-warn-app/cwa-app-android#930] opened 2020-07-25 18:32 UTC
In the exposure log file "all-exposure-checks" you only can find the log of the last 7 days but the CWA was active for more than 14 days. I would expect logs for all 14 days and not only the last 7 days because the person carrying the phone with CWA lives in Berlin in the City-Center and many contacts highly likely. 

[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/4976165/all-exposure-checks.txt)

And in the exposure log file "all-exposure-checks"  you don't find an event with "matchesCount":**1** but in the CWA you can see that there was one exposure event ("1 Risko-Begegenung"). 

**How can there be no match in the log-file but one exposure event ("1 Risko-Begegenung") displayed in the CWA?**

Please see log file and pic. 

![7fec7f0b-1242-40ea-a438-afd01ca97813](https://user-images.githubusercontent.com/46868732/88463696-e2a32800-ceb4-11ea-8392-f4aa4ccac525.jpg)

---
Internal Tracking ID: EXPOSUREAPP-1924

**Comment by daimpi** [comment] 2020-07-25 19:59
Interesting that there are zero match counts. Also curious that `keyCount` = `matchesCount` = 0, until the 23rd (which is what I generally expected after reading [those](https://github.com/corona-warn-app/cwa-app-android/issues/744#issuecomment-650302530) [comments](https://github.com/corona-warn-app/cwa-app-android/issues/744#issuecomment-650532041)), but from the 24th on the `keyCount` is suddenly > 0 while `matchesCount` stays on 0. I just checked in my Phone and found the same pattern, but starting already from the 23rd with `keyCount` >0. Maybe that's the new ENF v1.5 being rolled out?

Regarding the issue of only seeing the last 7 days: This could be b/c of the overly eager “energy saving” of the manufacturer OS. It would also fit your log in the sense that not only are days before the 18th missing, but also on the 21st there was seemingly no check performed. In the latest CWA version there is a setting which can fix this problem: Within CWA go to “settings” and enable “Prioritized Background Activity”: https://www.coronawarn.app/en/faq/#no_risk_update

Anyway: it is indeed strange that there are no matches in the exposure check logs, do you still remember when you first saw the "one risk encounter" display?

**Comment by jeschket** [comment] 2020-07-26 07:20
_Anyway: it is indeed strange that there are no matches in the exposure check logs, do you still remember when you first saw the "one risk encounter" display?_ 

The person said she did not open the CWA between 13.07.2020-21.07.2020 and up to 12.07.2020 there was no "risk encounter" shown. The one risk encounter was noticed on the 22.07.2020 in the CWA and is still shown to this day (26.07.2020).

**Comment by daimpi** [comment] 2020-07-26 10:57
I see, thanks for the detailed info :)

Something strange seems to be going on which the devs should take a look at.

**Comment by GPclips** [comment] 2020-07-26 14:24
@jeschket thanks for pointing this out. I will bring take this item into the discussion with our development team.

**Comment by daimpi** [comment] 2020-07-26 14:35
@GPclips could you maybe leave this issue open until it is resolved? Because currently anyone else who has this problem will not easily find that this issue has already been raised which might lead to unnecessary duplicates. Also: just for tracking purposes it would make sense to have the status of issues which are not yet resolved as "open".

**Comment by GPclips** [comment] 2020-07-26 14:37
@daimpi sure, thank you. accidentally hit the wrong button :-)

**Comment by daimpi** [comment] 2020-07-27 21:57
I might have found part of the puzzle: I was checking my ENF log for the last two days and found that even though it shows “237 checks performed in the last 14 days", when I select this to see the actual checks, it only shows me 100 entries. If I export the data, the .json file also contains only 100 entries. 
<img src="https://user-images.githubusercontent.com/22129968/88575206-c5e92a80-d043-11ea-87f3-a6b3beb4329e.jpg" width="400">

On the next day the 14 entries which were on top of the list the previous day, were not not shown anymore and were also missing from in the .json file. Instead 14 new entry with the checks performed today were inserted in the bottom third of the list (but not at the end). The length of the list therefore remained exactly at 100. Additionally the “checks performed” counter was decremented by 14 to 223. 

So my guess is that Google somehow limits the number of checks it will list to 100, even though it might have performed more checks. And given that the order in which days appear in the log seems to follow no discernible pattern it could be that your friends checks on the 21st were on top of the list and got flushed out by the time you exported the log, while they were actually performed back then and contained the positive check. I don't know for sure if that's what actually happened and this should definitely be investigated further, but it seems to be a possible scenario.


- my logs from the 26th and 27th: [my logs.zip](https://github.com/corona-warn-app/cwa-app-android/files/4984606/my.logs.zip)

**Comment by SebastianWolf-SAP** [comment] 2020-07-28 14:11
@daimpi Interesting that Apple obviously also limits the number of list entries to 100. We even have a dedicated issue for that: https://github.com/corona-warn-app/cwa-app-ios/issues/934 Feel free to open another issue for that here in this repository as well. We will then add this to the list of things we need to discuss with Google.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by daimpi** [comment] 2020-07-29 19:54
Ok I think I have to revise my theory from above: because even though for the past few days it looked like the list was always getting truncated at the top, this seems not to be the case. I was expecting that today (29th) the entries which were on the top of the list yesterday (which were for the checks performed on the 23rd) would fall off my list, and therefore create a hole, as entries for the 22nd and 21st are situated much more towards the end of the list. To my surprise this didn’t happen, instead the new entries from today were added in the beginning of the list and the checks for the 21st (which were in the middle of the list) were cut out.

So it seems that ENF somehow makes sure that the most recent 100 entries are shown, even though the list is in no discernable order.

This kinda kills my hypothesis that the checks for the 21st in your friends log somehow got “flushed out” because they were in the beginning of the list, as your friends log contains entries which are from before that.
- [my ENF logs 26-29.zip](https://github.com/corona-warn-app/cwa-app-android/files/4997108/my.ENF.logs.26-29.zip)

**Comment by jeschket** [comment] 2020-07-30 07:42
For documentation: Here you can find the updated log file for the same phone (update date today 30.07.2020)

[all-exposure-checks_S_30.07.2020.txt](https://github.com/corona-warn-app/cwa-app-android/files/4999575/all-exposure-checks_S_30.07.2020.txt)

**Comment by Wyand87** [comment] 2020-08-13 07:31
Hi everyone, this description seems to match the faulty behaviour I have been observing on my phone for quite a while now.

I received two positive contacts relatively early on, one of which vanished after about a week. The other one is persistently shown for over five weeks now. I manually checked the ENF log on my phone several times and cannot find a positive match. Given that I had the notification displayed in the app for over five weeks, checking the app daily and how unlikely it would be for me to always get a new positive match once the current one runs out (becomes older than 14 days), I suspect the app to display one positive encounter without there actually being one in the past 14 days.

So it is either stuck in an old state, or it somehow evaluates data more than five weeks old.

The app is up to date, my phone (Google, android 10) has every covid related feature active and I check the app manually several times a day.

If there's a way for me to provide useful data, just let me know how.

**Comment by daimpi** [comment] 2020-08-13 12:21
@Wyand87 I think what you're experiencing is: https://github.com/corona-warn-app/cwa-app-android/issues/911

A fix for this has been merged, but will only be [rolled out with version 1.3](https://github.com/corona-warn-app/cwa-app-android/issues/911#issuecomment-671227418).

And on a more general note: upon revisiting this issue I think OP’s friend might be experiencing #911 as well:
> The person said she did not open the CWA between 13.07.2020-21.07.2020 and up to 12.07.2020 there was no "risk encounter" shown. The one risk encounter was noticed on the 22.07.2020 in the CWA and is still shown to this day (26.07.2020).

Unfortunately the exposure logs we have cut off in the middle of 18.07 and we're missing anything before that. 
So my new hypothesis is:
1. OP’s friend downloaded a key with which they matched between the 13.07 - 17.07.
2. The actual encounter with the key they matched occurred somewhere before the 04.07 (14 days before the 18.07). 
3. Because of #911 one match was persisted in CWA even though it should have been purged.
4. Because the encounter is more than 14 days in the past from the point where we have logs (partially starting at 18.07) we cannot see the match in the ENF log.

**Comment by jeschket** [comment] 2020-08-20 06:56
Update:

The low risk encounter did not vanish after 14 days and is still shown in the app untill now.

**Comment by daimpi** [comment] 2020-08-20 12:34
@jeschket Yes, that makes a lot of sense if your friend is experiencing #911 :)

**Comment by daimpi** [comment] 2020-09-13 20:18
@jeschket did the encounter vanish after updating CWA to version 1.3? 🙂

**Comment by jeschket** [comment] 2020-09-14 13:02
Yes its gone :)

**Comment by daimpi** [comment] 2020-09-14 13:54
@jeschket great to hear 😊.

This means it was indeed most likely issue #911 which your friend was experiencing. 

I think this issue here can then also be closed 🙂.

**Comment by abro1i** [comment] 2020-09-15 09:12
Agreed :+1:

Best regards,
ABB

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment] 2020-09-15 09:12
Duplicate of #911

**Closed by abro1i** 2020-09-15 09:12 UTC
Labels: bug, mirrored-to-jira
