### ISSUE TITLE
Check-in disappeared from contact journal

### ISSUE THREAD

**Issue by derbuelti** [corona-warn-app/cwa-app-android#2986] opened 2021-04-28 09:01 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Motorola Moto G6 (XT1925-5)
- Android version: 9
- App version: 2.0.4

## Describe the bug

I registered at an event by scanning the QR-Code. I got the answer, that I am registered and will be checked out automatically after 2:30 h. When I left, I wanted to check out, but the event was not longer listed e.g. in the diary. So if I now would send a positive testresult, nobody taking place in that event could be informed.

## Steps to reproduce the issue

Sorry, none...
## Expected behaviour

Event ist shown in diary or other lists

----
Internal Tracking-ID: [EXPOSUREAPP-6990](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6990)

**Comment by Ein-Tim** [comment] 2021-04-28 09:06
@derbuelti 

So if you click on "Check-In" on the tab bar, there is no event, like in this screenshot:

https://www.coronawarn.app/assets/img/screenshots/de/android/check_in_attendee_view_my_check_ins.png

**Comment by derbuelti** [comment] 2021-04-28 09:43
I saw a screen like your screenshot when I checked in. When I later clicked on "Check-In" there was no event, nor was in the diary. It completely disappeared, though I got the correct message after checking in.

**Comment by Ein-Tim** [comment] 2021-04-28 09:59
@derbuelti 

Okay. You can deactivate that the event is entered into the contact diary, but it is not possible that the event isn't shown on the "My Check-Ins" screen (but if it is older than 16 days - which (if the date was set correctly) is not possible). 

This has to be further investigated.

**Comment by vaubaehn** [comment] 2021-04-28 10:02
I experienced something similar last week end. I checked in with automatic check out, then didn't open CWA for many hours. In the end of the day, there was no check in anymore, and I wondered whether my brain tricked me and I had just forgotton to check in...
Next time I checked in everything worked as expected, so I didn't follow it further yet...

**Comment by heinezen** [comment] 2021-05-02 14:34
@vaubaehn @derbuelti ,

Thank you for your insights. We have forwarded the issue to the development team by creating Jira ticket [EXPOSUREAPP-6990](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6990). If there is progress on the issue, we will report back here on Github.

----
Corona-Warn-App Open Source Team

**Comment by d4rken** [comment] 2021-07-02 16:52
Was the device low on storage when this happened?
Did the device use an internal sdcard as storage?

**Comment by vaubaehn** [comment] 2021-07-02 17:14
@d4rken 
> Was the device low on storage when this happened?

In my case yes.

> Did the device use an external sdcard as internal storage ( I think the Moto G6 supports that)?

LG-G4 and internal storage.

**Comment by mtwalli** [comment] 2022-09-13 07:34
We could not reproduce it, and from the comments I understand it was one time issue, Please submit an error report if you experience it again?

**Closed by mtwalli** 2022-09-13 07:34 UTC
Labels: bug, in review, mirrored-to-jira
