### ISSUE TITLE
Direct apk Download from Webpage or Fdroid

### ISSUE THREAD

**Issue by schonma** [corona-warn-app/cwa-app-android#529] opened 2020-06-16 10:38 UTC
it would be nice to see the cwa-app-andoird in the fdroid store

**Comment by tomjschwanke** [comment] 2020-06-16 10:40
see #477

**Comment by tkowark** [comment] 2020-06-16 11:01
As noted by @tomjschwanke , this is a duplicate of #477 and corona-warn-app/cwa-documentation#5. Please refer to these issues for further explanation.

**Closed by tkowark** 2020-06-16 11:01 UTC
Labels: duplicate

**Comment by corneliusroemer** [comment] 2020-06-18 13:05
I invite @schonma to contribute to this current issue #514 

The reasons given for not hosting apks on Github so far have not been satisfactory from a community viewpoint.
