### ISSUE TITLE
"Test result certificate can't be downloaded #3571" is again here

### ISSUE THREAD

**Issue by TanCari** [corona-warn-app/cwa-app-android#3638] opened 2021-07-05 22:00 UTC
I could not download the certificate for rapid tests, precisely as described in issue #3571. After the update to version 2.4.3 everything worked fine. Over the week end I could download two certificates correctly. Now I have exactly the same problem.
I beg for help, as I have to fly very early on wednesday: After seeing certificates on my mobile I thought the problem was definitely over. Thanx!

---
Internal Tracking ID: [EXPOSUREAPP-8162](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8162)

**Comment by thomasaugsten** [comment] 2021-07-05 22:03
Can you post an screenshot of the detail error

**Comment by TanCari** [comment] 2021-07-05 22:09
> Can you post an screenshot of the detail error

Yeah, just the time to prepare it now and I post it. The exception is extremely similar to the one in in #3571, I would say.

**Comment by TanCari** [comment] 2021-07-05 22:16
> Can you post an screenshot of the detail error

![Screenshot_20210706-001221](https://user-images.githubusercontent.com/35867729/124521314-5a7d1080-ddef-11eb-9e47-b978295f3189.jpg)

**Comment by TanCari** [comment] 2021-07-05 22:18
Possibly android was automatically updated between the last achieved certificate and this failed attempt. I'm at disposal for all further infomation needed.

**Comment by vaubaehn** [comment] 2021-07-05 22:48
@TanCari 
Can you try again? There is always a low chance for a short temporary server maintenance...
As I can reach the server now, you're probably able to get it now?

@dsarkar it's past midnight! Are you never sleeping? 😉

**Comment by TanCari** [comment] 2021-07-05 22:55
@vaubaehn I have tried it again and I astill get the same error. Also restarted the device and the app: it did not help.

**Comment by vaubaehn** [comment] 2021-07-05 22:58
@TanCari 
Thanks for trying. Since the weekend there was no update of CWA. I still believe this is most likely a server issue.
@thomasaugsten will handle it best way, I'm sure

**Comment by vaubaehn** [comment] 2021-07-05 23:11
@TanCari 
Now I read that you think your whole Android was updated? Full version upgrade?

@thomasaugsten is the key ring (private/public) mechanism for test data encryption on Android dependent on Android keystore? But in any case for every test a complete new key would be generated, there is no dependency on a master key, is there?

**Comment by thomasaugsten** [comment] 2021-07-05 23:15
The keys has no depending. You can close the app and try again on mobile network.

**Comment by TanCari** [comment] 2021-07-05 23:18
@vaubaehn I am not sure that any update of my android took place since the last successfull covid certificate yesterday. For sure not for my own initiative. If any, then an automatic one. I can check it, if it can be useful. Any suggestion how to do it, in that case?

**Comment by vaubaehn** [comment] 2021-07-05 23:21
@TanCari 
As Thomas wrote, it's unlikely connected with any Android update. Please first try again on a mobile connection, like he suggested. If you have already been on mobile, then switch to Wifi to try again. At the moment it looks more like a connection failure somewhere between your phone and the server

**Comment by TanCari** [comment] 2021-07-05 23:23
> The keys has no depending. You can close the app and try again on mobile network.

@thomasaugsten Tried with mobile network, after restarting the app. Same result. (Connection is there)

**Comment by vaubaehn** [comment] 2021-07-05 23:27
@TanCari 
If still still doesn't work, it may help to create an error report. From home screen in CWA tap the 3 dots, and go to 'app information'. Find 'error report' (Fehlerbericht) there and start it.
Then try to get your certificate again.
When requested by @thomasaugsten or @dsarkar or any other developer, go back to that menu and upload it. You will then need to copy the error report id to here so that devs can identify it and search deeper for the cause.

**Comment by TanCari** [comment] 2021-07-05 23:30
@vaubaehn Now tried several times, both with mobile connection and with wifi. That I know, I did exactly the same procedure as yesterday, when I last got a certificate. Can I test my conncetion to the server and possible related errors in any other way?

**Comment by vaubaehn** [comment] 2021-07-05 23:35
@TanCari 
> Can I test my conncetion to the server and possible related errors in any other way?

You can try https://dcc.coronawarn.app from your phone's browser. You should see a 'white label  error' page and 'forbidden' as the cause. Of you see that, then your phone can reach the server.
(But there still could be some maintenance under the hood...)
If you see that page, activate error report like described above, try to get your certificate again (to produce the error) and wait for a 'go' from the devs to upload the report.

**Comment by TanCari** [comment] 2021-07-05 23:43
'error report' started and asked for the certificate again.

On https://dcc.coronawarn.app from the web browser I see "white label error" and "Type=Forbidden" as expected.

**Comment by vaubaehn** [comment] 2021-07-05 23:48
@TanCari 
Great. Then let's see what happens - I wouldn't be surprised if it works tomorrow automagically... Fingers crossed 🤞 
We should sleep now - have a good night! 🌙

**Comment by TanCari** [comment] 2021-07-05 23:49
Thank you very much for suggestions.

**Comment by TanCari** [comment] 2021-07-06 05:40
@vaubaehn today at 7.30 the situation seems to be the same.

**Comment by thomasaugsten** [comment] 2021-07-06 06:29
Can you activate the error report under app information and let the error appear and provide the error id

**Comment by vaubaehn** [comment] 2021-07-06 07:14
@TanCari 
As Thomas wrote:
> Can you activate the error report under app information and let the error appear and provide the error id

You already started it and produced error, so only upload needed and  report id copied to here.

Did you receive any QR code from your test center/provider as PDF by email or as a paper print out? If yes, are you able to scan that into CovPass app or into CWA?

**Comment by TanCari** [comment] 2021-07-06 07:31
![Screenshot_20210706-092632](https://user-images.githubusercontent.com/35867729/124560213-d9e50100-de3c-11eb-98ec-d46d819293c2.jpg)


I am not sure whay it only shows errors since 5 minutes ago

**Comment by vaubaehn** [comment] 2021-07-06 07:36
@TanCari 
The time should be the time when you uploaded your error report, not the time when errors focused.

When looking to your screenshot - there is a stop sign in the info bar at the very top - what is it about, why is it shown?

**Comment by TanCari** [comment] 2021-07-06 09:50
Second from left? It is the printer, nothing to do with CWA.

**Comment by thomasaugsten** [comment] 2021-07-06 09:54
It looks like there was a connection problem while uploading the public key. I think you will not receive a DCC for this test. You have to scan a new test in the CWA

**Comment by TanCari** [comment] 2021-07-06 09:59
... would this be compatible with the fact, that the test was correctly uploaded in the corona warn app? I can see the test, just I cannot obtain the certificate.

**Comment by TanCari** [comment] 2021-07-06 10:07
I may try soon with another test as soon as possible. Do I have to do anything before trying again (possibly apart from deleting the previous test) and do I have to pay attention to anything when uploading? (for example, better a wifi or a mobile connection?)

**Comment by thomasaugsten** [comment] 2021-07-06 10:11
Deleting old test and good connection. We will improve the process and make it more robust

**Comment by TanCari** [comment] 2021-07-06 10:13
Thank you. I will try within one or two hours and report here the result.

**Comment by vaubaehn** [comment] 2021-07-06 10:17
@TanCari 
> do I have to pay attention to anything when uploading? (for example, better a wifi or a mobile connection?)

If you're on a WiFi Mesh, that sometimes interrupts connection to get you to another station with better connection, that could result in unexpected problems. In that case a stable mobile connection with good quality would be sufficient.
Be sure to have the connection already enabled for a minute or two. Try to avoid actions that may initiate heavy downloads (like searching for updates in Google Play).
You could open CWA, jump through the menus for a minute or two (to prevent screensaver / display lock from getting active) and then register the test.
The suggestions I gave are usually useful for older and slow phones like mine...

**Comment by TanCari** [comment] 2021-07-06 10:20
> @TanCari
> 
> > do I have to pay attention to anything when uploading? (for example, better a wifi or a mobile connection?)
> 
> If you're on a WiFi Mesh, that sometimes interrupts connection to get you to another station with better connection, that could result in unexpected problems. In that case a stable mobile connection with good quality would be sufficient.
> Be sure to have the connection already enabled for a minute or two. Try to avoid actions that may initiate heavy downloads (like searching for updates in Google Play).
> You could open CWA, jump through the menus for a minute or two (to prevent screensaver / display lock from getting active) and then register the test.
> The suggestions I gave are usually useful for older and slow phones like mine...

Thanx, I will try it!

**Comment by TanCari** [comment] 2021-07-06 12:56
Hi, I have made another test and tried again: now it worked! I basically changed nothing, except for trying to start the process with the CWA when my device was "still" (no downloads or similar) and a stable connection (in my case a mobile one).
 
Thank you a lot for prompt support and taking care of constantly improving the app.

**Comment by vaubaehn** [comment] 2021-07-06 13:05
@TanCari 
I'm happy it worked for you now!

It looks like, at the time before you got the error and registered your test, there was a connectivity problem (e.g. connection reset). Reading the comment in #3650 , it seems that the server indeed got the registration, but CWA didn't get any response that this was successful. When CWA was trying to register the test again later, it created a new key and sent it to the server, but the server complained and wanted the old key that was discarded, because CWA didn't get any response.
@d4rken fixed the process, that in future the first key won't be discarded, until the whole registration completed. The fix will likely be rolled out with CWA 2.5.x, but as you already have your new test registered, everything is fine.

Enjoy your trip and stay safe and healthy!

**Comment by heinezen** [comment] 2021-07-06 13:07
@TanCari Thanks for reporting back. If you think everythimg works as expected, you can close the issue now.

----
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment] 2021-07-06 13:08
@heinezen or maybe leave it open until 2.5 has rolled out? There may be others affected, too...

**Comment by vaubaehn** [comment] 2021-07-06 13:15
@heinezen 
Is this issue also possible on iOS?

**Comment by TanCari** [comment] 2021-07-06 13:23
Thanx for all explanations, from which I actually learn new things.

Could you please decide for me if the issue should be closed? I am not an expert of github.

Thanx again, stay healthy and happy too.

**Comment by heinezen** [comment] 2021-07-06 14:28
@vaubaehn @TanCari 

2.5 is around the corner, so we can leave it open for a bit to see if anybody else has the problems. Maybe it helps them too.

> Thanx again, stay healthy and happy too.

Thanks, you too!

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-08-21 09:30
@heinezen 
I'm just wondering if this issue can be closed now. It has the Fix 2.5 label and the current Android version is 2.7.1.

**Comment by heinezen** [comment] 2021-10-02 13:06
Seems to be fixed.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-10-02 13:06 UTC
Labels: bug, mirrored-to-jira, Fix 2.5
