### ISSUE TITLE
Scaling of PDF certificate export

### ISSUE THREAD

**Issue by framihoki** [corona-warn-app/cwa-app-android#5350] opened 2022-07-14 13:21 UTC
## Avoid duplicates
* [x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x ] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A52
- Android version: 12
- App version: 2.24.2

## Describe the bug

When exporting individual or all certificates into a PDF document, the resulting PDF does not seem to be at scale for A4 paper. The booklet marks are not centred and do not reach up to the paper edge. In earlier versions, the scaling was always correct. It seems that in the current version the scaling is about 10% too small and the edges are not compatible with the A4 paper format.

## Expected behaviour

Like in the previous versions, the alignment marks should be centred in the PDF and the full A4 paper size should be used.

## Possible Fix

Correct PDF scaling.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-13633](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13633) Scaling issue, duplicates
Internal Tracking ID: [EXPOSUREAPP-13440](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13440)

Internal Tracking ID: [EXPOSUREAPP-13635](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13635) Template issues

**Comment by dsarkar** [comment] 2022-07-14 13:54
@framihoki Thanks for reporting, we are currently trying to reproduce your issue. Thanks.

**Comment by MikeMcC399** [comment] 2022-07-14 14:26
@dsarkar 

I can reproduce this issue on a Samsung Galaxy A52 with 2.24.0 and 2.24.2. It is a regression from 2.23.2.

## Steps to reproduce

Tap Certificates
Tap right-arrow
Tap certificate tile
Tap three-dot symbol
Select Display Print Version
Tap print symbol
Print with HP 

I am seeing Paper size ISO A4.

## Additional issue

Tap share
Select (Google) Drive
View uploaded file on Desktop with Adobe Acrobat DC

fails with error: "There was an error processing a page. There was a problem reading this document (109)."

**Comment by MikeMcC399** [comment] 2022-07-14 15:04
@dsarkar 

> Thanks for reporting!

The root cause may be the same as the scaling issue, but anyway I will submit a separate report about the compatibility issue with Adobe Acrobat DC.

**Comment by MikeMcC399** [comment] 2022-07-14 19:34
The reported scaling and centering issue is reproducible on a Pixel 3a emulator with Android 12. Whereas on CWA Android 2.23.2 the exported PDF is centered and full size, the exported PDF using CWA Android 2.24.2 is smaller. The folding guide, which is supposed to be in the center of the DIN A4 paper, is shifted down and to the left from the center of the paper page.

## Steps to reproduce the issue

On Desktop

1. Use Android Studio Device File Explorer to transfer vaccination certificate PDF to the emulator

In CWA App

2. Tap Scan
3. Tap Open File
4. Navigate to vaccination certificate in File app and tap on file
5. Tap three-dot symbol
6. Select Display Print Version, tap "Next"
7. Tap Share symbol
8. Tap Drive symbol
9. Tap Save

On Desktop

10. Open Drive https://drive.google.com/drive/my-drive
11. Open saved PDF with Adobe Acrobat DC
12. File > Print
13. Select "Shrink oversized pages" and note that Scale 97% 210,02 x 297,01 mm is shown
14. Click Print
15. Note that folding guide cross is not in the center of the page

I haven't been able to reliably reproduce the unreadable PDF. I will look at this again.

**Comment by MikeMcC399** [comment] 2022-07-15 07:40
@dsarkar 

There may be a problem with the template being used. I noticed also that there are formatting issues in the text. See below, where there is a gap between Sie and the comma (,) following it.

![image](https://user-images.githubusercontent.com/66998419/179173408-48630b5f-16be-4edd-940c-d3ab45747091.png)

This problem occurs in both CWA 2.24.2 and CovPass 1.27.0.

It is a regression from CWA 2.23.2.

I will see if I can find out if there is an earlier version of CovPass without the formatting issue as well.

**Comment by dsarkar** [comment] 2022-07-15 07:54
@MikeMcC399 Many thanks, will forward your findings.

**Comment by dsarkar** [comment] 2022-07-15 08:06
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5303

**Comment by MikeMcC399** [comment] 2022-07-15 08:31
@dsarkar 

[release/2.25.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.25.x) improves the PDF formatting, however it does not completely fix the issue:

1. The folding cross is centered on the page from left to right (105 mm from left and right edge of paper), however it is not centered top to bottom (it should be at 297 mm / 2 = 148.5 mm). The cross is 143 mm from the top and 153 mm from the bottom.
2. The formatting issue with the gap between "Sie" and "," is still present.

Should we continue in this issue or would it be better to track the remaining problems in one or more separate GitHub issues?

**Comment by MikeMcC399** [comment] 2022-07-15 09:54
- The formatting issue I mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/5350#issuecomment-1185269059 is a regression from CWA 2.23.2 compared to CWA 2.24.2. Here is a full screen-shot of that section:

![Certificate infos](https://user-images.githubusercontent.com/66998419/179200132-ea01085b-67e6-44e5-b950-dd0498b366cd.jpg)


- For CovPass I went back to version 1.16.0 and found it was already present in that version. Since the problem still occurs in the current CovPass 1.27.0 version I went ahead and submitted a bug-report https://github.com/Digitaler-Impfnachweis/covpass-android/issues/222 against CovPass.

- I believe that the certificate templates are shared, so it may be that part of the resolution will need to come from the CovPass team.

**Comment by thomasaugsten** [comment] 2022-07-15 10:36
I think the correct issue belongs to the template repo
https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/templates

**Comment by MikeMcC399** [comment] 2022-07-15 10:56
@thomasaugsten 

> I think the correct issue belongs to the template repo
> https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/templates

I noticed when I printed out https://github.com/corona-warn-app/cwa-app-android/blob/release/2.24.x/Corona-Warn-App/src/main/assets/template/vc_v4.1.svg that it looked fine (no scaling issue, no whitespace issue), but I haven't tried to understand how the final PDF is actually built.

Also the templates on https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/templates haven't changed in almost 12 months, so it would be good to understand why there is suddenly an issue in CWA Android 2.24.2, when the format was correct still on CWA Android 2.23.2.

If an issue needs to be raised against the templates, then it would probably be better for the Open Source Team to do that directly, rather than the community, as I cannot specifically identify any issue with the templates.

**Comment by thomasaugsten** [comment] 2022-07-15 11:06
Ok we will double check this

**Comment by MikeMcC399** [comment] 2022-07-15 12:09
@thomasaugsten 

There is no documentation on https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/templates about how to use the templates, however it seems like the `svg` template files are not scalable, despite the extension (`svg` for Scalable Vector Graphics). If they are not used at exactly 100% of DIN A4 size 210 x 297 mm then the text portions will have gaps (if the certificate is less than 100% size) or overlap (if more than 100% size) since their position on the page is defined with absolute coordinates. 

I believe that CWA needs to somehow revert to using the templates at 100% size to solve the issue.

**Comment by MikeMcC399** [comment] 2022-07-30 17:01
@dsarkar 

- This issue is only partially resolved in CWA Android 2.25.0.

- The fold markers in CWA Android 2.25.0 at the edge of the paper are 10 mm (left and right), 13 mm (top) and 18 mm (bottom) from the edge of the paper, whereas in CWA Android 2.23.0 they met the edge of the paper (left and right) or were at a maximum of 1 mm away (top and bottom) from the edge of the paper. Should the certificate be scaled so it looks like the export of CWA Android 2.23.0 or is it intended that the certificate is now smaller?

- Issue #5369 regarding the centering of the folding cross marker is still open. The folding cross is vertically misaligned.

- Additionally the related issue #5356 is still open.

- #5370 is also still open, however it does not concern scaling.

**Comment by MikeMcC399** [comment] 2022-08-01 14:38
@dsarkar 

Since this issue is not resolved in 2.25.0 (refer to issue description in OP) the label https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E25 should be removed.

**Comment by MikeMcC399** [comment] 2022-08-05 14:04
There was announcement in the iOS repository regarding the availability of community managers (see https://github.com/corona-warn-app/cwa-app-ios/issues/4602#issuecomment-1205004898). Will anybody else maintain the fix labels here?

**Comment by sapcoder123** [comment] 2022-08-08 12:37
@MikeMcC399: Fix label adjusted to 2.26

**Comment by MikeMcC399** [comment] 2022-08-09 07:23
@sapcoder123 

> Fix label adjusted to 2.26

This issue is only partially resolved for 2.26. The OP expectations are:

> Like in the previous versions, the alignment marks should be centred in the PDF and the full A4 paper size should be used.

- The alignment marks are centered with PR https://github.com/corona-warn-app/cwa-app-android/pull/5427, however the full A4 paper size is not used. The left and right margins are 10mm, the top margin is 15 mm and the bottom margin is 19 mm.

**Comment by MikeMcC399** [comment] 2022-09-15 12:16
The export from 2.26 leaves a blank margin around the margin which holds only the fold markers, so it is not using the full size of the paper:

![2 26 export](https://user-images.githubusercontent.com/66998419/190400937-c988edd3-bb7a-41ed-bf99-9077905b4b1f.jpg)

**Comment by sapcoder123** [comment] 2022-09-15 15:21
@MikeMcC399 Thank you for reporting, I forwarded it to the dev team

**Comment by MikeMcC399** [comment] 2022-11-09 17:27
This is still not fixed in 2.28.3. An exported certificate is scaled down and does not fill the paper.

**Comment by MikeMcC399** [comment] 2023-01-09 07:31
Same issue in CovPass 1.38.0.

**Closed** 2023-03-14 17:00 UTC
Labels: bug, mirrored-to-jira

**Comment by MikeMcC399** [comment] 2023-03-14 17:34
@mtwalli 

Thank you for trying to fix this! I don't think it matters much more as certificates are hardly being used in Germany these days.
