### ISSUE TITLE
URSACHE: 9002 Etwas ist schiefgelaufen. SSL handshake timed out (when trying to update testresult)

### ISSUE THREAD

**Issue by brianhorn** [corona-warn-app/cwa-app-android#1188] opened 2020-09-20 14:56 UTC
On friday, I got a QR Code to be notified about my test result. Until a few hours ago everything loaded as expected, however since then when trying to load the result the above mentioned error happens. I have not found this version of the 9002 error in the open issues or the FAQ yet. 

App Version: 1.3.0
Phone: Pocophone F1
Android Version: MIUI 10 V10.3.4.0.PEJMIXM (stable)

<strong> Edit: </strong> This problem only occurs when using mobile data.

# Screenshot
![Screenshot_2020-09-20-15-22-42-834_de rki coronawarnapp](https://user-images.githubusercontent.com/22959622/93714235-96e1c780-fb61-11ea-8dd2-2d6df29c63ed.png)

---
Internal Tracking ID: EXPOSUREAPP-2784

**Comment by heinezen** [comment] 2020-09-20 15:38
Hey @brianhorn ,

Thanks for your input. The issue could be related to https://github.com/corona-warn-app/cwa-app-android/issues/998, although your error shows a different message. Could you have a look and check if the behaviour of the errors matches?

Also, some users mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/998#issuecomment-691399034 that the problem only happens when using mobile data. Does the same error appear when you switch to WiFi?

Thanks

----
Corona-Warn-App Open Source Team

**Comment by brianhorn** [comment] 2020-09-20 15:51
Hi @heinezen, thanks for your suggestions! The behaviour of the error does not seem to be too close as in my case, it only affects the functionality of the app related to retrieving a test result. I don't get any errors on the contact tracing. 

However you are right, in my case it also only happens when using mobile data. I have not thought of that since our home internet was not working most of the day so I could not check with wifi, but now it is there again and it works (so far) every time with wifi and does not work a single time with mobile data.

**Comment by heinezen** [comment] 2020-09-20 16:15
@brianhorn 

Great that at least the workaround works! 9002 seems to have different causes that have been addressed in #1138 which will be part of a future update (v1.4.0). After that, the error hopefully disappears. If it still persist, feel free to report back here.

Thanks again.

----
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment] 2020-09-21 16:10
Hi @brianhorn , what is your mobile provider? Is it also vodafone?

**Comment by brianhorn** [comment] 2020-09-21 19:52
@vaubaehn yes, I am also on vodafone.

**Comment by vaubaehn** [comment] 2020-09-21 20:22
Hi @brianhorn ,

> @vaubaehn yes, I am also on vodafone.

Thanks a lot for your report!

@thomasaugsten @svengabr @JoachimFritsch 
I am also on vodafone mobile, and I can reliably reproduce the issue by calling
https://verification.coronawarn.app
and
https://submission.coronawarn.app
via browser. Mobile connection ends up in timeout, wifi (different provider) results in response 'forbidden' (as expected).
https://www.coronawarn.app works fine in either mobile and wifi.
Strong assumption: vodafone has a failing configuration in packet handling for these 2 subdomains (to assure exception from mobile data quota).
Maybe T-Systems can have a look into it and contact vodafone in case of being able to validate?
Thank you

**Comment by brianhorn** [comment] 2020-09-21 20:27
@vaubaeh that is very interesting! I can reproduce the issue just like you - on wifi and tmobiles mobile data I get 'forbidden', with vodafone mobile data it times out. Interesting observation!

**Comment by vaubaehn** [comment] 2020-09-21 20:42
Hi @brianhorn ,

> @vaubaeh that is very interesting! I can reproduce the issue just like you - on wifi and tmobiles mobile data I get 'forbidden', with vodafone mobile data it times out. Interesting observation!

Your additional observation underlines the assumption, that there is a vodafone internal configuration problem.
Thanks again, and let's see, what will happen (and when) 😉

**Comment by vaubaehn** [comment] 2020-09-21 21:18
@svengabr , please refer to Google Playstore (J) Support team, as I already saw some people coming there with this issue. Thanks a lot!

**Comment by thomasaugsten** [comment] 2020-09-22 12:13
@brianhorn  @vaubaehn 
If this error stills occurs can you please provide me your mobile vodafone ips via e-mail
thomas.augsten@sap.com

**Comment by olmomp** [comment] 2020-09-22 12:18
@thomasaugsten Same issue here, was unable to scan QR Code today due to above mentioned error. Using a VPN all worked fine. Now when I open the app I get the error again constantly, as it says "Data being retrieved ..." / Test result is being updated. Again, need to be off Vodafone mobile data network to get it to work.

Mobile provider is otelo (so Vodafone network as well). Mail with IPs following.

**Comment by lothas** [comment] 2020-09-23 08:38
I had the same issue trying to scan the QR code on the Vodafone network: SSL handshake timed out.
I tried on the Telekom network and it finally worked! Thanks for reporting this! One more benefit of Open Source Software 🥇

**Comment by thomasaugsten** [comment] 2020-09-23 09:27
We are able to find the issue and will fix this together with vodafone as soon as possible.

**Comment by vaubaehn** [comment] 2020-09-23 13:26
Hi @thomasaugsten , the status for https://verification.coronawarn.app and https://submission.coronawarn.app now changed: instead of error: timeout it's now error: connection refused.
Is this intended behaviour by vodafone (translating server response 'forbidden' to connection 'refused')? Or is there still an issue?

@olmomp  @lothas @brianhorn : could you try to update your test results while being on vodafone mobile? Is there still an error or does it work now?

**Comment by lothas** [comment] 2020-09-23 13:34
I'm still getting "Failed to connect to verification.coronawarn.app"

**Comment by vaubaehn** [comment] 2020-09-23 13:35
@lothas - when trying to update test status from inside corona warn app? Or while opening via URL via browser?

**Comment by vaubaehn** [comment] 2020-09-23 13:39
@lothas - to make it precise (hope not to bother): so, instead of error 9002: ssl handshake timeout from inside CWA, there is now "Failed to connect to verification.coronawarn.app" from inside CWA?

**Comment by lothas** [comment] 2020-09-23 13:43
The complete message is

> URSACHE: 9002
> Etwas ist schiefgelaufen
> failed to connect to verification.coronawarn.app/
> [IP] (port 443) from [IP + port]
> after 10000ms

**Comment by vaubaehn** [comment] 2020-09-23 13:44
@lothas : Thanks very much!

@thomasaugsten : I'm so sorry... config changed, but still not solved.

**Comment by thomasaugsten** [comment] 2020-09-24 09:28
The connection from Vodafone mobile is working again. Thanks for the information.

**Comment by vaubaehn** [comment] 2020-09-24 09:31
> The connection from Vodafone mobile is working again. Thanks for the information.

I can confirm. Thank you for fixing!

**Closed** 2020-09-24 12:15 UTC
Labels: bug, mirrored-to-jira
