### ISSUE TITLE
Fehler bei Google API(39508)

### ISSUE THREAD

**Issue by neffmartin** [corona-warn-app/cwa-app-android#1525] opened 2020-11-03 14:15 UTC
Fehler bei Google API(39508)

Mobile device: Pixel 3
Android version: 11
App Version: 1.5.1
ENF Version: 17203915000
Play Services version: 20.39.15

**Comment by heinezen** [comment] 2020-11-03 14:43
Hey @neffmartin ,

Thank you for the report. This issue is already reported in https://github.com/corona-warn-app/cwa-app-android/issues/1459 . We are currently investigating the bug to find a solution for this behaviour. If there are any news or updates on the situation they will be posted in https://github.com/corona-warn-app/cwa-app-android/issues/1459 . Therefore, please continue the discussion in there and subsribe to the issue so that you are notified about the updates. I will close this issue as a duplicate.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-11-03 14:43
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1459

**Closed by heinezen** 2020-11-03 14:43 UTC
Labels: bug
