### ISSUE TITLE
Status update is not working on a Realme smartphone

### ISSUE THREAD

**Issue by vaggelisdouros** [corona-warn-app/cwa-app-android#5397] opened 2022-07-28 23:57 UTC
## Technical details

- Device name: Realme 7 5G
- Android version: 12
- App version: 2.25

## Describe the bug

It has been 2,5 days since the last status update of the app. At some point today, I saw an error message saying something like that, even though the exposure logging is working properly, it’s not possible to update the status (I’ll save a screenshot if it pops up again). Then, it tried to have an update but this failed and the status remained to the previous date and time. 
The problem started with the previous app version. After tonight's update to v.2.25, the app still doesn't show an update.  I restarted the phone a couple of times just in case but this did not help. No ultra-saving mode has been activated. I have used this phone for a year and the app was working properly till this incident. 

## Screenshots
![screen1](https://user-images.githubusercontent.com/73972744/181655389-87b5ab41-3d45-4e27-bc2e-5a0340e43d35.jpg)
![screen2](https://user-images.githubusercontent.com/73972744/181655403-0f0aeb5a-8a27-43db-9578-ad1553d5d9d9.jpg)

---
Internal Tracking ID: [EXPOSUREAPP-11805](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11805)

**Comment by dsarkar** [comment] 2022-07-29 06:00
Hi @vaggelisdouros,

thank you very much for reporting.

1. Could you post a screenshot from the "status" page, i.e. the risk card showing date and time of last risk check, please.
2. Could you start error logging, please? Keep it running for some days, please. See 
- **EN** https://www.coronawarn.app/en/faq/results/#error_log
- **DE** https://www.coronawarn.app/de/faq/results/#error_log

Thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team


 Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)

**Comment by vaggelisdouros** [comment] 2022-07-29 11:49
Last "status" update was on 26 Jul, 16:40. The app started working again, today early in the morning. Not sure what was the issue, but now it seems that it works again. 


![Screenshot_2022-07-29-13-45-34-21_f7aa348215f5d566f9e4ca860f474209](https://user-images.githubusercontent.com/73972744/181752244-e1609dac-8e6b-4cc1-bb01-8bf3d156c7fd.jpg)

**Comment by dsarkar** [comment] 2022-07-29 12:24
@vaggelisdouros Thanks for your feedback, glad it works for you right now. Should it happen again, the development team would appreciate very much an error log, since they might find hints about the root cause of this issue. 

So, if this is not the first time that this happened, i.e. you observed this issue regularly, maybe we can ask you to run the error log until you observe the same issue. If nothing unusual happens after 2 or 3 or more days, stop the log, and start a new one after maybe 2 or 3 days. Hopefully like this you "catch" the moment when risk calculation stops and hopefully in the log there is something useful for the dev team. 


Thanks again, Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by vaggelisdouros** [comment] 2022-07-29 12:30
@dsarkar I just checked that the status of the app updated again after 4+ hours from the last update. So, it seems that it works. As I said, this was the first time that I noticed a problem with the app during the last year that i use it in this phone. Should an issue arise again, i'll run error logging.

**Comment by MikeMcC399** [comment] 2022-08-04 18:38
@vaggelisdouros 

If you're not seeing this problem any more I would suggest closing the issue. You should see a button for this at the bottom.

**Comment by mtwalli** [comment] 2022-08-11 09:45
@vaggelisdouros  Feel free to re-open the issue and post the error log ID if you experience this issue again. I will close in the mean time

**Closed by mtwalli** 2022-08-11 09:45 UTC
Labels: bug, mirrored-to-jira, risk-check
