### ISSUE TITLE
Import of previously saved certificates only imports last one in the list

### ISSUE THREAD

**Issue by gleichda** [corona-warn-app/cwa-app-android#5602] opened 2022-09-29 06:37 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) (no iPhone to compare behaviour)
* [x] Bug is not already reported in another issue

## Technical details

- Android version: 13
- App version: 2.26.0

## Describe the bug

When importing a file with multiple certificates only the last one is imported

## Steps to reproduce the issue

1. Export all certificates from the app via export function
2. Import the certificate(s) from the previously printed PDF

## Expected behaviour

All Certificates from the file are imported

## Additional context

This behaviour feels inconsistent across the app. If I can use the export function the import should be able to handle the same. Otherwise for people without a second device it will get hard to reimport certificates.

**Comment by Ein-Tim** [comment] 2022-09-29 07:16
- Closely related/duplicate of: https://github.com/corona-warn-app/cwa-wishlist/issues/841

**Comment by mtwalli** [comment] 2022-09-29 07:48
@gleichda This is not a bug, the app is currently supports single import. Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/841

**Closed by mtwalli** 2022-09-29 07:48 UTC
Labels: bug
