### ISSUE TITLE
Showing an antigen test results takes a long time when offline

### ISSUE THREAD

**Issue by bedo2991** [corona-warn-app/cwa-app-android#4445] opened 2021-11-29 14:40 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues/questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 4a
- Android version: 12
- App version: 2.14.1

## Describe the bug

Showing an antigen test result (the one with the timer) takes a long time/is not possible when the phone is offline or has a slow internet connection.

## Steps to reproduce the issue

1. Register a negative antigen test in the CWA, get the negative result, close the app.
2. Simulate an offline situation (for example, plane mode)
3. Open the Corona Warn app
4. Datenabruf... (Das Ergebnis wird aktualisiert)
5. "Schnelltest Fehler", "Möglicherweise wurde Ihre Internet-Verbindung unterbrochen. Bitte stellen Sie sicher, dass sie mit dem Internet verbunden sind.
6. Timeout, sometimes the negative result gets shown, sometimes the "Datenabruf" message remains.

## Expected behaviour

The negative test should be shown

## Possible Fix

You could check if the phone is offline before refreshing the result. If it is, then refresh the result, if not, show the cached result.

**Comment by Ein-Tim** [comment] 2021-11-29 15:13
This seems like it is a duplicate of #4338.

**Closed** 2021-11-29 15:15 UTC
Labels: bug
