### ISSUE TITLE
Risk-Calculation Update time lies in the past on some devices

### ISSUE THREAD

**Issue by vaporwave9** [corona-warn-app/cwa-app-android#590] opened 2020-06-17 10:19 UTC
## Describe the bug

For testing the Corona-Warn-App was installed on 2 devices:
Stock Xiaomi Redmi Note 8 Pro (Android 10 + full PlayServices)
Samsung S4 Value with Lineage OS (Android 10 + full PlayServices)

The **stock, unmodified Xiaomi** will show a **"Aktualisiert: Gestern, 11:58"** timestamp, but that is impossible, since that was about 1 hour after installing it for the first time.

## Expected behaviour

Like the modded Samsung S4 Value, a correct "Aktualisert: Heute, 09:47" is expected, not "Gestern".
When the risk is calculated each day, the timestamp of the database update should be the same day.
Assuming correct operation of the app, a "last update" cannot lie in the past, when the app is only installed for 1 day.

## Steps to reproduce the issue

You install the app normally on an unmodified, stock Xiaomi Redmi Note 8 Pro.

## Technical details

- Host Machine OS (Windows/Linux/Mac):
Sorry, what? Android 10.

## Possible Fix

No solution as of now.

## Additional context

Screenshots attached:

([Samsung S4 Value](https://user-images.githubusercontent.com/64961250/84885877-ec569600-b093-11ea-96b1-99181cfaccb3.png))

([Xiaomi Redmi Note 8 Pro](https://user-images.githubusercontent.com/64961250/84885888-f24c7700-b093-11ea-9712-adcb1740c017.png))

**Comment by jakobmoellersap** [comment] 2020-06-17 10:24
Hi! Can you check if the device time is set to automatic timezone fetching or if you manually set the time of your device?

**Comment by vaporwave9** [comment] 2020-06-17 10:30
Thanks for your reply. Currently the affected Xiaomi receives both time and timezone autonomously out of the cell network of the German provider Congstar (Telekom subsidiary). Matching time on my desktop PC. The timezone is MESZ GMT+02:00.

**Comment by jakobmoellersap** [comment] 2020-06-17 14:22
That could have happened but it is quite unlikely. Are you sure that the switch you are describing with your Xiamoi references 11 am and not 11 pm? That would mean that the device would have switched the date in the meantime. This would also mean that you would face the same issue tomorrow morning.

If you cannot reproduce today, I would kindly ask you to monitor your device tomorrow and see if you face the same behaviour.

Regarding the other assumptions: Your devices will never update at the same time due to randomized background jobs. So no worries that only one device updates at a time.

 Also thanks for doing a time-travelling investigation with us 👍 

BR,
Jakob

**Comment by vaporwave9** [comment] 2020-06-17 15:15
I try to give more info:
My phone is in 24 hour time format.
All events in the thread occurred around lunch time (high-noon 🤠) on the 17th, app was installed the day before.

Since I did **not** change date-time ever manually and it has been correct since DST self-applied on Easter holidays I guess it **might** be a problem with how it runs on the Xiaomi?

Surely I can keep you updated if the problem will happen again tomorrow. 


> 
> Regarding the other assumptions: Your devices will never update at the same time due to randomized background jobs. So no worries that only one device updates at a time.
> 

Ah good to know, I thought it might force an update once interval >24hours is hit, but I see there might be a grace time to reduce server-loads.

>
> Also thanks for doing a time-travelling investigation with us 👍
> 

No worries, I really enjoy the app and will keep using it on both devices.
The support by the Github team is very good :)

**Comment by mbw83** [comment] 2020-06-17 17:31
I have the same Problem with a Xiaomi Mi 9 Lite. I installed it yesterday around 9 am. It showed "unbekanntes Risiko" until this morning around 10 am (I checked it maybe at 10:30), since then it is showing "Aktualisiert: Gestern, 10:11".

Date / Time is set to automatic, as well as "Vom Netzwerk gesendete Zeitzone verwenden" (I don't know what the correct english Translation would be). 
Timezone is GMT+2, 24h clock is used and at the moment my clock shows "Mittwoch, 17.06.2020 19:31"

Best regards,
Matthias

**Comment by vaporwave9** [comment] 2020-06-18 11:07
Both devices (Xiaomi and Samsung) updated correctly **and only once** on day 2 as intended.
The timestamps on day 2 showed no more contradictions and referenced "Heute" as intended.

Since I cannot reproduce the error, this issue can be closed as "non-reproducible" unless @mbw83 still wants to comment about his Mi 9.

But many thanks for the help!

**Comment by mbw83** [comment] 2020-06-18 12:35
Mine didn't update since monday, I have now the issue, that the Exposure logging is not possible, see also #637.

**Comment by jakobmoellersap** [comment] 2020-06-18 12:59
As a result of this discussion, I will have to close this with not reproducible. Thanks for your input everyone.

**Closed by jakobmoellersap** 2020-06-18 12:59 UTC
Labels: bug, not reproducible
